//! The external tools the gate drives: `xmllint` and the two reference schema trees.
//!
//! # Skipping
//!
//! The schemas are not committed (`References/` is git-ignored by a standing rule of this
//! repository), so when they — or `xmllint` — are absent the gate **skips**, printing a notice and
//! passing, exactly as the LibreOffice canary does for a missing `soffice`. `MJX_REQUIRE_SCHEMA=1`
//! turns any absence into a hard failure so the coverage can never silently disappear, and CI sets
//! it. `MJX_SCHEMA_DIR` and `MJX_OPC_SCHEMA_DIR` override where the two trees are looked for.
//!
//! # The driver schema, and why every validation goes through one
//!
//! `wml.xsd:21` and `shared-math.xsd:13` import `http://www.w3.org/XML/1998/namespace` with **no
//! `schemaLocation`**, and the Transitional set ships no `xml.xsd`. libxml2 then cannot resolve
//! `xml:space` and the whole schema *fails to compile* — so before this crate existed there was no
//! way to validate a single line of WordprocessingML.
//!
//! A bare import gives libxml2 no URI to fetch, so an XML catalog has nothing to rewrite. What works
//! is a tiny generated **driver** schema that imports [`crate::XML_NAMESPACE_SCHEMA`] for the XML
//! namespace and then the real XSD; by the time the bare import is processed the components are
//! already there. Every validation goes through a driver, not only the two schemas that need one:
//! one code path is cheaper to trust than a flag saying which schemas are special, and it means
//! `shared-math.xsd` — MJXOFF-134's arm — inherits the fix with no further work.
//!
//! The drivers are written once per process into a directory named after the schema tree, so
//! repeated runs reuse them instead of accumulating.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

use mjx_fixtures::workspace_root;

use crate::categories::{SchemaRef, SchemaSet};

/// The path of the committed schema for the XML namespace, resolved at compile time of *this*
/// crate — so it is the same path whichever crate's test binary is running.
pub const XML_NAMESPACE_SCHEMA: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/schemas/xml.xsd");

/// The validator and the two schema trees.
#[derive(Debug)]
pub struct Harness {
    xmllint: PathBuf,
    /// ECMA-376 Part 4, `OfficeOpenXML-XMLSchema-Transitional`.
    markup_schemas: PathBuf,
    /// ECMA-376 Part 2, `OpenPackagingConventions-XMLSchema`.
    packaging_schemas: PathBuf,
    /// Where the generated driver schemas live.
    drivers: PathBuf,
}

impl Harness {
    /// The absolute path of the XSD governing a namespace, in its own tree.
    #[must_use]
    pub fn schema_path(&self, schema: SchemaRef) -> PathBuf {
        match schema.set {
            SchemaSet::Markup => self.markup_schemas.join(schema.file),
            SchemaSet::Packaging => self.packaging_schemas.join(schema.file),
        }
    }

    /// The driver schema that pairs `schema` with the XML-namespace schema, writing it if needed.
    fn driver_path(&self, schema: SchemaRef, namespace: &str) -> PathBuf {
        let driver = self.drivers.join(format!("driver-{}", schema.file));
        if driver.is_file() {
            return driver;
        }
        let target = self.schema_path(schema);
        let source = format!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
             <!-- Generated by mjx-schema-gate; see harness.rs for why. -->\n\
             <xsd:schema xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  \
             <xsd:import namespace=\"http://www.w3.org/XML/1998/namespace\" \
             schemaLocation=\"{xml}\"/>\n  \
             <xsd:import namespace=\"{namespace}\" schemaLocation=\"{target}\"/>\n\
             </xsd:schema>\n",
            xml = XML_NAMESPACE_SCHEMA,
            target = target.display(),
        );
        // Written under a unique name and renamed into place: two test binaries may reach this at
        // the same moment, and a half-written schema would be reported as a compile failure.
        // Unique per call, not merely per process: cargo runs the cases in a binary concurrently
        // and two threads reach this for the same schema at the same moment.
        static SERIAL: AtomicUsize = AtomicUsize::new(0);
        let staging = self.drivers.join(format!(
            "driver-{}.{}.{}.staging",
            schema.file,
            std::process::id(),
            SERIAL.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::write(&staging, source).expect("write the driver schema");
        std::fs::rename(&staging, &driver).expect("publish the driver schema");
        driver
    }

    /// Runs the validator over one file and returns its report when the part fails to validate.
    ///
    /// A schema that fails to *compile* is a harness fault, not a fixture defect, so it panics
    /// rather than being reported as invalid markup.
    ///
    /// # Panics
    /// If `xmllint` cannot be run, or the schema does not compile.
    #[must_use]
    pub fn validate(&self, schema: SchemaRef, namespace: &str, file: &Path) -> Option<String> {
        let driver = self.driver_path(schema, namespace);
        let output = Command::new(&self.xmllint)
            .arg("--noout")
            .arg("--schema")
            .arg(&driver)
            .arg(file)
            .output()
            .unwrap_or_else(|e| panic!("running {}: {e}", self.xmllint.display()));

        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        assert!(
            !stderr.contains("failed to compile"),
            "{} failed to compile — the schema tree is unusable:\n{stderr}",
            self.schema_path(schema).display()
        );
        if output.status.success() {
            return None;
        }
        // Keep only the validity errors: the trailing "<file> fails to validate" line tells the
        // caller nothing it does not know, and a libxml2 parser *warning* is not a deviation.
        let report: Vec<&str> = stderr
            .lines()
            .filter(|line| !line.ends_with("fails to validate"))
            .filter(|line| !line.contains("warning :"))
            .collect();
        Some(report.join("\n"))
    }
}

/// Searches `PATH`, then a few well-known locations, for `name`.
fn find_on_path(name: &str) -> Option<PathBuf> {
    if let Some(path) = std::env::var_os("PATH") {
        for dir in std::env::split_paths(&path) {
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    ["/usr/bin", "/usr/local/bin", "/opt/homebrew/bin"]
        .iter()
        .map(|dir| Path::new(dir).join(name))
        .find(|p| p.is_file())
}

/// A directory of XSDs, located from an environment override or the git-ignored `References/` tree
/// at the workspace root, and confirmed present by **every** schema this gate validates against.
///
/// Checking all of them, not one marker, is what makes a half-extracted tree skip loudly instead of
/// reporting perfectly good markup as invalid because the schema behind it was missing.
///
/// `References/` is never read as a *committed* test input — its absence skips the gate.
fn find_schema_dir(env_var: &str, default_suffix: &str, markers: &[&str]) -> Option<PathBuf> {
    let candidate = match std::env::var_os(env_var) {
        Some(dir) => PathBuf::from(dir),
        None => workspace_root().join("References").join(default_suffix),
    };
    if !markers
        .iter()
        .all(|marker| candidate.join(marker).is_file())
    {
        return None;
    }
    // Canonicalized: the schemas import one another by absolute path, and libxml2 warns about a
    // "duplicate" import when the same file is reached by two spellings of the same directory.
    Some(candidate.canonicalize().unwrap_or(candidate))
}

/// The harness, or `None` when the gate should skip.
///
/// Skipping prints a notice and passes, so the workspace stays green without the reference schemas.
/// `MJX_REQUIRE_SCHEMA` turns a missing tool or schema tree into a hard failure.
///
/// # Panics
/// If `MJX_REQUIRE_SCHEMA` is set and anything is missing.
#[must_use]
pub fn harness() -> Option<Harness> {
    let xmllint = find_on_path("xmllint");
    // Every markup schema `MODELED_SCHEMAS` names must be present, not just one marker.
    let markup = find_schema_dir(
        "MJX_SCHEMA_DIR",
        "ECMA-376-4_5th_edition_december_2016/OfficeOpenXML-XMLSchema-Transitional",
        &crate::categories::MODELED_SCHEMAS
            .iter()
            .filter(|entry| entry.schema.set == SchemaSet::Markup)
            .map(|entry| entry.schema.file)
            .collect::<Vec<_>>(),
    );
    let packaging = find_schema_dir(
        "MJX_OPC_SCHEMA_DIR",
        "ECMA-376-2_5th_edition_december_2021/OpenPackagingConventions-XMLSchema",
        &crate::categories::MODELED_SCHEMAS
            .iter()
            .filter(|entry| entry.schema.set == SchemaSet::Packaging)
            .map(|entry| entry.schema.file)
            .collect::<Vec<_>>(),
    );

    if let (Some(xmllint), Some(markup_schemas), Some(packaging_schemas)) =
        (&xmllint, &markup, &packaging)
    {
        return Some(Harness {
            xmllint: xmllint.clone(),
            drivers: driver_dir(markup_schemas, packaging_schemas),
            markup_schemas: markup_schemas.clone(),
            packaging_schemas: packaging_schemas.clone(),
        });
    }

    let mut missing = Vec::new();
    if xmllint.is_none() {
        missing.push("xmllint");
    }
    if markup.is_none() {
        missing.push("the ECMA-376 Part 4 Transitional schemas (References/ or MJX_SCHEMA_DIR)");
    }
    if packaging.is_none() {
        missing.push("the ECMA-376 Part 2 OPC schemas (References/ or MJX_OPC_SCHEMA_DIR)");
    }
    let missing = missing.join(", ");
    assert!(
        std::env::var_os("MJX_REQUIRE_SCHEMA").is_none(),
        "MJX_REQUIRE_SCHEMA is set but {missing} could not be found"
    );
    eprintln!("skipping schema-validity tests: {missing} not available on this machine");
    None
}

/// A directory for the generated driver schemas, named after the two schema trees so a run with a
/// different `MJX_SCHEMA_DIR` cannot reuse drivers pointing at the other one.
fn driver_dir(markup: &Path, packaging: &Path) -> PathBuf {
    let mut hasher = DefaultHasher::new();
    markup.hash(&mut hasher);
    packaging.hash(&mut hasher);
    XML_NAMESPACE_SCHEMA.hash(&mut hasher);
    let dir = std::env::temp_dir().join(format!("mjx-schema-gate-{:016x}", hasher.finish()));
    std::fs::create_dir_all(&dir).expect("create the driver schema directory");
    dir
}

/// A private working directory under the system temp dir, removed on drop.
#[derive(Debug)]
pub struct WorkDir(PathBuf);

impl WorkDir {
    /// A fresh directory tagged with `tag`, unique per process and per call.
    ///
    /// # Panics
    /// If the directory cannot be created.
    #[must_use]
    pub fn new(tag: &str) -> Self {
        // Cargo runs the cases in a binary concurrently and several of them inspect the same deck,
        // so the pid alone does not make the name unique — a serial number does. Without it one case
        // clears the directory another is still writing into.
        static SERIAL: AtomicUsize = AtomicUsize::new(0);
        let serial = SERIAL.fetch_add(1, Ordering::Relaxed);
        let dir =
            std::env::temp_dir().join(format!("mjx_schema_{tag}_{}_{serial}", std::process::id()));
        // Fresh: clear any leftovers from a previous crashed run.
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create work dir");
        Self(dir)
    }

    /// The directory's path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for WorkDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_xml_namespace_schema_is_committed_and_declares_xml_space() {
        let source = std::fs::read_to_string(XML_NAMESPACE_SCHEMA)
            .expect("the XML-namespace schema ships with this crate");
        assert!(
            source.contains(r#"targetNamespace="http://www.w3.org/XML/1998/namespace""#),
            "the committed schema must target the XML namespace"
        );
        assert!(
            source.contains(r#"<xsd:attribute name="space">"#),
            "`xml:space` is the one attribute ECMA-376 references; without it `wml.xsd` cannot \
             compile"
        );
    }
}
