//! `mjx-ooxml-core` — shared foundations for the mjx-ooxml-rs workspace.
//!
//! This is the bottom layer of the workspace: it has **no dependencies**, and every other crate
//! builds on it. It provides two things today.
//!
//! # String interning
//!
//! OOXML repeats the same namespace URIs and element/attribute names thousands of times per part.
//! [`Interner`] stores each distinct string once and hands out a 4-byte [`Symbol`], so equality is an
//! integer compare and memory stays flat. One interner is created per parsed part (it lives on
//! [`RawDocument`]).
//!
//! # The raw preservation tree
//!
//! [`RawDocument`] → [`RawNode`] → [`RawElement`] is a **lossless DOM**. Names are interned
//! [`Symbol`]s; attribute values and text are stored as *raw, escaped bytes* exactly as they appeared
//! in the source. That is what lets the `mjx-xml` fidelity writer reproduce a part's bytes exactly.
//! A `Vec<RawNode>` also serves as the "unknown content bucket" the future typed model carries so it
//! can round-trip anything it does not itself model.
//!
//! Trees are normally produced by the `mjx-xml` fidelity reader rather than built by hand.
//!
//! # Typed-model conversion
//!
//! [`FromXml`] / [`ToXml`] (in [`convert`]) are the seam between the raw tree and typed models: a
//! type parses itself out of a [`RawElement`] and rebuilds one, reusing interned [`Symbol`]s so the
//! result round-trips. The format crates implement them (by hand first, later via `mjx-derive`).
//!
//! # Typed attributes
//!
//! [`attribute`] holds the other half of that seam: [`AttributeCodec`], the wire ⇄ Rust conversion
//! for one kind of attribute value, and [`AttributeError`], what reading one can fail with. A modeled
//! type keeps its attribute vector verbatim and exposes accessors over it — generated by
//! `#[derive(XmlAttributes)]` in `mjx-derive` — so unknown attributes, their order and their quote
//! style survive untouched.
//!
//! # Byte-budgeted caches
//!
//! [`cache`] holds [`ByteBudgetCache`], the workspace's one least-recently-used cache with a
//! declared byte ceiling. It is here for the same reason [`Emu`] is: three crates at three
//! different ranks need one — `mjx-scene`'s tessellation cache at 1.7, `mjx-session`'s worksheet
//! residency at 3.5 and `mjx-view`'s per-stage caches at 3.8 — and a cache written in the highest
//! of those is unreachable from the other two.
//!
//! # Measures
//!
//! [`measure`] holds the two units that are nobody's markup: [`Emu`], the English
//! Metric Unit every length in every one of the three formats finally reduces to, and
//! [`Angle`]. They were `mjx-dml`'s until MJXOFF-160 and now sit here, because the
//! client platform's box model (`mjx-layout`, rank 1.6) positions every fragment in EMU and may not
//! reach `mjx-dml` (rank 2.0). `mjx-dml` re-exports them, so there is still exactly one `Emu` in the
//! workspace.
//!
//! Later phases also add the arena + stable-handle primitives, when the typed model needs them (see
//! `PLAN.md`).
//!
//! # Example
//!
//! ```
//! use mjx_ooxml_core::Interner;
//!
//! let mut interner = Interner::new();
//! let a = interner.intern("w:val");
//! let b = interner.intern("w:val"); // same string → same symbol, no second allocation
//! assert_eq!(a, b);
//! assert_eq!(interner.resolve(a), "w:val");
//! ```

pub mod attribute;
pub mod cache;
pub mod convert;
pub mod intern;
pub mod measure;
pub mod raw;

pub use attribute::{
    AttributeCodec, AttributeError, Enumeration, InvalidAttributeValue, Number, Text,
};
pub use cache::{Admission, ByteBudgetCache, CacheStats, Rejection, ENTRY_OVERHEAD_BYTES};
pub use convert::{FromXml, FromXmlError, ToXml};
pub use intern::{Interner, Symbol};
pub use measure::{Angle, Emu};
pub use raw::{
    QuoteStyle, RawAttribute, RawDocument, RawElement, RawElementContent, RawName, RawNode,
};
