//! `mjx-omml` — Office MathML (`shared-math.xsd`, ECMA-376 Part 1 §22.1, targetNamespace
//! `http://schemas.openxmlformats.org/officeDocument/2006/math`): the equation markup Word embeds as
//! `m:oMath`/`m:oMathPara`.
//!
//! # What this crate models
//!
//! All 72 `shared-math.xsd` complex types. Structure: [`Math`] (`m:oMath`, `CT_OMath`),
//! [`MathParagraph`] (`m:oMathPara`, `CT_OMathPara`), [`arg::Argument`] (`CT_OMathArg` — every
//! object's own operand slot, and the crate's recursive core), [`objects::Run`] (`m:r`, `CT_R`),
//! [`leaf::Text`] (`m:t`, `CT_Text`), [`leaf::ControlProperties`] (`m:ctrlPr`, `CT_CtrlPr`),
//! [`leaf::RunProperties`] (`m:rPr`, `CT_RPR`). Objects and their paired `*Pr` properties types (see
//! `objects`): accent, bar, box, border box, delimiter, equation array, fraction, function-apply,
//! group character, lower/upper limit, matrix (with its row/column/column-properties family), n-ary
//! operator, phantom, radical, and the four script forms (pre-script, subscript, superscript,
//! subscript-superscript). Document-level [`properties::MathProperties`] (`m:mathPr`, `CT_MathPr`).
//! **Twenty leaf `CT_*` value types** (`CT_OnOff`, `CT_Shp`, `CT_Integer255`, …) share one Rust
//! mechanism rather than twenty near-identical types — see `leaf`'s own doc comment, and
//! [`objects::ControlOnlyProperties`]'s for the six single-`ctrlPr`-child `*Pr` types that do the
//! same. `mjx-ooxml-types::officemath` (generated by MJXOFF-144) supplies every one of the schema's
//! 14 simple types (`ST_Shp` → [`mjx_ooxml_types::officemath::DelimiterShape`], `ST_LimLoc` →
//! [`mjx_ooxml_types::officemath::LimitLocation`], and so on) — this crate never hand-writes one.
//!
//! # The layering tension, and how it is resolved
//!
//! `CT_CtrlPr` (`m:ctrlPr`) — the trailing control-properties pass-through every object's own `*Pr`
//! type may carry — is, in the schema's own words, `EG_RPrMath`: a `w:rPr` (`CT_RPr`), or a `w:ins`/
//! `w:del` (`CT_MathCtrlIns`/`CT_MathCtrlDel`, which themselves extend `CT_TrackChange` and carry a
//! `w:rPr`). Every one of those is a WordprocessingML type. `shared-math.xsd` itself imports
//! `wml.xsd` for exactly this reason — the schema places a `wml` type inside a `shared-math` type,
//! which is the standard's own layering, not an artifact of this workspace's crate boundaries. But
//! `mjx-omml` sits *below* `mjx-docx` in this project's dependency graph (`mjx-ooxml-core`,
//! `mjx-xml`, `mjx-derive`, `mjx-ooxml-types` only), so it cannot name `mjx-docx`'s `RunProperties`,
//! and mirroring the schema's own direction would be exactly the upward edge CLAUDE.md's layering
//! rule forbids.
//!
//! The resolution: [`leaf::ControlProperties`] preserves its children **wholesale, raw** — the same
//! mechanism `mjx-dml`'s `WordprocessingGroup`/`WordprocessingCanvas` already use for their own
//! WordprocessingML-typed member shapes, for the identical reason. Every byte round-trips regardless
//! of whether this crate understands what is inside; `mjx-docx`, which already depends on this crate,
//! adds typed accessors **over** a `ControlProperties`' raw children where it needs them — see
//! `crates/mjx-docx/src/document/revisions.rs`'s own `CT_MathCtrlIns`/`CT_MathCtrlDel` types, added
//! by this same child as the reachable call site MJXOFF-126 deferred them for want of. This is not a
//! narrower feature than "model `CT_CtrlPr`'s children" — every object in this crate that carries a
//! `ctrlPr` exposes it as a typed [`leaf::ControlProperties`] whose own raw children are exactly as
//! reachable (by whoever can type them) as a fully-decomposed field would be, and fidelity does not
//! depend on which side of the crate boundary the decomposition happens on.
//!
//! # Fidelity
//!
//! Every modelled type is a fidelity wrapper — `name`/`attributes`/`children`/`empty`, preserved
//! verbatim on `to_xml` — with typed **read** accessors layered over the preserved state, never a
//! decomposed set of typed fields to lose track of unknown content. An equation parsed and re-emitted
//! without an edit is byte-identical; editing one leaf (an [`leaf::Text`]'s own characters, several
//! nesting levels deep) leaves every sibling, at every level, untouched — the standard
//! `RawElement::replace_preserving_verbatim_source`/copy-on-write machinery this project already
//! relies on everywhere else, which needs nothing extra from this crate to keep working.
//!
//! # Example
//!
//! ```
//! use mjx_ooxml_core::FromXml;
//! use mjx_omml::Math;
//!
//! let doc = mjx_xml::fidelity::parse(
//!     br##"<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">
//!   <m:f>
//!     <m:num><m:r><m:t>1</m:t></m:r></m:num>
//!     <m:den><m:r><m:t>2</m:t></m:r></m:den>
//!   </m:f>
//! </m:oMath>"##,
//! )
//! .expect("parse the equation");
//! let math = Math::from_xml(&doc.root, &doc.interner).expect("read m:oMath");
//! let elements = math.elements(&doc.interner);
//! assert_eq!(elements.len(), 1);
//! let mjx_omml::MathElement::Fraction(fraction) = &elements[0] else {
//!     panic!("expected a fraction");
//! };
//! let numerator = fraction.numerator(&doc.interner).expect("m:num is present");
//! assert_eq!(numerator.elements(&doc.interner).len(), 1);
//! ```

mod arg;
mod leaf;
mod math;
mod objects;
mod properties;
mod support;

pub use arg::{Argument, ArgumentProperties};
pub use leaf::{ControlProperties, RunProperties, Text};
pub use math::{Math, MathParagraph, MathParagraphProperties};
pub use objects::{
    Accent, AccentProperties, Bar, BarProperties, BorderBox, BorderBoxProperties,
    ControlOnlyProperties, Delimiter, DelimiterProperties, EquationArray, EquationArrayProperties,
    Fraction, FractionProperties, Function, GroupCharacter, GroupCharacterProperties, LowerLimit,
    MathBox, MathElement, Matrix, MatrixColumn, MatrixColumnProperties, MatrixColumns,
    MatrixProperties, MatrixRow, NaryOperator, NaryOperatorProperties, Phantom, PhantomProperties,
    PreScript, Radical, RadicalProperties, Run, Subscript, SubscriptSuperscript,
    SubscriptSuperscriptProperties, Superscript, UpperLimit,
};
pub use properties::MathProperties;
