//! `mjx_ooxml` for Python — the whole PowerPoint surface, as an extension module.
//!
//! ```python
//! import mjx_ooxml
//!
//! deck = mjx_ooxml.Deck.open(open("in.pptx", "rb").read())
//! for index in range(deck.slide_count()):
//!     print(index, deck.shape_text(index, 0))
//! ```
//!
//! # What this crate is
//!
//! A thin, complete projection of [`mjx_ooxml`] — 257 `Deck` methods and the 205 classes their
//! arguments and results are made of. It adds no behaviour: every method calls exactly one method
//! one layer down, and every class wraps exactly one value. What it *does* add is the shape a
//! Python caller expects — an exception hierarchy, keyword arguments, `bytes`, `list`, `dict`, and
//! a bare `int` where Rust would take an `impl Into<Surface>`.
//!
//! ## The mapping is identity
//!
//! `mjx-ooxml`'s method and field names are already `snake_case` and already self-explanatory, so
//! nothing is renamed: `deck.set_shape_run_properties(…)` in Rust is
//! `deck.set_shape_run_properties(…)` in Python, and the guide translates line for line. There are
//! exactly two exceptions, both forced:
//!
//! * `None` is a Python keyword, so the `None` **member** of nine enumerations is spelled `NONE`.
//!   See [`enums`].
//! * `Deck.presentation`, `Deck.presentation_mut` and `Deck.into_presentation` are absent, because
//!   all three hand back a `Presentation` — the Rust-only escape hatch whose value is precisely the
//!   `ShapeCursor` and closure-taking readers a binding cannot carry.
//!
//! The WebAssembly binding diverges on purpose: it is `camelCase`, because a `snake_case` API is an
//! immediate smell to a TypeScript consumer, while Python's own standard library is `snake_case`.
//!
//! # Safety
//!
//! This crate carries `#![allow(unsafe_code)]`, against a workspace that denies it. The
//! justification, in full:
//!
//! **There is no hand-written `unsafe` in this crate.** Every `unsafe` block reaching the compiler
//! is generated by `#[pyclass]`, `#[pymethods]`, `#[pyfunction]` or `#[pymodule]` — the macros that
//! own the CPython ABI contract, implement `PyTypeInfo` and `PyClassImpl`, and lay out the type
//! objects CPython requires. The allowance exists because those expansions land in this crate's
//! token stream, not because this crate performs unsafe operations of its own. This is the first
//! use of the `deny`-not-`forbid` escape hatch the workspace lints were written to permit
//! (`Cargo.toml`'s `[workspace.lints.rust]`), and CI enforces the claim: `.github/workflows/ci.yml`
//! greps `bindings/*/src` for `unsafe` outside this comment and fails if it finds any.
//!
//! # Panics
//!
//! A panic crossing the CPython boundary is not a Python exception; PyO3 catches the unwind and
//! turns it into `pyo3_runtime.PanicException`, which is why the workspace release profile keeps
//! `panic = "unwind"`. But that is a backstop, not a design: **every fallible path in this crate
//! returns a `PyErr`.** No `unwrap`, no `expect`, no indexing that can go out of range — the
//! conversions in [`errors`] are written so that even a failure while *building* an exception
//! yields an exception.

// See the module documentation above: no hand-written `unsafe` appears in this crate; the
// allowance covers only the blocks the PyO3 attribute macros generate.
#![allow(unsafe_code)]

use pyo3::prelude::*;
use pyo3::types::PyModule;

#[macro_use]
mod support;

// Every module is public so the crate is usable as an ordinary Rust library too — `cargo test`
// builds it as an `rlib` — and so that `unreachable_pub` has nothing to complain about: a
// `#[pyclass]` must be nameable from wherever PyO3's generated code refers to it.
pub mod address;
pub mod charts;
pub mod content;
pub mod deck;
pub mod enums;
pub mod errors;
pub mod format;
pub mod geometry;
pub mod measures;
pub mod paint;
pub mod tables;
pub mod text;
pub mod three_d;

/// The `mjx_ooxml` extension module.
///
/// Registration order matters only for the exceptions, which are created on first use and must
/// exist before any method can raise one; everything else is independent.
#[pymodule]
fn _mjx_ooxml(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add("__doc__", MODULE_DOC)?;
    module.add("__version__", env!("CARGO_PKG_VERSION"))?;

    errors::register(module)?;
    enums::register(module)?;
    address::register(module)?;
    measures::register(module)?;
    paint::register(module)?;
    text::register(module)?;
    geometry::register(module)?;
    three_d::register(module)?;
    tables::register(module)?;
    charts::register(module)?;
    content::register(module)?;
    format::register(module)?;
    deck::register(module)?;

    // `__all__` is derived from what was actually registered, so it cannot drift from the module:
    // a class added above appears here, and one removed disappears. `from mjx_ooxml import *`
    // therefore imports exactly the documented surface and nothing else.
    let mut exported: Vec<String> = module
        .dict()
        .keys()
        .iter()
        .filter_map(|name| name.extract::<String>().ok())
        .filter(|name| !name.starts_with("__"))
        .collect();
    exported.sort();
    module.add("__all__", exported)
}

/// What `help(mjx_ooxml)` shows.
const MODULE_DOC: &str = "\
Read, edit and write PowerPoint files — a pure-Rust OOXML library, bound to Python.

    import mjx_ooxml

    deck = mjx_ooxml.Deck.blank(mjx_ooxml.SlideSize.widescreen())
    slide = deck.add_slide_from_layout(0)
    deck.add_text_box(slide, 'Hello', mjx_ooxml.ShapeBounds.from_inches(1, 1, 6, 1))
    open('out.pptx', 'wb').write(deck.save())

The library is bytes in and bytes out: it never touches a filesystem, a clock, a thread or a
random number generator, so the file I/O above is deliberately the caller's.

Addressing. A surface is an int (the slide index) or a Surface; a shape is an int (a top-level
shape), a list of ints (a descent through groups), or a ShapePath. Both spellings work wherever
either is expected.

Errors. Everything raises a subclass of OoxmlError, one per error code, each carrying .code and
the coordinates .surface, .shape, .row, .column and .index. IndexOutOfRangeError is also an
IndexError.

Threading. Use one Deck from one thread. Deck.open and Deck.save release the interpreter lock;
nothing else does enough work to be worth it.
";
