//! The four artefacts, rendered from one checked [`TokenSet`].
//!
//! Each renderer is pure — `&TokenSet -> String` — which is what lets the `--check` mode compare
//! what the source *would* produce against what is committed without writing anything, and what
//! lets the tests below generate from a synthetic source in memory.
//!
//! Three of them are written for consumers that share nothing: a stylesheet the Web-Component
//! chrome imports, a module the shell's TypeScript imports, and a Rust table the document canvas
//! reads. Every value therefore has to survive three spellings of the same name and one spelling of
//! the same value; `crates/mjx-tokens/tests/artefacts_agree.rs` is what proves it did.
//!
//! The fourth, [`derivations_css`], is written for the *cascade* rather than for a consumer: it
//! restates the derived tier as the `color-mix()` it came from, so that a host overriding a seed
//! re-themes everything mixed from it. See that function's documentation for why it is a separate
//! file.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::codegen::tokens::model::{
    custom_property, derivation_reference, dotted, number, rust_field, scheme_aliases,
    typescript_path, typescript_property, Derivation, Entry, Group, Length, MixNode, MixPercentage,
    MixTerm, Rgba, SchemeAlias, Shadow, Token, TokenSet, Usage, Value,
};

/// The line every artefact opens with, so a reader who lands in one of them knows in the first line
/// that editing it is pointless.
const GENERATED_BY: &str =
    "@generated by `cargo run -p xtask -- tokens` from docs/client-platform/data/tokens.json.";

/// The width prose is wrapped to inside a generated comment.
const COMMENT_WIDTH: usize = 96;

/// Wraps `text` to `width` columns on whitespace. Descriptions in the source are single-paragraph,
/// so there is no paragraph handling to do.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.chars().count() + 1 + word.chars().count() > width {
            lines.push(std::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        lines.push(line);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}

/// A token's one-line provenance note: what it may be used for, and what it measured. It reads the
/// same in all three artefacts on purpose — the note is part of the token, not of the file.
fn provenance(token: &Token) -> Option<String> {
    let usage = token.usage?;
    let mut note = format!("usage `{}`", usage.as_str());
    if let (Some(background), Some(contrast)) = (token.background.as_ref(), token.contrast) {
        let _ = write!(note, " · {contrast:.2} : 1 on `{background}`");
    }
    Some(note)
}

// ---------------------------------------------------------------------------------------------
// tokens.css
// ---------------------------------------------------------------------------------------------

/// Renders `ui/tokens/tokens.css`.
///
/// Two layers. The first declares every token in the source as a flat custom property under the
/// name the source stylesheet itself uses (`--color-paper`, `--radius-card`), which is what makes
/// *"drop the platform into a host that already defines these properties and it re-themes with no
/// code change"* true rather than aspirational. The second resolves each scheme group onto a
/// scheme-independent name (`--theme-background`), in the only cascade order that behaves: light by
/// default, dark when the system asks for it and the host has not said otherwise, dark whenever the
/// host says so explicitly.
pub(crate) fn css(set: &TokenSet) -> String {
    let mut out = String::new();
    out.push_str("/*\n");
    let _ = writeln!(out, " * {GENERATED_BY}");
    out.push_str(" * DO NOT EDIT. Edit the source and regenerate.\n *\n");
    for line in wrap(&set.description, COMMENT_WIDTH) {
        let _ = writeln!(out, " * {line}");
    }
    out.push_str(" */\n\n:root {\n");
    css_entries(&set.entries, &mut out);
    out.push_str("}\n");

    let aliases = scheme_aliases(set);
    if !aliases.is_empty() {
        css_scheme_layer(set, &aliases, &mut out);
    }
    out
}

fn css_entries(entries: &[Entry], out: &mut String) {
    for entry in entries {
        match entry {
            Entry::Group(group) => {
                let _ = writeln!(out, "\n  /* ── {} ──", dotted(&group.path));
                if let Some(description) = &group.description {
                    for line in wrap(description, COMMENT_WIDTH - 5) {
                        let _ = writeln!(out, "     {line}");
                    }
                }
                out.push_str("  */\n");
                css_entries(&group.entries, out);
            }
            Entry::Token(token) => {
                if let Some(description) = &token.description {
                    for line in wrap(description, COMMENT_WIDTH - 5) {
                        let _ = writeln!(out, "  /* {line} */");
                    }
                }
                if let Some(note) = provenance(token) {
                    let _ = writeln!(out, "  /* {note} */");
                }
                let _ = writeln!(
                    out,
                    "  {}: {};",
                    custom_property(&token.path),
                    token.value.css()
                );
            }
        }
    }
}

fn css_scheme_layer(set: &TokenSet, aliases: &[SchemeAlias], out: &mut String) {
    let default_scheme = 0;
    out.push_str("\n/*\n * The colour-scheme layer. Every property below resolves to whichever\n");
    out.push_str(" * scheme is in force, so a component names `--theme-surface` and never a\n");
    out.push_str(" * scheme. The order of the three rules is the behaviour: the light scheme is\n");
    out.push_str(" * the default, the system's preference wins unless the host has asked for\n");
    out.push_str(" * light, and an explicit `data-theme` wins over both.\n */\n");

    let _ = writeln!(out, "\n:root {{");
    for alias in aliases {
        let _ = writeln!(
            out,
            "  {}: var({});",
            alias.custom_property, alias.per_scheme[default_scheme]
        );
    }
    out.push_str("}\n");

    for (at, scheme) in set.scheme_names.iter().enumerate().skip(1) {
        let _ = writeln!(
            out,
            "\n@media (prefers-color-scheme: {scheme}) {{\n  :root:not([data-theme=\"{}\"]) {{",
            set.scheme_names[default_scheme]
        );
        for alias in aliases {
            let _ = writeln!(
                out,
                "    {}: var({});",
                alias.custom_property, alias.per_scheme[at]
            );
        }
        out.push_str("  }\n}\n");
    }

    for (at, scheme) in set.scheme_names.iter().enumerate() {
        if at == default_scheme {
            continue;
        }
        let _ = writeln!(out, "\n:root[data-theme=\"{scheme}\"] {{");
        for alias in aliases {
            let _ = writeln!(
                out,
                "  {}: var({});",
                alias.custom_property, alias.per_scheme[at]
            );
        }
        out.push_str("}\n");
    }
}

// ---------------------------------------------------------------------------------------------
// tokens.ts
// ---------------------------------------------------------------------------------------------

/// Renders `ui/tokens/tokens.ts`: one interface per group, the `Tokens` type, the constant that
/// satisfies it, and the map from a token's path to the CSS custom property a host would override
/// it with — which is the half of the runtime resolver's contract this child owns.
///
/// Property names are **camelCase**, from the same rule `bindings/mjx-wasm` applies to every method
/// it exports: a `snake_case` API is an immediate smell to a TypeScript consumer.
pub(crate) fn typescript(set: &TokenSet) -> String {
    let mut out = String::new();
    out.push_str("/**\n");
    let _ = writeln!(out, " * {GENERATED_BY}");
    out.push_str(" * DO NOT EDIT. Edit the source and regenerate.\n *\n");
    for line in wrap(&set.description, COMMENT_WIDTH) {
        let _ = writeln!(out, " * {line}");
    }
    out.push_str(" */\n");

    let mut emitted: BTreeSet<&str> = BTreeSet::new();
    for group in set.groups() {
        if !emitted.insert(group.rust_type.as_str()) {
            continue;
        }
        typescript_interface(group, &mut out);
    }

    out.push_str("\n/** The whole token set. */\nexport interface Tokens {\n");
    typescript_members(&set.entries, &mut out);
    out.push_str("}\n");

    if !set.scheme_names.is_empty() {
        out.push_str("\n/** The colour schemes every scheme group in the source declares. */\n");
        let _ = writeln!(
            out,
            "export type ColorScheme = {};",
            set.scheme_names
                .iter()
                .map(|scheme| format!("'{scheme}'"))
                .collect::<Vec<_>>()
                .join(" | ")
        );
    }

    out.push_str("\n/** The generated defaults — the values this platform ships with. */\n");
    out.push_str("export const tokens: Tokens = {\n");
    typescript_values(&set.entries, 1, &mut out);
    out.push_str("};\n");

    out.push_str(
        "
/**
 * Every token's CSS custom property, keyed by its path in `tokens`. A runtime resolver reads these
 * names off the host element; a host that already defines one is re-theming the platform, which is
 * exactly what it is meant to be able to do.
 */
export const customProperties: Readonly<Record<string, string>> = {
",
    );
    for token in set.tokens() {
        let _ = writeln!(
            out,
            "  '{}': '{}',",
            typescript_path(&token.path),
            custom_property(&token.path)
        );
    }
    out.push_str("};\n");
    out
}

fn typescript_interface(group: &Group, out: &mut String) {
    out.push('\n');
    typescript_doc(group.description.as_deref(), None, 0, out);
    let _ = writeln!(out, "export interface {} {{", group.rust_type);
    typescript_members(&group.entries, out);
    out.push_str("}\n");
}

fn typescript_members(entries: &[Entry], out: &mut String) {
    for entry in entries {
        match entry {
            Entry::Group(group) => {
                typescript_doc(group.description.as_deref(), None, 1, out);
                let _ = writeln!(
                    out,
                    "  readonly {}: {};",
                    typescript_property(group.path.last().map_or("", String::as_str)),
                    group.rust_type
                );
            }
            Entry::Token(token) => {
                // TypeScript erases the token's own type — a dimension and a colour are both
                // `string` — so the note carries it. Rust's field type says it already.
                let note = format!(
                    "CSS: `{}` · type `{}`{}",
                    custom_property(&token.path),
                    token.value.type_name(),
                    provenance(token).map_or_else(String::new, |note| format!(" · {note}"))
                );
                typescript_doc(token.description.as_deref(), Some(&note), 1, out);
                let _ = writeln!(
                    out,
                    "  readonly {}: {};",
                    typescript_property(token.path.last().map_or("", String::as_str)),
                    if token.value.is_typescript_number() {
                        "number"
                    } else {
                        "string"
                    }
                );
            }
        }
    }
}

fn typescript_doc(description: Option<&str>, note: Option<&str>, depth: usize, out: &mut String) {
    if description.is_none() && note.is_none() {
        return;
    }
    let pad = "  ".repeat(depth);
    let _ = writeln!(out, "{pad}/**");
    if let Some(description) = description {
        for line in wrap(description, COMMENT_WIDTH - pad.len() - 3) {
            let _ = writeln!(out, "{pad} * {line}");
        }
    }
    if let Some(note) = note {
        if description.is_some() {
            let _ = writeln!(out, "{pad} *");
        }
        for line in wrap(note, COMMENT_WIDTH - pad.len() - 3) {
            let _ = writeln!(out, "{pad} * {line}");
        }
    }
    let _ = writeln!(out, "{pad} */");
}

fn typescript_values(entries: &[Entry], depth: usize, out: &mut String) {
    let pad = "  ".repeat(depth);
    for entry in entries {
        match entry {
            Entry::Group(group) => {
                let _ = writeln!(
                    out,
                    "{pad}{}: {{",
                    typescript_property(group.path.last().map_or("", String::as_str))
                );
                typescript_values(&group.entries, depth + 1, out);
                let _ = writeln!(out, "{pad}}},");
            }
            Entry::Token(token) => {
                let rendered = token.value.css();
                let value = if token.value.is_typescript_number() {
                    rendered
                } else {
                    format!("'{}'", rendered.replace('\\', "\\\\").replace('\'', "\\'"))
                };
                let _ = writeln!(
                    out,
                    "{pad}{}: {value},",
                    typescript_property(token.path.last().map_or("", String::as_str))
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------------------------
// crates/mjx-tokens/src/generated.rs
// ---------------------------------------------------------------------------------------------

/// Renders `crates/mjx-tokens/src/generated.rs`: the group structs, the `Tokens` struct, its
/// `const` default table, the two accessors the runtime resolver drives it through, and the index
/// that ties a token's three names together.
///
/// The output is not formatted here; [`super::run`] passes it through `rustfmt` the same way the
/// schema codegen does, so `cargo fmt --all --check` and this generator can never disagree about
/// the committed file.
pub(crate) fn rust(set: &TokenSet) -> String {
    let tokens = set.tokens();
    let mut out = String::new();
    let _ = writeln!(out, "//! {GENERATED_BY}");
    out.push_str("//! DO NOT EDIT. Edit the source and regenerate.\n//!\n");
    for line in wrap(&set.description, COMMENT_WIDTH - 4) {
        let _ = writeln!(out, "//! {line}");
    }

    let mut imports: BTreeSet<&'static str> =
        ["Derivation", "TokenError", "TokenIdentity", "TokenValue"]
            .into_iter()
            .collect();
    imports.insert("parse_token");
    for token in &tokens {
        for name in rust_imports(&token.value) {
            imports.insert(name);
        }
        // Only when something actually declares one, so a source with no colours in it emits a file
        // that still compiles rather than one with an unused import.
        if token.usage.is_some() {
            imports.insert("ColorUsage");
        }
        let Some(derivation) = &token.derivation else {
            continue;
        };
        imports.insert("DerivedFrom");
        let Derivation::Mix(nodes) = derivation else {
            continue;
        };
        imports.insert("MixNode");
        imports.insert("MixTerm");
        for node in nodes {
            if matches!(node.first, MixTerm::Literal(_))
                || matches!(node.second, MixTerm::Literal(_))
            {
                imports.insert("Color");
            }
            for percentage in [&node.first_percentage, &node.second_percentage] {
                match percentage {
                    None => {}
                    Some(MixPercentage::Fixed(_)) => {
                        imports.insert("MixPercentage");
                        imports.insert("Percentage");
                    }
                    Some(MixPercentage::Token(_)) => {
                        imports.insert("MixPercentage");
                    }
                }
            }
        }
    }
    let _ = writeln!(
        out,
        "\nuse crate::{{{}}};\n",
        imports.into_iter().collect::<Vec<_>>().join(", ")
    );

    let mut emitted: BTreeSet<&str> = BTreeSet::new();
    for group in set.groups() {
        if !emitted.insert(group.rust_type.as_str()) {
            continue;
        }
        rust_struct(
            &group.rust_type,
            group.description.as_deref(),
            &group.entries,
            &mut out,
        );
    }

    if !set.scheme_names.is_empty() {
        rust_scheme_enum(set, &mut out);
        let mut seen: BTreeSet<&str> = BTreeSet::new();
        for group in set.groups().into_iter().filter(|group| group.schemes) {
            if !seen.insert(group.rust_type.as_str()) {
                continue;
            }
            rust_scheme_accessor(set, group, &mut out);
        }
    }

    rust_struct(
        "Tokens",
        Some(
            "The whole design-token set: the values the client platform ships with, and the shape a \
             host's overrides are resolved into.",
        ),
        &set.entries,
        &mut out,
    );

    out.push_str(
        "
impl Tokens {
    /// The generated defaults — the bottom of the resolution order *explicit configuration →
    /// host-supplied overrides → generated defaults*.
    pub const DEFAULTS: Self = Self {
",
    );
    rust_default_members(&set.entries, 2, &mut out);
    out.push_str("    };\n");

    out.push_str(
        "
    /// The typed value of one token, by the CSS custom property that names it, or `None` when the
    /// platform defines no such token.
    #[must_use]
    pub fn custom_property(&self, custom_property: &str) -> Option<TokenValue> {
        Some(match custom_property {
",
    );
    for token in &tokens {
        let _ = writeln!(
            out,
            "            {:?} => TokenValue::{}(self.{}{}),",
            custom_property(&token.path),
            rust_token_value_variant(&token.value),
            rust_access(&token.path),
            if matches!(token.value, Value::FontStack(_)) {
                ".clone()"
            } else {
                ""
            }
        );
    }
    out.push_str("            _ => return None,\n        })\n    }\n");

    out.push_str(
        "
    /// Replaces one token's value, parsed from the CSS text a host declared it with.
    ///
    /// # Errors
    ///
    /// [`TokenError::UnknownCustomProperty`] when the platform defines no such token, and
    /// [`TokenError::MalformedValue`] when the text is not a value of that token's type.
    pub fn set_custom_property(
        &mut self,
        custom_property: &str,
        css_text: &str,
    ) -> Result<(), TokenError> {
        match custom_property {
",
    );
    for token in &tokens {
        let _ = writeln!(
            out,
            "            {:?} => self.{} = parse_token(custom_property, css_text)?,",
            custom_property(&token.path),
            rust_access(&token.path)
        );
    }
    out.push_str(
        "            _ => {
                return Err(TokenError::UnknownCustomProperty {
                    custom_property: custom_property.to_owned(),
                })
            }
        }
        Ok(())
    }
}

/// Every token the platform defines, in the order the source declares them, with the three names it
/// goes by — its path in `tokens.json`, its CSS custom property, and its path in `tokens.ts` — and
/// the contrast metadata every colour carries.
///
/// This is what makes the three artefacts comparable. A test that had to re-derive
/// `--color-ink-soft` from `color.inkSoft` itself could agree perfectly with a wrong rule.
///
/// `usage` and `background` are emitted as **data** rather than only as prose in each token's docs
/// (MJXOFF-166), because `xtask`'s generator is not the only writer of `tokens.json`: the canvas
/// harness's live token editor writes back to it and may not depend on `xtask`, so it has to be
/// able to call `mjx_tokens::check_usage` for itself.
pub const TOKENS: &[TokenIdentity] = &[
",
    );
    for token in &tokens {
        let _ = writeln!(
            out,
            "    TokenIdentity {{ path: {:?}, custom_property: {:?}, typescript_path: {:?}, \
             usage: {}, background: {} }},",
            dotted(&token.path),
            custom_property(&token.path),
            typescript_path(&token.path),
            match token.usage {
                None => "None".to_owned(),
                Some(usage) => format!("Some(ColorUsage::{})", usage_variant(usage)),
            },
            match &token.background {
                None => "None".to_owned(),
                Some(path) => format!("Some({path:?})"),
            }
        );
    }
    out.push_str("];\n");

    rust_derivations(set, &mut out);
    out
}

/// The derived tier, as the table `mjx_tokens::Tokens::rederive` walks.
///
/// Emitted in token order, which [`crate::codegen::tokens::model`] has already checked is a
/// topological order — so one forward pass is enough and the runtime needs no scheduler.
fn rust_derivations(set: &TokenSet, out: &mut String) {
    let derived: Vec<&Token> = set
        .tokens()
        .into_iter()
        .filter(|token| token.derivation.is_some())
        .collect();

    out.push_str(
        "
/// Every derived colour, and the `color-mix(in srgb, …)` expression it comes from.
///
/// The committed value of a derived token is what this expression evaluated to for the seeds and
/// knobs the source ships with. `Tokens::rederive` re-evaluates it for whichever seeds actually
/// won, which is the fourth step of the resolution order and the reason a host can re-theme the
/// whole platform by setting one custom property.
///
/// `ui/tokens/derivations.css` states the same expressions for the browser, so the chrome
/// re-derives through the cascade with no code at all;
/// `ui/tokens/chromium-agreement.mjs` asserts the two evaluators agree.
pub const DERIVATIONS: &[Derivation] = &[
",
    );
    for token in derived {
        let derivation = token
            .derivation
            .as_ref()
            .expect("filtered to the derived tokens");
        let _ = writeln!(
            out,
            "    // {}\n    Derivation {{ custom_property: {:?}, source: ",
            dotted(&token.path),
            custom_property(&token.path)
        );
        match derivation {
            Derivation::Alias(path) => {
                let _ = writeln!(
                    out,
                    "        DerivedFrom::Token({:?}),",
                    rust_reference(path)
                );
            }
            Derivation::Mix(nodes) => {
                out.push_str("        DerivedFrom::Mix(&[\n");
                for node in nodes {
                    let _ = writeln!(out, "            {},", rust_mix_node(set, node));
                }
                out.push_str("        ]),\n");
            }
        }
        out.push_str("    },\n");
    }
    out.push_str("];\n");
}

/// A dotted token path as the custom property the Rust table names it by — the token's **own**
/// property, never the scheme alias, for the reason `mjx_tokens::MixTerm::Token` documents.
fn rust_reference(path: &str) -> String {
    custom_property(&path.split('.').map(str::to_owned).collect::<Vec<_>>())
}

fn rust_mix_node(set: &TokenSet, node: &MixNode) -> String {
    format!(
        "MixNode {{ first: {}, first_percentage: {}, second: {}, second_percentage: {} }}",
        rust_mix_term(set, &node.first),
        rust_mix_percentage(set, &node.first_percentage),
        rust_mix_term(set, &node.second),
        rust_mix_percentage(set, &node.second_percentage),
    )
}

fn rust_mix_term(set: &TokenSet, term: &MixTerm) -> String {
    match term {
        MixTerm::Literal(colour) => format!("MixTerm::Literal({})", rust_colour(*colour)),
        MixTerm::Transparent => "MixTerm::Transparent".to_owned(),
        MixTerm::Nested(at) => format!("MixTerm::Nested({at})"),
        // The token's OWN property, never the scheme alias: this table is read by a renderer that
        // already knows which scheme it is painting. `derivations.css` is where the alias goes.
        MixTerm::Token(path) => {
            let _ = set;
            format!("MixTerm::Token({:?})", rust_reference(path))
        }
    }
}

fn rust_mix_percentage(set: &TokenSet, percentage: &Option<MixPercentage>) -> String {
    match percentage {
        None => "None".to_owned(),
        Some(MixPercentage::Fixed(value)) => format!(
            "Some(MixPercentage::Fixed(Percentage {{ value: {} }}))",
            rust_float(*value)
        ),
        Some(MixPercentage::Token(path)) => {
            let _ = set;
            format!("Some(MixPercentage::Token({:?}))", rust_reference(path))
        }
    }
}

// ---------------------------------------------------------------------------------------------
// ui/tokens/derivations.css
// ---------------------------------------------------------------------------------------------

/// Renders `ui/tokens/derivations.css` — the layer that makes a host's seed override propagate.
///
/// `tokens.css` declares every token as the **resolved** colour, which is what the Rust canvas, the
/// TypeScript shell and every contrast gate need. That resolution is fixed at generation time, so
/// on its own a host that sets `--theme-midground` re-themes nothing.
///
/// This file is the answer, and it is a separate stylesheet on purpose: a second declaration of the
/// same property inside `tokens.css` would be a duplicate the drift gates read as a defect, and it
/// would also force every consumer of `tokens.css` to cope with a `color-mix()` where it expects a
/// colour. Import it *after* `tokens.css` and every derived colour becomes an expression again,
/// resolved by the browser from whichever seeds are in force.
///
/// One declaration per derived **member**, written in terms of the scheme-relative aliases, which
/// is why the model refuses two schemes that derive a member differently: the alias is the name a
/// host sets, and it is the only name that is correct in both schemes.
pub(crate) fn derivations_css(set: &TokenSet) -> String {
    let mut out = String::new();
    out.push_str("/*\n");
    let _ = writeln!(out, " * {GENERATED_BY}");
    out.push_str(" * DO NOT EDIT. Edit the source and regenerate.\n *\n");
    for line in wrap(
        "The derived tier. `tokens.css` carries every token as the colour it resolved to for the \
         seeds this platform ships with; this file restates the derived ones as the \
         `color-mix(in srgb, …)` they came from, in terms of the scheme-relative aliases. Import it \
         AFTER tokens.css and a host that overrides one seed — `--theme-midground`, \
         `--theme-background-seed`, `--theme-mix-chrome` — re-themes every colour mixed from it \
         through the cascade, with no code. The Rust canvas cannot inherit a custom property, so it \
         evaluates the same expressions through `mjx_tokens::Tokens::rederive`; \
         ui/tokens/chromium-agreement.mjs asserts that the browser and that one implementation \
         agree, for every derived token, in both schemes.",
        COMMENT_WIDTH,
    ) {
        let _ = writeln!(out, " * {line}");
    }
    out.push_str(" */\n\n:root {\n");

    let mut written: BTreeSet<String> = BTreeSet::new();
    for token in set.tokens() {
        let Some(derivation) = &token.derivation else {
            continue;
        };
        let name = derivation_reference(set, &dotted(&token.path));
        if !written.insert(name.clone()) {
            // The other scheme's copy of the same member, which the model has already proved is
            // the same expression.
            continue;
        }
        if let Some(description) = &token.description {
            for line in wrap(description, COMMENT_WIDTH - 5) {
                let _ = writeln!(out, "  /* {line} */");
            }
        }
        let value = match derivation {
            Derivation::Alias(path) => format!("var({})", derivation_reference(set, path)),
            Derivation::Mix(nodes) => css_mix(set, nodes, nodes.len() - 1),
        };
        let _ = writeln!(out, "  {name}: {value};");
    }
    out.push_str("}\n");
    out
}

/// One `color-mix()` expression as CSS.
fn css_mix(set: &TokenSet, nodes: &[MixNode], at: usize) -> String {
    let node = &nodes[at];
    format!(
        "color-mix(in srgb, {}{}, {}{})",
        css_mix_term(set, nodes, &node.first),
        css_mix_percentage(set, &node.first_percentage),
        css_mix_term(set, nodes, &node.second),
        css_mix_percentage(set, &node.second_percentage),
    )
}

fn css_mix_term(set: &TokenSet, nodes: &[MixNode], term: &MixTerm) -> String {
    match term {
        MixTerm::Literal(colour) => colour.css(),
        MixTerm::Transparent => "transparent".to_owned(),
        MixTerm::Nested(at) => css_mix(set, nodes, *at),
        MixTerm::Token(path) => format!("var({})", derivation_reference(set, path)),
    }
}

fn css_mix_percentage(set: &TokenSet, percentage: &Option<MixPercentage>) -> String {
    match percentage {
        None => String::new(),
        Some(MixPercentage::Fixed(value)) => format!(" {}%", number(*value)),
        Some(MixPercentage::Token(path)) => {
            format!(" var({})", derivation_reference(set, path))
        }
    }
}

/// The `mjx-tokens` types one value kind needs in scope.
fn rust_imports(value: &Value) -> &'static [&'static str] {
    match value {
        Value::Color(_) => &["Color"],
        Value::Dimension(_) => &["Dimension", "LengthUnit"],
        Value::Duration(_) => &["Duration"],
        Value::Number(_) | Value::FontWeight(_) => &[],
        Value::FontStack(_) => &["FontStack"],
        Value::CubicBezier(_) => &["CubicBezier"],
        Value::Shadow(_) => &["Color", "Dimension", "LengthUnit", "Shadow"],
        Value::Percentage(_) => &["Percentage"],
    }
}

/// The `ColorUsage` variant a usage is spelled with in Rust.
///
/// Derived from `mjx_tokens::ColorUsage::ALL` by an exhaustive match rather than by transforming
/// the wire spelling, so adding a fourth usage fails to compile here instead of emitting a variant
/// that does not exist.
fn usage_variant(usage: Usage) -> &'static str {
    match usage {
        Usage::OnLightText => "OnLightText",
        Usage::OnDarkText => "OnDarkText",
        Usage::FillOnly => "FillOnly",
    }
}

fn rust_type_of(value: &Value) -> &'static str {
    match value {
        Value::Color(_) => "Color",
        Value::Dimension(_) => "Dimension",
        Value::Duration(_) => "Duration",
        Value::Number(_) => "f32",
        Value::FontWeight(_) => "u16",
        Value::FontStack(_) => "FontStack",
        Value::CubicBezier(_) => "CubicBezier",
        Value::Shadow(_) => "Shadow",
        Value::Percentage(_) => "Percentage",
    }
}

fn rust_token_value_variant(value: &Value) -> &'static str {
    match value {
        Value::Color(_) => "Color",
        Value::Dimension(_) => "Dimension",
        Value::Duration(_) => "Duration",
        Value::Number(_) => "Number",
        Value::FontWeight(_) => "FontWeight",
        Value::FontStack(_) => "FontStack",
        Value::CubicBezier(_) => "CubicBezier",
        Value::Shadow(_) => "Shadow",
        Value::Percentage(_) => "Percentage",
    }
}

/// `color.ink-soft` → `color.ink_soft`, the field expression that reaches it from a `Tokens`.
fn rust_access(path: &[String]) -> String {
    path.iter()
        .map(|segment| rust_field(segment))
        .collect::<Vec<_>>()
        .join(".")
}

/// A Rust float literal: always with a decimal point, because `0` is an integer literal and
/// `let magnitude: f32 = 0;` does not compile.
fn rust_float(value: f64) -> String {
    let text = number(value);
    if text.contains('.') || text.contains('e') || text.contains('E') {
        text
    } else {
        format!("{text}.0")
    }
}

fn rust_colour(colour: Rgba) -> String {
    format!(
        "Color {{ red: 0x{:02x}, green: 0x{:02x}, blue: 0x{:02x}, alpha: 0x{:02x} }}",
        colour.red, colour.green, colour.blue, colour.alpha
    )
}

fn rust_length(length: Length) -> String {
    format!(
        "Dimension {{ magnitude: {}, unit: LengthUnit::{} }}",
        rust_float(length.magnitude),
        length.unit.rust_variant()
    )
}

fn rust_shadow(shadow: Shadow) -> String {
    format!(
        "Shadow {{ offset_x: {}, offset_y: {}, blur: {}, spread: {}, color: {} }}",
        rust_length(shadow.offset_x),
        rust_length(shadow.offset_y),
        rust_length(shadow.blur),
        rust_length(shadow.spread),
        rust_colour(shadow.color)
    )
}

fn rust_literal(value: &Value) -> String {
    match value {
        Value::Color(colour) => rust_colour(*colour),
        Value::Dimension(length) => rust_length(*length),
        Value::Duration(milliseconds) => {
            format!("Duration {{ milliseconds: {} }}", rust_float(*milliseconds))
        }
        Value::Number(value) => rust_float(*value),
        Value::FontWeight(weight) => weight.to_string(),
        Value::FontStack(_) => format!("FontStack::from_static({:?})", value.css()),
        Value::CubicBezier([x1, y1, x2, y2]) => format!(
            "CubicBezier {{ x1: {}, y1: {}, x2: {}, y2: {} }}",
            rust_float(*x1),
            rust_float(*y1),
            rust_float(*x2),
            rust_float(*y2)
        ),
        Value::Shadow(shadow) => rust_shadow(*shadow),
        Value::Percentage(value) => format!("Percentage {{ value: {} }}", rust_float(*value)),
    }
}

fn rust_doc(description: Option<&str>, note: Option<&str>, indent: &str, out: &mut String) {
    let mut wrote = false;
    if let Some(description) = description {
        for line in wrap(description, COMMENT_WIDTH - indent.len() - 4) {
            let _ = writeln!(out, "{indent}/// {line}");
        }
        wrote = true;
    }
    if let Some(note) = note {
        if wrote {
            let _ = writeln!(out, "{indent}///");
        }
        for line in wrap(note, COMMENT_WIDTH - indent.len() - 4) {
            let _ = writeln!(out, "{indent}/// {line}");
        }
        wrote = true;
    }
    if !wrote {
        // `missing_docs` is a workspace lint: every public item carries a doc, generated or not.
        let _ = writeln!(out, "{indent}/// Generated from the design-token source.");
    }
}

fn rust_struct(name: &str, description: Option<&str>, entries: &[Entry], out: &mut String) {
    out.push('\n');
    rust_doc(description, None, "", out);
    out.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    let _ = writeln!(out, "pub struct {name} {{");
    for entry in entries {
        match entry {
            Entry::Group(group) => {
                rust_doc(group.description.as_deref(), None, "    ", out);
                let _ = writeln!(
                    out,
                    "    pub {}: {},",
                    rust_field(group.path.last().map_or("", String::as_str)),
                    group.rust_type
                );
            }
            Entry::Token(token) => {
                let note = format!(
                    "CSS: `{}`{}",
                    custom_property(&token.path),
                    provenance(token).map_or_else(String::new, |note| format!(" · {note}"))
                );
                rust_doc(token.description.as_deref(), Some(&note), "    ", out);
                let _ = writeln!(
                    out,
                    "    pub {}: {},",
                    rust_field(token.path.last().map_or("", String::as_str)),
                    rust_type_of(&token.value)
                );
            }
        }
    }
    out.push_str("}\n");
}

fn rust_default_members(entries: &[Entry], depth: usize, out: &mut String) {
    let pad = "    ".repeat(depth);
    for entry in entries {
        match entry {
            Entry::Group(group) => {
                let _ = writeln!(
                    out,
                    "{pad}{}: {} {{",
                    rust_field(group.path.last().map_or("", String::as_str)),
                    group.rust_type
                );
                rust_default_members(&group.entries, depth + 1, out);
                let _ = writeln!(out, "{pad}}},");
            }
            Entry::Token(token) => {
                let _ = writeln!(
                    out,
                    "{pad}{}: {},",
                    rust_field(token.path.last().map_or("", String::as_str)),
                    rust_literal(&token.value)
                );
            }
        }
    }
}

/// `text-primary` → `TextPrimary`: a path segment as a Rust variant name.
fn rust_variant(segment: &str) -> String {
    let mut variant = String::new();
    for part in segment.split('-') {
        let mut characters = part.chars();
        if let Some(first) = characters.next() {
            variant.extend(first.to_uppercase());
            variant.push_str(characters.as_str());
        }
    }
    variant
}

fn rust_scheme_enum(set: &TokenSet, out: &mut String) {
    out.push_str(
        "
/// The colour schemes the platform defines. Generated from the source's scheme groups, so a third
/// scheme is a change to `tokens.json` and to nothing else.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ColorScheme {
",
    );
    for scheme in &set.scheme_names {
        let _ = writeln!(
            out,
            "    /// The `{scheme}` scheme.\n    {},",
            rust_variant(scheme)
        );
    }
    out.push_str("}\n");
}

fn rust_scheme_accessor(set: &TokenSet, group: &Group, out: &mut String) {
    let Some(Entry::Group(first)) = group.entries.first() else {
        return;
    };
    let _ = writeln!(out, "\nimpl {} {{", group.rust_type);
    let _ = writeln!(
        out,
        "    /// The `{}` values for one colour scheme.\n    #[must_use]\n    pub fn scheme(&self, \
         scheme: ColorScheme) -> &{} {{\n        match scheme {{",
        first.rust_type, first.rust_type
    );
    for (at, scheme) in set.scheme_names.iter().enumerate() {
        let variant = rust_variant(scheme);
        let field = match group.entries.get(at) {
            Some(Entry::Group(child)) => rust_field(child.path.last().map_or("", String::as_str)),
            _ => continue,
        };
        let _ = writeln!(out, "            ColorScheme::{variant} => &self.{field},");
    }
    out.push_str("        }\n    }\n}\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::tokens::model::read;

    /// A source small enough to read whole, and deliberately *not* the committed one: a fixture
    /// that already matches the assertion tests nothing.
    const SOURCE: &str = r##"{
      "$description": "a test source",
      "color": {
        "$type": "color",
        "$extensions": { "mjx": { "rustType": "Palette" } },
        "white": { "$value": "#ffffff", "$extensions": { "mjx": { "usage": "fill-only" } } },
        "ink-soft": {
          "$value": "#5c7168",
          "$description": "secondary text.",
          "$extensions": { "mjx": { "usage": "on-light-text", "background": "{color.white}" } }
        }
      },
      "radius": {
        "$type": "dimension",
        "$extensions": { "mjx": { "rustType": "Radii" } },
        "card": { "$value": "16px" }
      },
      "theme": {
        "$type": "color",
        "$extensions": { "mjx": { "rustType": "Themes", "schemes": true } },
        "light": {
          "$extensions": { "mjx": { "rustType": "ThemeColors" } },
          "surface": { "$value": "{color.white}", "$extensions": { "mjx": { "usage": "fill-only" } } }
        },
        "dark": {
          "$extensions": { "mjx": { "rustType": "ThemeColors" } },
          "surface": { "$value": "#1b2420", "$extensions": { "mjx": { "usage": "fill-only" } } }
        }
      }
    }"##;

    #[test]
    fn one_token_reaches_all_three_artefacts_under_all_three_of_its_names() {
        let set = read(SOURCE).expect("valid");
        let css = css(&set);
        let typescript = typescript(&set);
        let rust = rust(&set);

        assert!(css.contains("--color-ink-soft: #5c7168;"), "{css}");
        assert!(typescript.contains("inkSoft: '#5c7168',"), "{typescript}");
        assert!(
            rust.contains("ink_soft: Color { red: 0x5c, green: 0x71, blue: 0x68, alpha: 0xff }"),
            "{rust}"
        );
        // The measured ratio is recorded in all three, so the decision is auditable wherever a
        // reader happens to be.
        for artefact in [&css, &typescript, &rust] {
            assert!(
                artefact.contains("5.23 : 1 on `color.white`"),
                "the measured ratio is missing: {artefact}"
            );
        }
    }

    /// The derivation gate in miniature: a token added to the source appears in all three
    /// artefacts, and a token removed from it leaves all three.
    #[test]
    fn adding_and_removing_a_token_moves_all_three_artefacts_together() {
        let with_extra = SOURCE.replace(
            r#""card": { "$value": "16px" }"#,
            r#""card": { "$value": "16px" }, "tooltip": { "$value": "6px" }"#,
        );
        assert_ne!(with_extra, SOURCE, "the fixture edit must have applied");

        let before = read(SOURCE).expect("valid");
        let after = read(&with_extra).expect("valid");

        for artefact in [css(&before), typescript(&before), rust(&before)] {
            assert!(
                !artefact.contains("tooltip"),
                "the token is not in the source yet: {artefact}"
            );
        }
        assert!(css(&after).contains("--radius-tooltip: 6px;"));
        assert!(typescript(&after).contains("tooltip: '6px',"));
        assert!(rust(&after)
            .contains("tooltip: Dimension { magnitude: 6.0, unit: LengthUnit::Pixels }"));
    }

    /// The scheme layer's cascade is the behaviour, not decoration: light by default, the system's
    /// preference unless the host asked for light, and an explicit `data-theme` over both.
    #[test]
    fn the_scheme_layer_cascades_in_the_only_order_that_behaves() {
        let css = css(&read(SOURCE).expect("valid"));
        let default_at = css
            .find("--theme-surface: var(--theme-light-surface);")
            .expect("the light scheme is the default");
        let media_at = css
            .find("@media (prefers-color-scheme: dark)")
            .expect("the system preference is honoured");
        let explicit_at = css
            .find("[data-theme=\"dark\"] {")
            .expect("an explicit theme is honoured");
        assert!(
            default_at < media_at && media_at < explicit_at,
            "an explicit `data-theme` must be able to beat the media query"
        );
        assert!(
            css.contains(":root:not([data-theme=\"light\"])"),
            "a host that asked for light must not be overridden by the system preference"
        );
    }

    /// A two-tier source: the derived tier reaches the resolved colour in three artefacts and the
    /// *expression* in the fourth, under the scheme-relative alias.
    const DERIVED_SOURCE: &str = r##"{
      "$description": "a test source",
      "theme": {
        "$type": "color",
        "$extensions": { "mjx": { "rustType": "Themes", "schemes": true } },
        "light": {
          "$extensions": { "mjx": { "rustType": "ThemeColors" } },
          "seed": { "$value": "#000000", "$extensions": { "mjx": { "usage": "fill-only" } } },
          "knob": { "$type": "percentage", "$value": "20%" },
          "surface": {
            "$value": { "mix": [
              { "color": "{theme.light.seed}", "percentage": "{theme.light.knob}" },
              { "color": "#ffffff" }
            ] },
            "$extensions": { "mjx": { "usage": "fill-only" } }
          }
        },
        "dark": {
          "$extensions": { "mjx": { "rustType": "ThemeColors" } },
          "seed": { "$value": "#ffffff", "$extensions": { "mjx": { "usage": "fill-only" } } },
          "knob": { "$type": "percentage", "$value": "40%" },
          "surface": {
            "$value": { "mix": [
              { "color": "{theme.dark.seed}", "percentage": "{theme.dark.knob}" },
              { "color": "#ffffff" }
            ] },
            "$extensions": { "mjx": { "usage": "fill-only" } }
          }
        }
      }
    }"##;

    #[test]
    fn the_derived_tier_is_a_colour_in_three_artefacts_and_an_expression_in_the_fourth() {
        let set = read(DERIVED_SOURCE).expect("valid");

        // Resolved everywhere a consumer needs a colour — a canvas cannot paint an expression, and
        // a contrast gate cannot measure one.
        assert!(
            css(&set).contains("--theme-light-surface: #cccccc;"),
            "{}",
            css(&set)
        );
        assert!(typescript(&set).contains("surface: '#cccccc',"));
        assert!(rust(&set)
            .contains("surface: Color { red: 0xcc, green: 0xcc, blue: 0xcc, alpha: 0xff }"));

        // …and the expression exactly once, under the alias a host overrides through.
        let derivations = derivations_css(&set);
        assert!(
            derivations.contains(
                "--theme-surface: color-mix(in srgb, var(--theme-seed) var(--theme-knob), #ffffff);"
            ),
            "{derivations}"
        );
        assert!(
            !derivations.contains("--theme-light-surface"),
            "one declaration per member, not one per scheme: {derivations}"
        );

        // The Rust table names the per-scheme properties instead, because a renderer already knows
        // which scheme it is painting.
        let rust = rust(&set);
        assert!(
            rust.contains("MixTerm::Token(\"--theme-light-seed\")"),
            "{rust}"
        );
        assert!(
            rust.contains("MixPercentage::Token(\"--theme-dark-knob\")"),
            "{rust}"
        );
    }

    #[test]
    fn the_scheme_accessor_is_generated_from_the_source_and_not_hard_coded() {
        let rust = rust(&read(SOURCE).expect("valid"));
        assert!(rust.contains("pub enum ColorScheme"), "{rust}");
        assert!(
            rust.contains("ColorScheme::Light => &self.light,"),
            "{rust}"
        );
        assert!(rust.contains("ColorScheme::Dark => &self.dark,"), "{rust}");
    }
}
