//! **The plates are R10's plates**, and the approval machinery is R10's machinery.
//!
//! Three things this suite is for, and one it deliberately is not.
//!
//! * **The manifest is the schema U01 already reads.** R10's hand-off 4: *"your 61 entries extend
//!   `plates`; do not invent a second schema."* So the manifest is parsed back with
//!   `mjx_render_oracle::json` and asked every question a loader will ask — which is the shape
//!   `tests/the_plate_manifest_reaches_a_loader.rs` established, and for the reason it gives: *a
//!   manifest checked by asserting on the string that produced it proves that `format!` works.*
//! * **An unapproved plate fails.** Not warns, not skips. The whole approval apparatus exists
//!   because a golden image generated by the code under test always matches the code under test,
//!   and a baseline nobody approved is that tautology with a green tick on it.
//! * **Nobody has looked at these images.** Every approval this crate ships is
//!   `Approver::Generator`, which is a real approval record — the digest binding is live, so a
//!   silent regeneration is caught — and is **not** a human review. The suite asserts that it says
//!   so, in the manifest and in the checklist, rather than trusting anyone to remember.
//!
//! What it is not is a fidelity claim. `parity` is `false` on every plate, computed rather than
//! written, and a canvas overlay has no PowerPoint to be at parity with in the first place — it is
//! this platform's own design.

use mjx_canvas_harness::inventory::INVENTORY;
use mjx_canvas_harness::plates;
use mjx_render_oracle::authority::ReferenceProvider;
use mjx_render_oracle::baseline::{ApprovalState, Baselines};
use mjx_render_oracle::json;
use mjx_render_oracle::plate::MANIFEST_VERSION;
use mjx_tokens::Tokens;

/// The plate set for the committed baselines.
fn set() -> mjx_render_oracle::plate::PlateSet {
    plates::plate_set(
        &plates::baselines(),
        ReferenceProvider::None,
        &Tokens::DEFAULTS.clone(),
    )
    .expect("every entry renders")
}

#[test]
fn every_plate_is_approved_and_none_of_them_by_a_person() {
    let store = plates::baselines();
    let mut unapproved = Vec::new();
    for entry in &INVENTORY {
        let name = entry.slug();
        match store.approval(&name) {
            ApprovalState::Approved(approval) => {
                assert!(
                    !approval.is_reviewed(),
                    "`{name}` is recorded as approved by a person. If that is true it is excellent \
                     news and this assertion is what has to change; if it is not, an agent has \
                     stamped a human approval, which is the one thing MJXOFF-166 forbids outright."
                );
            }
            other => unapproved.push(format!(
                "{}: {}",
                name,
                other.refusal().unwrap_or_else(|| "unusable".to_owned())
            )),
        }
    }
    assert!(
        unapproved.is_empty(),
        "{} of {} plates have no usable approval:\n  {}",
        unapproved.len(),
        INVENTORY.len(),
        unapproved.join("\n  ")
    );
    assert_eq!(
        plates::awaiting_human_review(&store).len(),
        INVENTORY.len(),
        "the listing of images nobody has looked at should hold every one of them today"
    );
}

#[test]
fn an_unapproved_plate_fails_rather_than_passing() {
    // The gate proved able to fail, in a temporary directory so the committed store is untouched.
    let root = std::env::temp_dir().join(format!(
        "mjx-canvas-harness-unapproved-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let store = Baselines::at(&root);
    let tokens = Tokens::DEFAULTS.clone();
    let entry = &INVENTORY[0];

    let artefacts = plates::artefacts(entry, &tokens).expect("the first entry renders");
    std::fs::create_dir_all(store.directory(&entry.slug())).expect("a directory");
    for (name, bytes) in &artefacts {
        std::fs::write(store.directory(&entry.slug()).join(name), bytes).expect("an artefact");
    }

    let refusal = plates::check_entry(&store, entry, &tokens)
        .expect_err("a baseline with no approval record is unusable");
    assert!(
        refusal.contains("nobody has approved it"),
        "the refusal should say what is wrong; it said `{refusal}`"
    );

    // And once it is approved, the same artefacts compare clean — which is what makes the failure
    // above about the *approval* rather than about the render.
    store
        .approve(
            &entry.slug(),
            mjx_render_oracle::baseline::Approver::Generator,
            "written by this test",
        )
        .expect("an approval");
    let verdict =
        plates::check_entry(&store, entry, &tokens).expect("an approved baseline is usable");
    assert!(
        verdict.is_clean(),
        "the same artefacts should compare clean: {verdict:?}"
    );

    let _ = std::fs::remove_dir_all(&root);
}

#[test]
fn the_manifest_answers_every_question_a_loader_asks() {
    let set = set();
    let manifest = set.manifest();
    let parsed = json::parse(&manifest).expect("the manifest is JSON");

    assert_eq!(
        parsed.get("version").and_then(json::Value::string),
        None,
        "`version` is a number, not a string"
    );
    assert!(
        manifest.contains(&format!("\"version\": {MANIFEST_VERSION}")),
        "the manifest states R10's schema version, so a loader can refuse a version it does not know"
    );
    assert!(
        manifest.contains("\"premultiplied\": false"),
        "a loader decoding these files has to know, and R10's decision is that a PNG sample is not \
         premultiplied"
    );
    assert!(
        manifest.contains("\"parityClaimed\": false"),
        "no plate here may be read as matching PowerPoint"
    );

    let entries = parsed
        .get("plates")
        .and_then(json::Value::array)
        .expect("the manifest carries a `plates` array");
    assert_eq!(
        entries.len(),
        INVENTORY.len(),
        "the manifest carries {} plates and the inventory has {}",
        entries.len(),
        INVENTORY.len()
    );

    for (plate, entry) in entries.iter().zip(INVENTORY.iter()) {
        let name = plate
            .get("name")
            .and_then(json::Value::string)
            .expect("every plate has a name");
        assert_eq!(name, entry.slug());
        let file = plate
            .get("file")
            .and_then(json::Value::string)
            .expect("every plate names its file");
        assert_eq!(file, format!("{}.png", entry.slug()));
        assert!(
            set.images.iter().any(|(named, _)| *named == file),
            "the manifest names `{file}` and the set does not carry it"
        );
        for key in ["description", "sha256", "content", "provider", "approver"] {
            assert!(
                plate.get(key).and_then(json::Value::string).is_some(),
                "plate `{name}` has no `{key}`"
            );
        }
        assert!(
            plate.get("reviewed").is_some() && plate.get("parity").is_some(),
            "plate `{name}` does not say whether a person has looked at it"
        );
    }

    // Every plate is the document's own geometry, drew something, and covered pixels.
    for plate in &set.plates {
        assert_eq!(
            plate.placeholders, 0,
            "plate `{}` drew {} stand-in outline(s)",
            plate.name, plate.placeholders
        );
        assert!(plate.draw_calls > 0, "plate `{}` drew nothing", plate.name);
        assert!(
            plate.covered > 500,
            "plate `{}` covered {} pixels",
            plate.name,
            plate.covered
        );
        assert!(
            !plate.reviewed,
            "plate `{}` claims a human review",
            plate.name
        );
        assert!(!plate.parity, "plate `{}` claims parity", plate.name);
    }

    // The `documents` array is empty on purpose: this harness needs no document and no fixture,
    // which is what lets in-canvas design be settled before any format renders.
    assert!(
        set.documents.is_empty(),
        "a canvas element has no document fixture to name"
    );
}

#[test]
fn the_provider_exclusion_has_something_to_exclude_and_something_to_leave_alone() {
    // R10's hand-off 14, exercised rather than described: the exclusion is a property of the
    // *provider*, so a gradient plate is not evidence against a LibreOffice reference and a stroked
    // outline is. A corpus that was all one content kind would make the exclusion vacuous.
    let against_libreoffice = plates::plate_set(
        &plates::baselines(),
        ReferenceProvider::LibreOffice,
        &Tokens::DEFAULTS.clone(),
    )
    .expect("every entry renders");
    let excluded = against_libreoffice
        .plates
        .iter()
        .filter(|plate| plate.exclusion.is_some())
        .count();
    let admitted = against_libreoffice.plates.len() - excluded;
    assert!(
        excluded > 0,
        "no plate is excluded from a LibreOffice comparison, so the exclusion is vacuous here"
    );
    assert!(
        admitted > 0,
        "every plate is excluded, so the exclusion says nothing about which content kinds matter"
    );
    println!(
        "\nagainst LibreOffice: {excluded} of {} plates are not evidence, {admitted} are.",
        against_libreoffice.plates.len()
    );
    // And against **no provider at all** — the state the committed plates are generated in —
    // *every* plate is excluded, which is stronger than it first reads and worth asserting rather
    // than assuming. `ReferenceProvider::None` is not the absence of a provider; it is a provider
    // that answers nothing, and its exclusion says so in a sentence: *"there is no reference to
    // compare against; this run proves the pipeline and nothing about fidelity."* A run whose plates
    // came back unexcluded would be one quietly claiming to have been compared with something.
    let none = set();
    assert!(
        none.plates.iter().all(|plate| plate.exclusion.is_some()),
        "a plate generated against `ReferenceProvider::None` claims a comparison that did not happen"
    );
    assert!(none.plates.iter().all(|plate| !plate.parity));
}

#[test]
fn the_checklist_ticks_nothing() {
    let text = mjx_canvas_harness::checklist::render(&plates::baselines());
    assert!(
        !text.contains("[x]") && !text.contains("[X]"),
        "the checklist has a ticked box in it, and MJXOFF-166 forbids marking an entry approved on \
         the user's behalf"
    );
    assert_eq!(
        text.matches("| [ ] |").count(),
        INVENTORY.len(),
        "the checklist should carry one empty box per element"
    );
    for entry in &INVENTORY {
        assert!(
            text.contains(entry.title),
            "the checklist does not mention entry {} (`{}`)",
            entry.number,
            entry.title
        );
    }
    assert!(
        text.contains("Human review: 0 of 61"),
        "the checklist must say how many images a person has looked at, and today that is none"
    );
}
