//! The audit checklist: one line per element, ready for the user's pass.
//!
//! # ⚠ Nothing here is ever marked
//!
//! MJXOFF-166's *Done when* ends with six words that are the whole of this module's design:
//! **"Never mark an entry approved on the user's behalf."** So every box is empty, every line says
//! what to look at rather than what was concluded, and the one machine-filled column is the
//! *approval state of the plate* — which is a fact about a file on disk, and which says
//! `generator` for every entry until a person changes it.
//!
//! It is the same rule as `mjx_render_oracle::baseline`'s two-valued [`Approver`], written for a
//! Markdown file instead of for a record: an agent can produce the surface a person judges from, and
//! it cannot produce the judgement.
//!
//! [`Approver`]: mjx_render_oracle::baseline::Approver

use mjx_render_oracle::baseline::{ApprovalState, Baselines};

use crate::inventory::{Family, INVENTORY};
use crate::state::{Axis, Density, Input, Interaction};

/// The checklist, as Markdown.
///
/// `store` is read only to report whether each plate carries a **human** approval; it is never
/// written and no box is ever ticked.
#[must_use]
pub fn render(store: &Baselines) -> String {
    let mut out = String::with_capacity(16_384);
    out.push_str("# The in-canvas UI audit — one line per element\n\n");
    out.push_str(
        "Generated by `cargo run -p mjx-canvas-harness -- checklist`. **Nothing in this file is \
         ticked, and no agent may tick it.** The boxes are for the person doing the pass.\n\n",
    );
    out.push_str("## How to run the pass\n\n");
    out.push_str(
        "```sh\ncargo run -p mjx-canvas-harness -- serve\n```\n\n\
         Open the address it prints. The scene list is on the left, the state panel on the right. \
         For each element below:\n\n\
         1. Look at it at **1×, 2× and 3×**, in **light and dark**. The density toggle is the one \
            that finds a hairline that has vanished or doubled.\n\
         2. Step the **interaction** toggle through default, hover, active, focused and disabled. \
            An element whose toggle does nothing is either finished or wrong, and the harness's \
            own gate says which — see the `responds to` column.\n\
         3. Turn on the **hit-test overlay** and judge the grab region. Then set **input** to \
            touch and judge it again.\n\
         4. For the eleven touch elements, **open the harness on a phone** \
            (`serve --host 0.0.0.0`, then the machine's address on the same network) and use a \
            thumb. A touch target judged with a mouse has not been judged.\n\
         5. Tweak whatever is wrong in the **token editor**. It writes back to \
            `docs/client-platform/data/tokens.json`; run `cargo run -p xtask -- tokens` afterwards \
            to carry the change into the three generated artefacts.\n\
         6. When an element is right, tick its box here, and record the approval against its \
            plate:\n\n\
         ```sh\nMJX_ORACLE_APPROVED_BY='Your Name' \\\n  cargo run -p mjx-canvas-harness -- \
         approve <number> \"why\"\n```\n\n",
    );

    let reviewed = INVENTORY
        .iter()
        .filter(|entry| store.approval(&entry.slug()).is_reviewed())
        .count();
    out.push_str(&format!(
        "**Human review: {reviewed} of {}.** A plate approved by the generator is a real approval \
         record — the digest binding is live, so a silent regeneration is caught — and it is *not* \
         a person having looked at the image.\n\n",
        INVENTORY.len()
    ));

    out.push_str("## The state matrix\n\n");
    out.push_str(&format!(
        "| Axis | Values |\n|---|---|\n\
         | interaction | {} |\n\
         | scheme | light, dark |\n\
         | density | {} |\n\
         | input | {} |\n\n",
        Interaction::ALL
            .iter()
            .map(|value| value.slug())
            .collect::<Vec<_>>()
            .join(", "),
        Density::ALL
            .iter()
            .map(|value| value.slug())
            .collect::<Vec<_>>()
            .join(", "),
        Input::ALL
            .iter()
            .map(|value| value.slug())
            .collect::<Vec<_>>()
            .join(", "),
    ));

    for family in Family::ALL {
        out.push_str(&format!(
            "## §{} · {} ({})\n\n",
            family.section(),
            family.label(),
            family.size()
        ));
        out.push_str("| | # | Element | Responds to | Plate approved by | What to judge |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for entry in INVENTORY.iter().filter(|entry| entry.family == family) {
            let responds: Vec<&str> = entry
                .responds
                .iter()
                .copied()
                .filter(|axis| !matches!(axis, Axis::Scheme | Axis::Density))
                .map(Axis::label)
                .collect();
            let responds = if responds.is_empty() {
                "scheme and density only".to_owned()
            } else {
                responds.join(", ")
            };
            let approver = match store.approval(&entry.slug()) {
                ApprovalState::Approved(approval) => {
                    if approval.is_reviewed() {
                        approval.approver.label()
                    } else {
                        "the generator — nobody has looked".to_owned()
                    }
                }
                other => other
                    .refusal()
                    .map_or_else(|| "unapproved".to_owned(), |_| "**no approval**".to_owned()),
            };
            out.push_str(&format!(
                "| [ ] | {} | {} | {} | {} | {} |\n",
                entry.number,
                escape_cell(entry.title),
                responds,
                approver,
                escape_cell(entry.description),
            ));
        }
        out.push('\n');
    }

    out.push_str("## What this checklist does not cover\n\n");
    out.push_str(
        "* **Behaviour.** Nothing here is wired to a document, to selection or to editing — that \
         is loop 2. The elements are *exercised*, not *connected*.\n\
         * **The chrome.** Toolbars, panels and dialogues are web components and are audited in \
         Storybook; this is the surface that cannot be one.\n\
         * **Parity with PowerPoint.** These are this platform's own design, not a reproduction of \
         somebody else's, so there is nothing to be at parity with. Every plate records \
         `parity: false` and it is computed rather than written.\n",
    );
    out
}

/// A cell that cannot break the table it is in.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}
