//! **The canvas UI harness** (MJXOFF-166): the sixty-one in-canvas elements of
//! `docs/client-platform/CANVAS_UI_INVENTORY.md`, exercised by hand.
//!
//! # What this is for, and why it is not a test suite
//!
//! The inventory says it in one table:
//!
//! | Instrument | Role | Driven by |
//! |---|---|---|
//! | **This harness** | the audit surface — manual, interactive, exhaustive | a person |
//! | Golden plates | regression only — appearance locked once approved | CI, headless `tiny-skia` |
//!
//! *"The earlier proposal — render each element to a PNG and publish the plates into Storybook —
//! proves **appearance** and nothing else. Almost everything on this surface is only correct in
//! motion and under the pointer."* A handle you cannot drag says nothing about its grab tolerance; a
//! touch target is only real on a touch device. So this crate ships **both** roles and keeps them
//! apart: [`server`] is the thing a person sits in front of, and [`plates`] is the thing CI runs.
//!
//! # How a person runs it
//!
//! ```text
//! cargo run -p mjx-canvas-harness -- serve
//! ```
//!
//! and open the URL it prints. On a phone, `--host 0.0.0.0` and the machine's address on the same
//! network: the eleven touch entries are then being judged **by a thumb on a real screen**, which is
//! the only honest way to judge them.
//!
//! # ⚠ Where the pixels come from, and where they do not
//!
//! **Every pixel on that page is drawn in Rust**, by `mjx-paint`'s software painter, through
//! `mjx-scene`'s display list, from a `mjx-layout` fragment tree. The browser is the *chrome* — the
//! scene list, the state panel, the token editor — which is `docs/UI_PLATFORM_PLAN.md`'s own
//! division and the user's standing constraint: *the document renderer is entirely Rust, with no
//! JavaScript graphics library.* The page contains no `<canvas>` drawing, no SVG generation and no
//! plotting library; it contains an `<img>` whose bytes came out of [`crate::render`].
//!
//! That extends to the overlays. The ruler, the hit-test regions and the pixel probe are all
//! computed and drawn on the Rust side — the hit regions out of `mjx_layout::SpatialIndex` itself,
//! never recomputed in script — because a visualiser that drew its own idea of where an element is
//! would be a second answer to a question the workspace has one answer to.
//!
//! # The four traps this crate is built against
//!
//! 1. **"All 61 elements have a scene" is satisfied by 61 empty canvases.** Answered in
//!    [`inventory`] and `tests/every_entry_draws.rs`: five counters per entry, including a distinct
//!    colour count, and a command-count floor measured against the bare stage.
//! 2. **A state axis nothing reads is a toggle that does nothing.** Answered in [`state`] and
//!    `tests/the_axes_are_not_identities.rs`, which measures each entry's declared axes against its
//!    renders in both directions and prints how many distinct values the gate actually saw.
//! 3. **A visualiser that computes its own regions proves nothing about the index.** Answered in
//!    [`render`] and `tests/the_visualiser_shows_the_index.rs`.
//! 4. **A golden image generated by the code under test always matches the code under test.**
//!    Answered by not answering it here at all: the baselines, the approval events and the
//!    regeneration gate are `mjx_render_oracle::baseline`'s, and this crate's sixty-one plates go
//!    through that store unchanged. See [`plates`].
//!
//! # Where it sits
//!
//! Test-only, `publish = false`, **outside the ranked graph and at the top of it**, beside
//! `mjx-reference-pack`. It names `mjx-paint` (rank 5.5) and `mjx-render-oracle` together, which is
//! a pair no ranked crate may declare; nothing may depend on it in either section, and
//! `xtask/tests/layering.rs` enforces both halves by name.
//!
//! It is the **second** consumer of `mjx-render-oracle` and the first of that crate's *plate
//! generator*: the reference pack takes the authority vocabulary and never renders a plate, so
//! before this crate existed the permitted direction of that rule was asserted and unexercised.

pub mod canvas;
pub mod checklist;
pub mod inventory;
pub mod page;
pub mod plates;
pub mod render;
pub mod scenes;
pub mod server;
pub mod state;
pub mod tokens_source;

pub use canvas::{Canvas, Ink};
pub use inventory::{entry, entry_by_slug, Draws, Entry, Family, ELEMENTS, INVENTORY};
pub use render::{render, render_png, Overlays, Rendered, Scene};
pub use state::{Axis, ColorScheme, Density, Input, Interaction, State};
