//! The canvas UI harness's command line.
//!
//! ```text
//! cargo run -p mjx-canvas-harness -- serve [--host 0.0.0.0] [--port 7761]
//! cargo run -p mjx-canvas-harness -- list
//! cargo run -p mjx-canvas-harness -- check
//! cargo run -p mjx-canvas-harness -- plates [directory]
//! cargo run -p mjx-canvas-harness -- checklist [file]
//! MJX_ORACLE_REGENERATE=1 cargo run -p mjx-canvas-harness -- regenerate [number]
//! MJX_ORACLE_APPROVED_BY='Your Name' cargo run -p mjx-canvas-harness -- approve <number> "why"
//! ```
//!
//! # ⚠ Two paths are deliberately not automatic
//!
//! For `mjx-render-oracle`'s reason, one level in: **a golden image generated by the code under test
//! always matches the code under test.** `regenerate` refuses without `MJX_ORACLE_REGENERATE=1` and
//! removes the approval it overwrites; `approve` refuses without `MJX_ORACLE_APPROVED_BY` and is the
//! only way a plate becomes human-reviewed. Nothing in this binary stamps a human approval.

use std::process::ExitCode;

use mjx_canvas_harness::plates;
use mjx_render_oracle::authority::ReferenceProvider;
use mjx_render_oracle::baseline::{RegenerationIntent, APPROVED_BY};
use mjx_render_oracle::gallery;
use mjx_tokens::Tokens;

fn main() -> ExitCode {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    let command = arguments.first().map_or("serve", String::as_str);
    let result = match command {
        "serve" => serve(&arguments),
        "list" => list(),
        "check" => check(),
        "plates" => write_plates(arguments.get(1).map(String::as_str)),
        "checklist" => checklist(arguments.get(1).map(String::as_str)),
        "regenerate" => regenerate(arguments.get(1).map(String::as_str)),
        "approve" => approve(&arguments),
        "help" | "--help" | "-h" => {
            println!("{USAGE}");
            Ok(())
        }
        other => Err(format!("`{other}` is not a command.\n\n{USAGE}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

/// What the binary answers `help` with.
const USAGE: &str = "\
mjx-canvas-harness — the sixty-one in-canvas UI elements, exercised by hand.

  serve [--host H] [--port N]   the audit surface (default 127.0.0.1:7761)
  list                          every element, its family and its plate's approval state
  check                         every plate against its committed baseline, at three tiers
  plates [directory]            write the plates and the manifest (default target/canvas-plates)
  checklist [file]              the audit checklist (default docs/client-platform/CANVAS_UI_AUDIT.md)
  regenerate [number]           rewrite baselines; needs MJX_ORACLE_REGENERATE=1
  approve <number> \"why\"        record a HUMAN approval; needs MJX_ORACLE_APPROVED_BY

On a phone: `serve --host 0.0.0.0`, then the machine's address on the same network. Eleven of the
sixty-one elements are about touch, and a touch target judged with a mouse has not been judged.";

/// `serve`.
fn serve(arguments: &[String]) -> Result<(), String> {
    let mut host = "127.0.0.1".to_owned();
    let mut port = 7761_u16;
    let mut index = 1;
    while index < arguments.len() {
        match arguments[index].as_str() {
            "--host" => {
                host = arguments
                    .get(index + 1)
                    .ok_or("`--host` needs an address")?
                    .clone();
                index += 2;
            }
            "--port" => {
                port = arguments
                    .get(index + 1)
                    .ok_or("`--port` needs a number")?
                    .parse()
                    .map_err(|_| "`--port` needs a number".to_owned())?;
                index += 2;
            }
            other => {
                return Err(format!(
                    "`{other}` is not an option `serve` takes.\n\n{USAGE}"
                ))
            }
        }
    }
    mjx_canvas_harness::server::serve(&host, port)
}

/// `list`.
fn list() -> Result<(), String> {
    let store = plates::baselines();
    for entry in &mjx_canvas_harness::INVENTORY {
        let approval = store.approval(&entry.slug());
        println!(
            "{:>2}  {:<26}  {:<18}  {}",
            entry.number,
            entry.slug(),
            entry.family.slug(),
            if approval.is_reviewed() {
                "human-approved".to_owned()
            } else {
                approval.refusal().map_or_else(
                    || "generator (nobody has looked)".to_owned(),
                    |_| "NO APPROVAL".to_owned(),
                )
            }
        );
    }
    let awaiting = plates::awaiting_human_review(&store);
    println!(
        "\n{} of {} plates carry no human review.",
        awaiting.len(),
        mjx_canvas_harness::ELEMENTS
    );
    Ok(())
}

/// `check`.
fn check() -> Result<(), String> {
    let store = plates::baselines();
    let tokens = Tokens::DEFAULTS.clone();
    let verdicts = plates::check(&store, &tokens)?;
    let moved: Vec<_> = verdicts.iter().filter(|v| !v.is_clean()).collect();
    for verdict in &moved {
        println!(
            "{:>2}  {}  — {}",
            verdict.number,
            verdict.name,
            verdict.localisation()
        );
        for line in [&verdict.fragments, &verdict.commands, &verdict.pixels]
            .into_iter()
            .flatten()
        {
            println!("      {line}");
        }
    }
    if moved.is_empty() {
        println!(
            "all {} plates match their approved baselines.",
            verdicts.len()
        );
        // **The disclosure, where the reader actually is** (audit pass 10, G8). `check` is the
        // command `CLAUDE.md` documents and the one CI runs, and *"approved baselines"* is the
        // phrase a person will quote out of its output. It said nothing else, while `list`, the
        // gallery, the checklist and the CI job all say this — so the one surface that reads as an
        // endorsement was the one surface that did not carry the qualification.
        //
        // `mjx-render-oracle -- check` ends with the same two lines, and this is deliberately the
        // same sentence: two instruments over the same baseline store, saying one thing.
        let awaiting = plates::awaiting_human_review(&store);
        if !awaiting.is_empty() {
            println!(
                "\n⚠ {} of {} carry NO HUMAN REVIEW — every one is stamped `approver = generator`, \
                 which is a real approval record (the digest binding is live, so a silent \
                 regeneration is caught) and is NOT a person having looked at the image.\n  \
                 `list` says which; `serve` is where a person looks; `approve` is how they say so.",
                awaiting.len(),
                mjx_canvas_harness::ELEMENTS
            );
        }
        Ok(())
    } else {
        Err(format!(
            "{} of {} plates no longer match. Look at them — `plates` writes the gallery — and \
             then either fix the renderer or regenerate and re-approve.",
            moved.len(),
            verdicts.len()
        ))
    }
}

/// `plates`.
fn write_plates(directory: Option<&str>) -> Result<(), String> {
    let directory = std::path::PathBuf::from(directory.unwrap_or("target/canvas-plates"));
    let store = plates::baselines();
    let tokens = Tokens::DEFAULTS.clone();
    let set = plates::plate_set(&store, ReferenceProvider::None, &tokens)?;
    set.write(&directory)?;
    let page = gallery::render(&set);
    let path = directory.join(gallery::GALLERY_FILE);
    std::fs::write(&path, page).map_err(|error| format!("writing {}: {error}", path.display()))?;
    println!(
        "{} plates and the manifest in {}\n{}",
        set.plates.len(),
        directory.display(),
        path.display()
    );
    Ok(())
}

/// `checklist`.
fn checklist(file: Option<&str>) -> Result<(), String> {
    let path = file.map_or_else(
        || {
            mjx_canvas_harness::tokens_source::workspace_root()
                .join("docs/client-platform/CANVAS_UI_AUDIT.md")
        },
        std::path::PathBuf::from,
    );
    let text = mjx_canvas_harness::checklist::render(&plates::baselines());
    std::fs::write(&path, text).map_err(|error| format!("writing {}: {error}", path.display()))?;
    println!("{}", path.display());
    Ok(())
}

/// `regenerate`.
fn regenerate(number: Option<&str>) -> Result<(), String> {
    let intent = RegenerationIntent::from_environment()?;
    let only = match number {
        None => None,
        Some(text) => Some(
            text.parse::<u8>()
                .map_err(|_| format!("`{text}` is not an inventory number"))?,
        ),
    };
    let store = plates::baselines();
    let tokens = Tokens::DEFAULTS.clone();
    let written = plates::regenerate(&store, intent, &tokens, only)?;
    let stamped = plates::stamp_generated(&store)?;
    println!(
        "{} baselines rewritten, {} stamped `approver = generator`.\n\
         **NOBODY HAS LOOKED AT THESE IMAGES.** Open the harness, look, and run `approve`.",
        written.len(),
        stamped.len()
    );
    Ok(())
}

/// `approve`.
fn approve(arguments: &[String]) -> Result<(), String> {
    let name = std::env::var(APPROVED_BY).map_err(|_| {
        format!(
            "an approval records who gave it, so {APPROVED_BY} has to say who you are. This is the \
             one thing in the harness an agent cannot do for you: everything else here is the \
             renderer checking itself."
        )
    })?;
    let number: u8 = arguments
        .get(1)
        .ok_or("`approve` needs an inventory number")?
        .parse()
        .map_err(|_| "`approve` needs an inventory number".to_owned())?;
    let note = arguments
        .get(2)
        .ok_or("`approve` needs a note saying why you approved it")?;
    let store = plates::baselines();
    let approval = plates::approve(&store, number, &name, note)?;
    println!(
        "{} approved by {} on {}.",
        approval.specimen,
        approval.approver.label(),
        approval.date()
    );
    Ok(())
}
