/**
 * @generated by `cargo run -p xtask -- tokens` from docs/client-platform/data/tokens.json.
 * DO NOT EDIT. Edit the source and regenerate.
 *
 * The design-token source for the mjx-ooxml-rs client platform (MJXOFF-156, re-seeded from
 * hermes-universal by MJXOFF-271). It is TWO TIERS. The first is literal and is what a host
 * overrides: the `color` palette, and — inside `theme` — the ~14 skin SEEDS and the ~11 mix KNOBS,
 * whose CSS custom properties are byte for byte the ones
 * `apps/hermes-universal/src/themes/context.tsx` writes inline on `:root` (`--theme-foreground`,
 * `--theme-midground`, `--theme-background-seed`, `--theme-mix-chrome`, …). The second tier is
 * DERIVED: a colour written as `{ "mix": [ … ] }` is a CSS `color-mix(in srgb, …)` of the first
 * tier, and the surfaces, the text colours and the strokes are all derived rather than stated —
 * which is what makes dark mode the same seeds with different knobs instead of a second palette,
 * and what lets one overridden seed re-theme everything mixed from it. There is exactly ONE
 * implementation of that mix, `mjx_tokens::color_mix`; the generator evaluates every derivation
 * through it so all four artefacts carry the RESOLVED colour (a canvas needs a colour, not an
 * expression), and `ui/tokens/derivations.css` restates the expressions for the browser so the
 * cascade re-derives them. `ui/tokens/chromium-agreement.mjs` asserts that our one implementation
 * and Chromium's agree, for every derived token, in both schemes. The `font`, `font-weight`,
 * `text`, `leading`, `tracking`, `radius`, `spacing`, `shadow`, `ease` and `duration` groups are
 * the allr.work values as measured in docs/client-platform/DESIGN_TOKENS.md §1. This file is the
 * ONLY hand-edited artefact in the pipeline; ui/tokens/tokens.css, ui/tokens/derivations.css,
 * ui/tokens/tokens.ts and crates/mjx-tokens/src/generated.rs are emitted from it by `cargo run -p
 * xtask -- tokens`. FORMAT: W3C Design Tokens Community Group format, in its string profile —
 * `color` is `#rrggbb` or `#rrggbbaa`, `dimension` is a CSS length such as `8px`, `duration` is
 * `150ms`, `percentage` is `92%`. EXTENSIONS live under the `mjx` key: `rustType` names the struct
 * a group becomes in Rust; `schemes` marks a group whose children are colour schemes; `usage` and
 * `background` are the contrast metadata, required on every colour token.
 */

/**
 * The Allr brand constants. Warm and organic: the neutrals are beige rather than grey and the
 * `black` is a green. These are the raw ramp steps — `theme` names which of them plays which
 * role, and derives the surfaces from them. The values are hermes-universal's own
 * (`apps/hermes-universal/src/themes/presets.ts`, the `allr` skin), which is the same brand as
 * DESIGN_TOKENS.md §1 measured from the site; where the two differ the product's value wins,
 * because the point of the re-seed is that the editor and the app it is embedded in never
 * disagree about a colour.
 */
export interface Palette {
  /**
   * page background — warm off-white. DESIGN_TOKENS.md §1 measured `#fdfcf9` from the marketing
   * site's stylesheet; hermes's `ALLR_PAPER` is this, and it is the value the surrounding
   * application actually paints.
   *
   * CSS: `--color-paper` · type `color` · usage `fill-only`
   */
  readonly paper: string;
  /**
   * the site's actual page background — warmer than `paper`, and hermes's sidebar seed
   * (`ALLR_BODY`).
   *
   * CSS: `--color-body` · type `color` · usage `fill-only`
   */
  readonly body: string;
  /**
   * raised surfaces. hermes's rule: `card` is the sole `#ffffff`, and it is a surface, never a
   * text colour.
   *
   * CSS: `--color-card` · type `color` · usage `fill-only`
   */
  readonly card: string;
  /**
   * true white; the site declares it beside `card` and this file keeps both names.
   *
   * CSS: `--color-white` · type `color` · usage `fill-only`
   */
  readonly white: string;
  /**
   * the warm neutral the chrome and sidebar seeds are mixed toward (`--theme-neutral-chrome` /
   * `--theme-neutral-sidebar`). Without it a skin whose background seed is a strong colour
   * would paint the whole chrome in it.
   *
   * CSS: `--color-paper-neutral` · type `color` · usage `fill-only`
   */
  readonly paperNeutral: string;
  /**
   * the neutral the card and elevated seeds are mixed toward (`--theme-neutral-card`).
   *
   * CSS: `--color-card-neutral` · type `color` · usage `fill-only`
   */
  readonly cardNeutral: string;
  /**
   * primary text — a deep, desaturated green-black (hermes's `ALLR_INK`, "deep pine"). It is
   * also the dark scheme's card surface, which is what makes the dark theme read as the light
   * theme's ink rather than as a grey product.
   *
   * CSS: `--color-ink` · type `color` · usage `on-light-text` · 11.38 : 1 on `color.paper`
   */
  readonly ink: string;
  /**
   * secondary text.
   *
   * CSS: `--color-ink-soft` · type `color` · usage `on-light-text` · 4.93 : 1 on `color.paper`
   */
  readonly inkSoft: string;
  /**
   * borders — warm beige, not grey.
   *
   * CSS: `--color-line` · type `color` · usage `fill-only`
   */
  readonly line: string;
  /**
   * subtle dividers.
   *
   * CSS: `--color-line-soft` · type `color` · usage `fill-only`
   */
  readonly lineSoft: string;
  /**
   * primary accent. DESIGN_TOKENS.md §2.2: 3.39 : 1 on white — legal for UI components and
   * large text, ILLEGAL for body text. Fills, borders, indicators and icons only; `green-deep`
   * is the accent-coloured text colour.
   *
   * CSS: `--color-green` · type `color` · usage `fill-only` · 3.39 : 1 on `color.white`
   */
  readonly green: string;
  /**
   * accent, pressed / on-light text. DESIGN_TOKENS.md §2.2: 5.34 : 1 on white — legal for body
   * text. hermes uses it as the CTA colour for exactly that reason.
   *
   * CSS: `--color-green-deep` · type `color` · usage `on-light-text` · 5.34 : 1 on
   * `color.white`
   */
  readonly greenDeep: string;
  /**
   * the dark scheme's accent-coloured text. hermes: "lifted off #2e9e63 — the brand green is
   * tuned for white and drops below 4.5 : 1 against pine".
   *
   * CSS: `--color-green-lifted` · type `color` · usage `on-dark-text` · 4.83 : 1 on `color.ink`
   */
  readonly greenLifted: string;
  /**
   * accent border.
   *
   * CSS: `--color-green-line` · type `color` · usage `fill-only`
   */
  readonly greenLine: string;
  /**
   * accent surface.
   *
   * CSS: `--color-green-tint` · type `color` · usage `fill-only`
   */
  readonly greenTint: string;
  /**
   * secondary accent — "lamplight".
   *
   * CSS: `--color-honey` · type `color` · usage `fill-only` · 2.07 : 1 on `color.white`
   */
  readonly honey: string;
  /**
   * secondary accent, deep. Measured at 3.49 : 1 on white by this generator, so — unlike
   * `green-deep`, its counterpart in the green ramp — it is NOT legal for body text and is
   * tagged `fill-only`. hermes reaches the same conclusion from the other direction: `#e9a83e`
   * is 1.95 : 1 on paper and therefore invisible as a 1px focus ring, so honey-deep is the
   * light scheme's `midground`.
   *
   * CSS: `--color-honey-deep` · type `color` · usage `fill-only` · 3.49 : 1 on `color.white`
   */
  readonly honeyDeep: string;
  /**
   * secondary border.
   *
   * CSS: `--color-honey-line` · type `color` · usage `fill-only`
   */
  readonly honeyLine: string;
  /**
   * secondary surface.
   *
   * CSS: `--color-honey-tint` · type `color` · usage `fill-only`
   */
  readonly honeyTint: string;
  /**
   * tertiary border.
   *
   * CSS: `--color-sage-line` · type `color` · usage `fill-only`
   */
  readonly sageLine: string;
  /**
   * tertiary surface — hermes's `accent-soft`.
   *
   * CSS: `--color-sage-tint` · type `color` · usage `fill-only`
   */
  readonly sageTint: string;
  /**
   * warm neutral surface.
   *
   * CSS: `--color-clay-tint` · type `color` · usage `fill-only`
   */
  readonly clayTint: string;
  /**
   * hermes's `ALLR_CLAY` — the destructive colour, warm rather than a generic red.
   *
   * CSS: `--color-clay` · type `color` · usage `fill-only` · 5.31 : 1 on `color.white`
   */
  readonly clay: string;
  /**
   * the warm glow seed (`--theme-warm`).
   *
   * CSS: `--color-warm` · type `color` · usage `fill-only`
   */
  readonly warm: string;
}

/**
 * The site's three families. Young Serif is display-only — empty states and onboarding, never
 * the chrome and never document content.
 */
export interface FontFamilies {
  /**
   * the chrome face; a rounded humanist that reads slightly wider than a typical UI font.
   *
   * CSS: `--font-sans` · type `fontFamily`
   */
  readonly sans: string;
  /**
   * display only.
   *
   * CSS: `--font-serif` · type `fontFamily`
   */
  readonly serif: string;
  /**
   * DESIGN_TOKENS.md §1 elides this stack after `Liberation Mono`; the elision is the standard
   * Tailwind v4 monospace stack, written out here in full.
   *
   * CSS: `--font-mono` · type `fontFamily`
   */
  readonly mono: string;
}

/**
 * The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
 * custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the layer
 * the site's theme is written in.
 */
export interface FontWeights {
  /**
   * CSS: `--font-weight-medium` · type `fontWeight`
   */
  readonly medium: number;
  /**
   * CSS: `--font-weight-semibold` · type `fontWeight`
   */
  readonly semibold: number;
  /**
   * CSS: `--font-weight-bold` · type `fontWeight`
   */
  readonly bold: number;
  /**
   * CSS: `--font-weight-extrabold` · type `fontWeight`
   */
  readonly extrabold: number;
}

/**
 * The two small type sizes the site declares. Dense editor surfaces — the formula bar, the cell
 * grid, a properties inspector — use `xs` with `leading.tight`, not the site's relaxed body
 * measure.
 */
export interface TextSizes {
  /**
   * CSS: `--text-xs` · type `dimension`
   */
  readonly xs: string;
  /**
   * CSS: `--text-sm` · type `dimension`
   */
  readonly sm: string;
}

/**
 * Line heights, unitless.
 */
export interface LineHeights {
  /**
   * CSS: `--leading-tight` · type `number`
   */
  readonly tight: number;
  /**
   * CSS: `--leading-snug` · type `number`
   */
  readonly snug: number;
  /**
   * CSS: `--leading-relaxed` · type `number`
   */
  readonly relaxed: number;
  /**
   * DESIGN_TOKENS.md §1 records this as `body line-height` with no custom-property name of its
   * own; it joins the `leading` family here.
   *
   * CSS: `--leading-body` · type `number`
   */
  readonly body: number;
}

/**
 * Letter spacing.
 */
export interface LetterSpacings {
  /**
   * CSS: `--tracking-tight` · type `dimension`
   */
  readonly tight: string;
}

/**
 * The radii are large, and that is the most recognisable part of the source's character.
 * Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners Office
 * uses.
 */
export interface Radii {
  /**
   * CSS: `--radius-chip` · type `dimension`
   */
  readonly chip: string;
  /**
   * CSS: `--radius-control` · type `dimension`
   */
  readonly control: string;
  /**
   * CSS: `--radius-card` · type `dimension`
   */
  readonly card: string;
  /**
   * CSS: `--radius-panel` · type `dimension`
   */
  readonly panel: string;
  /**
   * CSS: `--radius-frame` · type `dimension`
   */
  readonly frame: string;
  /**
   * CSS: `--radius-phone` · type `dimension`
   */
  readonly phone: string;
}

/**
 * Shadows are ink-tinted, never neutral black.
 */
export interface Shadows {
  /**
   * the site's one elevation, tinted with `color.ink` at 11% alpha.
   *
   * CSS: `--shadow-lift` · type `shadow`
   */
  readonly lift: string;
}

/**
 * `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to a
 * document object, where overshoot reads as imprecision. Selection, handles and canvas motion
 * use `ink`.
 */
export interface Easings {
  /**
   * CSS: `--ease-ink` · type `cubicBezier`
   */
  readonly ink: string;
  /**
   * CSS: `--ease-out-soft` · type `cubicBezier`
   */
  readonly outSoft: string;
  /**
   * CSS: `--ease-spring` · type `cubicBezier`
   */
  readonly spring: string;
}

/**
 * DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no custom-property
 * name of its own; it is named `--duration-transition` here for what it is.
 */
export interface Durations {
  /**
   * CSS: `--duration-transition` · type `duration`
   */
  readonly transition: string;
}

/**
 * The application theme, in both colour schemes and in three layers. SEEDS come first — the
 * skin's raw colours, whose scheme-relative custom properties (`--theme-foreground`,
 * `--theme-primary`, `--theme-midground`, `--theme-background-seed`, …) are exactly the names
 * hermes-universal's `applyTheme()` writes inline on `:root`, so dropping this platform into
 * that application re-themes it with no code. KNOBS come second — the mix percentages
 * `applyTheme()` writes beside them. The SEMANTIC layer comes last and is mostly DERIVED from
 * the two above by `color-mix(in srgb, …)`: that is why the dark scheme is not a second palette
 * but the same expressions over different seeds, and why one overridden seed moves every
 * surface, text colour and stroke that is mixed from it. The two schemes must carry exactly the
 * same member names AND derive each of them the same way; the generator fails if either drifts.
 */
export interface Themes {
  readonly light: ThemeColors;
  readonly dark: ThemeColors;
}

export interface ThemeColors {
  /**
   * SEED. The ink every text colour and every stroke is mixed from. `--theme-foreground`.
   *
   * CSS: `--theme-light-foreground` · type `color` · usage `on-light-text` · 11.30 : 1 on
   * `theme.light.background`
   */
  readonly foreground: string;
  /**
   * SEED. The CTA colour — hermes uses green-deep rather than the brand green so small white
   * label text on a primary control stays legible. `--theme-primary`.
   *
   * CSS: `--theme-light-primary` · type `color` · usage `on-light-text` · 5.26 : 1 on
   * `theme.light.surface`
   */
  readonly primary: string;
  /**
   * SEED. `--theme-secondary`.
   *
   * CSS: `--theme-light-secondary` · type `color` · usage `fill-only`
   */
  readonly secondary: string;
  /**
   * SEED. `--theme-accent-soft`.
   *
   * CSS: `--theme-light-accent-soft` · type `color` · usage `fill-only`
   */
  readonly accentSoft: string;
  /**
   * SEED. What hermes calls the ring colour: focus rings, the streaming cursor, active pills,
   * and — through the stroke knobs below — every border in the chrome. Honey-DEEP in the light
   * scheme, because `#e9a83e` measures 1.95 : 1 on paper and a 1px ring in it is invisible.
   * `--theme-midground`.
   *
   * CSS: `--theme-light-midground` · type `color` · usage `fill-only` · 3.44 : 1 on
   * `theme.light.surface`
   */
  readonly midground: string;
  /**
   * SEED. The warm-glow tint. `--theme-warm`.
   *
   * CSS: `--theme-light-warm` · type `color` · usage `fill-only`
   */
  readonly warm: string;
  /**
   * SEED. The chrome's own colour, before it is mixed toward `neutral-chrome`.
   * `--theme-background-seed`.
   *
   * CSS: `--theme-light-background-seed` · type `color` · usage `fill-only`
   */
  readonly backgroundSeed: string;
  /**
   * SEED. `--theme-sidebar-seed`.
   *
   * CSS: `--theme-light-sidebar-seed` · type `color` · usage `fill-only`
   */
  readonly sidebarSeed: string;
  /**
   * SEED. `--theme-card-seed`.
   *
   * CSS: `--theme-light-card-seed` · type `color` · usage `fill-only`
   */
  readonly cardSeed: string;
  /**
   * SEED. `--theme-elevated-seed`.
   *
   * CSS: `--theme-light-elevated-seed` · type `color` · usage `fill-only`
   */
  readonly elevatedSeed: string;
  /**
   * SEED. `--theme-bubble-seed`.
   *
   * CSS: `--theme-light-bubble-seed` · type `color` · usage `fill-only`
   */
  readonly bubbleSeed: string;
  /**
   * SEED. What the chrome seed is mixed toward, so that a strongly coloured skin still yields a
   * habitable chrome. `--theme-neutral-chrome`.
   *
   * CSS: `--theme-light-neutral-chrome` · type `color` · usage `fill-only`
   */
  readonly neutralChrome: string;
  /**
   * SEED. `--theme-neutral-sidebar`.
   *
   * CSS: `--theme-light-neutral-sidebar` · type `color` · usage `fill-only`
   */
  readonly neutralSidebar: string;
  /**
   * SEED. `--theme-neutral-card`.
   *
   * CSS: `--theme-light-neutral-card` · type `color` · usage `fill-only`
   */
  readonly neutralCard: string;
  /**
   * KNOB. How much of `background-seed` survives into the chrome. `--theme-mix-chrome`.
   *
   * CSS: `--theme-light-mix-chrome` · type `percentage`
   */
  readonly mixChrome: string;
  /**
   * KNOB. `--theme-mix-sidebar`. Declared although no member below reads it yet: hermes writes
   * all five surface knobs together, and a host that set four of five would otherwise leave the
   * fifth silently at our default.
   *
   * CSS: `--theme-light-mix-sidebar` · type `percentage`
   */
  readonly mixSidebar: string;
  /**
   * KNOB. `--theme-mix-card`.
   *
   * CSS: `--theme-light-mix-card` · type `percentage`
   */
  readonly mixCard: string;
  /**
   * KNOB. `--theme-mix-elevated`.
   *
   * CSS: `--theme-light-mix-elevated` · type `percentage`
   */
  readonly mixElevated: string;
  /**
   * KNOB. `--theme-mix-bubble`. Declared for the reason `mix-sidebar` gives.
   *
   * CSS: `--theme-light-mix-bubble` · type `percentage`
   */
  readonly mixBubble: string;
  /**
   * KNOB. How much accent a primary fill carries. `--theme-fill-primary-accent-mix`.
   *
   * CSS: `--theme-light-fill-primary-accent-mix` · type `percentage`
   */
  readonly fillPrimaryAccentMix: string;
  /**
   * KNOB. `--theme-fill-secondary-accent-mix`.
   *
   * CSS: `--theme-light-fill-secondary-accent-mix` · type `percentage`
   */
  readonly fillSecondaryAccentMix: string;
  /**
   * KNOB. `--theme-fill-tertiary-accent-mix`.
   *
   * CSS: `--theme-light-fill-tertiary-accent-mix` · type `percentage`
   */
  readonly fillTertiaryAccentMix: string;
  /**
   * KNOB. `--theme-stroke-primary-accent-mix`.
   *
   * CSS: `--theme-light-stroke-primary-accent-mix` · type `percentage`
   */
  readonly strokePrimaryAccentMix: string;
  /**
   * KNOB. `--theme-stroke-secondary-accent-mix`.
   *
   * CSS: `--theme-light-stroke-secondary-accent-mix` · type `percentage`
   */
  readonly strokeSecondaryAccentMix: string;
  /**
   * KNOB. `--theme-stroke-tertiary-accent-mix`.
   *
   * CSS: `--theme-light-stroke-tertiary-accent-mix` · type `percentage`
   */
  readonly strokeTertiaryAccentMix: string;
  /**
   * DERIVED — hermes's `--ui-bg-chrome`. The application background.
   *
   * CSS: `--theme-light-background` · type `color` · usage `fill-only`
   */
  readonly background: string;
  /**
   * DERIVED — hermes's `--ui-bg-editor`.
   *
   * CSS: `--theme-light-surface` · type `color` · usage `fill-only`
   */
  readonly surface: string;
  /**
   * DERIVED — hermes's `--ui-bg-elevated`.
   *
   * CSS: `--theme-light-surface-raised` · type `color` · usage `fill-only`
   */
  readonly surfaceRaised: string;
  /**
   * The ink itself, and NOT hermes's `--ui-text-primary` (which is the ink at 94% alpha). ⚠
   * Measured, not preferred: this token must be opaque, because the contrast gate refuses a
   * translucent text colour on the ground that it would be measured against a surface it is
   * never seen on — and an opaque approximation of `rgba(ink, 0.94)` is only exact on the one
   * surface it was composited over, which is a promise a primary text colour cannot keep across
   * a background, a surface and a raised surface. Softening it also costs the palette its
   * dynamic range: with primary text at 94% the picker's swatch indicator — which chooses
   * between this and `surface` — bottomed out at 2.99 : 1 over the 4,352-colour sweep, below
   * WCAG 1.4.11's floor. hermes's softening survives where it is a genuine hierarchy step
   * rather than a texture, which is `text-secondary` at 74%.
   *
   * CSS: `--theme-light-text-primary` · type `color` · usage `on-light-text` · 11.30 : 1 on
   * `theme.light.background`
   */
  readonly textPrimary: string;
  /**
   * DERIVED — hermes's `--ui-text-secondary`, composited for the reason `text-primary` gives.
   *
   * CSS: `--theme-light-text-secondary` · type `color` · usage `on-light-text` · 5.23 : 1 on
   * `theme.light.background`
   */
  readonly textSecondary: string;
  /**
   * DERIVED — hermes's `--ui-stroke-secondary`: a little accent over ink at low alpha, so
   * strokes stay pine-and-lamplight rather than going grey against a warm surface. hermes mixes
   * toward `transparent`; this mixes toward the background instead, which is the same colour
   * once composited and is what keeps the token opaque and measurable.
   *
   * CSS: `--theme-light-border` · type `color` · usage `fill-only`
   */
  readonly border: string;
  /**
   * DERIVED — hermes's `--ui-stroke-tertiary`.
   *
   * CSS: `--theme-light-border-subtle` · type `color` · usage `fill-only`
   */
  readonly borderSubtle: string;
  /**
   * Fills, borders, indicators and icons. NOT text — see `accent-pressed`.
   *
   * CSS: `--theme-light-accent` · type `color` · usage `fill-only` · 3.34 : 1 on
   * `theme.light.surface`
   */
  readonly accent: string;
  /**
   * The pressed accent, and the only accent-coloured text colour on a light surface.
   *
   * CSS: `--theme-light-accent-pressed` · type `color` · usage `on-light-text` · 5.26 : 1 on
   * `theme.light.surface`
   */
  readonly accentPressed: string;
  /**
   * DERIVED — hermes's `--ui-bg-primary` shape, with two corrections that are measurements
   * rather than taste. It tints the **surface** and not the chrome background, because an
   * accent surface is a tinted surface and that is what it sits on. And it uses the SECONDARY
   * fill knob: at the primary knob's 16% the accent surface reaches 4.23 : 1 against
   * `accent-pressed`, and this pairing is a labelled button in the shared harness — below the
   * 4.5 : 1 body-text minimum, on every story. The TERTIARY knob is the strongest tint at which
   * the accent-coloured label stays legal in BOTH schemes: 4.76 : 1 light and 4.63 : 1 dark,
   * against 4.23 and 3.90 at the primary knob. The dark side is the binding one, because there
   * the accent fill and `accent-pressed` are near neighbours in lightness.
   *
   * CSS: `--theme-light-accent-surface` · type `color` · usage `fill-only`
   */
  readonly accentSurface: string;
  /**
   * DERIVED — hermes's `--ui-stroke-primary` shape, in the accent rather than the ring colour,
   * over the surface it is drawn on.
   *
   * CSS: `--theme-light-accent-border` · type `color` · usage `fill-only`
   */
  readonly accentBorder: string;
  /**
   * The ring colour, exposed under the name the chrome uses for it.
   *
   * CSS: `--theme-light-secondary-accent` · type `color` · usage `fill-only` · 3.44 : 1 on
   * `theme.light.surface`
   */
  readonly secondaryAccent: string;
  /**
   * DERIVED. The secondary accent's own fill, mixed by the same knob and over the same surface
   * as `accent-surface`, so the two ramps cannot drift apart — and so the contrast decision
   * taken for one holds for the other.
   *
   * CSS: `--theme-light-secondary-surface` · type `color` · usage `fill-only`
   */
  readonly secondarySurface: string;
}

/**
 * The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
 * conflating them is the classic mistake. The page stays true white in both schemes — a
 * document is white paper, and a warm-tinted or dark page changes what the author sees relative
 * to what they will print or send. What changes with the scheme is the canvas backdrop behind
 * the page, the page shadow, and the in-canvas UI. A reading-mode inversion of the page itself
 * is a user setting, not a theme consequence. These are the tokens the Rust canvas needs and a
 * CSS custom property cannot reach it, which is the reason this pipeline emits four artefacts
 * instead of one.
 */
export interface DocumentSurfaces {
  readonly light: DocumentColors;
  readonly dark: DocumentColors;
}

export interface DocumentColors {
  /**
   * KNOB. How much of the accent a selection fill carries. It is a knob rather than a number
   * inside the derivation because the two schemes want different strengths, and one
   * `color-mix()` declaration has to serve both.
   *
   * CSS: `--document-light-selection-alpha` · type `percentage`
   */
  readonly selectionAlpha: string;
  /**
   * The chrome's own background behind a true-white page, which makes the page read as a
   * distinct, lit object rather than dissolving into it.
   *
   * CSS: `--document-light-backdrop` · type `color` · usage `fill-only`
   */
  readonly backdrop: string;
  /**
   * CSS: `--document-light-page` · type `color` · usage `fill-only`
   */
  readonly page: string;
  /**
   * The page's edge is the chrome's own border colour, so the one place chrome meets canvas
   * cannot disagree with itself.
   *
   * CSS: `--document-light-page-border` · type `color` · usage `fill-only`
   */
  readonly pageBorder: string;
  /**
   * CSS: `--document-light-page-shadow` · type `shadow`
   */
  readonly pageShadow: string;
  /**
   * DERIVED. `color-mix(in srgb, C p%, transparent)` is an ALPHA operation and not a blend
   * toward black — it yields the accent's own channels at `p%` alpha — which is why a selection
   * fill can be written this way at all.
   *
   * CSS: `--document-light-selection-fill` · type `color` · usage `fill-only`
   */
  readonly selectionFill: string;
  /**
   * CSS: `--document-light-selection-handle` · type `color` · usage `fill-only`
   */
  readonly selectionHandle: string;
  /**
   * CSS: `--document-light-alignment-guide` · type `color` · usage `fill-only`
   */
  readonly alignmentGuide: string;
  /**
   * grid and ruler lines.
   *
   * CSS: `--document-light-grid-line` · type `color` · usage `fill-only`
   */
  readonly gridLine: string;
  /**
   * CSS: `--document-light-comment-anchor` · type `color` · usage `fill-only`
   */
  readonly commentAnchor: string;
  /**
   * Tagged `fill-only`: measured against the page it does not reach 4.5 : 1, so it is legal for
   * the change bar, the underline rule and the marker, and a tracked insertion's own glyphs
   * must stay `theme.*.text-primary`.
   *
   * CSS: `--document-light-tracked-change-insert` · type `color` · usage `fill-only` · 3.39 : 1
   * on `document.light.page`
   */
  readonly trackedChangeInsert: string;
  /**
   * Tagged `fill-only` for the same reason as `tracked-change-insert`.
   *
   * CSS: `--document-light-tracked-change-delete` · type `color` · usage `fill-only` · 3.49 : 1
   * on `document.light.page`
   */
  readonly trackedChangeDelete: string;
}

/** The whole token set. */
export interface Tokens {
  /**
   * The Allr brand constants. Warm and organic: the neutrals are beige rather than grey and the
   * `black` is a green. These are the raw ramp steps — `theme` names which of them plays which
   * role, and derives the surfaces from them. The values are hermes-universal's own
   * (`apps/hermes-universal/src/themes/presets.ts`, the `allr` skin), which is the same brand
   * as DESIGN_TOKENS.md §1 measured from the site; where the two differ the product's value
   * wins, because the point of the re-seed is that the editor and the app it is embedded in
   * never disagree about a colour.
   */
  readonly color: Palette;
  /**
   * The site's three families. Young Serif is display-only — empty states and onboarding, never
   * the chrome and never document content.
   */
  readonly font: FontFamilies;
  /**
   * The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
   * custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the layer
   * the site's theme is written in.
   */
  readonly fontWeight: FontWeights;
  /**
   * The two small type sizes the site declares. Dense editor surfaces — the formula bar, the
   * cell grid, a properties inspector — use `xs` with `leading.tight`, not the site's relaxed
   * body measure.
   */
  readonly text: TextSizes;
  /**
   * Line heights, unitless.
   */
  readonly leading: LineHeights;
  /**
   * Letter spacing.
   */
  readonly tracking: LetterSpacings;
  /**
   * The radii are large, and that is the most recognisable part of the source's character.
   * Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners
   * Office uses.
   */
  readonly radius: Radii;
  /**
   * The base spacing step, from which the site's spacing scale is multiplied. It is a token in
   * its own right rather than a group so that its custom property is `--spacing`, exactly as
   * the site declares it.
   *
   * CSS: `--spacing` · type `dimension`
   */
  readonly spacing: string;
  /**
   * Shadows are ink-tinted, never neutral black.
   */
  readonly shadow: Shadows;
  /**
   * `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to a
   * document object, where overshoot reads as imprecision. Selection, handles and canvas motion
   * use `ink`.
   */
  readonly ease: Easings;
  /**
   * DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no custom-property
   * name of its own; it is named `--duration-transition` here for what it is.
   */
  readonly duration: Durations;
  /**
   * The application theme, in both colour schemes and in three layers. SEEDS come first — the
   * skin's raw colours, whose scheme-relative custom properties (`--theme-foreground`,
   * `--theme-primary`, `--theme-midground`, `--theme-background-seed`, …) are exactly the names
   * hermes-universal's `applyTheme()` writes inline on `:root`, so dropping this platform into
   * that application re-themes it with no code. KNOBS come second — the mix percentages
   * `applyTheme()` writes beside them. The SEMANTIC layer comes last and is mostly DERIVED from
   * the two above by `color-mix(in srgb, …)`: that is why the dark scheme is not a second
   * palette but the same expressions over different seeds, and why one overridden seed moves
   * every surface, text colour and stroke that is mixed from it. The two schemes must carry
   * exactly the same member names AND derive each of them the same way; the generator fails if
   * either drifts.
   */
  readonly theme: Themes;
  /**
   * The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
   * conflating them is the classic mistake. The page stays true white in both schemes — a
   * document is white paper, and a warm-tinted or dark page changes what the author sees
   * relative to what they will print or send. What changes with the scheme is the canvas
   * backdrop behind the page, the page shadow, and the in-canvas UI. A reading-mode inversion
   * of the page itself is a user setting, not a theme consequence. These are the tokens the
   * Rust canvas needs and a CSS custom property cannot reach it, which is the reason this
   * pipeline emits four artefacts instead of one.
   */
  readonly document: DocumentSurfaces;
}

/** The colour schemes every scheme group in the source declares. */
export type ColorScheme = 'light' | 'dark';

/** The generated defaults — the values this platform ships with. */
export const tokens: Tokens = {
  color: {
    paper: '#fbf8f2',
    body: '#f7f1e6',
    card: '#ffffff',
    white: '#ffffff',
    paperNeutral: '#f5efe4',
    cardNeutral: '#fffdf9',
    ink: '#223b33',
    inkSoft: '#5c7168',
    line: '#e7e0d2',
    lineSoft: '#efe9dc',
    green: '#2e9e63',
    greenDeep: '#1e7a49',
    greenLifted: '#45b87f',
    greenLine: '#c2e5d0',
    greenTint: '#e4f4ea',
    honey: '#e9a83e',
    honeyDeep: '#b77e1f',
    honeyLine: '#f0dcb4',
    honeyTint: '#fbefd8',
    sageLine: '#dce8dd',
    sageTint: '#ecf2ec',
    clayTint: '#f6ede2',
    clay: '#a6543c',
    warm: '#cf806d',
  },
  font: {
    sans: '"Nunito Sans", system-ui, sans-serif',
    serif: '"Young Serif", serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  fontWeight: {
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
  },
  text: {
    xs: '0.75rem',
    sm: '0.875rem',
  },
  leading: {
    tight: 1.25,
    snug: 1.375,
    relaxed: 1.625,
    body: 1.7,
  },
  tracking: {
    tight: '-0.025em',
  },
  radius: {
    chip: '4px',
    control: '6px',
    card: '10px',
    panel: '12px',
    frame: '14px',
    phone: '24px',
  },
  spacing: '0.25rem',
  shadow: {
    lift: '0px 18px 48px #223b331c',
  },
  ease: {
    ink: 'cubic-bezier(0.45, 0, 0.2, 1)',
    outSoft: 'cubic-bezier(0.22, 1, 0.36, 1)',
    spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
  duration: {
    transition: '150ms',
  },
  theme: {
    light: {
      foreground: '#223b33',
      primary: '#1e7a49',
      secondary: '#fbefd8',
      accentSoft: '#ecf2ec',
      midground: '#b77e1f',
      warm: '#cf806d',
      backgroundSeed: '#fbf8f2',
      sidebarSeed: '#f7f1e6',
      cardSeed: '#ffffff',
      elevatedSeed: '#ffffff',
      bubbleSeed: '#fbefd8',
      neutralChrome: '#f5efe4',
      neutralSidebar: '#f5efe4',
      neutralCard: '#fffdf9',
      mixChrome: '92%',
      mixSidebar: '100%',
      mixCard: '22%',
      mixElevated: '28%',
      mixBubble: '0%',
      fillPrimaryAccentMix: '16%',
      fillSecondaryAccentMix: '11%',
      fillTertiaryAccentMix: '8%',
      strokePrimaryAccentMix: '24%',
      strokeSecondaryAccentMix: '16%',
      strokeTertiaryAccentMix: '10%',
      background: '#fbf7f1',
      surface: '#fffdfa',
      surfaceRaised: '#fffefb',
      textPrimary: '#223b33',
      textSecondary: '#5a6c64',
      border: '#e3d9c4',
      borderSubtle: '#eae3d3',
      accent: '#2e9e63',
      accentPressed: '#1e7a49',
      accentSurface: '#eef6ee',
      accentBorder: '#cde7d6',
      secondaryAccent: '#b77e1f',
      secondarySurface: '#f9f3e9',
    },
    dark: {
      foreground: '#f0e9da',
      primary: '#45b87f',
      secondary: '#2e4a40',
      accentSoft: '#2e4a40',
      midground: '#e9a83e',
      warm: '#cf806d',
      backgroundSeed: '#16241f',
      sidebarSeed: '#101c18',
      cardSeed: '#223b33',
      elevatedSeed: '#2e4a40',
      bubbleSeed: '#2a4239',
      neutralChrome: '#101c18',
      neutralSidebar: '#0c1613',
      neutralCard: '#223b33',
      mixChrome: '74%',
      mixSidebar: '100%',
      mixCard: '38%',
      mixElevated: '46%',
      mixBubble: '46%',
      fillPrimaryAccentMix: '16%',
      fillSecondaryAccentMix: '11%',
      fillTertiaryAccentMix: '5%',
      strokePrimaryAccentMix: '24%',
      strokeSecondaryAccentMix: '16%',
      strokeTertiaryAccentMix: '10%',
      background: '#14221d',
      surface: '#223b33',
      surfaceRaised: '#284239',
      textPrimary: '#f0e9da',
      textSecondary: '#b7b5a9',
      border: '#43432e',
      borderSubtle: '#343829',
      accent: '#2e9e63',
      accentPressed: '#45b87f',
      accentSurface: '#234035',
      accentBorder: '#25533f',
      secondaryAccent: '#e9a83e',
      secondarySurface: '#2c4034',
    },
  },
  document: {
    light: {
      selectionAlpha: '18%',
      backdrop: '#fbf7f1',
      page: '#ffffff',
      pageBorder: '#e3d9c4',
      pageShadow: '0px 2px 10px #223b3314',
      selectionFill: '#2e9e632e',
      selectionHandle: '#1e7a49',
      alignmentGuide: '#b77e1f',
      gridLine: '#eae3d3',
      commentAnchor: '#b77e1f',
      trackedChangeInsert: '#2e9e63',
      trackedChangeDelete: '#b77e1f',
    },
    dark: {
      selectionAlpha: '22%',
      backdrop: '#14221d',
      page: '#ffffff',
      pageBorder: '#43432e',
      pageShadow: '0px 2px 14px #00000059',
      selectionFill: '#2e9e6338',
      selectionHandle: '#45b87f',
      alignmentGuide: '#e9a83e',
      gridLine: '#343829',
      commentAnchor: '#e9a83e',
      trackedChangeInsert: '#2e9e63',
      trackedChangeDelete: '#e9a83e',
    },
  },
};

/**
 * Every token's CSS custom property, keyed by its path in `tokens`. A runtime resolver reads these
 * names off the host element; a host that already defines one is re-theming the platform, which is
 * exactly what it is meant to be able to do.
 */
export const customProperties: Readonly<Record<string, string>> = {
  'color.paper': '--color-paper',
  'color.body': '--color-body',
  'color.card': '--color-card',
  'color.white': '--color-white',
  'color.paperNeutral': '--color-paper-neutral',
  'color.cardNeutral': '--color-card-neutral',
  'color.ink': '--color-ink',
  'color.inkSoft': '--color-ink-soft',
  'color.line': '--color-line',
  'color.lineSoft': '--color-line-soft',
  'color.green': '--color-green',
  'color.greenDeep': '--color-green-deep',
  'color.greenLifted': '--color-green-lifted',
  'color.greenLine': '--color-green-line',
  'color.greenTint': '--color-green-tint',
  'color.honey': '--color-honey',
  'color.honeyDeep': '--color-honey-deep',
  'color.honeyLine': '--color-honey-line',
  'color.honeyTint': '--color-honey-tint',
  'color.sageLine': '--color-sage-line',
  'color.sageTint': '--color-sage-tint',
  'color.clayTint': '--color-clay-tint',
  'color.clay': '--color-clay',
  'color.warm': '--color-warm',
  'font.sans': '--font-sans',
  'font.serif': '--font-serif',
  'font.mono': '--font-mono',
  'fontWeight.medium': '--font-weight-medium',
  'fontWeight.semibold': '--font-weight-semibold',
  'fontWeight.bold': '--font-weight-bold',
  'fontWeight.extrabold': '--font-weight-extrabold',
  'text.xs': '--text-xs',
  'text.sm': '--text-sm',
  'leading.tight': '--leading-tight',
  'leading.snug': '--leading-snug',
  'leading.relaxed': '--leading-relaxed',
  'leading.body': '--leading-body',
  'tracking.tight': '--tracking-tight',
  'radius.chip': '--radius-chip',
  'radius.control': '--radius-control',
  'radius.card': '--radius-card',
  'radius.panel': '--radius-panel',
  'radius.frame': '--radius-frame',
  'radius.phone': '--radius-phone',
  'spacing': '--spacing',
  'shadow.lift': '--shadow-lift',
  'ease.ink': '--ease-ink',
  'ease.outSoft': '--ease-out-soft',
  'ease.spring': '--ease-spring',
  'duration.transition': '--duration-transition',
  'theme.light.foreground': '--theme-light-foreground',
  'theme.light.primary': '--theme-light-primary',
  'theme.light.secondary': '--theme-light-secondary',
  'theme.light.accentSoft': '--theme-light-accent-soft',
  'theme.light.midground': '--theme-light-midground',
  'theme.light.warm': '--theme-light-warm',
  'theme.light.backgroundSeed': '--theme-light-background-seed',
  'theme.light.sidebarSeed': '--theme-light-sidebar-seed',
  'theme.light.cardSeed': '--theme-light-card-seed',
  'theme.light.elevatedSeed': '--theme-light-elevated-seed',
  'theme.light.bubbleSeed': '--theme-light-bubble-seed',
  'theme.light.neutralChrome': '--theme-light-neutral-chrome',
  'theme.light.neutralSidebar': '--theme-light-neutral-sidebar',
  'theme.light.neutralCard': '--theme-light-neutral-card',
  'theme.light.mixChrome': '--theme-light-mix-chrome',
  'theme.light.mixSidebar': '--theme-light-mix-sidebar',
  'theme.light.mixCard': '--theme-light-mix-card',
  'theme.light.mixElevated': '--theme-light-mix-elevated',
  'theme.light.mixBubble': '--theme-light-mix-bubble',
  'theme.light.fillPrimaryAccentMix': '--theme-light-fill-primary-accent-mix',
  'theme.light.fillSecondaryAccentMix': '--theme-light-fill-secondary-accent-mix',
  'theme.light.fillTertiaryAccentMix': '--theme-light-fill-tertiary-accent-mix',
  'theme.light.strokePrimaryAccentMix': '--theme-light-stroke-primary-accent-mix',
  'theme.light.strokeSecondaryAccentMix': '--theme-light-stroke-secondary-accent-mix',
  'theme.light.strokeTertiaryAccentMix': '--theme-light-stroke-tertiary-accent-mix',
  'theme.light.background': '--theme-light-background',
  'theme.light.surface': '--theme-light-surface',
  'theme.light.surfaceRaised': '--theme-light-surface-raised',
  'theme.light.textPrimary': '--theme-light-text-primary',
  'theme.light.textSecondary': '--theme-light-text-secondary',
  'theme.light.border': '--theme-light-border',
  'theme.light.borderSubtle': '--theme-light-border-subtle',
  'theme.light.accent': '--theme-light-accent',
  'theme.light.accentPressed': '--theme-light-accent-pressed',
  'theme.light.accentSurface': '--theme-light-accent-surface',
  'theme.light.accentBorder': '--theme-light-accent-border',
  'theme.light.secondaryAccent': '--theme-light-secondary-accent',
  'theme.light.secondarySurface': '--theme-light-secondary-surface',
  'theme.dark.foreground': '--theme-dark-foreground',
  'theme.dark.primary': '--theme-dark-primary',
  'theme.dark.secondary': '--theme-dark-secondary',
  'theme.dark.accentSoft': '--theme-dark-accent-soft',
  'theme.dark.midground': '--theme-dark-midground',
  'theme.dark.warm': '--theme-dark-warm',
  'theme.dark.backgroundSeed': '--theme-dark-background-seed',
  'theme.dark.sidebarSeed': '--theme-dark-sidebar-seed',
  'theme.dark.cardSeed': '--theme-dark-card-seed',
  'theme.dark.elevatedSeed': '--theme-dark-elevated-seed',
  'theme.dark.bubbleSeed': '--theme-dark-bubble-seed',
  'theme.dark.neutralChrome': '--theme-dark-neutral-chrome',
  'theme.dark.neutralSidebar': '--theme-dark-neutral-sidebar',
  'theme.dark.neutralCard': '--theme-dark-neutral-card',
  'theme.dark.mixChrome': '--theme-dark-mix-chrome',
  'theme.dark.mixSidebar': '--theme-dark-mix-sidebar',
  'theme.dark.mixCard': '--theme-dark-mix-card',
  'theme.dark.mixElevated': '--theme-dark-mix-elevated',
  'theme.dark.mixBubble': '--theme-dark-mix-bubble',
  'theme.dark.fillPrimaryAccentMix': '--theme-dark-fill-primary-accent-mix',
  'theme.dark.fillSecondaryAccentMix': '--theme-dark-fill-secondary-accent-mix',
  'theme.dark.fillTertiaryAccentMix': '--theme-dark-fill-tertiary-accent-mix',
  'theme.dark.strokePrimaryAccentMix': '--theme-dark-stroke-primary-accent-mix',
  'theme.dark.strokeSecondaryAccentMix': '--theme-dark-stroke-secondary-accent-mix',
  'theme.dark.strokeTertiaryAccentMix': '--theme-dark-stroke-tertiary-accent-mix',
  'theme.dark.background': '--theme-dark-background',
  'theme.dark.surface': '--theme-dark-surface',
  'theme.dark.surfaceRaised': '--theme-dark-surface-raised',
  'theme.dark.textPrimary': '--theme-dark-text-primary',
  'theme.dark.textSecondary': '--theme-dark-text-secondary',
  'theme.dark.border': '--theme-dark-border',
  'theme.dark.borderSubtle': '--theme-dark-border-subtle',
  'theme.dark.accent': '--theme-dark-accent',
  'theme.dark.accentPressed': '--theme-dark-accent-pressed',
  'theme.dark.accentSurface': '--theme-dark-accent-surface',
  'theme.dark.accentBorder': '--theme-dark-accent-border',
  'theme.dark.secondaryAccent': '--theme-dark-secondary-accent',
  'theme.dark.secondarySurface': '--theme-dark-secondary-surface',
  'document.light.selectionAlpha': '--document-light-selection-alpha',
  'document.light.backdrop': '--document-light-backdrop',
  'document.light.page': '--document-light-page',
  'document.light.pageBorder': '--document-light-page-border',
  'document.light.pageShadow': '--document-light-page-shadow',
  'document.light.selectionFill': '--document-light-selection-fill',
  'document.light.selectionHandle': '--document-light-selection-handle',
  'document.light.alignmentGuide': '--document-light-alignment-guide',
  'document.light.gridLine': '--document-light-grid-line',
  'document.light.commentAnchor': '--document-light-comment-anchor',
  'document.light.trackedChangeInsert': '--document-light-tracked-change-insert',
  'document.light.trackedChangeDelete': '--document-light-tracked-change-delete',
  'document.dark.selectionAlpha': '--document-dark-selection-alpha',
  'document.dark.backdrop': '--document-dark-backdrop',
  'document.dark.page': '--document-dark-page',
  'document.dark.pageBorder': '--document-dark-page-border',
  'document.dark.pageShadow': '--document-dark-page-shadow',
  'document.dark.selectionFill': '--document-dark-selection-fill',
  'document.dark.selectionHandle': '--document-dark-selection-handle',
  'document.dark.alignmentGuide': '--document-dark-alignment-guide',
  'document.dark.gridLine': '--document-dark-grid-line',
  'document.dark.commentAnchor': '--document-dark-comment-anchor',
  'document.dark.trackedChangeInsert': '--document-dark-tracked-change-insert',
  'document.dark.trackedChangeDelete': '--document-dark-tracked-change-delete',
};
