/**
 * @generated by `cargo run -p xtask -- tokens` from docs/client-platform/data/tokens.json.
 * DO NOT EDIT. Edit the source and regenerate.
 *
 * The design-token source for the mjx-ooxml-rs client platform (MJXOFF-156). The `color`, `font`,
 * `font-weight`, `text`, `leading`, `tracking`, `radius`, `spacing`, `shadow`, `ease` and
 * `duration` groups are the allr.work values as measured in docs/client-platform/DESIGN_TOKENS.md
 * §1 — read from the site's own stylesheet, never approximated. The `theme` and `document` groups
 * are this project's three additions (§2.1, §2.2, §2.3): a derived dark palette, a
 * document-surface palette that keeps the page true white in both schemes, and the contrast
 * metadata that turns §2.2's rule into a build failure. This file is the ONLY hand-edited artefact
 * in the pipeline; ui/tokens/tokens.css, ui/tokens/tokens.ts and
 * crates/mjx-tokens/src/generated.rs are emitted from it by `cargo run -p xtask -- tokens`.
 * FORMAT: W3C Design Tokens Community Group format, in its string profile — `color` is `#rrggbb`
 * or `#rrggbbaa`, `dimension` is a CSS length such as `8px`, `duration` is `150ms`. The later
 * drafts' object forms carry no information this pipeline uses and would make the one hand-edited
 * file in the pipeline three times longer. EXTENSIONS live under the `mjx` key: `rustType` names
 * the struct a group becomes in Rust; `schemes` marks a group whose children are colour schemes;
 * `usage` and `background` are the contrast metadata, required on every colour token.
 */

/**
 * The allr.work palette, verbatim. Warm and organic: the neutrals are beige rather than grey
 * and the `black` is a green. These are the names the site itself declares, so dropping the
 * platform into a host that already defines them re-themes it with no code change.
 */
export interface Palette {
  /**
   * page background — warm off-white.
   *
   * CSS: `--color-paper` · type `color` · usage `fill-only`
   */
  readonly paper: string;
  /**
   * raised surfaces.
   *
   * CSS: `--color-card` · type `color` · usage `fill-only`
   */
  readonly card: string;
  /**
   * true white; the site declares it beside `card` and this file keeps both names.
   *
   * CSS: `--color-white` · type `color` · usage `fill-only`
   */
  readonly white: string;
  /**
   * primary text — a deep, desaturated green-black.
   *
   * CSS: `--color-ink` · type `color` · usage `on-light-text` · 11.75 : 1 on `color.paper`
   */
  readonly ink: string;
  /**
   * secondary text.
   *
   * CSS: `--color-ink-soft` · type `color` · usage `on-light-text` · 5.10 : 1 on `color.paper`
   */
  readonly inkSoft: string;
  /**
   * borders — warm beige, not grey.
   *
   * CSS: `--color-line` · type `color` · usage `fill-only`
   */
  readonly line: string;
  /**
   * subtle dividers.
   *
   * CSS: `--color-line-soft` · type `color` · usage `fill-only`
   */
  readonly lineSoft: string;
  /**
   * primary accent. DESIGN_TOKENS.md §2.2: 3.39 : 1 on white — legal for UI components and
   * large text, ILLEGAL for body text. Fills, borders, indicators and icons only; `green-deep`
   * is the accent-coloured text colour.
   *
   * CSS: `--color-green` · type `color` · usage `fill-only` · 3.39 : 1 on `color.white`
   */
  readonly green: string;
  /**
   * accent, pressed / on-light text. DESIGN_TOKENS.md §2.2: 5.34 : 1 on white — legal for body
   * text.
   *
   * CSS: `--color-green-deep` · type `color` · usage `on-light-text` · 5.34 : 1 on
   * `color.white`
   */
  readonly greenDeep: string;
  /**
   * accent border.
   *
   * CSS: `--color-green-line` · type `color` · usage `fill-only`
   */
  readonly greenLine: string;
  /**
   * accent surface.
   *
   * CSS: `--color-green-tint` · type `color` · usage `fill-only`
   */
  readonly greenTint: string;
  /**
   * secondary accent.
   *
   * CSS: `--color-honey` · type `color` · usage `fill-only` · 2.07 : 1 on `color.white`
   */
  readonly honey: string;
  /**
   * secondary accent, deep. Measured at 3.49 : 1 on white by this generator, so — unlike
   * `green-deep`, its counterpart in the green ramp — it is NOT legal for body text and is
   * tagged `fill-only`. DESIGN_TOKENS.md §2.2 measured only the greens; this is the honey
   * ramp's answer to the same question.
   *
   * CSS: `--color-honey-deep` · type `color` · usage `fill-only` · 3.49 : 1 on `color.white`
   */
  readonly honeyDeep: string;
  /**
   * secondary border.
   *
   * CSS: `--color-honey-line` · type `color` · usage `fill-only`
   */
  readonly honeyLine: string;
  /**
   * secondary surface.
   *
   * CSS: `--color-honey-tint` · type `color` · usage `fill-only`
   */
  readonly honeyTint: string;
  /**
   * tertiary border.
   *
   * CSS: `--color-sage-line` · type `color` · usage `fill-only`
   */
  readonly sageLine: string;
  /**
   * tertiary surface.
   *
   * CSS: `--color-sage-tint` · type `color` · usage `fill-only`
   */
  readonly sageTint: string;
  /**
   * warm neutral surface.
   *
   * CSS: `--color-clay-tint` · type `color` · usage `fill-only`
   */
  readonly clayTint: string;
}

/**
 * The site's three families. Young Serif is display-only — empty states and onboarding, never
 * the chrome and never document content.
 */
export interface FontFamilies {
  /**
   * the chrome face; a rounded humanist that reads slightly wider than a typical UI font.
   *
   * CSS: `--font-sans` · type `fontFamily`
   */
  readonly sans: string;
  /**
   * display only.
   *
   * CSS: `--font-serif` · type `fontFamily`
   */
  readonly serif: string;
  /**
   * DESIGN_TOKENS.md §1 elides this stack after `Liberation Mono`; the elision is the standard
   * Tailwind v4 monospace stack, written out here in full.
   *
   * CSS: `--font-mono` · type `fontFamily`
   */
  readonly mono: string;
}

/**
 * The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
 * custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the layer
 * the site's theme is written in.
 */
export interface FontWeights {
  /**
   * CSS: `--font-weight-medium` · type `fontWeight`
   */
  readonly medium: number;
  /**
   * CSS: `--font-weight-semibold` · type `fontWeight`
   */
  readonly semibold: number;
  /**
   * CSS: `--font-weight-bold` · type `fontWeight`
   */
  readonly bold: number;
  /**
   * CSS: `--font-weight-extrabold` · type `fontWeight`
   */
  readonly extrabold: number;
}

/**
 * The two small type sizes the site declares. Dense editor surfaces — the formula bar, the cell
 * grid, a properties inspector — use `xs` with `leading.tight`, not the site's relaxed body
 * measure.
 */
export interface TextSizes {
  /**
   * CSS: `--text-xs` · type `dimension`
   */
  readonly xs: string;
  /**
   * CSS: `--text-sm` · type `dimension`
   */
  readonly sm: string;
}

/**
 * Line heights, unitless.
 */
export interface LineHeights {
  /**
   * CSS: `--leading-tight` · type `number`
   */
  readonly tight: number;
  /**
   * CSS: `--leading-snug` · type `number`
   */
  readonly snug: number;
  /**
   * CSS: `--leading-relaxed` · type `number`
   */
  readonly relaxed: number;
  /**
   * DESIGN_TOKENS.md §1 records this as `body line-height` with no custom-property name of its
   * own; it joins the `leading` family here.
   *
   * CSS: `--leading-body` · type `number`
   */
  readonly body: number;
}

/**
 * Letter spacing.
 */
export interface LetterSpacings {
  /**
   * CSS: `--tracking-tight` · type `dimension`
   */
  readonly tight: string;
}

/**
 * The radii are large, and that is the most recognisable part of the source's character.
 * Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners Office
 * uses.
 */
export interface Radii {
  /**
   * CSS: `--radius-chip` · type `dimension`
   */
  readonly chip: string;
  /**
   * CSS: `--radius-control` · type `dimension`
   */
  readonly control: string;
  /**
   * CSS: `--radius-card` · type `dimension`
   */
  readonly card: string;
  /**
   * CSS: `--radius-panel` · type `dimension`
   */
  readonly panel: string;
  /**
   * CSS: `--radius-frame` · type `dimension`
   */
  readonly frame: string;
  /**
   * CSS: `--radius-phone` · type `dimension`
   */
  readonly phone: string;
}

/**
 * Shadows are ink-tinted, never neutral black.
 */
export interface Shadows {
  /**
   * the site's one elevation, tinted with `color.ink` at 11% alpha.
   *
   * CSS: `--shadow-lift` · type `shadow`
   */
  readonly lift: string;
}

/**
 * `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to a
 * document object, where overshoot reads as imprecision. Selection, handles and canvas motion
 * use `ink`.
 */
export interface Easings {
  /**
   * CSS: `--ease-ink` · type `cubicBezier`
   */
  readonly ink: string;
  /**
   * CSS: `--ease-out-soft` · type `cubicBezier`
   */
  readonly outSoft: string;
  /**
   * CSS: `--ease-spring` · type `cubicBezier`
   */
  readonly spring: string;
}

/**
 * DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no custom-property
 * name of its own; it is named `--duration-transition` here for what it is.
 */
export interface Durations {
  /**
   * CSS: `--duration-transition` · type `duration`
   */
  readonly transition: string;
}

/**
 * The semantic application palette, in both colour schemes. DESIGN_TOKENS.md §2.1: the source
 * stylesheet has no `prefers-color-scheme` block, no `.dark` class and no `[data-theme]`
 * selector, so the dark scheme is DERIVED — the source's hue relationships held and lightness
 * inverted, so the dark theme reads as the same brand rather than a different product. The two
 * schemes must carry exactly the same member names; the generator fails if they drift, because
 * a semantic role that exists in one scheme and not the other is a component that cannot be
 * themed.
 */
export interface Themes {
  readonly light: ThemeColors;
  readonly dark: ThemeColors;
}

export interface ThemeColors {
  /**
   * the application background.
   *
   * CSS: `--theme-light-background` · type `color` · usage `fill-only`
   */
  readonly background: string;
  /**
   * CSS: `--theme-light-surface` · type `color` · usage `fill-only`
   */
  readonly surface: string;
  /**
   * CSS: `--theme-light-surface-raised` · type `color` · usage `fill-only`
   */
  readonly surfaceRaised: string;
  /**
   * CSS: `--theme-light-text-primary` · type `color` · usage `on-light-text` · 11.75 : 1 on
   * `theme.light.background`
   */
  readonly textPrimary: string;
  /**
   * CSS: `--theme-light-text-secondary` · type `color` · usage `on-light-text` · 5.10 : 1 on
   * `theme.light.background`
   */
  readonly textSecondary: string;
  /**
   * CSS: `--theme-light-border` · type `color` · usage `fill-only`
   */
  readonly border: string;
  /**
   * CSS: `--theme-light-border-subtle` · type `color` · usage `fill-only`
   */
  readonly borderSubtle: string;
  /**
   * fills, borders, indicators and icons. NOT text — see `accent-pressed`.
   *
   * CSS: `--theme-light-accent` · type `color` · usage `fill-only` · 3.39 : 1 on
   * `theme.light.surface`
   */
  readonly accent: string;
  /**
   * the pressed accent, and the only accent-coloured text colour on a light surface.
   *
   * CSS: `--theme-light-accent-pressed` · type `color` · usage `on-light-text` · 5.34 : 1 on
   * `theme.light.surface`
   */
  readonly accentPressed: string;
  /**
   * CSS: `--theme-light-accent-surface` · type `color` · usage `fill-only`
   */
  readonly accentSurface: string;
  /**
   * CSS: `--theme-light-accent-border` · type `color` · usage `fill-only`
   */
  readonly accentBorder: string;
  /**
   * CSS: `--theme-light-secondary-accent` · type `color` · usage `fill-only` · 2.07 : 1 on
   * `theme.light.surface`
   */
  readonly secondaryAccent: string;
  /**
   * CSS: `--theme-light-secondary-surface` · type `color` · usage `fill-only`
   */
  readonly secondarySurface: string;
}

/**
 * The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
 * conflating them is the classic mistake. The page stays true white in both schemes — a
 * document is white paper, and a warm-tinted or dark page changes what the author sees relative
 * to what they will print or send. What changes with the scheme is the canvas backdrop behind
 * the page, the page shadow, and the in-canvas UI. A reading-mode inversion of the page itself
 * is a user setting, not a theme consequence. These are the tokens the Rust canvas needs and a
 * CSS custom property cannot reach it, which is the reason this pipeline emits three artefacts
 * instead of one.
 */
export interface DocumentSurfaces {
  readonly light: DocumentColors;
  readonly dark: DocumentColors;
}

export interface DocumentColors {
  /**
   * `color.paper` behind a true-white page makes the page read as a distinct, lit object rather
   * than dissolving into the background.
   *
   * CSS: `--document-light-backdrop` · type `color` · usage `fill-only`
   */
  readonly backdrop: string;
  /**
   * CSS: `--document-light-page` · type `color` · usage `fill-only`
   */
  readonly page: string;
  /**
   * CSS: `--document-light-page-border` · type `color` · usage `fill-only`
   */
  readonly pageBorder: string;
  /**
   * CSS: `--document-light-page-shadow` · type `shadow`
   */
  readonly pageShadow: string;
  /**
   * `color.green` at 18% alpha (0.18 × 255 = 46 = 0x2e).
   *
   * CSS: `--document-light-selection-fill` · type `color` · usage `fill-only`
   */
  readonly selectionFill: string;
  /**
   * CSS: `--document-light-selection-handle` · type `color` · usage `fill-only`
   */
  readonly selectionHandle: string;
  /**
   * CSS: `--document-light-alignment-guide` · type `color` · usage `fill-only`
   */
  readonly alignmentGuide: string;
  /**
   * grid and ruler lines.
   *
   * CSS: `--document-light-grid-line` · type `color` · usage `fill-only`
   */
  readonly gridLine: string;
  /**
   * CSS: `--document-light-comment-anchor` · type `color` · usage `fill-only`
   */
  readonly commentAnchor: string;
  /**
   * tagged `fill-only`: measured against the page it does not reach 4.5 : 1, so it is legal for
   * the change bar, the underline rule and the marker, and a tracked insertion's own glyphs
   * must stay `theme.*.text-primary`.
   *
   * CSS: `--document-light-tracked-change-insert` · type `color` · usage `fill-only` · 3.39 : 1
   * on `document.light.page`
   */
  readonly trackedChangeInsert: string;
  /**
   * tagged `fill-only` for the same reason as `tracked-change-insert`.
   *
   * CSS: `--document-light-tracked-change-delete` · type `color` · usage `fill-only` · 3.49 : 1
   * on `document.light.page`
   */
  readonly trackedChangeDelete: string;
}

/** The whole token set. */
export interface Tokens {
  /**
   * The allr.work palette, verbatim. Warm and organic: the neutrals are beige rather than grey
   * and the `black` is a green. These are the names the site itself declares, so dropping the
   * platform into a host that already defines them re-themes it with no code change.
   */
  readonly color: Palette;
  /**
   * The site's three families. Young Serif is display-only — empty states and onboarding, never
   * the chrome and never document content.
   */
  readonly font: FontFamilies;
  /**
   * The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
   * custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the layer
   * the site's theme is written in.
   */
  readonly fontWeight: FontWeights;
  /**
   * The two small type sizes the site declares. Dense editor surfaces — the formula bar, the
   * cell grid, a properties inspector — use `xs` with `leading.tight`, not the site's relaxed
   * body measure.
   */
  readonly text: TextSizes;
  /**
   * Line heights, unitless.
   */
  readonly leading: LineHeights;
  /**
   * Letter spacing.
   */
  readonly tracking: LetterSpacings;
  /**
   * The radii are large, and that is the most recognisable part of the source's character.
   * Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners
   * Office uses.
   */
  readonly radius: Radii;
  /**
   * The base spacing step, from which the site's spacing scale is multiplied. It is a token in
   * its own right rather than a group so that its custom property is `--spacing`, exactly as
   * the site declares it.
   *
   * CSS: `--spacing` · type `dimension`
   */
  readonly spacing: string;
  /**
   * Shadows are ink-tinted, never neutral black.
   */
  readonly shadow: Shadows;
  /**
   * `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to a
   * document object, where overshoot reads as imprecision. Selection, handles and canvas motion
   * use `ink`.
   */
  readonly ease: Easings;
  /**
   * DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no custom-property
   * name of its own; it is named `--duration-transition` here for what it is.
   */
  readonly duration: Durations;
  /**
   * The semantic application palette, in both colour schemes. DESIGN_TOKENS.md §2.1: the source
   * stylesheet has no `prefers-color-scheme` block, no `.dark` class and no `[data-theme]`
   * selector, so the dark scheme is DERIVED — the source's hue relationships held and lightness
   * inverted, so the dark theme reads as the same brand rather than a different product. The
   * two schemes must carry exactly the same member names; the generator fails if they drift,
   * because a semantic role that exists in one scheme and not the other is a component that
   * cannot be themed.
   */
  readonly theme: Themes;
  /**
   * The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
   * conflating them is the classic mistake. The page stays true white in both schemes — a
   * document is white paper, and a warm-tinted or dark page changes what the author sees
   * relative to what they will print or send. What changes with the scheme is the canvas
   * backdrop behind the page, the page shadow, and the in-canvas UI. A reading-mode inversion
   * of the page itself is a user setting, not a theme consequence. These are the tokens the
   * Rust canvas needs and a CSS custom property cannot reach it, which is the reason this
   * pipeline emits three artefacts instead of one.
   */
  readonly document: DocumentSurfaces;
}

/** The colour schemes every scheme group in the source declares. */
export type ColorScheme = 'light' | 'dark';

/** The generated defaults — the values this platform ships with. */
export const tokens: Tokens = {
  color: {
    paper: '#fdfcf9',
    card: '#ffffff',
    white: '#ffffff',
    ink: '#223b33',
    inkSoft: '#5c7168',
    line: '#e7e0d2',
    lineSoft: '#efe9dc',
    green: '#2e9e63',
    greenDeep: '#1e7a49',
    greenLine: '#c2e5d0',
    greenTint: '#e4f4ea',
    honey: '#e9a83e',
    honeyDeep: '#b77e1f',
    honeyLine: '#f0dcb4',
    honeyTint: '#fbefd8',
    sageLine: '#dce8dd',
    sageTint: '#ecf2ec',
    clayTint: '#f6ede2',
  },
  font: {
    sans: '"Nunito Sans", system-ui, sans-serif',
    serif: '"Young Serif", serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  fontWeight: {
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
  },
  text: {
    xs: '0.75rem',
    sm: '0.875rem',
  },
  leading: {
    tight: 1.25,
    snug: 1.375,
    relaxed: 1.625,
    body: 1.7,
  },
  tracking: {
    tight: '-0.025em',
  },
  radius: {
    chip: '8px',
    control: '10px',
    card: '16px',
    panel: '20px',
    frame: '22px',
    phone: '36px',
  },
  spacing: '0.25rem',
  shadow: {
    lift: '0px 18px 48px #223b331c',
  },
  ease: {
    ink: 'cubic-bezier(0.45, 0, 0.2, 1)',
    outSoft: 'cubic-bezier(0.22, 1, 0.36, 1)',
    spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
  duration: {
    transition: '150ms',
  },
  theme: {
    light: {
      background: '#fdfcf9',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      textPrimary: '#223b33',
      textSecondary: '#5c7168',
      border: '#e7e0d2',
      borderSubtle: '#efe9dc',
      accent: '#2e9e63',
      accentPressed: '#1e7a49',
      accentSurface: '#e4f4ea',
      accentBorder: '#c2e5d0',
      secondaryAccent: '#e9a83e',
      secondarySurface: '#fbefd8',
    },
    dark: {
      background: '#131a17',
      surface: '#1b2420',
      surfaceRaised: '#23302a',
      textPrimary: '#e8efe9',
      textSecondary: '#9aaba2',
      border: '#2e3b35',
      borderSubtle: '#26312c',
      accent: '#4fc98a',
      accentPressed: '#2e9e63',
      accentSurface: '#163023',
      accentBorder: '#224934',
      secondaryAccent: '#f0be62',
      secondarySurface: '#33260f',
    },
  },
  document: {
    light: {
      backdrop: '#fdfcf9',
      page: '#ffffff',
      pageBorder: '#e7e0d2',
      pageShadow: '0px 2px 10px #223b3314',
      selectionFill: '#2e9e632e',
      selectionHandle: '#1e7a49',
      alignmentGuide: '#e9a83e',
      gridLine: '#efe9dc',
      commentAnchor: '#e9a83e',
      trackedChangeInsert: '#2e9e63',
      trackedChangeDelete: '#b77e1f',
    },
    dark: {
      backdrop: '#131a17',
      page: '#ffffff',
      pageBorder: '#2e3b35',
      pageShadow: '0px 2px 14px #00000059',
      selectionFill: '#4fc98a38',
      selectionHandle: '#4fc98a',
      alignmentGuide: '#f0be62',
      gridLine: '#26312c',
      commentAnchor: '#f0be62',
      trackedChangeInsert: '#4fc98a',
      trackedChangeDelete: '#f0be62',
    },
  },
};

/**
 * Every token's CSS custom property, keyed by its path in `tokens`. A runtime resolver reads these
 * names off the host element; a host that already defines one is re-theming the platform, which is
 * exactly what it is meant to be able to do.
 */
export const customProperties: Readonly<Record<string, string>> = {
  'color.paper': '--color-paper',
  'color.card': '--color-card',
  'color.white': '--color-white',
  'color.ink': '--color-ink',
  'color.inkSoft': '--color-ink-soft',
  'color.line': '--color-line',
  'color.lineSoft': '--color-line-soft',
  'color.green': '--color-green',
  'color.greenDeep': '--color-green-deep',
  'color.greenLine': '--color-green-line',
  'color.greenTint': '--color-green-tint',
  'color.honey': '--color-honey',
  'color.honeyDeep': '--color-honey-deep',
  'color.honeyLine': '--color-honey-line',
  'color.honeyTint': '--color-honey-tint',
  'color.sageLine': '--color-sage-line',
  'color.sageTint': '--color-sage-tint',
  'color.clayTint': '--color-clay-tint',
  'font.sans': '--font-sans',
  'font.serif': '--font-serif',
  'font.mono': '--font-mono',
  'fontWeight.medium': '--font-weight-medium',
  'fontWeight.semibold': '--font-weight-semibold',
  'fontWeight.bold': '--font-weight-bold',
  'fontWeight.extrabold': '--font-weight-extrabold',
  'text.xs': '--text-xs',
  'text.sm': '--text-sm',
  'leading.tight': '--leading-tight',
  'leading.snug': '--leading-snug',
  'leading.relaxed': '--leading-relaxed',
  'leading.body': '--leading-body',
  'tracking.tight': '--tracking-tight',
  'radius.chip': '--radius-chip',
  'radius.control': '--radius-control',
  'radius.card': '--radius-card',
  'radius.panel': '--radius-panel',
  'radius.frame': '--radius-frame',
  'radius.phone': '--radius-phone',
  'spacing': '--spacing',
  'shadow.lift': '--shadow-lift',
  'ease.ink': '--ease-ink',
  'ease.outSoft': '--ease-out-soft',
  'ease.spring': '--ease-spring',
  'duration.transition': '--duration-transition',
  'theme.light.background': '--theme-light-background',
  'theme.light.surface': '--theme-light-surface',
  'theme.light.surfaceRaised': '--theme-light-surface-raised',
  'theme.light.textPrimary': '--theme-light-text-primary',
  'theme.light.textSecondary': '--theme-light-text-secondary',
  'theme.light.border': '--theme-light-border',
  'theme.light.borderSubtle': '--theme-light-border-subtle',
  'theme.light.accent': '--theme-light-accent',
  'theme.light.accentPressed': '--theme-light-accent-pressed',
  'theme.light.accentSurface': '--theme-light-accent-surface',
  'theme.light.accentBorder': '--theme-light-accent-border',
  'theme.light.secondaryAccent': '--theme-light-secondary-accent',
  'theme.light.secondarySurface': '--theme-light-secondary-surface',
  'theme.dark.background': '--theme-dark-background',
  'theme.dark.surface': '--theme-dark-surface',
  'theme.dark.surfaceRaised': '--theme-dark-surface-raised',
  'theme.dark.textPrimary': '--theme-dark-text-primary',
  'theme.dark.textSecondary': '--theme-dark-text-secondary',
  'theme.dark.border': '--theme-dark-border',
  'theme.dark.borderSubtle': '--theme-dark-border-subtle',
  'theme.dark.accent': '--theme-dark-accent',
  'theme.dark.accentPressed': '--theme-dark-accent-pressed',
  'theme.dark.accentSurface': '--theme-dark-accent-surface',
  'theme.dark.accentBorder': '--theme-dark-accent-border',
  'theme.dark.secondaryAccent': '--theme-dark-secondary-accent',
  'theme.dark.secondarySurface': '--theme-dark-secondary-surface',
  'document.light.backdrop': '--document-light-backdrop',
  'document.light.page': '--document-light-page',
  'document.light.pageBorder': '--document-light-page-border',
  'document.light.pageShadow': '--document-light-page-shadow',
  'document.light.selectionFill': '--document-light-selection-fill',
  'document.light.selectionHandle': '--document-light-selection-handle',
  'document.light.alignmentGuide': '--document-light-alignment-guide',
  'document.light.gridLine': '--document-light-grid-line',
  'document.light.commentAnchor': '--document-light-comment-anchor',
  'document.light.trackedChangeInsert': '--document-light-tracked-change-insert',
  'document.light.trackedChangeDelete': '--document-light-tracked-change-delete',
  'document.dark.backdrop': '--document-dark-backdrop',
  'document.dark.page': '--document-dark-page',
  'document.dark.pageBorder': '--document-dark-page-border',
  'document.dark.pageShadow': '--document-dark-page-shadow',
  'document.dark.selectionFill': '--document-dark-selection-fill',
  'document.dark.selectionHandle': '--document-dark-selection-handle',
  'document.dark.alignmentGuide': '--document-dark-alignment-guide',
  'document.dark.gridLine': '--document-dark-grid-line',
  'document.dark.commentAnchor': '--document-dark-comment-anchor',
  'document.dark.trackedChangeInsert': '--document-dark-tracked-change-insert',
  'document.dark.trackedChangeDelete': '--document-dark-tracked-change-delete',
};
