#!/usr/bin/env node
/**
 * The icon subsetter — the only thing that may read `@fluentui/svg-icons`.
 *
 * MJXOFF-181: *"subset at build time to the icons actually referenced (19,757 icons must never
 * reach a bundle)"*. The vendor package ships 20,679 SVG files and 12.7 MB. This reads
 * `src/icons/manifest.ts`, pulls exactly the files it asks for, and writes
 * `src/icons/generated.ts`.
 *
 * ## Committed output, not a build step
 *
 * The same doctrine as `mjx-ooxml-types` and the design tokens: **the output is committed and
 * regenerated by an explicit command, never by a `build.rs` or a bundler plugin.** Three reasons,
 * and the third is the one that decided it:
 *
 * 1. A reviewer can see exactly what the bundle will contain, in a diff.
 * 2. `npm ci && npm run check` needs no generator step, so a contributor who never runs this still
 *    builds the same catalogue.
 * 3. **The subset must be reviewable as a subset.** A plugin that inlined icons on demand would
 *    make "which icons ship" a property of whatever the bundler happened to resolve that day,
 *    which is precisely the thing the ticket wants asserted.
 *
 * ## `--check`
 *
 * Regenerates in memory and compares. This is what `npm run icons:check` runs, and it is what
 * catches a hand-edit to `generated.ts` — including a hand-added icon that no manifest row asks
 * for, which is how a subset stops being one.
 *
 * ## Why it refuses anything but paths
 *
 * Every icon it accepts must be `<svg …><path d="…"/>…</svg>` and nothing else. The vendor's
 * `_color` variants carry `fill` attributes and multiple element types, and an icon that cannot be
 * tinted from a token is not an icon this design system can use. So the generator *fails* on one
 * rather than passing markup through: the runtime then builds `<path>` elements with the DOM API
 * and never calls `innerHTML`, which removes the injection question entirely rather than answering
 * it with a sanitiser.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const uiRoot = resolve(import.meta.dirname, '..');
const vendorRoot = resolve(uiRoot, 'node_modules/@fluentui/svg-icons/icons');
const outputPath = resolve(uiRoot, 'src/icons/generated.ts');

const manifest = await import(pathToFileURL(resolve(uiRoot, 'src/icons/manifest.ts')).href);
const { iconRequests, iconId, fluentFileName, iconIdPrefix } = manifest;

/** `<svg … viewBox="0 0 20 20"><path d="…"/></svg>`, and refuses anything richer. */
function readGlyph(name, size, variant) {
  const file = fluentFileName(name, size, variant);
  let source;
  try {
    source = readFileSync(resolve(vendorRoot, file), 'utf8').trim();
  } catch {
    throw new Error(
      `the manifest asks for '${name}' at ${size} ${variant}, and @fluentui/svg-icons has no ` +
        `${file}. Fluent does not draw every icon at every size — check the package before ` +
        'changing the manifest.',
    );
  }

  const viewBox = /viewBox="([^"]+)"/.exec(source)?.[1];
  if (viewBox === undefined) throw new Error(`${file} has no viewBox.`);
  if (viewBox !== `0 0 ${String(size)} ${String(size)}`) {
    throw new Error(
      `${file} declares viewBox '${viewBox}', which is not the ${size}×${size} box its name ` +
        'claims. The size attribute and the drawing must agree or every icon in the catalogue is ' +
        'the wrong size by an amount nothing measures.',
    );
  }

  const body = source.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
  const paths = [];
  const pathPattern = /<path d="([^"]+)"\s*\/>/g;
  let consumed = 0;
  for (let match = pathPattern.exec(body); match !== null; match = pathPattern.exec(body)) {
    paths.push(match[1]);
    consumed += match[0].length;
  }
  if (paths.length === 0 || consumed !== body.length) {
    throw new Error(
      `${file} is not a plain sequence of <path d="…"/> elements. This generator accepts only ` +
        'those, so that the runtime can build them with the DOM API and never call innerHTML, ' +
        "and so that every icon is tintable from a token. Fluent's `_color` variants are not " +
        'usable here.',
    );
  }
  return { viewBox, paths };
}

/** The generated module, as a string. */
function render() {
  /** @type {{ id: string, viewBox: string, paths: string[] }[]} */
  const glyphs = [];
  for (const request of iconRequests) {
    for (const size of request.sizes) {
      for (const variant of request.variants) {
        const { viewBox, paths } = readGlyph(request.name, size, variant);
        glyphs.push({ id: iconId(request.name, size, variant), viewBox, paths });
      }
    }
  }

  const duplicated = glyphs.map((glyph) => glyph.id).filter((id, index, all) => all.indexOf(id) !== index);
  if (duplicated.length > 0) {
    throw new Error(`the manifest asks for ${duplicated[0]} more than once.`);
  }

  const pathBytes = glyphs.reduce(
    (total, glyph) => total + glyph.paths.reduce((sum, path) => sum + path.length, 0),
    0,
  );

  const lines = [];
  lines.push('/**');
  lines.push(' * @generated by `npm run icons:subset` from src/icons/manifest.ts and');
  lines.push(' * @fluentui/svg-icons. DO NOT EDIT — edit the manifest and regenerate.');
  lines.push(' *');
  lines.push(' * Fluent UI System Icons are MIT licensed, © Microsoft Corporation. The licence is');
  lines.push(' * reproduced in ui/src/icons/LICENSE-fluent.txt.');
  lines.push(' *');
  lines.push(` * ${String(glyphs.length)} glyphs, ${String(pathBytes)} bytes of path data, subset from the`);
  lines.push(' * 20,679 files the package ships. `npm run icons:check` re-derives this file and fails on');
  lines.push(' * any difference; tests/browser/icons.spec.ts asserts that the built bundle contains');
  lines.push(' * exactly these ids and no others.');
  lines.push(' */');
  lines.push('');
  lines.push('/** One drawing: the box it was drawn in, and its paths in order. */');
  lines.push('export interface IconGlyph {');
  lines.push('  readonly viewBox: string;');
  lines.push('  readonly paths: readonly string[];');
  lines.push('}');
  lines.push('');
  lines.push('/** Every glyph in the subset, by its id. */');
  lines.push('export const iconGlyphs: Readonly<Record<string, IconGlyph>> = {');
  for (const glyph of glyphs) {
    lines.push(`  '${glyph.id}': {`);
    lines.push(`    viewBox: '${glyph.viewBox}',`);
    lines.push(`    paths: [${glyph.paths.map((path) => `'${path.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`).join(', ')}],`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('/** How many glyphs the subset carries. The bundle gate compares against this. */');
  lines.push(`export const subsetGlyphCount = ${String(glyphs.length)};`);
  lines.push('');
  lines.push('/**');
  lines.push(' * Total bytes of SVG path data in the subset.');
  lines.push(' *');
  lines.push(' * This is the number the bundle budget is derived from, and the reason it is emitted');
  lines.push(' * rather than computed at runtime is that a budget computed from the same data it is');
  lines.push(' * measuring can never be exceeded — the identity-value trap in arithmetic form.');
  lines.push(' */');
  lines.push(`export const subsetPathBytes = ${String(pathBytes)};`);
  lines.push('');
  lines.push('/** The sentinel every id above carries, restated so a Node-side gate need not guess. */');
  lines.push(`export const generatedIconIdPrefix = '${iconIdPrefix}';`);
  lines.push('');

  return lines.join('\n');
}

const rendered = render();
const checking = process.argv.includes('--check');

if (!checking) {
  writeFileSync(outputPath, rendered, 'utf8');
  console.log(`wrote ${outputPath}`);
  process.exit(0);
}

let committed;
try {
  committed = readFileSync(outputPath, 'utf8');
} catch {
  console.error('src/icons/generated.ts is missing. Run `npm run icons:subset`.');
  process.exit(1);
}

if (committed === rendered) {
  const count = (rendered.match(/^ {2}'mjx-fluent:/gm) ?? []).length;
  console.log(`icons:check — ${String(count)} glyphs, generated.ts agrees with the manifest.`);
  process.exit(0);
}

console.error(
  'src/icons/generated.ts does not match what the manifest and @fluentui/svg-icons produce.\n' +
    'Either it was hand-edited — which is how a subset stops being a subset — or the manifest\n' +
    'changed and nobody regenerated. Run `npm run icons:subset`.',
);
const committedLines = committed.split('\n');
const renderedLines = rendered.split('\n');
for (let index = 0; index < Math.max(committedLines.length, renderedLines.length); index += 1) {
  if (committedLines[index] !== renderedLines[index]) {
    console.error(`  first difference at line ${String(index + 1)}:`);
    console.error(`    committed: ${String(committedLines[index] ?? '(end of file)').slice(0, 160)}`);
    console.error(`    generated: ${String(renderedLines[index] ?? '(end of file)').slice(0, 160)}`);
    break;
  }
}
process.exit(1);
