//! Committed baselines, and **the approval event without which a baseline is not one**.
//!
//! # ⚠ The trap this module exists for
//!
//! MJXOFF-165 states it more sharply than anything else in the loop: **a golden image generated by
//! the code under test always matches the code under test.** Regenerate-and-compare is green by
//! construction and proves nothing whatever. Three things follow, and all three are enforced here
//! rather than described:
//!
//! 1. **A baseline with no approval record fails.** Not warns, not skips — [`ApprovalState::Missing`]
//!    is a failure, and `tests/an_unapproved_baseline_fails.rs` proves it by adding one.
//! 2. **Regeneration is explicit and cannot happen implicitly.** [`Baselines::regenerate`] takes a
//!    [`RegenerationIntent`], and the only way to obtain one is
//!    [`RegenerationIntent::from_environment`], which reads [`REGENERATE`] and refuses without it.
//!    A check path cannot construct one by accident, because it cannot construct one at all.
//! 3. **Regeneration deletes the approval.** Writing new artefacts and leaving the old approval in
//!    place is precisely how an auto-regenerating baseline ratifies the regression it exists to
//!    catch, so the approval is removed in the same call, before the artefacts are written.
//!
//! # What an approval binds to
//!
//! **The bytes, not the name.** An approval that recorded only *"solid-panels is approved"* would be
//! satisfied by any file that later appeared under that name. So it records a SHA-256 per artefact,
//! and a baseline whose artefacts no longer hash to those numbers is [`ApprovalState::Stale`] — a
//! failure that names the artefact, the number recorded and the number found. The digests are
//! ordinary SHA-256, so `sha256sum` reproduces them and the record is auditable by the person whose
//! approval it claims.
//!
//! # ⚠ The honest part: who has actually looked
//!
//! An agent cannot manufacture a human's approval, and pretending otherwise would be a worse defect
//! than having no approval machinery at all. So [`Approver`] has **two** values and the difference is
//! visible everywhere a baseline is:
//!
//! * [`Approver::Human`] — a person ran [`Baselines::approve`], named themselves, and said why. The
//!   only kind of approval that means anyone looked at the image.
//! * [`Approver::Generator`] — this crate stamped it when the baseline was created. It is **still an
//!   approval record**, so the digest binding above is live and a later regeneration is caught; and
//!   it is **never** a human review, so [`Approval::is_reviewed`] is `false`, and
//!   [`awaiting_human_review`] lists every one of them so the set cannot age into an unexamined one.
//!
//! Every baseline this crate ships is [`Approver::Generator`]. That is the true state of the project
//! and it is stated in the gallery, in the manifest, in the report and here. The way it stops being
//! true is a person looking at the gallery and running `approve`; nothing else changes it.
//!
//! This is the exact analogue of [`crate::authority`]'s provisional reference, one level in: there,
//! a reference nobody authoritative produced; here, an approval nobody human gave. Both are recorded
//! rather than assumed, both are listable, and neither may ever be reported as the stronger thing.

use std::path::{Path, PathBuf};

use crate::digest::sha256_hex;

/// The environment variable that permits [`Baselines::regenerate`] to run at all.
pub const REGENERATE: &str = "MJX_ORACLE_REGENERATE";

/// The environment variable naming the person approving, for [`Baselines::approve`].
pub const APPROVED_BY: &str = "MJX_ORACLE_APPROVED_BY";

/// The file an approval is written to, inside a baseline's own directory.
pub const APPROVAL_FILE: &str = "APPROVAL";

/// The three artefacts a baseline holds, in the order the tiers use them.
pub const ARTEFACTS: [&str; 3] = ["fragments.snapshot", "commands.snapshot", "render.png"];

/// Who approved a baseline.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Approver {
    /// A person, who named themselves.
    Human {
        /// How they named themselves — a name, an address, whatever they typed.
        name: String,
    },
    /// This crate, when the baseline was created. **Not a review.**
    Generator,
}

impl Approver {
    /// How it is written in the record, and read back out of it.
    #[must_use]
    pub fn wire(&self) -> &str {
        match self {
            Self::Human { .. } => "human",
            Self::Generator => "generator",
        }
    }

    /// How it is named to a reader.
    #[must_use]
    pub fn label(&self) -> String {
        match self {
            Self::Human { name } => name.clone(),
            Self::Generator => "the generator (no human has looked at this image)".to_owned(),
        }
    }
}

/// One recorded approval.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Approval {
    /// Which baseline.
    pub specimen: String,
    /// Who.
    pub approver: Approver,
    /// When, as seconds since the Unix epoch. A number rather than a formatted date because a
    /// record has to be comparable and a date string is not.
    pub approved_at: u64,
    /// Why, in the approver's own words.
    pub note: String,
    /// Each artefact and the SHA-256 it had when it was approved, in [`ARTEFACTS`] order.
    pub digests: Vec<(String, String)>,
}

impl Approval {
    /// Whether a **person** approved this.
    ///
    /// `false` for [`Approver::Generator`], which is what keeps a generated baseline out of any
    /// sentence that claims someone looked at it.
    #[must_use]
    pub fn is_reviewed(&self) -> bool {
        matches!(self.approver, Approver::Human { .. })
    }

    /// The approval date, as `YYYY-MM-DD` in UTC.
    #[must_use]
    pub fn date(&self) -> String {
        iso_date(self.approved_at)
    }

    /// The record's text.
    #[must_use]
    pub fn to_text(&self) -> String {
        let mut text = String::new();
        text.push_str(
            "# The approval event for this baseline. Written by `mjx-render-oracle approve`.\n\
             #\n\
             # A baseline with no such file FAILS rather than passes, and the digests below bind the\n\
             # approval to the bytes that were approved: regenerating an artefact without approving\n\
             # it again is caught here rather than passing silently.\n\
             #\n\
             # `approver = generator` means NOBODY HAS LOOKED AT THIS IMAGE. It is a real approval\n\
             # record — the digest binding is live — and it is not a human review. Run\n\
             #   MJX_ORACLE_APPROVED_BY='Your Name' \\\n\
             #     cargo run -p mjx-render-oracle -- approve <specimen> \"why\"\n\
             # after looking at the gallery, and this line becomes `human`.\n",
        );
        text.push_str(&format!("specimen = {}\n", self.specimen));
        text.push_str(&format!("approver = {}\n", self.approver.wire()));
        text.push_str(&format!("approved-by = {}\n", self.approver.label()));
        text.push_str(&format!("approved-at = {}\n", self.approved_at));
        text.push_str(&format!("approved-on = {}\n", self.date()));
        text.push_str(&format!("note = {}\n", self.note));
        for (artefact, digest) in &self.digests {
            text.push_str(&format!("sha256 {artefact} = {digest}\n"));
        }
        text
    }

    /// Read a record back.
    ///
    /// # Errors
    ///
    /// A sentence naming the key that was missing or unreadable. A malformed record is a failure and
    /// never an absence: an approval nobody can read is not an approval, and treating it as one
    /// missing would let a corrupted file be fixed by regenerating.
    pub fn parse(text: &str) -> Result<Self, String> {
        let mut specimen = None;
        let mut approver_kind = None;
        let mut approved_by = None;
        let mut approved_at = None;
        let mut note = None;
        let mut digests = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                return Err(format!("`{line}` is not a `key = value` line"));
            };
            let (key, value) = (key.trim(), value.trim());
            match key {
                "specimen" => specimen = Some(value.to_owned()),
                "approver" => approver_kind = Some(value.to_owned()),
                "approved-by" => approved_by = Some(value.to_owned()),
                "approved-at" => {
                    approved_at = Some(value.parse::<u64>().map_err(|_| {
                        format!("`approved-at` is `{value}`, which is not a Unix second")
                    })?);
                }
                // Derived from `approved-at` and written for a reader; never read back, so that two
                // fields cannot disagree about when.
                "approved-on" => {}
                "note" => note = Some(value.to_owned()),
                other => match other.strip_prefix("sha256 ") {
                    Some(artefact) => digests.push((artefact.trim().to_owned(), value.to_owned())),
                    None => return Err(format!("`{other}` is not a key this record has")),
                },
            }
        }
        let approver = match approver_kind.as_deref() {
            Some("human") => Approver::Human {
                name: approved_by.ok_or("`approved-by` is missing from a human approval")?,
            },
            Some("generator") => Approver::Generator,
            Some(other) => return Err(format!("`approver = {other}` is not human or generator")),
            None => return Err("`approver` is missing".to_owned()),
        };
        Ok(Self {
            specimen: specimen.ok_or("`specimen` is missing")?,
            approver,
            approved_at: approved_at.ok_or("`approved-at` is missing")?,
            note: note.ok_or("`note` is missing")?,
            digests,
        })
    }

    /// The digest recorded for `artefact`.
    #[must_use]
    pub fn digest_of(&self, artefact: &str) -> Option<&str> {
        self.digests
            .iter()
            .find(|(name, _)| name == artefact)
            .map(|(_, digest)| digest.as_str())
    }
}

/// What a baseline's approval is worth right now.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum ApprovalState {
    /// A record exists, every artefact is present, and every digest matches.
    Approved(Approval),
    /// There is no record. **A failure**, and the one MJXOFF-165 names explicitly.
    Missing,
    /// There is a record, but an artefact's bytes are not the ones it approved.
    Stale {
        /// Which artefact.
        artefact: String,
        /// What the record says its digest was.
        recorded: String,
        /// What it is now, or a sentence when the file is absent.
        actual: String,
    },
    /// There is a record and it cannot be read.
    Malformed {
        /// Why.
        reason: String,
    },
}

impl ApprovalState {
    /// Whether the baseline may be used at all.
    ///
    /// **Every state but [`Approved`](Self::Approved) is a failure.** A baseline that cannot say who
    /// approved it, or whose bytes have moved since, is not a baseline: comparing against it is the
    /// regenerate-and-compare tautology with extra steps.
    #[must_use]
    pub const fn is_usable(&self) -> bool {
        matches!(self, Self::Approved(_))
    }

    /// Whether a **person** approved it.
    #[must_use]
    pub fn is_reviewed(&self) -> bool {
        match self {
            Self::Approved(approval) => approval.is_reviewed(),
            _ => false,
        }
    }

    /// Why the baseline is unusable, or `None` when it is not.
    #[must_use]
    pub fn refusal(&self) -> Option<String> {
        match self {
            Self::Approved(_) => None,
            Self::Missing => Some(format!(
                "there is no `{APPROVAL_FILE}` beside this baseline, so nobody has approved it. A \
                 golden image generated by the code under test always matches the code under test; \
                 an unapproved one is that tautology and nothing else."
            )),
            Self::Stale {
                artefact,
                recorded,
                actual,
            } => Some(format!(
                "`{artefact}` is not what was approved: the record says {recorded} and the file is \
                 {actual}. Regenerating an artefact does not re-approve it — look at the gallery \
                 and run `approve` again."
            )),
            Self::Malformed { reason } => Some(format!(
                "the `{APPROVAL_FILE}` beside this baseline cannot be read: {reason}"
            )),
        }
    }
}

/// **The only way to reach [`Baselines::regenerate`].**
///
/// A value with a private field and one constructor, which reads [`REGENERATE`]. There is no
/// `Default`, no `new`, and no way to make one from inside a check path — which is the mechanical
/// form of *"a regenerate-baselines path must be explicit and never automatic"*. A type rather than
/// a boolean argument because a boolean argument is one `true` away from being passed by a caller
/// that did not think about it.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct RegenerationIntent {
    stated: (),
}

impl RegenerationIntent {
    /// The intent, if [`REGENERATE`] is set to `1`.
    ///
    /// # Errors
    ///
    /// A sentence saying what to set, when it is not.
    pub fn from_environment() -> Result<Self, String> {
        match std::env::var(REGENERATE).as_deref() {
            Ok("1") => Ok(Self { stated: () }),
            _ => Err(format!(
                "regenerating a baseline overwrites the image a person approved, so it never \
                 happens on its own. Set {REGENERATE}=1 to state that you mean it — and then \
                 look at the gallery and approve what you regenerated, because a regenerated \
                 baseline is unapproved until you do."
            )),
        }
    }
}

/// The committed baselines, in a directory.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Baselines {
    root: PathBuf,
}

impl Baselines {
    /// The baselines under `root`.
    #[must_use]
    pub fn at(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// The committed set, `crates/mjx-render-oracle/baselines/`.
    #[must_use]
    pub fn committed() -> Self {
        Self::at(Path::new(env!("CARGO_MANIFEST_DIR")).join("baselines"))
    }

    /// Where the baselines are.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// One baseline's directory.
    #[must_use]
    pub fn directory(&self, specimen: &str) -> PathBuf {
        self.root.join(specimen)
    }

    /// One artefact's bytes.
    ///
    /// # Errors
    ///
    /// A sentence naming the path that could not be read.
    pub fn artefact(&self, specimen: &str, artefact: &str) -> Result<Vec<u8>, String> {
        let path = self.directory(specimen).join(artefact);
        std::fs::read(&path).map_err(|error| format!("reading {}: {error}", path.display()))
    }

    /// What the approval beside `specimen` is worth.
    #[must_use]
    pub fn approval(&self, specimen: &str) -> ApprovalState {
        let path = self.directory(specimen).join(APPROVAL_FILE);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return ApprovalState::Missing;
        };
        let approval = match Approval::parse(&text) {
            Ok(approval) => approval,
            Err(reason) => return ApprovalState::Malformed { reason },
        };
        if approval.specimen != specimen {
            return ApprovalState::Malformed {
                reason: format!(
                    "the record in `{specimen}` says it approves `{}`",
                    approval.specimen
                ),
            };
        }
        for artefact in ARTEFACTS {
            let Some(recorded) = approval.digest_of(artefact) else {
                return ApprovalState::Stale {
                    artefact: artefact.to_owned(),
                    recorded: "nothing — the record does not mention it".to_owned(),
                    actual: "present".to_owned(),
                };
            };
            let actual = match self.artefact(specimen, artefact) {
                Ok(bytes) => sha256_hex(&bytes),
                Err(reason) => {
                    return ApprovalState::Stale {
                        artefact: artefact.to_owned(),
                        recorded: recorded.to_owned(),
                        actual: format!("absent ({reason})"),
                    }
                }
            };
            if actual != recorded {
                return ApprovalState::Stale {
                    artefact: artefact.to_owned(),
                    recorded: recorded.to_owned(),
                    actual,
                };
            }
        }
        ApprovalState::Approved(approval)
    }

    /// Write a baseline's artefacts, **and remove whatever approval was beside them**.
    ///
    /// # Errors
    ///
    /// A sentence naming the path that could not be written.
    pub fn regenerate(
        &self,
        _intent: RegenerationIntent,
        specimen: &str,
        artefacts: &[(&str, Vec<u8>)],
    ) -> Result<(), String> {
        let directory = self.directory(specimen);
        std::fs::create_dir_all(&directory)
            .map_err(|error| format!("creating {}: {error}", directory.display()))?;

        // **The approval goes first.** If the artefacts were written first and this failed, the
        // baseline would carry an approval of bytes that are no longer there — the exact state the
        // whole module exists to make impossible.
        let approval = directory.join(APPROVAL_FILE);
        if approval.exists() {
            std::fs::remove_file(&approval)
                .map_err(|error| format!("removing {}: {error}", approval.display()))?;
        }
        for (name, bytes) in artefacts {
            let path = directory.join(name);
            std::fs::write(&path, bytes)
                .map_err(|error| format!("writing {}: {error}", path.display()))?;
        }
        Ok(())
    }

    /// Record an approval of whatever is on disk right now.
    ///
    /// # Errors
    ///
    /// A sentence, when an artefact is missing or the record cannot be written. A baseline whose
    /// artefacts are incomplete cannot be approved — there would be nothing to bind the approval to.
    pub fn approve(
        &self,
        specimen: &str,
        approver: Approver,
        note: &str,
    ) -> Result<Approval, String> {
        let mut digests = Vec::with_capacity(ARTEFACTS.len());
        for artefact in ARTEFACTS {
            let bytes = self.artefact(specimen, artefact)?;
            digests.push((artefact.to_owned(), sha256_hex(&bytes)));
        }
        let approval = Approval {
            specimen: specimen.to_owned(),
            approver,
            approved_at: now(),
            note: note.to_owned(),
            digests,
        };
        let path = self.directory(specimen).join(APPROVAL_FILE);
        std::fs::write(&path, approval.to_text())
            .map_err(|error| format!("writing {}: {error}", path.display()))?;
        Ok(approval)
    }
}

/// Every specimen whose baseline exists and carries no **human** approval.
///
/// The listing MJXOFF-165 asks the suite to be able to produce, one level in from
/// [`provisional_baselines`](crate::authority::provisional_baselines): there, every observation a
/// non-authoritative reference produced; here, every image no person has looked at. Both sets are
/// meant to shrink, and neither shrinks by itself.
#[must_use]
pub fn awaiting_human_review(baselines: &Baselines, specimens: &[&str]) -> Vec<String> {
    specimens
        .iter()
        .filter(|specimen| !baselines.approval(specimen).is_reviewed())
        .map(|specimen| (*specimen).to_owned())
        .collect()
}

/// Seconds since the Unix epoch, or zero on a clock set before it.
fn now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_secs())
}

/// `YYYY-MM-DD` in UTC, from seconds since the epoch.
///
/// Howard Hinnant's `civil_from_days`, which is exact for every date the proleptic Gregorian
/// calendar has and is fifteen lines. A date formatter is not worth a dependency in a crate nothing
/// depends on.
#[must_use]
pub fn iso_date(seconds: u64) -> String {
    let days = (seconds / 86_400) as i64;
    // Shift the epoch to 0000-03-01, so that a leap day is the last day of the year.
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = if month_prime < 10 {
        month_prime + 3
    } else {
        month_prime - 9
    };
    let year = if month <= 2 { year + 1 } else { year };
    format!("{year:04}-{month:02}-{day:02}")
}
