//! SHA-256, so that an approval names **an image** and not merely a file name.
//!
//! # Why a digest at all, and why this one
//!
//! MJXOFF-165's sharpest sentence is that *a golden image generated by the code under test always
//! matches the code under test*. The answer this crate gives is that a baseline is only a baseline
//! once a person has approved it — and an approval that named only the baseline's *name* would be
//! satisfied by any bytes that later appeared under that name, which is exactly the regeneration
//! path it exists to catch. So an approval records the digest of what was approved, and a baseline
//! whose artefacts no longer hash to it is **unapproved**, not merely changed.
//!
//! SHA-256 rather than a fast non-cryptographic hash for one practical reason: a person can check it
//! without this crate. `sha256sum baselines/<name>/render.png` on any machine reproduces the number
//! in the approval record, so the record is auditable by the human whose approval it claims.
//!
//! # Why it is written out here
//!
//! `CLAUDE.md`'s pure-Rust rule and this crate's *"nothing depends on it"* position both point the
//! same way, but the real reason is smaller: this is sixty lines of a published, fixed algorithm
//! with official test vectors, and it is proved against those vectors in
//! `tests/the_instruments_measure_what_they_claim.rs` rather than trusted.

/// The eight initial hash values: the fractional parts of the square roots of the first eight
/// primes, as FIPS 180-4 §5.3.3 gives them.
const INITIAL: [u32; 8] = [
    0x6a09_e667,
    0xbb67_ae85,
    0x3c6e_f372,
    0xa54f_f53a,
    0x510e_527f,
    0x9b05_688c,
    0x1f83_d9ab,
    0x5be0_cd19,
];

/// The sixty-four round constants: the fractional parts of the cube roots of the first sixty-four
/// primes, as FIPS 180-4 §4.2.2 gives them.
const ROUND: [u32; 64] = [
    0x428a_2f98,
    0x7137_4491,
    0xb5c0_fbcf,
    0xe9b5_dba5,
    0x3956_c25b,
    0x59f1_11f1,
    0x923f_82a4,
    0xab1c_5ed5,
    0xd807_aa98,
    0x1283_5b01,
    0x2431_85be,
    0x550c_7dc3,
    0x72be_5d74,
    0x80de_b1fe,
    0x9bdc_06a7,
    0xc19b_f174,
    0xe49b_69c1,
    0xefbe_4786,
    0x0fc1_9dc6,
    0x240c_a1cc,
    0x2de9_2c6f,
    0x4a74_84aa,
    0x5cb0_a9dc,
    0x76f9_88da,
    0x983e_5152,
    0xa831_c66d,
    0xb003_27c8,
    0xbf59_7fc7,
    0xc6e0_0bf3,
    0xd5a7_9147,
    0x06ca_6351,
    0x1429_2967,
    0x27b7_0a85,
    0x2e1b_2138,
    0x4d2c_6dfc,
    0x5338_0d13,
    0x650a_7354,
    0x766a_0abb,
    0x81c2_c92e,
    0x9272_2c85,
    0xa2bf_e8a1,
    0xa81a_664b,
    0xc24b_8b70,
    0xc76c_51a3,
    0xd192_e819,
    0xd699_0624,
    0xf40e_3585,
    0x106a_a070,
    0x19a4_c116,
    0x1e37_6c08,
    0x2748_774c,
    0x34b0_bcb5,
    0x391c_0cb3,
    0x4ed8_aa4a,
    0x5b9c_ca4f,
    0x682e_6ff3,
    0x748f_82ee,
    0x78a5_636f,
    0x84c8_7814,
    0x8cc7_0208,
    0x90be_fffa,
    0xa450_6ceb,
    0xbef9_a3f7,
    0xc671_78f2,
];

/// The SHA-256 of `bytes`, as sixty-four lower-case hexadecimal digits.
///
/// The same string `sha256sum` prints, which is the point: a person auditing an approval record does
/// not have to run this crate to check it.
#[must_use]
pub fn sha256_hex(bytes: &[u8]) -> String {
    let digest = sha256(bytes);
    let mut hex = String::with_capacity(64);
    for byte in digest {
        hex.push(char::from_digit(u32::from(byte >> 4), 16).unwrap_or('0'));
        hex.push(char::from_digit(u32::from(byte & 0x0f), 16).unwrap_or('0'));
    }
    hex
}

/// The raw thirty-two byte digest of `bytes`.
#[must_use]
pub fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut state = INITIAL;

    // The padded message is the input, a `0x80`, zeroes up to 56 modulo 64, then the length in bits
    // as a big-endian `u64`. Only the **tail** is copied: a baseline image is megabytes and every
    // check hashes all of them, so the whole-message copy a naive padding does would be the most
    // expensive thing in the suite.
    let bit_length = (bytes.len() as u64).wrapping_mul(8);
    let remainder = bytes.len() % 64;
    let (whole, partial) = bytes.split_at(bytes.len() - remainder);
    let mut tail = Vec::with_capacity(128);
    tail.extend_from_slice(partial);
    tail.push(0x80);
    while tail.len() % 64 != 56 {
        tail.push(0);
    }
    tail.extend_from_slice(&bit_length.to_be_bytes());

    for block in whole.as_chunks::<64>().0 {
        compress(&mut state, block);
    }
    for block in tail.as_chunks::<64>().0 {
        compress(&mut state, block);
    }

    let mut digest = [0u8; 32];
    for (word, slot) in state.iter().zip(digest.as_chunks_mut::<4>().0) {
        *slot = word.to_be_bytes();
    }
    digest
}

/// One sixty-four byte block, folded into `state`.
fn compress(state: &mut [u32; 8], block: &[u8; 64]) {
    let mut schedule = [0u32; 64];
    for (index, word) in block.as_chunks::<4>().0.iter().enumerate().take(16) {
        schedule[index] = u32::from_be_bytes(*word);
    }
    for index in 16..64 {
        let s0 = schedule[index - 15].rotate_right(7)
            ^ schedule[index - 15].rotate_right(18)
            ^ (schedule[index - 15] >> 3);
        let s1 = schedule[index - 2].rotate_right(17)
            ^ schedule[index - 2].rotate_right(19)
            ^ (schedule[index - 2] >> 10);
        schedule[index] = schedule[index - 16]
            .wrapping_add(s0)
            .wrapping_add(schedule[index - 7])
            .wrapping_add(s1);
    }

    let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = *state;
    for index in 0..64 {
        let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
        let choose = (e & f) ^ ((!e) & g);
        let temporary1 = h
            .wrapping_add(s1)
            .wrapping_add(choose)
            .wrapping_add(ROUND[index])
            .wrapping_add(schedule[index]);
        let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
        let majority = (a & b) ^ (a & c) ^ (b & c);
        let temporary2 = s0.wrapping_add(majority);
        h = g;
        g = f;
        f = e;
        e = d.wrapping_add(temporary1);
        d = c;
        c = b;
        b = a;
        a = temporary1.wrapping_add(temporary2);
    }

    for (slot, value) in state.iter_mut().zip([a, b, c, d, e, f, g, h]) {
        *slot = slot.wrapping_add(value);
    }
}
