//! **The fidelity oracle** (MJXOFF-165): layered assertions, perceptual diffing, and the document
//! plate gallery.
//!
//! # ⚠ Read this before quoting anything this crate prints
//!
//! **Every gate here can pass with no authoritative reference in existence**, and most of what it
//! measures is the renderer against *itself at a moment a person approved*. That is a regression
//! oracle, and a regression oracle is not a fidelity claim. The claims are written down in code
//! rather than left to be inferred from a green run:
//!
//! **What this crate proves today:**
//!
//! * The rendering path — `FragmentTree -> DisplayList -> pixels` — still produces what it produced
//!   when a baseline was taken, and **which of the three stages moved** when it does not.
//! * Every plate draws the document's own geometry: `DrawReport::placeholders` is zero, asserted,
//!   beside a non-zero draw count so that a page which drew nothing cannot satisfy it.
//! * The PDF layout tier works, on our own exports, *before* the Windows sitting: two documents'
//!   word boxes are compared and a one-word displacement is **named**.
//! * A baseline with no approval record fails, a regenerated baseline is unapproved until somebody
//!   approves it again, and regeneration cannot happen without an explicit statement of intent.
//!
//! **What it cannot prove, and will not claim:**
//!
//! * That any page matches PowerPoint. Not one.
//!   [`Baseline::may_be_called_parity`](authority::Baseline::may_be_called_parity) is `false` for
//!   every observation available today, and it is `false` *by construction* — the only authoritative
//!   provider is an Office export, and there are none.
//! * That anybody has looked at the committed images. Every approval this crate ships is
//!   [`Approver::Generator`], which is a real approval record and not
//!   a human review; [`baseline::awaiting_human_review`] lists all of them.
//!
//! # The trap, and the three things that answer it
//!
//! **A golden image generated by the code under test always matches the code under test.**
//! Regenerate-and-compare is green by construction. See [`baseline`] for the whole of the answer;
//! in one line each: an unapproved baseline **fails**, regeneration needs a
//! [`RegenerationIntent`] that only the environment can hand out, and
//! an approval binds a SHA-256 rather than a name.
//!
//! # The three tiers, and why localisation is the point
//!
//! A single golden image answers every regression the same way — *the picture changed* — and a
//! wrapped line, a mis-tessellated corner and a lost clip stack all look identical in a diff. So the
//! same specimen is asserted at three stages of one pipeline, and [`tiers::Localisation`] says which
//! stage. See [`tiers`].
//!
//! # The two traps that point in opposite directions
//!
//! Both are enforced in [`authority`], which this crate owns and `mjx-reference-pack` re-exports:
//!
//! * **A provisional baseline read as parity.** Approve against LibreOffice, keep it quietly when
//!   PowerPoint arrives, and LibreOffice's quirks are ratified into the ledger — worse than having
//!   no reference, because it *looks* like parity.
//! * **A reference defect read as our defect.** LibreOffice's PDF export does not reproduce
//!   gradients or shades, so a pixel difference there is the reference's fault; nothing in a pixel
//!   diff says which way round it is. The exclusion is a property of the **provider**, so it lifts
//!   automatically for an authoritative one, and an excluded result is [`Verdict::NotEvidence`] —
//!   never a pass, never a failure.
//!
//! # Where this crate sits
//!
//! Test-only, `publish = false`, **outside the ranked graph**. **No crate with a rank may depend on
//! it, in either dependency section** — a `[dev-dependencies]` entry included, because this crate
//! names `mjx-paint` and a test build that links Vulkan is still a build that links Vulkan. A crate
//! that is *itself* above the whole document graph may: `mjx-reference-pack` is the first, and
//! MJXOFF-166's canvas harness — specified to reach [`plate`] rather than write a second PNG
//! emitter — will be the second. `xtask/tests/layering.rs` refuses the illegal direction by name and
//! asserts the legal edge exists, because a rule written for a consumer with no consumer is one that
//! would go on passing if this crate no longer existed.
//!
//! # What is here
//!
//! | Module | What it is |
//! |---|---|
//! | [`authority`] | Where a reference came from, what it is worth, and the third answer that is neither pass nor fail |
//! | [`baseline`] | Committed baselines, the approval event, and the explicit-only regeneration path |
//! | [`digest`] | SHA-256, so an approval names an image rather than a file name |
//! | [`gallery`] | The plate gallery, and the surface a person approves from |
//! | [`geom`] | Rectangles, in points and in raster pixels |
//! | [`json`] | Just enough JSON to write the plate manifest **and read it back** |
//! | [`pdf`] | The layout tier and the pixel tier, both working today on our own exports |
//! | [`perceptual`] | A structural metric and a per-specimen tolerance — never a byte compare |
//! | [`plate`] | The plate generator and the manifest R11 and U01 load |
//! | [`png`] | A PNG encoder, and **the premultiplied-alpha decision** |
//! | [`snapshot`] | Tiers one and two as text a diff can name a line of |
//! | [`specimen`] | The pages the oracle asserts over, and the two perturbations |
//! | [`tiers`] | The three layered assertions, and which stage a difference belongs to |
//! | [`tools`] | `pdftoppm`, `pdftotext`, `pdfinfo`, `soffice` — and the loud named skip |

pub mod authority;
pub mod baseline;
pub mod digest;
pub mod gallery;
pub mod geom;
pub mod json;
pub mod pdf;
pub mod perceptual;
pub mod plate;
pub mod png;
pub mod snapshot;
pub mod specimen;
pub mod tiers;
pub mod tools;

pub use authority::{
    parity_count, provisional_baselines, Baseline, ReferenceProvider, RenderedContent, Verdict,
};
pub use baseline::{
    awaiting_human_review, Approval, ApprovalState, Approver, Baselines, RegenerationIntent,
};
pub use perceptual::{Difference, Tolerance};
pub use snapshot::Snapshot;
pub use specimen::{Perturbation, Specimen, SPECIMENS};
pub use tiers::{LayeredComparison, Localisation, TierOutcome};

/// Compare one specimen against its committed baseline, at all three tiers.
///
/// `perturbation` is what was deliberately changed before rendering; a check run passes
/// [`Perturbation::None`] and the two gate tests pass the others.
///
/// # Errors
///
/// A sentence, when the baseline cannot be used at all — no approval, a stale digest, a missing
/// artefact — or when the specimen will not render. **An unusable baseline is an error and never a
/// tier outcome**, because a comparison against a baseline nobody approved is the tautology this
/// crate exists to refuse, and reporting it as *"the tiers agreed"* would be that tautology with a
/// green tick on it.
pub fn compare_against_baseline(
    baselines: &Baselines,
    specimen: &Specimen,
    perturbation: Perturbation,
) -> Result<LayeredComparison, String> {
    let approval = baselines.approval(specimen.name);
    if let Some(refusal) = approval.refusal() {
        return Err(format!("`{}`: {refusal}", specimen.name));
    }

    let tree = specimen::fragments(specimen, perturbation);
    let taken_fragments = snapshot::fragments(&tree);
    let stored_fragments = snapshot::Snapshot::parse(&String::from_utf8_lossy(
        &baselines.artefact(specimen.name, baseline::ARTEFACTS[0])?,
    ));

    let list = specimen::display_list(specimen, perturbation)?;
    let taken_commands = snapshot::commands(&list);
    let stored_commands = snapshot::Snapshot::parse(&String::from_utf8_lossy(
        &baselines.artefact(specimen.name, baseline::ARTEFACTS[1])?,
    ));

    let rendered = specimen::render(specimen, perturbation)?;
    let taken_image = png::image_from_pixels(&rendered.pixels);
    let stored_image = png::decode(&baselines.artefact(specimen.name, baseline::ARTEFACTS[2])?)?;
    // **Not a byte compare**, even though these two would be byte-identical on a run that changed
    // nothing. The metric is what makes a failure say *where* the page moved and how much, and it
    // is the same metric the cross-producer pixel tier in `crate::pdf` uses — one instrument, held
    // to two tolerances, rather than a strict path here and a lenient one there that could disagree
    // about what "the same picture" means.
    let difference = perceptual::compare(&taken_image, &stored_image, specimen.tolerance)?;
    let pixels = TierOutcome::from_difference(&difference, specimen.tolerance);

    Ok(LayeredComparison {
        specimen: specimen.name.to_owned(),
        // The tiers compare against this crate's own committed baselines, which no external producer
        // made. `None` is a *provider that answers nothing*, not the absence of one — which is what
        // keeps `may_be_called_parity` false rather than unasked.
        provider: ReferenceProvider::None,
        content: specimen.content,
        fragments: TierOutcome::from_snapshots(&taken_fragments, &stored_fragments),
        commands: TierOutcome::from_snapshots(&taken_commands, &stored_commands),
        pixels,
    })
}
