//! **Tier one, over the fixture corpus.** One committed text snapshot per slide, compared line by
//! line, so a text-position regression surfaces as *"line 14: node 6's rect is 152400 wide and was
//! 101600"* rather than as a mysterious picture.
//!
//! # Why this is here and not in `mjx-render-oracle`
//!
//! MJXOFF-165 built exactly this machinery — the three assertion tiers, the localisation, the
//! approval records — and R14's ticket asks for it to be used. **It cannot be, and the reason is
//! structural rather than a preference.** `mjx-render-oracle` depends on `mjx-paint`, which links
//! Vulkan; `xtask/tests/layering.rs` therefore forbids *any* ranked crate from naming it, in either
//! dependency section, because a test build that links Vulkan is still a build that links Vulkan.
//! This crate has a rank, so the edge is refused by name.
//!
//! The oracle cannot host these snapshots either: it is specified to name no format crate at all —
//! it is the rendering path with no document anywhere in it — and a specimen read from a `.pptx`
//! would make every one of its baselines a baseline of the box model as well as of the renderer,
//! which is exactly the confusion it was built to prevent.
//!
//! So the *technique* is copied and the crate is not: `tests/support/mod.rs` writes the same line
//! shape the oracle's tier one writes, down to carrying a glyph **count** rather than glyph ids —
//! because a baseline holding glyph ids is a baseline of a shaper version, and a patch release of
//! `swash` would expire it for a reason that has nothing to do with layout.
//!
//! # ⚠ Regeneration is deliberately not automatic
//!
//! A golden file generated by the code under test always matches the code under test. So
//! [`regenerate`] refuses without `MJX_LAYOUT_PPTX_REGENERATE=1`, and every committed baseline
//! states who approved it. Today every one says `generator`, which is a real record — it says the
//! file is a **change detector** and that no person has looked at it — and is not a human review.
//! The Windows sitting is where a person approves what these numbers should be.

mod support;

use std::path::{Path, PathBuf};

use mjx_layout::{BoxModel, PageIndex};
use mjx_layout_pptx::{constraints_for, SlideDeck};
use mjx_pptx::Presentation;

use support::{fixture, model, snapshot};

/// One slide with a committed baseline.
struct Specimen {
    /// The fixture it is read from.
    file: &'static str,
    /// Which slide of it.
    slide: usize,
    /// Why this one is in the corpus — the thing its snapshot would notice.
    covers: &'static str,
}

/// The corpus. Committed fixtures only: a baseline over a deck this crate *authored* would move
/// whenever `Presentation::blank` changed a default, which is a regression in a different crate.
const CORPUS: &[Specimen] = &[
    Specimen {
        file: "sample.pptx",
        slide: 0,
        covers:
            "a placeholder no tier places — the slide's `p:spPr` is empty and its layout has no \
                 matching slot — so nothing is drawn at all",
    },
    Specimen {
        file: "text_levels.pptx",
        slide: 0,
        covers: "nine indent levels with their bullets, as a real deck states them",
    },
    Specimen {
        file: "layouts.pptx",
        slide: 0,
        covers: "placeholders whose bounds and text properties come from a layout and a master",
    },
    Specimen {
        file: "effects_theme.pptx",
        slide: 0,
        covers: "shapes with theme effects, whose fills and outlines resolve to decoration handles",
    },
    Specimen {
        file: "vml.pptx",
        slide: 0,
        covers: "a deck carrying legacy VML, which the box model neither reads nor trips over",
    },
    Specimen {
        file: "charts.pptx",
        slide: 0,
        covers: "graphic frames, which occupy their boxes and become fragments in R15",
    },
    Specimen {
        file: "charts.pptx",
        slide: 1,
        covers: "the second page of a deck, reached through the first page's checkpoint",
    },
    Specimen {
        file: "tables.pptx",
        slide: 0,
        covers: "a table's graphic frame, laid out as the box it occupies until R15",
    },
    Specimen {
        file: "hyperlinks.pptx",
        slide: 0,
        covers: "runs that carry a hyperlink, which changes their formatting and not their layout",
    },
];

impl Specimen {
    /// The baseline file this specimen is compared against.
    fn baseline(&self) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/baselines")
            .join(format!(
                "{}-slide{}.txt",
                self.file.trim_end_matches(".pptx"),
                self.slide
            ))
    }

    /// The snapshot this specimen produces now.
    fn taken(&self) -> String {
        let mut presentation = Presentation::open(&fixture(self.file))
            .unwrap_or_else(|error| panic!("opening {}: {error}", self.file));
        let deck = SlideDeck::read(&mut presentation)
            .unwrap_or_else(|error| panic!("reading {}: {error}", self.file));
        assert!(
            self.slide < deck.slide_count(),
            "{} has no slide {}",
            self.file,
            self.slide
        );
        let constraints = constraints_for(&deck);
        let mut model = model();

        // Reached the way a reader reaches it — page by page, through each checkpoint — so that a
        // baseline of page two is also a check that resumption produces the same page.
        let mut resume = None;
        let mut fragments = None;
        for index in 0..=self.slide {
            let page = model
                .layout_page(
                    &deck,
                    PageIndex::new(u32::try_from(index).expect("small")),
                    &constraints,
                    resume.as_ref(),
                )
                .unwrap_or_else(|error| panic!("{} slide {index}: {error}", self.file));
            resume = page.continuation().cloned();
            fragments = Some(page);
        }
        let page = fragments.expect("at least one page");
        format!(
            "# specimen: {} slide {}\n# covers: {}\n# approver: generator\n# approval: a change \
             detector written by the code under test; no person has reviewed these numbers, and \
             the Windows sitting is where one will\n{}",
            self.file,
            self.slide,
            self.covers,
            snapshot(page.fragments())
        )
    }
}

/// A baseline's text, with trailing whitespace stripped and a trailing blank line dropped, so an
/// editor that adds or removes a final newline cannot expire an approval.
fn normalise(text: &str) -> Vec<String> {
    let mut lines: Vec<String> = text
        .lines()
        .map(|line| line.trim_end().to_owned())
        .collect();
    while lines.last().is_some_and(String::is_empty) {
        lines.pop();
    }
    lines
}

/// The first line at which two snapshots differ, quoted from both sides.
///
/// **One line, not a whole diff.** A page is hundreds of lines and a failure that printed all of
/// them would be scrolled past; the first divergence is where a reader has to look and every later
/// one is usually its consequence.
fn first_difference(taken: &[String], baseline: &[String]) -> Option<String> {
    for (number, (mine, theirs)) in taken.iter().zip(baseline.iter()).enumerate() {
        if mine != theirs {
            return Some(format!(
                "line {}:\n  baseline: {theirs}\n  this run: {mine}",
                number + 1
            ));
        }
    }
    match taken.len().cmp(&baseline.len()) {
        std::cmp::Ordering::Equal => None,
        std::cmp::Ordering::Greater => Some(format!(
            "line {}: the baseline ends here and this run adds `{}` ({} lines against {})",
            baseline.len() + 1,
            taken.get(baseline.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
        std::cmp::Ordering::Less => Some(format!(
            "line {}: this run ends here and the baseline has `{}` ({} lines against {})",
            taken.len() + 1,
            baseline.get(taken.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
    }
}

#[test]
fn every_specimen_matches_its_committed_baseline() {
    let regenerate = std::env::var("MJX_LAYOUT_PPTX_REGENERATE").as_deref() == Ok("1");
    let mut failures = Vec::new();

    for specimen in CORPUS {
        let taken = specimen.taken();
        let path = specimen.baseline();
        if regenerate {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).expect("the baseline directory");
            }
            std::fs::write(&path, &taken)
                .unwrap_or_else(|error| panic!("writing {}: {error}", path.display()));
            continue;
        }

        let Ok(committed) = std::fs::read_to_string(&path) else {
            failures.push(format!(
                "{} has no committed baseline. Regenerate with \
                 `MJX_LAYOUT_PPTX_REGENERATE=1 cargo test -p mjx-layout-pptx --test \
                 the_fragments_match_their_baselines`, then read what it wrote before committing it.",
                path.display()
            ));
            continue;
        };
        if let Some(difference) = first_difference(&normalise(&taken), &normalise(&committed)) {
            failures.push(format!("{}\n{difference}", path.display()));
        }
    }

    assert!(
        !regenerate,
        "MJX_LAYOUT_PPTX_REGENERATE=1 rewrote every baseline. That is not a passing run: a golden \
         file generated by the code under test always matches the code under test. Read the diff.",
    );
    assert!(
        failures.is_empty(),
        "{} of {} specimens moved:\n\n{}",
        failures.len(),
        CORPUS.len(),
        failures.join("\n\n")
    );
}

#[test]
fn every_baseline_carries_an_approval_record() {
    // A baseline with no approver is a number nobody has taken responsibility for. `generator` is a
    // real record — it says the file is a change detector — and it is the only value in the tree
    // today; a human approval would name a person.
    for specimen in CORPUS {
        let path = specimen.baseline();
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue; // The other test reports a missing baseline; this one is about content.
        };
        let header: Vec<&str> = text.lines().take(4).collect();
        assert!(
            header
                .first()
                .is_some_and(|line| line.starts_with("# specimen: ")),
            "{} does not name its specimen",
            path.display()
        );
        assert!(
            header.iter().any(|line| line.starts_with("# covers: ")),
            "{} does not say what it covers",
            path.display()
        );
        assert!(
            header.iter().any(|line| line.starts_with("# approver: ")),
            "{} carries no approval record",
            path.display()
        );
        assert!(
            header.iter().any(|line| line.starts_with("# approval: ")),
            "{} carries no approval note",
            path.display()
        );
    }
}

#[test]
fn a_baseline_notices_a_moved_fragment() {
    // The instrument's own instrument: proof that a snapshot comparison would *fail* if a fragment
    // moved, rather than being satisfied by any two runs of the same code.
    let specimen = CORPUS
        .iter()
        .find(|specimen| specimen.file == "text_levels.pptx")
        .expect("a specimen with text in it");
    let taken = specimen.taken();
    let mut perturbed = normalise(&taken);
    let position = perturbed
        .iter()
        .position(|line| line.contains("line rect=["))
        .expect("a line fragment in the snapshot");
    perturbed[position] = perturbed[position].replace("rect=[", "rect=[9");
    assert!(
        first_difference(&perturbed, &normalise(&taken)).is_some(),
        "a snapshot that cannot notice a moved fragment is not a baseline"
    );
}

#[test]
fn the_corpus_covers_more_than_one_shape_of_slide() {
    // The "how many distinct values did the gate see?" instrument: a corpus of one deck asserts one
    // deck's arrangement, and every corner it happens not to use is uncovered.
    let files: std::collections::BTreeSet<&str> =
        CORPUS.iter().map(|specimen| specimen.file).collect();
    assert!(files.len() >= 5, "{files:?}");
    assert!(
        CORPUS.iter().any(|specimen| specimen.slide > 0),
        "some specimen must be reached through a checkpoint rather than as page one"
    );
}
