//! Renders the committed child-order tables for `mjx-ooxml-types::child_order`.
//!
//! One `ChildOrder` per `xsd:complexType` of every schema this workspace writes markup for, holding
//! each child element's namespace, local name, own complex type, and rank (see
//! [`super::complex`] for what rank means). The tables are sorted by XSD symbol so the by-symbol
//! lookup can bisect; the curated `pub static` aliases in [`spec::CHILD_ORDER_EXPORTS`] give the
//! types our serializers use a self-explanatory name to hold as a constant.
//!
//! This is mechanical extraction plus one curated naming table — the same discipline the simple-type
//! allowlist already follows.

// This module emits source code, so explicit trailing newlines in `write!` are intentional.
#![allow(clippy::write_with_newline)]

use std::collections::BTreeMap;
use std::fmt::Write as _;

use anyhow::{bail, Result};

use crate::codegen::complex::{ContentModel, FlatType, Schema, SchemaSet};
use crate::codegen::naming::screaming_snake;
use crate::codegen::spec;

/// One schema's flattened types, with the identifiers the generated source will use.
struct Table {
    /// The `SCREAMING_SNAKE` array name, e.g. `DRAWINGML_TYPES`.
    array: String,
    /// The namespace constant name, e.g. `DML_MAIN`.
    namespace_const: String,
    /// The schema file, for the provenance comment.
    file: String,
    /// The flattened types, sorted by symbol.
    types: Vec<FlatType>,
    /// The schema's global element declarations, as `(local, complex-type symbol)`.
    roots: Vec<(String, String)>,
}

/// Renders the whole `child_order` module from the parsed schema set.
///
/// `order` names the schemas to emit, by file stem, in the order their tables should appear.
pub fn generate(set: &SchemaSet, stems: &[&str]) -> Result<String> {
    // Namespace URI → the `namespaces` constant name, derived from the file stem exactly as the
    // namespace table itself is.
    let mut namespace_consts: BTreeMap<&str, String> = BTreeMap::new();
    for schema in set.schemas() {
        let stem = schema.file.trim_end_matches(".xsd");
        namespace_consts.insert(&schema.target_namespace, screaming_snake(stem));
    }

    let mut tables = Vec::new();
    for stem in stems {
        let schema = set
            .schemas()
            .iter()
            .find(|s| s.file == format!("{stem}.xsd"))
            .ok_or_else(|| anyhow::anyhow!("schema `{stem}.xsd` was not parsed"))?;
        tables.push(table_for(set, schema, &namespace_consts)?);
    }

    let mut s = String::new();
    s.push_str(
        "// @generated by xtask — do not edit.\n\
         //\n\
         // Regenerate with: cargo run -p xtask -- codegen\n\
         // Source: the `xsd:complexType` content models of the Transitional reference schemas.\n\
         //! Generated child-order tables — the `xsd:sequence` position of every child of every\n\
         //! complex type in the schemas this workspace authors markup for.\n\
         //!\n\
         //! See [`crate::child_order`] for what a rank is and how these tables are used.\n\n\
         use crate::child_order::{in_namespace, ChildOrder, ChildSlot, ContentModel, TypeReference};\n",
    );
    let mut used: Vec<&String> = namespace_consts.values().collect();
    used.sort_unstable();
    used.dedup();
    let _ = write!(
        s,
        "use crate::generated::namespaces::{{{}}};\n\n",
        used.iter()
            .map(|n| n.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    );

    for table in &tables {
        render_table(&mut s, table, &namespace_consts)?;
    }
    render_find(&mut s, &tables);
    render_roots(&mut s, &tables);
    render_exports(&mut s, &tables)?;
    Ok(s)
}

fn table_for(
    set: &SchemaSet,
    schema: &Schema,
    namespace_consts: &BTreeMap<&str, String>,
) -> Result<Table> {
    let mut types = set.flatten_schema(schema)?;
    types.sort_by(|a, b| a.symbol.cmp(&b.symbol));
    // A schema may declare the same complex type name twice only by being malformed; a duplicate
    // would silently shadow one of them in the bisecting lookup, so refuse rather than guess.
    if let Some(pair) = types.windows(2).find(|w| w[0].symbol == w[1].symbol) {
        bail!(
            "{}: duplicate complexType `{}`",
            schema.file,
            pair[0].symbol
        );
    }

    let mut roots = Vec::new();
    for (local, qname) in schema.global_elements() {
        let symbol = qname.split_once(':').map_or(qname, |(_, rest)| rest);
        if symbol.starts_with("CT_") && types.iter().any(|t| t.symbol == symbol) {
            roots.push((local.to_owned(), symbol.to_owned()));
        }
    }
    roots.sort();

    let stem = schema.file.trim_end_matches(".xsd");
    Ok(Table {
        array: format!("{}_TYPES", screaming_snake(stem)),
        namespace_const: namespace_consts
            .get(schema.target_namespace.as_str())
            .cloned()
            .unwrap_or_default(),
        file: schema.file.clone(),
        types,
        roots,
    })
}

fn model_path(model: ContentModel) -> &'static str {
    match model {
        ContentModel::Empty => "ContentModel::Empty",
        ContentModel::Sequence => "ContentModel::Sequence",
        ContentModel::Choice => "ContentModel::Choice",
        ContentModel::All => "ContentModel::All",
    }
}

fn render_table(
    s: &mut String,
    table: &Table,
    namespace_consts: &BTreeMap<&str, String>,
) -> Result<()> {
    let _ = write!(
        s,
        "/// Every complex type of `{}`, sorted by XSD symbol.\n\
         pub static {}: [ChildOrder; {}] = [\n",
        table.file,
        table.array,
        table.types.len()
    );
    for flat in &table.types {
        let _ = write!(
            s,
            "    ChildOrder {{ symbol: {:?}, namespace: {}, model: {}, slots: &[",
            flat.symbol,
            table.namespace_const,
            model_path(flat.model)
        );
        for slot in &flat.slots {
            let namespace = namespace_consts
                .get(slot.namespace.as_str())
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "{}: child `{}` is in namespace `{}`, whose schema was not parsed",
                        flat.symbol,
                        slot.local,
                        slot.namespace
                    )
                })?;
            let complex_type = match &slot.complex_type {
                Some((ns, symbol)) => match namespace_consts.get(ns.as_str()) {
                    Some(constant) => format!(
                        "Some(TypeReference {{ namespace: {constant}, symbol: {symbol:?} }})"
                    ),
                    // A child typed by a schema outside this table's set is still a valid child; it
                    // simply cannot be descended into.
                    None => "None".to_owned(),
                },
                None => "None".to_owned(),
            };
            let _ = write!(
                s,
                "ChildSlot {{ namespace: {}, local: {:?}, complex_type: {}, rank: {}, repeatable: {}, ambiguous: {} }}, ",
                namespace, slot.local, complex_type, slot.rank, slot.repeatable, slot.ambiguous
            );
        }
        s.push_str("] },\n");
    }
    s.push_str("];\n\n");
    Ok(())
}

fn render_find(s: &mut String, tables: &[Table]) {
    s.push_str(
        "/// The child order of the complex type `symbol` declared in `namespace`, or `None` if the\n\
         /// tables do not cover it.\n\
         ///\n\
         /// `namespace` may be either the Strict or the Transitional URI. This is the by-name\n\
         /// lookup a tree walk needs; a serializer holds its own type's `ChildOrder` as a constant\n\
         /// instead of calling this.\n\
         #[must_use]\n\
         pub fn find(namespace: &str, symbol: &str) -> Option<&'static ChildOrder> {\n\
         \x20   let table: &'static [ChildOrder] = ",
    );
    for table in tables {
        let _ = write!(
            s,
            "if in_namespace(namespace, {ns}) {{\n        &{array}\n    }} else ",
            ns = table.namespace_const,
            array = table.array
        );
    }
    s.push_str(
        "{\n\
         \x20       return None;\n\
         \x20   };\n\
         \x20   table\n\
         \x20       .binary_search_by(|order| order.symbol.cmp(symbol))\n\
         \x20       .ok()\n\
         \x20       .map(|index| &table[index])\n\
         }\n\n",
    );
}

fn render_roots(s: &mut String, tables: &[Table]) {
    s.push_str(
        "/// The child order of the complex type a schema's **global** element declaration names —\n\
         /// how a walk over a whole part starts, given only the part's root element name.\n\
         #[must_use]\n\
         pub fn root_element(namespace: &str, local: &str) -> Option<&'static ChildOrder> {\n\
         \x20   let symbol = ",
    );
    for table in tables {
        let _ = write!(
            s,
            "if in_namespace(namespace, {ns}) {{\n        match local {{\n",
            ns = table.namespace_const
        );
        for (element, symbol) in &table.roots {
            let _ = write!(s, "            {element:?} => {symbol:?},\n");
        }
        s.push_str(
            "            _ => return None,\n        }
    } else ",
        );
    }
    s.push_str(
        "{\n\
         \x20       return None;\n\
         \x20   };\n\
         \x20   find(namespace, symbol)\n\
         }\n\n",
    );
}

fn render_exports(s: &mut String, tables: &[Table]) -> Result<()> {
    for (name, stem, symbol, description) in spec::CHILD_ORDER_EXPORTS {
        let table = tables
            .iter()
            .find(|t| t.file == format!("{stem}.xsd"))
            .ok_or_else(|| anyhow::anyhow!("export `{name}` names unemitted schema `{stem}`"))?;
        let index = table
            .types
            .iter()
            .position(|t| t.symbol == *symbol)
            .ok_or_else(|| anyhow::anyhow!("export `{name}`: no `{symbol}` in {}", table.file))?;
        let _ = write!(
            s,
            "/// {description} (`{symbol}`, `{file}`).\n\
             pub static {name}: &ChildOrder = &{array}[{index}];\n\n",
            file = table.file,
            array = table.array
        );
    }
    Ok(())
}
