//! Renders committed Rust source for the shared simple types. Pure: `bytes → String`.

// This module emits source code, so explicit trailing newlines in `write!` are intentional
// (they lay out the generated Rust); `write_with_newline` would be noise here.
#![allow(clippy::write_with_newline)]

use std::fmt::Write as _;

use anyhow::Result;

use crate::codegen::spec;
use crate::codegen::xsd::{parse_simple_types, SimpleKind};

/// Renders the `shared` module from the `shared-commonSimpleTypes.xsd` bytes.
pub fn emit_shared_types(xsd: &[u8], source_note: &str) -> Result<String> {
    let types = parse_simple_types(xsd)?;
    let mut out = String::new();
    out.push_str(&file_header(source_note));

    for st in &types {
        if spec::SKIP_TYPES.contains(&st.name.as_str()) {
            let _ = writeln!(
                out,
                "// `{}` — subsumed by another representation; intentionally not emitted.\n",
                st.name
            );
            continue;
        }
        if let Some((normalizer, optional)) = spec::bool_kind(&st.name) {
            out.push_str(&emit_bool_alias(&st.name, normalizer, optional));
            continue;
        }
        match &st.kind {
            SimpleKind::Enumeration { base, values } => {
                out.push_str(&emit_enum(&st.name, base, values));
            }
            SimpleKind::Restriction { base, pattern } => {
                if pattern.is_none() {
                    if let Some(primitive) = spec::primitive_for(base) {
                        out.push_str(&emit_primitive_alias(&st.name, base, primitive));
                        continue;
                    }
                }
                out.push_str(&emit_string_newtype(&st.name, base, pattern.as_deref()));
            }
            SimpleKind::Union { members } => {
                let note = format!("union of {}", members.join(" | "));
                out.push_str(&emit_string_newtype(&st.name, &note, None));
            }
            SimpleKind::List { item } => {
                let note = format!("list of {item}");
                out.push_str(&emit_string_newtype(&st.name, &note, None));
            }
        }
    }

    Ok(out)
}

fn file_header(source_note: &str) -> String {
    format!(
        "// @generated by xtask — do not edit.\n\
         //\n\
         // Regenerate with: cargo run -p xtask -- codegen\n\
         // Source: {source_note}\n\
         #![allow(clippy::enum_variant_names)]\n\
         //! Comprehensively-named OOXML simple types (see the naming convention in `PLAN.md`).\n\
         //!\n\
         //! Each item records its original `ST_*` symbol and exact wire token(s).\n\n"
    )
}

fn emit_enum(st_name: &str, base: &str, values: &[String]) -> String {
    let type_name = spec::ENGINE.type_name(st_name);
    let variants: Vec<(String, &str)> = values
        .iter()
        .map(|wire| (spec::ENGINE.variant_name(st_name, wire), wire.as_str()))
        .collect();

    let mut s = String::new();
    let _ = write!(
        s,
        "/// `{st_name}` — OOXML enumeration (base `{base}`). Wire tokens are preserved exactly.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n\
         pub enum {type_name} {{\n"
    );
    for (variant, wire) in &variants {
        let _ = write!(s, "    /// Wire value `{wire}`.\n    {variant},\n");
    }
    s.push_str("}\n\n");

    let _ = write!(s, "impl {type_name} {{\n");
    s.push_str("    /// Parses this value from its exact OOXML wire token.\n");
    s.push_str("    #[must_use]\n    pub fn from_wire(s: &str) -> Option<Self> {\n        Some(match s {\n");
    for (variant, wire) in &variants {
        let _ = writeln!(s, "            {wire:?} => Self::{variant},");
    }
    s.push_str("            _ => return None,\n        })\n    }\n\n");
    s.push_str("    /// The exact OOXML wire token for this value.\n");
    s.push_str(
        "    #[must_use]\n    pub fn to_wire(self) -> &'static str {\n        match self {\n",
    );
    for (variant, wire) in &variants {
        let _ = writeln!(s, "            Self::{variant} => {wire:?},");
    }
    s.push_str("        }\n    }\n}\n\n");

    let _ = write!(
        s,
        "impl core::fmt::Display for {type_name} {{\n\
         \x20   fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n\
         \x20       f.write_str(self.to_wire())\n    }}\n}}\n\n\
         impl core::str::FromStr for {type_name} {{\n\
         \x20   type Err = crate::UnknownWireValue;\n\
         \x20   fn from_str(s: &str) -> Result<Self, Self::Err> {{\n\
         \x20       Self::from_wire(s).ok_or_else(|| crate::UnknownWireValue::new(s))\n    }}\n}}\n\n"
    );
    s
}

fn emit_string_newtype(st_name: &str, base_note: &str, pattern: Option<&str>) -> String {
    let type_name = spec::ENGINE.type_name(st_name);
    let mut s = String::new();
    let _ = writeln!(
        s,
        "/// `{st_name}` — string-valued OOXML type (base `{base_note}`)."
    );
    if let Some(p) = pattern {
        let _ = writeln!(
            s,
            "///\n/// XSD pattern `{p}`. Validation is deferred; the value is stored verbatim."
        );
    }
    let _ = write!(
        s,
        "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n\
         pub struct {type_name}(pub String);\n\n\
         impl {type_name} {{\n\
         \x20   /// Wraps a wire string.\n    #[must_use]\n\
         \x20   pub fn from_wire(s: &str) -> Self {{\n        Self(s.to_owned())\n    }}\n\n\
         \x20   /// The wire string.\n    #[must_use]\n\
         \x20   pub fn to_wire(&self) -> &str {{\n        &self.0\n    }}\n}}\n\n\
         impl core::fmt::Display for {type_name} {{\n\
         \x20   fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n\
         \x20       f.write_str(&self.0)\n    }}\n}}\n\n"
    );
    s
}

fn emit_primitive_alias(st_name: &str, base: &str, primitive: &str) -> String {
    let type_name = spec::ENGINE.type_name(st_name);
    format!(
        "/// `{st_name}` — numeric OOXML type (base `{base}`); a `{primitive}`.\n\
         pub type {type_name} = {primitive};\n\n"
    )
}

fn emit_bool_alias(st_name: &str, normalizer: &str, optional: bool) -> String {
    let type_name = spec::ENGINE.type_name(st_name);
    let rust_ty = if optional { "Option<bool>" } else { "bool" };
    format!(
        "/// `{st_name}` — a two-valued OOXML toggle, modeled as `{rust_ty}`.\n\
         ///\n\
         /// Every wire spelling is normalized on read and one canonical form is written; see\n\
         /// [`crate::support::{normalizer}`].\n\
         pub type {type_name} = {rust_ty};\n\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &[u8] = br#"<?xml version="1.0"?>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:t">
          <xsd:simpleType name="ST_VerticalAlignRun">
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="baseline"/>
              <xsd:enumeration value="superscript"/>
            </xsd:restriction>
          </xsd:simpleType>
          <xsd:simpleType name="ST_OnOff">
            <xsd:union memberTypes="xsd:boolean ST_OnOff1"/>
          </xsd:simpleType>
          <xsd:simpleType name="ST_OnOff1">
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="on"/>
            </xsd:restriction>
          </xsd:simpleType>
          <xsd:simpleType name="ST_Lang">
            <xsd:restriction base="xsd:string"/>
          </xsd:simpleType>
          <xsd:simpleType name="ST_UnsignedDecimalNumber">
            <xsd:restriction base="xsd:unsignedLong"/>
          </xsd:simpleType>
        </xsd:schema>"#;

    #[test]
    fn emits_expected_shapes() {
        let src = emit_shared_types(SAMPLE, "test").unwrap();
        // enum with comprehensive names + wire mapping
        assert!(src.contains("pub enum VerticalTextPosition"));
        assert!(src.contains("Baseline,"));
        assert!(src.contains("\"superscript\" => Self::Superscript,"));
        // ST_OnOff -> bool alias; ST_OnOff1 skipped
        assert!(src.contains("pub type OnOff = bool;"));
        assert!(src.contains("subsumed by another representation"));
        assert!(!src.contains("pub enum OnOff1"));
        // string newtype + numeric alias
        assert!(src.contains("pub struct LanguageTag(pub String);"));
        assert!(src.contains("pub type UnsignedDecimalNumber = u64;"));
    }

    #[test]
    fn output_is_deterministic() {
        assert_eq!(
            emit_shared_types(SAMPLE, "test").unwrap(),
            emit_shared_types(SAMPLE, "test").unwrap()
        );
    }
}
