//! Schema code generation: parse the local `References/` XSDs and emit committed Rust source into
//! `mjx-ooxml-types`. Deterministic — re-running produces no diff.

mod emit;
mod namespaces;
mod naming;
mod spec;
mod xsd;

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{bail, Context, Result};

const STRICT_DIR: &str =
    "References/ECMA-376-1_5th_edition_december_2016/OfficeOpenXML-XMLSchema-Strict";
const TRANSITIONAL_DIR: &str =
    "References/ECMA-376-4_5th_edition_december_2016/OfficeOpenXML-XMLSchema-Transitional";

/// Regenerates the `mjx-ooxml-types` source from the reference schemas.
pub fn run() -> Result<()> {
    let root = workspace_root();
    let strict_dir = root.join(STRICT_DIR);
    let transitional_dir = root.join(TRANSITIONAL_DIR);
    if !transitional_dir.is_dir() {
        bail!(
            "reference schemas not found at {} — codegen needs the local References/ tree",
            transitional_dir.display()
        );
    }

    let out_dir = root.join("crates/mjx-ooxml-types/src/generated");
    std::fs::create_dir_all(&out_dir).context("creating generated/ dir")?;

    // 1. namespace table (both worlds)
    let ns_src = namespaces::generate(&strict_dir, &transitional_dir)?;
    write_generated(&out_dir.join("namespaces.rs"), &ns_src)?;

    // 2. shared simple types
    let shared_xsd_path = transitional_dir.join("shared-commonSimpleTypes.xsd");
    let shared_xsd = std::fs::read(&shared_xsd_path)
        .with_context(|| format!("reading {}", shared_xsd_path.display()))?;
    let shared_src = emit::emit_shared_types(
        &shared_xsd,
        "References/.../OfficeOpenXML-XMLSchema-Transitional/shared-commonSimpleTypes.xsd",
    )?;
    write_generated(&out_dir.join("shared.rs"), &shared_src)?;

    // 3. the generated module root
    let mod_src = "// @generated by xtask — do not edit.\n\
         //! Generated OOXML type modules. Regenerate with `cargo run -p xtask -- codegen`.\n\n\
         pub mod namespaces;\n\
         pub mod shared;\n"
        .to_owned();
    write_generated(&out_dir.join("mod.rs"), &mod_src)?;

    // 4. coverage manifest (which schemas are generated vs pending)
    write_plain(
        &root.join("crates/mjx-ooxml-types/COVERAGE.md"),
        &coverage_manifest(&shared_xsd)?,
    )?;

    println!("codegen: wrote namespaces.rs, shared.rs, mod.rs, COVERAGE.md");
    Ok(())
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is the xtask crate dir; the workspace root is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent dir")
        .to_path_buf()
}

/// Formats source with rustfmt, then writes it.
fn write_generated(path: &Path, src: &str) -> Result<()> {
    let formatted = rustfmt(src).with_context(|| format!("formatting {}", path.display()))?;
    write_plain(path, &formatted)
}

fn write_plain(path: &Path, contents: &str) -> Result<()> {
    std::fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

fn rustfmt(src: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("spawning rustfmt (is the `rustfmt` component installed?)")?;
    child
        .stdin
        .take()
        .context("rustfmt stdin")?
        .write_all(src.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        bail!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8(output.stdout).context("rustfmt produced non-UTF-8")
}

fn coverage_manifest(shared_xsd: &[u8]) -> Result<String> {
    let types = xsd::parse_simple_types(shared_xsd)?;
    let mut generated: Vec<&str> = types
        .iter()
        .map(|t| t.name.as_str())
        .filter(|n| !spec::SKIP_TYPES.contains(n))
        .collect();
    generated.sort_unstable();

    let mut s = String::new();
    s.push_str("# Generated-type coverage\n\n");
    s.push_str("_Generated by `cargo run -p xtask -- codegen`; do not edit by hand._\n\n");
    s.push_str("| Schema | Status |\n|---|---|\n");
    s.push_str("| shared-commonSimpleTypes | generated |\n");
    for schema in ["wml", "sml", "pml", "dml-main", "shared-math"] {
        s.push_str(&format!("| {schema} | pending |\n"));
    }
    s.push_str(&format!(
        "\n## shared-commonSimpleTypes — {} types generated\n\n",
        generated.len()
    ));
    for name in generated {
        s.push_str(&format!("- `{name}`\n"));
    }
    Ok(s)
}
