//! Generates the namespace-URI table from every schema's `targetNamespace` (both worlds).

// This module emits source code; explicit trailing newlines in `write!` lay out the generated Rust.
#![allow(clippy::write_with_newline)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result};

use crate::codegen::naming::screaming_snake;
use crate::codegen::xsd::target_namespace;

/// Reads `*.xsd` files in a directory, returning `stem → targetNamespace`, sorted by stem.
fn read_dir_namespaces(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut map = BTreeMap::new();
    let entries = std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))?;
    for entry in entries {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("xsd") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .context("bad file name")?
            .to_owned();
        let bytes = std::fs::read(&path)?;
        map.insert(stem, target_namespace(&bytes)?);
    }
    Ok(map)
}

/// Renders the `namespaces` module from the Strict and Transitional schema directories.
pub fn generate(strict_dir: &Path, transitional_dir: &Path) -> Result<String> {
    let strict = read_dir_namespaces(strict_dir)?;
    let transitional = read_dir_namespaces(transitional_dir)?;

    // Key by SCREAMING_SNAKE constant name (derived from the shared file stem), sorted.
    let mut rows: BTreeMap<String, (Option<String>, String)> = BTreeMap::new();
    for (stem, trans_uri) in &transitional {
        let name = screaming_snake(stem);
        let strict_uri = strict.get(stem).cloned();
        rows.insert(name, (strict_uri, trans_uri.clone()));
    }

    let mut s = String::new();
    s.push_str(
        "// @generated by xtask — do not edit.\n\
         //\n\
         // Regenerate with: cargo run -p xtask -- codegen\n\
         // Source: References/ schema targetNamespace declarations (Strict + Transitional).\n\
         //! OOXML namespace URIs, paired across the Strict (ISO) and Transitional worlds.\n\n",
    );
    s.push_str(
        "/// A schema's namespace URI in each OOXML conformance world.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct SchemaNamespace {\n\
         \x20   /// The Strict (ISO-29500) namespace URI, if the schema exists in the Strict set.\n\
         \x20   pub strict: Option<&'static str>,\n\
         \x20   /// The Transitional namespace URI — what Microsoft Office emits.\n\
         \x20   pub transitional: &'static str,\n\
         }\n\n\
         impl SchemaNamespace {\n\
         \x20   /// Returns the namespace URI to use for the given world (falls back to Transitional\n\
         \x20   /// when a Strict variant does not exist, e.g. legacy VML).\n\
         \x20   #[must_use]\n\
         \x20   pub fn for_strict(&self, strict: bool) -> &'static str {\n\
         \x20       if strict { self.strict.unwrap_or(self.transitional) } else { self.transitional }\n\
         \x20   }\n\
         }\n\n",
    );

    for (name, (strict_uri, trans_uri)) in &rows {
        let strict_lit = match strict_uri {
            Some(u) => format!("Some({u:?})"),
            None => "None".to_owned(),
        };
        let _ = write!(
            s,
            "/// Namespace for the `{name}` schema.\n\
             pub const {name}: SchemaNamespace = SchemaNamespace {{ strict: {strict_lit}, transitional: {trans_uri:?} }};\n\n"
        );
    }

    // A slice of everything, for iteration.
    s.push_str(
        "/// Every schema namespace, sorted by name.\npub const ALL: &[SchemaNamespace] = &[\n",
    );
    for name in rows.keys() {
        let _ = writeln!(s, "    {name},");
    }
    s.push_str("];\n");

    Ok(s)
}
