import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One autogenerated sidebar, and deliberately not a list of pages.
 *
 * The content tree under `docs/` is written by `cargo run -p xtask -- docs-site` and is git-ignored,
 * so a hand-written sidebar here would be a second statement of a page set that already has one —
 * the `include_str!` graph in `crates/mjx-ooxml/src/guide.rs`. Autogeneration reads the tree the
 * generator wrote, including the `_category_.json` it writes per section and the `sidebar_position`
 * in each page's front matter, so a page added to the guide appears here with nothing edited.
 */
const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
