//! A counting global allocator: live bytes, a high-water mark, and a hard ceiling.
//!
//! **Test-only and developer-tooling-only.** No shipped crate depends on this one, and nothing here
//! is reachable from a published artefact.
//!
//! # Why this is a crate rather than a module
//!
//! MJXOFF-146 wrote this allocator inside `xtask/src/fuzz/`, where the fuzz campaign needed a
//! *measured* memory ceiling instead of an OOM kill. MJXOFF-95 needs the same instrument for a
//! different question — "does a sheet with one populated cell allocate for one cell, or for the
//! grid it could address?" — from a test binary in `mjx-sml`, which sits in the shared-markup tier.
//!
//! `xtask` is a host-only developer binary and **nothing may depend on it**
//! (`xtask/tests/layering.rs::nothing_depends_on_a_binding_or_on_the_tooling`), so the instrument
//! could not be consumed where the second question is asked. The two available answers were to
//! write a second `unsafe impl GlobalAlloc` — which is the thing a workspace with
//! `unsafe_code = "deny"` should least like to have two of — or to give the one implementation a
//! home both callers can reach. This is that home; `xtask::fuzz` and `mjx-sml`'s allocation gate are
//! its two consumers, and the `unsafe` block below is still the only one in the workspace outside
//! the two binding crates.
//!
//! # What it can and cannot see
//!
//! It counts **bytes the program asked the allocator for**, which is a different question from peak
//! resident set (`xtask::corpus::memory` reads the kernel's `VmHWM` for that). The difference
//! matters in both directions, and each direction is the right instrument for a different gate:
//!
//! * A `Vec::with_capacity(1_048_576)` whose pages are never written is **fully visible here** and
//!   may be nearly invisible to `VmHWM`, because the kernel never has to back untouched pages. That
//!   is exactly the defect a sparse-store gate exists to catch, which is why such a gate must use
//!   this and not resident set.
//! * Memory the allocator holds without returning it to the operating system is visible to `VmHWM`
//!   and invisible here. That is why a "how much does opening this real file cost" figure is read
//!   from the kernel instead.
//!
//! # Safety
//!
//! `unsafe_code` is `deny` workspace-wide and this module `allow`s it locally — the other places
//! that do are the two binding crates, where every `unsafe` block is generated by `#[pyclass]` or
//! `#[wasm_bindgen]`. The justification here is narrow and checkable: the one `unsafe` block per
//! method forwards, unchanged, to [`System`], the allocator that would have served the request
//! anyway. Every `ptr`, `layout` and size argument is passed through untouched, so each call has
//! exactly the contract `System`'s does and this type adds no new obligation on the caller. Nothing
//! here dereferences a pointer, and no pointer is constructed. The bookkeeping around the forwarded
//! call is safe code operating on atomics.

use std::alloc::{GlobalAlloc, Layout, System};
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::OnceLock;

/// Bytes currently allocated by the process.
static LIVE: AtomicUsize = AtomicUsize::new(0);
/// The high-water mark since the last [`reset_peak`].
static PEAK: AtomicUsize = AtomicUsize::new(0);
/// The hard ceiling, in bytes. `usize::MAX` disables it.
static HARD_CEILING: AtomicUsize = AtomicUsize::new(usize::MAX);
/// What the abort message tells the operator to look at. Set by the first [`set_hard_ceiling`].
static CEILING_NOTE: OnceLock<&'static str> = OnceLock::new();
/// Set once the hard ceiling has fired, so the abort path cannot re-enter itself.
static ABORTING: AtomicBool = AtomicBool::new(false);

/// A [`System`] allocator that keeps a live-byte count and a high-water mark, and aborts the process
/// rather than let a single execution run away with the machine.
///
/// Register it with `#[global_allocator] static ALLOCATOR: Counting = Counting;` in the **binary**
/// that measures. A global allocator is process-wide, so a measurement made in a binary that runs
/// other work at the same time measures that other work too — which is why the gates using this
/// each get a target of their own.
#[derive(Debug)]
pub struct Counting;

impl Counting {
    /// Records `bytes` more live, updating the peak, and aborts past the hard ceiling.
    #[inline]
    fn note_allocation(bytes: usize) {
        let live = LIVE.fetch_add(bytes, Ordering::Relaxed) + bytes;
        PEAK.fetch_max(live, Ordering::Relaxed);
        if live > HARD_CEILING.load(Ordering::Relaxed) && !ABORTING.swap(true, Ordering::Relaxed) {
            // Deliberately terse and allocation-free: we are inside the allocator, past its ceiling,
            // and anything richer risks recursing back into this function. `OnceLock::get` is an
            // atomic load of an already-stored `&'static str`; it allocates nothing.
            let note = CEILING_NOTE.get().copied().unwrap_or_default();
            eprintln!("\nallocation: hard memory ceiling crossed. {note} Aborting.");
            std::process::abort();
        }
    }

    /// Records `bytes` freed.
    #[inline]
    fn note_deallocation(bytes: usize) {
        LIVE.fetch_sub(bytes, Ordering::Relaxed);
    }
}

// SAFETY: see the module docs. Each method forwards its arguments unchanged to `System`, which is
// the allocator that would otherwise have served the call, so the safety contract is exactly
// `System`'s and no additional obligation is introduced. No pointer is dereferenced or synthesised
// here; the counting is safe code on atomics.
#[allow(unsafe_code)]
unsafe impl GlobalAlloc for Counting {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let ptr = unsafe { System.alloc(layout) };
        if !ptr.is_null() {
            Self::note_allocation(layout.size());
        }
        ptr
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        unsafe { System.dealloc(ptr, layout) };
        Self::note_deallocation(layout.size());
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        let ptr = unsafe { System.alloc_zeroed(layout) };
        if !ptr.is_null() {
            Self::note_allocation(layout.size());
        }
        ptr
    }

    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        let new_ptr = unsafe { System.realloc(ptr, layout, new_size) };
        if !new_ptr.is_null() {
            Self::note_deallocation(layout.size());
            Self::note_allocation(new_size);
        }
        new_ptr
    }
}

/// Arms the hard ceiling at `bytes`, with `note` appended to the abort message so the operator knows
/// which artefact names the cause.
///
/// The ceiling may be re-armed at any figure; the **note is recorded once**, by the first call, for
/// the same reason the abort path is terse — it is read from inside the allocator, so it may not
/// allocate, and a `OnceLock<&'static str>` is the cheapest thing that cannot.
pub fn set_hard_ceiling(bytes: usize, note: &'static str) {
    let _ = CEILING_NOTE.set(note);
    HARD_CEILING.store(bytes, Ordering::Relaxed);
}

/// Resets the high-water mark to the current live figure, and returns that figure.
///
/// Call it immediately before the code under measurement so that the peak read afterwards belongs to
/// that code rather than to whatever ran before it.
pub fn reset_peak() -> usize {
    let live = LIVE.load(Ordering::Relaxed);
    PEAK.store(live, Ordering::Relaxed);
    live
}

/// The high-water mark since the last [`reset_peak`].
#[must_use]
pub fn peak() -> usize {
    PEAK.load(Ordering::Relaxed)
}

/// Bytes currently allocated and not yet freed.
///
/// The difference between two readings around a construction is what that construction *retains* —
/// which is the figure a "this store must cost O(populated cells)" gate is about, as distinct from
/// the [`peak`] it passed through on the way.
#[must_use]
pub fn live() -> usize {
    LIVE.load(Ordering::Relaxed)
}
