//! The committed design-token artefacts are derived, not hand-written (MJXOFF-156).
//!
//! # Why this runs the binary
//!
//! `xtask` is a binary crate, so an integration test cannot reach its generator directly. It can
//! run it: `CARGO_BIN_EXE_xtask` is the compiled binary this test was built alongside, and
//! `tokens --check` regenerates all three artefacts in memory and refuses if what is on disk is
//! not exactly what `docs/client-platform/data/tokens.json` produces. Running the real command is
//! also the stronger gate — a helper this test called instead could drift from the one a developer
//! types.
//!
//! # What this proves and what it does not
//!
//! It proves **derivation**: nobody hand-edited an artefact, and nobody edited the source without
//! regenerating. It does *not* prove the three agree with each other — an emitter that rendered a
//! colour one way for CSS and another for TypeScript would regenerate perfectly. That is
//! `crates/mjx-tokens/tests/artefacts_agree.rs`.
//!
//! Proved by mutation: change one hexadecimal digit in `ui/tokens/tokens.css` and
//! [`the_committed_artefacts_are_exactly_what_the_source_generates`] goes red naming the file, the
//! line and both spellings of the value.

use std::path::{Path, PathBuf};
use std::process::Command;

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent directory")
        .to_path_buf()
}

fn run_tokens(arguments: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_xtask"))
        .arg("tokens")
        .args(arguments)
        .current_dir(workspace_root())
        .output()
        .expect("running the xtask binary")
}

#[test]
fn the_committed_artefacts_are_exactly_what_the_source_generates() {
    let output = run_tokens(&["--check"]);
    assert!(
        output.status.success(),
        "`cargo run -p xtask -- tokens --check` failed. The committed artefacts have drifted from \
         the source; run `cargo run -p xtask -- tokens` and commit the result.\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    let reported = String::from_utf8_lossy(&output.stdout);
    assert!(
        reported.contains("3 artefacts match"),
        "`--check` must say what it checked, so a run that checked nothing is visible: {reported}"
    );
}

/// The three artefacts are committed, so a checkout has to contain them. A `--check` that passed
/// because it compared two empty strings would be exactly the failure this ticket names.
#[test]
fn all_three_artefacts_are_committed_and_carry_their_generated_header() {
    let root = workspace_root();
    for relative in [
        "ui/tokens/tokens.css",
        "ui/tokens/tokens.ts",
        "crates/mjx-tokens/src/generated.rs",
    ] {
        let path = root.join(relative);
        let contents = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        assert!(
            contents.len() > 2_000,
            "{relative} is {} bytes, which cannot be this token set",
            contents.len()
        );
        assert!(
            contents.contains("@generated by `cargo run -p xtask -- tokens`"),
            "{relative} does not say it is generated"
        );
        assert!(
            contents.contains("--color-green"),
            "{relative} does not mention a token this platform defines"
        );
    }
}

/// Regenerating twice produces the same tree — the idempotence the committed-output doctrine rests
/// on. Written as *generate, then check*: if the first run were not deterministic, the second would
/// see a different file than the one just written.
#[test]
fn regenerating_twice_produces_an_identical_tree() {
    let first = run_tokens(&[]);
    assert!(
        first.status.success(),
        "regeneration failed: {}",
        String::from_utf8_lossy(&first.stderr)
    );
    let second = run_tokens(&["--check"]);
    assert!(
        second.status.success(),
        "a second run disagreed with the first: {}{}",
        String::from_utf8_lossy(&second.stdout),
        String::from_utf8_lossy(&second.stderr),
    );
}

#[test]
fn an_unknown_argument_is_refused_rather_than_ignored() {
    let output = run_tokens(&["--force"]);
    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("unknown arguments"),
        "a mistyped flag must not be read as `write the files`"
    );
}
