//! **Which crates allow `unsafe`, held to the tree rather than to a sentence** (audit pass 10, D2).
//!
//! # The claim that drifted, and why it was worse than a typo
//!
//! `README.md` said, until this pass:
//!
//! > The two binding crates are the only ones in the workspace that carry `#![allow(unsafe_code)]`,
//! > for macro-generated `unsafe` only; **CI greps them to keep that claim true.**
//!
//! It had been false since MJXOFF-163. There are **four** crates, and `CLAUDE.md` has said so for
//! two children — `mjx-paint` at the platform boundary and `mjx-allocation-counter`'s
//! `unsafe impl GlobalAlloc` are the other two. The half-sentence at the end is what makes it worth
//! a test rather than an edit: it told a reader the claim was mechanically guarded, and the grep it
//! points at covers `bindings/*/src`, `bindings/*/tests` and `crates/mjx-paint/src` — which is a
//! guard on *what the allowance is used for*, and never a guard on *who has one*.
//!
//! A claim that drifted once will drift again, so this is the guard on who has one.
//!
//! # What it does and does not assert
//!
//! It asserts the **exact set** of files carrying the attribute. Not a floor: a `>=` would pass for
//! a scan that quietly stopped reading, and it would pass for a fifth crate quietly acquiring one,
//! which is the case that matters. A new allowance therefore fails here, and the failure names the
//! three places that have to move together — `README.md`, `CLAUDE.md`, and CI's grep.
//!
//! `crates/mjx-paint/tests/the_seam_holds.rs` is the deeper gate for the painter (exactly one
//! marked `unsafe` line, and no unmarked one); this is the shallower gate for the whole workspace,
//! and the two are about different questions.

use std::path::{Path, PathBuf};

/// The attribute, in both spellings a crate can write it.
///
/// Split so that this file's own source does not match the scan it performs — every `.rs` file in
/// the workspace is read, this one included.
fn attribute_forms() -> [String; 2] {
    let inner = format!("#![{}(unsafe_code)]", "allow");
    let outer = format!("#[{}(unsafe_code)]", "allow");
    [inner, outer]
}

/// Every file in the workspace that carries the allowance, relative to the repository root.
///
/// **This is the whole list, and it is exact.** Adding an entry is a decision with a written safety
/// justification and three documents to move; it is not a test to update on the way past.
const ALLOWED: &[&str] = &[
    // Rank 5.5, the platform boundary (MJXOFF-163). Exactly one hand-written `unsafe` block: the
    // surface created from a raw window handle the shell supplied. No safe API can promise that the
    // handle outlives the surface made from it — that is the window system's invariant and the
    // shell's to keep — and it is stated as the caller's obligation on `DesktopWindow::new`. Every
    // other `unsafe` in the crate's tree belongs to `wgpu`.
    "crates/mjx-paint/src/lib.rs",
    // Outside the graph, dependency-free. One `unsafe impl GlobalAlloc` whose every method forwards
    // its arguments unchanged to `std::alloc::System`, so it adds no obligation the system
    // allocator does not already carry. It is what gives the fuzz campaign a *measured* memory
    // ceiling instead of an OOM kill, and `mjx-sml`'s cell-store gate a byte bound instead of an
    // assertion by inspection.
    "crates/mjx-allocation-counter/src/lib.rs",
    // Rank 5.0. No hand-written `unsafe`; every block is generated by `#[pyclass]`.
    "bindings/mjx-python/src/lib.rs",
    // Rank 5.0. The same, for `#[wasm_bindgen]`.
    "bindings/mjx-wasm/src/lib.rs",
    // The same crate again, in the suite that runs the binding inside a real WebAssembly runtime.
    // **Four crates and five files**, which is the distinction `README.md` now draws explicitly:
    // the audit that produced this test found this occurrence and the audit before it did not.
    "bindings/mjx-wasm/tests/browser.rs",
];

/// The crates those files belong to, for the message.
const ALLOWED_CRATES: &[&str] = &[
    "mjx-paint",
    "mjx-allocation-counter",
    "bindings/mjx-python",
    "bindings/mjx-wasm",
];

fn repository() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits one level below the repository root")
        .to_path_buf()
}

/// Every `.rs` file under `root`, recursively, skipping `target/` and anything hidden.
fn rust_files(root: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut pending = vec![root.to_path_buf()];
    while let Some(current) = pending.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if name.starts_with('.') || name == "target" || name == "References" {
                continue;
            }
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|suffix| suffix == "rs") {
                found.push(path);
            }
        }
    }
    found.sort();
    found
}

#[test]
fn exactly_four_crates_allow_unsafe_and_the_documentation_names_them() {
    let root = repository();
    let forms = attribute_forms();
    let mut carrying: Vec<String> = Vec::new();
    let mut scanned = 0_usize;

    for path in rust_files(&root) {
        scanned += 1;
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let carries = text.lines().any(|line| {
            let code = line.trim_start();
            // A line that only *mentions* the attribute is prose or an assertion about it — the two
            // seam gates and this file all quote it — so only a line that *is* the attribute counts.
            forms.iter().any(|form| code == form)
        });
        if carries {
            carrying.push(
                path.strip_prefix(&root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
    carrying.sort();

    assert!(
        scanned > 300,
        "only {scanned} Rust files were scanned, which cannot be this workspace — the walk is \
         recursive and something has stopped it"
    );

    let mut expected: Vec<String> = ALLOWED.iter().map(|it| (*it).to_owned()).collect();
    expected.sort();
    assert_eq!(
        carrying,
        expected,
        "the set of files carrying `#![allow(unsafe_code)]` has changed. `README.md` names \
         {} crates and {} files, `CLAUDE.md` names the same four with a justification each, and \
         `.github/workflows/ci.yml` greps `bindings/*/src`, `bindings/*/tests` and \
         `crates/mjx-paint/src` — a new allowance moves all three, and needs a written safety \
         justification of its own. **No crate in the document graph may acquire one.**",
        ALLOWED_CRATES.len(),
        ALLOWED.len()
    );
}

#[test]
fn the_readme_states_the_count_this_test_holds() {
    let readme = std::fs::read_to_string(repository().join("README.md")).expect("README.md");
    assert!(
        readme.contains("**Four crates**") && readme.contains("**five files**"),
        "`README.md`'s architecture section has to state the count this test asserts, or the two \
         drift apart again — which is what audit pass 10 found: the sentence said *the two binding \
         crates are the only ones*, and had been false since MJXOFF-163"
    );
    for name in ALLOWED_CRATES {
        let short = name.rsplit('/').next().unwrap_or(name);
        assert!(
            readme.contains(short),
            "`README.md` no longer names `{short}` among the crates that allow `unsafe`"
        );
    }
    // And the claim that used to be there is gone, rather than sitting a paragraph further down.
    assert!(
        !readme.contains("The two binding crates are the only ones"),
        "the superseded sentence is back in `README.md`"
    );
}

/// The other half of `CONTRIBUTING.md`'s drift (audit pass 10, D4).
///
/// It said *"Pure-Rust dependencies only in shipped crates"*, which MJXOFF-163 superseded:
/// `mjx-paint` is a shipped crate and it links Vulkan. `CLAUDE.md` was amended and `CONTRIBUTING.md`
/// was not, so a contributor reading the file addressed to contributors got the pre-MJXOFF-163 rule.
#[test]
fn contributing_states_the_pure_rust_rule_the_way_claude_md_does() {
    let contributing =
        std::fs::read_to_string(repository().join("CONTRIBUTING.md")).expect("CONTRIBUTING.md");
    assert!(
        contributing.contains("in the document graph"),
        "`CONTRIBUTING.md` has to scope the pure-Rust rule to the **document graph**, as `CLAUDE.md` \
         does. `mjx-paint` at rank 5.5 is a shipped crate that links the platform's graphics API, \
         and a rule phrased as *\"shipped crates\"* is one a contributor would read as forbidding it"
    );
    assert!(
        !contributing.contains("Pure-Rust dependencies only in shipped crates"),
        "the superseded phrasing is back in `CONTRIBUTING.md`"
    );
    assert!(
        contributing.contains("mjx-paint"),
        "the rule has one named exception and `CONTRIBUTING.md` should say which crate it is"
    );
}
