//! `@mjx/ooxml` — the whole PowerPoint surface, as WebAssembly with TypeScript types.
//!
//! ```js
//! import init, { Deck, detectFormat, Format } from "@mjx/ooxml";
//!
//! await init();
//! const bytes = new Uint8Array(await file.arrayBuffer());
//! if (detectFormat(bytes) !== Format.Presentation) throw new Error("not a deck");
//!
//! const deck = Deck.open(bytes);
//! try {
//!   deck.setShapeTextContent(0, 0, "Quarterly results");
//!   const blob = new Blob([deck.save()], {
//!     type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
//!   });
//! } finally {
//!   deck.free();
//! }
//! ```
//!
//! # What this crate is
//!
//! A thin, complete projection of [`mjx_ooxml`] — 257 `Deck` methods and the classes their
//! arguments and results are made of. It adds no behaviour: every method calls exactly one method
//! one layer down, and every class wraps exactly one value. What it *does* add is the shape a
//! TypeScript caller expects — camelCase, `Uint8Array`, real `Error` objects, and a bare `number`
//! where Rust would take an `impl Into<Surface>`.
//!
//! The library is **bytes in and bytes out**: no filesystem, no clock, no threads, no random number
//! generator, no network. That is why it runs unchanged in a browser, and why `File` and `Blob`
//! stay on the JavaScript side of the boundary.
//!
//! # `free()` is mandatory
//!
//! Every class here owns memory on the wasm heap, which JavaScript's garbage collector does not
//! manage. **A `Deck` you do not `free()` is leaked** — see [`deck`] for the details and the
//! `try`/`finally` shape. `wasm-bindgen` also emits `[Symbol.dispose]`, so `using deck = …` works
//! wherever explicit resource management is available.
//!
//! # Naming
//!
//! Methods are camelCase, from an explicit `js_name` on every one; classes and enumeration members
//! keep their Rust PascalCase spelling. The mapping is mechanical — each underscore removed, the
//! following letter capitalised — so `set_shape_run_properties` is `setShapeRunProperties` and
//! nothing else changes.
//!
//! Two shapes differ from the Python binding, and both are forced by the platform rather than
//! chosen. A `Range<u32>` argument becomes two numbers (`…Start`, `…End`), because JavaScript has
//! no half-open range. And a format's five accessors are free functions rather than properties,
//! because a `wasm-bindgen` enumeration is a number in JavaScript and cannot carry a getter — see
//! [`mod@format`].
//!
//! # No serde
//!
//! Every class here is hand-written. `serde-wasm-bindgen` would need `Serialize`/`Deserialize`
//! derives on `FillSpec`, `ColorSpec`, `CharacterPropertiesSpec` and their friends, which live in
//! the **shipped** `mjx-dml` — contradicting the workspace's settled hand-written-de/serialization
//! decision — and would hand TypeScript structurally-typed objects with no methods and no
//! discriminated-union guarantees.
//!
//! # Safety
//!
//! This crate carries `#![allow(unsafe_code)]`, against a workspace that denies it. The
//! justification, in full:
//!
//! **There is no hand-written `unsafe` in this crate.** Every `unsafe` block reaching the compiler
//! is generated by `#[wasm_bindgen]` — the macro that owns the JavaScript ABI contract, implements
//! the `FromWasmAbi`/`IntoWasmAbi` conversions, and manages the pointers a JavaScript object holds
//! into the wasm heap. The allowance exists because those expansions land in this crate's token
//! stream, not because this crate performs unsafe operations of its own. CI enforces the claim:
//! `.github/workflows/ci.yml` greps `bindings/*/src` for `unsafe` outside this comment and fails if
//! it finds any.
//!
//! # Panics
//!
//! **Every fallible path returns a `Result<_, JsValue>`.** A Rust panic in a wasm module aborts the
//! instance — every later call throws `unreachable executed` and the only remedy is to reload the
//! module — so a panic here is not a recoverable error but a dead module. There is no `unwrap`, no
//! `expect`, and no indexing that can go out of range in this crate.

// See the module documentation above: no hand-written `unsafe` appears in this crate; the
// allowance covers only the blocks the `wasm_bindgen` attribute macro generates.
#![allow(unsafe_code)]

#[macro_use]
mod support;

// Every module is public so the crate is usable as an ordinary Rust library too — `cargo test`
// builds it as an `rlib` — and so that `unreachable_pub` has nothing to complain about: a
// `#[wasm_bindgen]` type must be nameable from wherever the generated code refers to it.
pub mod address;
pub mod charts;
pub mod content;
pub mod deck;
pub mod enums;
pub mod errors;
pub mod format;
pub mod geometry;
pub mod measures;
pub mod paint;
pub mod tables;
pub mod text;
pub mod three_d;

/// The version of `mjx-ooxml` this package was built from.
#[wasm_bindgen::prelude::wasm_bindgen(js_name = "version")]
#[must_use]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_owned()
}
