/**
 * Author colours — **eight of them, from the token palette, and distinguishable to a reader who
 * cannot tell red from green.**
 *
 * ## The trap, stated as a number
 *
 * > Author colours generated by hue rotation look distinct to a normal-vision reviewer and merge
 * > for a colour-blind one.
 *
 * They do, and `dev/colour-vision.ts` measures by how much. Eight hues evenly spaced around the
 * wheel at one saturation and one lightness — the implementation everybody writes — are 9.15 apart
 * in CIEDE2000 to a normal-vision reader and **0.00 apart** under simulated deuteranopia: the first
 * two are, after simulation, the *same colour, to the byte*. Nothing about that is visible in a
 * story, in a screenshot, or to the person who wrote it.
 *
 * So the eight below were not chosen; they were **searched for**, over the whole brand palette,
 * maximising the smallest CIEDE2000 distance across normal vision and all three common
 * deficiencies at once. `tests/annotation.test.ts` re-runs that measurement rather than trusting
 * this comment: the floor is [`authorColourMinimumDistance`], the light set clears it at 6.17 and
 * the dark set at 7.16, and the naive rotation is asserted to fail the same gate.
 *
 * ## Two tokens per slot, exactly as MJXOFF-192's reference colours are
 *
 * A slot is an **identity** — *the first author*, *the second* — and each scheme spells it with the
 * token that works there. `color.ink` is the whole point: it is 11.88 : 1 on the light surface and
 * **1.00 : 1** on the dark one, because the dark surface *is* `color.ink`. One token per slot would
 * have made an author invisible in whichever scheme nobody checked.
 *
 * The pairing is family-consistent in all eight slots — an author who is honey in light is honey in
 * dark — which was not free: a search that ignored families scored slightly higher and moved one
 * author from rose to olive when a reader toggled the theme.
 *
 * ## ⚠ An author colour is never a text colour, and that is a palette measurement
 *
 * Word colours the author's *name*. This catalogue cannot: the brand palette contains **six**
 * colours that reach 4.5 : 1 on the light surface, and two of them are the same green. Eight
 * author-coloured names at body-text contrast do not exist to be chosen. So the colour is carried
 * as a **band and a dot** — an area with a border around it, which is how WCAG treats adjacent
 * colours that are delineated — and the author's name is drawn in `theme.*.text-primary` like every
 * other name in the catalogue. [`authorColourVisibilityMinimum`] is the floor the band itself must
 * clear against its own scheme's surface, and it is 2 : 1 rather than 3 : 1 for that reason,
 * measured and asserted in both schemes.
 *
 * ## Node-importable
 *
 * Token *paths*, never colours: nothing here is a literal value, which is what lets it live in
 * `src/` at all.
 */

import type { TokenPath } from '../tokens/resolver.ts';

/** A colour a card's author band can be drawn in, named once and resolved per scheme. */
export interface AuthorColourSlot {
  /** What the slot is called, in the contract and in a story's readout. */
  readonly name: string;
  /** The token drawn on a light surface. */
  readonly light: TokenPath;
  /** The token drawn on a dark one. */
  readonly dark: TokenPath;
}

/**
 * The eight, in the order a document's authors are given them.
 *
 * Eight because that is what the ticket asks to be proved and what the palette can actually spell:
 * a ninth slot drops the light set's floor from 6.17 to 5.41, which is close enough to the gate to
 * be a colour nobody had measured. A document with more than eight authors reuses the ring from the
 * beginning, which [`assignAuthorColours`] states rather than hides.
 */
export const authorColourSlots: readonly AuthorColourSlot[] = [
  { name: 'moss', light: 'color.greenDeep', dark: 'color.greenLifted' },
  { name: 'fern', light: 'color.greenLifted', dark: 'color.greenDeep' },
  { name: 'bronze', light: 'color.honeyDeep', dark: 'color.honey' },
  { name: 'amber', light: 'color.honey', dark: 'color.honeyLine' },
  { name: 'clay', light: 'color.clay', dark: 'color.clay' },
  { name: 'rose', light: 'color.warm', dark: 'color.warm' },
  { name: 'ink', light: 'color.ink', dark: 'color.card' },
  { name: 'sage', light: 'color.inkSoft', dark: 'color.inkSoft' },
];

/**
 * The smallest CIEDE2000 distance any two author colours may sit at, under **any** of the four ways
 * of seeing them.
 *
 * Five, and it is a published landmark rather than a taste: 1.0 is the definition of a just
 * noticeable difference under ideal conditions and about 2.3 is one in practice, so 5 is a
 * comfortable *"these are different colours"* at a glance — which is what a reader scanning a
 * margin column is doing. The measured floors are 6.17 (light) and 7.16 (dark).
 */
export const authorColourMinimumDistance = 5;

/**
 * The smallest contrast ratio an author band may sit at against its own scheme's surface.
 *
 * ⚠ **2 : 1, not 3 : 1, and the difference is a finding rather than a relaxation.** Only nine
 * colours in the whole palette reach 2 : 1 on the light surface and **none** of the eight-colour
 * subsets reach 2.5 : 1, so a 3 : 1 floor would not have left eight author colours to choose
 * between — it would have left six. The band is a filled area with a border around it and carries
 * no text, so WCAG's non-text 3 : 1 is not the rule that binds it; what binds it is that a fill
 * indistinguishable from its surface is not a fill. Both numbers are asserted, in both schemes.
 */
export const authorColourVisibilityMinimum = 2;

/** The custom property a slot's colour is read from. Written by the sheet, read by the gate. */
export function authorColourProperty(slot: number): string {
  return `--mjx-author-colour-${String(slot)}`;
}

/**
 * Which colour each author gets: **by first appearance, never by hash.**
 *
 * ⚠ This is the decision in this file most likely to be undone by somebody being clever. Hashing a
 * name is stable across documents, needs no roster and is one line — and with eight slots and eight
 * authors it collides with probability *1 − 8!/8⁸ = 99.76%*. Two authors sharing a colour is the
 * exact failure the CVD search above exists to prevent, arrived at from the other direction, and it
 * would happen in practically every real document. `dev/colour-vision.ts` ships `naiveHashSlot` as
 * the positive control and `tests/annotation.test.ts` measures the collision rate over it rather
 * than quoting this number.
 *
 * Order of first appearance is what Word itself does, and it guarantees the first eight authors are
 * distinct. The cost is honest and worth stating: an author's colour is stable *for a document*,
 * not across documents, because it depends on who else is in the file. Nothing short of a server
 * can do better, and this project has no presence layer by design.
 */
export function assignAuthorColours(authors: readonly string[]): ReadonlyMap<string, number> {
  const slots = new Map<string, number>();
  for (const author of authors) {
    const key = authorKey(author);
    if (key === '' || slots.has(key)) continue;
    slots.set(key, slots.size % authorColourSlots.length);
  }
  return slots;
}

/** The author's identity, folded the way a document's own metadata varies: trimmed and case-less. */
export function authorKey(author: string): string {
  return author.trim().replaceAll(/\s+/g, ' ').toLocaleLowerCase();
}

/**
 * The slot an author holds in a roster, or the first slot when the roster does not name them.
 *
 * The fallback is deliberately *not* a hash: a card rendered outside a pane has no roster, and
 * giving it an arbitrary-looking colour would make the same author look different in the two
 * places. It gets the first slot and the pane corrects it, which is visible rather than plausible.
 */
export function authorColourFor(author: string, roster: ReadonlyMap<string, number>): number {
  return roster.get(authorKey(author)) ?? 0;
}

/**
 * The initials a card shows in its dot, from whatever the document carried.
 *
 * Word stores an initials string on a legacy comment and this is what stands in when it did not, so
 * it follows the same rule: the first letter of the first and last words, upper-cased. A one-word
 * name gives one letter; an empty name gives none, and the dot is then a plain colour swatch rather
 * than a circle with a stray character in it.
 */
export function authorInitials(author: string): string {
  const words = author.trim().split(/\s+/u).filter((word) => word !== '');
  const first = words[0];
  if (first === undefined) return '';
  const last = words.length > 1 ? words[words.length - 1] : undefined;
  const letters = last === undefined ? [first[0]] : [first[0], last[0]];
  return letters
    .filter((letter): letter is string => letter !== undefined)
    .join('')
    .toLocaleUpperCase();
}
