import { expect, test } from '@playwright/test';

import { builtStories, openStory } from './support.ts';

/**
 * Visual regression, on the plates where a pixel comparison actually means something.
 *
 * ## Why not every story
 *
 * A screenshot of antialiased text is a function of the machine's font stack, its hinting settings
 * and its subpixel geometry, none of which this repository controls. A "visual regression" suite
 * built on that produces a red build on a developer's laptop for reasons that have nothing to do
 * with the change, and the response to a flaky gate is always to stop reading it — at which point
 * the real regressions go through too. This project's own doctrine says the same thing about
 * golden images: the value is in *locking an approved appearance*, and an appearance that is not
 * stable was never approved.
 *
 * So the snapshots here are the text-free, token-driven plates: colour, geometry, radii, borders
 * and the ink-tinted shadow. Those are exactly what a token change moves, and they render
 * identically on any machine running the same pinned Chromium — which is what `@playwright/test`
 * guarantees and a system browser does not.
 *
 * A component's *layout* under a container change is not covered here either; that is
 * `container.spec.ts`, which asserts on the computed band rather than on pixels, and is the better
 * instrument for it.
 */

/**
 * ⚠ **These baselines were generated by the code under test and no person has approved them.**
 *
 * `mjx-render-oracle` says the same thing about its own committed baselines — every one is stamped
 * `approver = generator`, which is a real approval *record* and not a human review. The same is
 * true here, and it will stay true until the catalogue's first audit pass. What the snapshots do
 * today is lock the current appearance against accidental change; what they do not do is assert
 * that the appearance is right. The distinction matters enough to be written where the images are.
 */
const plates = [
  {
    title: 'Foundations/Document surface',
    name: 'Both Schemes',
    selector: 'mjx-document-surface-probe[scheme="light"]',
    file: 'document-surface-light.png',
  },
  {
    title: 'Foundations/Document surface',
    name: 'Both Schemes',
    selector: 'mjx-document-surface-probe[scheme="dark"]',
    file: 'document-surface-dark.png',
  },
];

test.describe('visual regression', () => {
  for (const plate of plates) {
    test(`${plate.file}`, async ({ page }) => {
      const story = builtStories().find(
        (entry) => entry.title === plate.title && entry.name === plate.name,
      );
      expect(story, `${plate.title} · ${plate.name} is missing from the catalogue`).toBeDefined();
      if (story === undefined) return;

      await openStory(page, story.id, { theme: 'light', containerPreset: 'desktop' });
      // The probe itself, not `#storybook-root`: the harness chrome around it carries text, and a
      // snapshot containing text is the flake this suite is shaped to avoid.
      await expect(page.locator(plate.selector)).toHaveScreenshot(plate.file, {
        animations: 'disabled',
      });
    });
  }
});
