//! @generated by `cargo run -p xtask -- tokens` from docs/client-platform/data/tokens.json.
//! DO NOT EDIT. Edit the source and regenerate.
//!
//! The design-token source for the mjx-ooxml-rs client platform (MJXOFF-156). The `color`,
//! `font`, `font-weight`, `text`, `leading`, `tracking`, `radius`, `spacing`, `shadow`, `ease`
//! and `duration` groups are the allr.work values as measured in
//! docs/client-platform/DESIGN_TOKENS.md §1 — read from the site's own stylesheet, never
//! approximated. The `theme` and `document` groups are this project's three additions (§2.1,
//! §2.2, §2.3): a derived dark palette, a document-surface palette that keeps the page true
//! white in both schemes, and the contrast metadata that turns §2.2's rule into a build
//! failure. This file is the ONLY hand-edited artefact in the pipeline; ui/tokens/tokens.css,
//! ui/tokens/tokens.ts and crates/mjx-tokens/src/generated.rs are emitted from it by `cargo run
//! -p xtask -- tokens`. FORMAT: W3C Design Tokens Community Group format, in its string profile
//! — `color` is `#rrggbb` or `#rrggbbaa`, `dimension` is a CSS length such as `8px`, `duration`
//! is `150ms`. The later drafts' object forms carry no information this pipeline uses and would
//! make the one hand-edited file in the pipeline three times longer. EXTENSIONS live under the
//! `mjx` key: `rustType` names the struct a group becomes in Rust; `schemes` marks a group
//! whose children are colour schemes; `usage` and `background` are the contrast metadata,
//! required on every colour token.

use crate::{
    parse_token, Color, ColorUsage, CubicBezier, Dimension, Duration, FontStack, LengthUnit,
    Shadow, TokenError, TokenIdentity, TokenValue,
};

/// The allr.work palette, verbatim. Warm and organic: the neutrals are beige rather than grey
/// and the `black` is a green. These are the names the site itself declares, so dropping the
/// platform into a host that already defines them re-themes it with no code change.
#[derive(Clone, Debug, PartialEq)]
pub struct Palette {
    /// page background — warm off-white.
    ///
    /// CSS: `--color-paper` · usage `fill-only`
    pub paper: Color,
    /// raised surfaces.
    ///
    /// CSS: `--color-card` · usage `fill-only`
    pub card: Color,
    /// true white; the site declares it beside `card` and this file keeps both names.
    ///
    /// CSS: `--color-white` · usage `fill-only`
    pub white: Color,
    /// primary text — a deep, desaturated green-black.
    ///
    /// CSS: `--color-ink` · usage `on-light-text` · 11.75 : 1 on `color.paper`
    pub ink: Color,
    /// secondary text.
    ///
    /// CSS: `--color-ink-soft` · usage `on-light-text` · 5.10 : 1 on `color.paper`
    pub ink_soft: Color,
    /// borders — warm beige, not grey.
    ///
    /// CSS: `--color-line` · usage `fill-only`
    pub line: Color,
    /// subtle dividers.
    ///
    /// CSS: `--color-line-soft` · usage `fill-only`
    pub line_soft: Color,
    /// primary accent. DESIGN_TOKENS.md §2.2: 3.39 : 1 on white — legal for UI components and
    /// large text, ILLEGAL for body text. Fills, borders, indicators and icons only;
    /// `green-deep` is the accent-coloured text colour.
    ///
    /// CSS: `--color-green` · usage `fill-only` · 3.39 : 1 on `color.white`
    pub green: Color,
    /// accent, pressed / on-light text. DESIGN_TOKENS.md §2.2: 5.34 : 1 on white — legal for
    /// body text.
    ///
    /// CSS: `--color-green-deep` · usage `on-light-text` · 5.34 : 1 on `color.white`
    pub green_deep: Color,
    /// accent border.
    ///
    /// CSS: `--color-green-line` · usage `fill-only`
    pub green_line: Color,
    /// accent surface.
    ///
    /// CSS: `--color-green-tint` · usage `fill-only`
    pub green_tint: Color,
    /// secondary accent.
    ///
    /// CSS: `--color-honey` · usage `fill-only` · 2.07 : 1 on `color.white`
    pub honey: Color,
    /// secondary accent, deep. Measured at 3.49 : 1 on white by this generator, so — unlike
    /// `green-deep`, its counterpart in the green ramp — it is NOT legal for body text and is
    /// tagged `fill-only`. DESIGN_TOKENS.md §2.2 measured only the greens; this is the honey
    /// ramp's answer to the same question.
    ///
    /// CSS: `--color-honey-deep` · usage `fill-only` · 3.49 : 1 on `color.white`
    pub honey_deep: Color,
    /// secondary border.
    ///
    /// CSS: `--color-honey-line` · usage `fill-only`
    pub honey_line: Color,
    /// secondary surface.
    ///
    /// CSS: `--color-honey-tint` · usage `fill-only`
    pub honey_tint: Color,
    /// tertiary border.
    ///
    /// CSS: `--color-sage-line` · usage `fill-only`
    pub sage_line: Color,
    /// tertiary surface.
    ///
    /// CSS: `--color-sage-tint` · usage `fill-only`
    pub sage_tint: Color,
    /// warm neutral surface.
    ///
    /// CSS: `--color-clay-tint` · usage `fill-only`
    pub clay_tint: Color,
}

/// The site's three families. Young Serif is display-only — empty states and onboarding, never
/// the chrome and never document content.
#[derive(Clone, Debug, PartialEq)]
pub struct FontFamilies {
    /// the chrome face; a rounded humanist that reads slightly wider than a typical UI font.
    ///
    /// CSS: `--font-sans`
    pub sans: FontStack,
    /// display only.
    ///
    /// CSS: `--font-serif`
    pub serif: FontStack,
    /// DESIGN_TOKENS.md §1 elides this stack after `Liberation Mono`; the elision is the
    /// standard Tailwind v4 monospace stack, written out here in full.
    ///
    /// CSS: `--font-mono`
    pub mono: FontStack,
}

/// The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
/// custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the layer
/// the site's theme is written in.
#[derive(Clone, Debug, PartialEq)]
pub struct FontWeights {
    /// CSS: `--font-weight-medium`
    pub medium: u16,
    /// CSS: `--font-weight-semibold`
    pub semibold: u16,
    /// CSS: `--font-weight-bold`
    pub bold: u16,
    /// CSS: `--font-weight-extrabold`
    pub extrabold: u16,
}

/// The two small type sizes the site declares. Dense editor surfaces — the formula bar, the
/// cell grid, a properties inspector — use `xs` with `leading.tight`, not the site's relaxed
/// body measure.
#[derive(Clone, Debug, PartialEq)]
pub struct TextSizes {
    /// CSS: `--text-xs`
    pub xs: Dimension,
    /// CSS: `--text-sm`
    pub sm: Dimension,
}

/// Line heights, unitless.
#[derive(Clone, Debug, PartialEq)]
pub struct LineHeights {
    /// CSS: `--leading-tight`
    pub tight: f32,
    /// CSS: `--leading-snug`
    pub snug: f32,
    /// CSS: `--leading-relaxed`
    pub relaxed: f32,
    /// DESIGN_TOKENS.md §1 records this as `body line-height` with no custom-property name of
    /// its own; it joins the `leading` family here.
    ///
    /// CSS: `--leading-body`
    pub body: f32,
}

/// Letter spacing.
#[derive(Clone, Debug, PartialEq)]
pub struct LetterSpacings {
    /// CSS: `--tracking-tight`
    pub tight: Dimension,
}

/// The radii are large, and that is the most recognisable part of the source's character.
/// Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners Office
/// uses.
#[derive(Clone, Debug, PartialEq)]
pub struct Radii {
    /// CSS: `--radius-chip`
    pub chip: Dimension,
    /// CSS: `--radius-control`
    pub control: Dimension,
    /// CSS: `--radius-card`
    pub card: Dimension,
    /// CSS: `--radius-panel`
    pub panel: Dimension,
    /// CSS: `--radius-frame`
    pub frame: Dimension,
    /// CSS: `--radius-phone`
    pub phone: Dimension,
}

/// Shadows are ink-tinted, never neutral black.
#[derive(Clone, Debug, PartialEq)]
pub struct Shadows {
    /// the site's one elevation, tinted with `color.ink` at 11% alpha.
    ///
    /// CSS: `--shadow-lift`
    pub lift: Shadow,
}

/// `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to a
/// document object, where overshoot reads as imprecision. Selection, handles and canvas motion
/// use `ink`.
#[derive(Clone, Debug, PartialEq)]
pub struct Easings {
    /// CSS: `--ease-ink`
    pub ink: CubicBezier,
    /// CSS: `--ease-out-soft`
    pub out_soft: CubicBezier,
    /// CSS: `--ease-spring`
    pub spring: CubicBezier,
}

/// DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no custom-property
/// name of its own; it is named `--duration-transition` here for what it is.
#[derive(Clone, Debug, PartialEq)]
pub struct Durations {
    /// CSS: `--duration-transition`
    pub transition: Duration,
}

/// The semantic application palette, in both colour schemes. DESIGN_TOKENS.md §2.1: the source
/// stylesheet has no `prefers-color-scheme` block, no `.dark` class and no `[data-theme]`
/// selector, so the dark scheme is DERIVED — the source's hue relationships held and lightness
/// inverted, so the dark theme reads as the same brand rather than a different product. The two
/// schemes must carry exactly the same member names; the generator fails if they drift, because
/// a semantic role that exists in one scheme and not the other is a component that cannot be
/// themed.
#[derive(Clone, Debug, PartialEq)]
pub struct Themes {
    /// Generated from the design-token source.
    pub light: ThemeColors,
    /// Generated from the design-token source.
    pub dark: ThemeColors,
}

/// Generated from the design-token source.
#[derive(Clone, Debug, PartialEq)]
pub struct ThemeColors {
    /// the application background.
    ///
    /// CSS: `--theme-light-background` · usage `fill-only`
    pub background: Color,
    /// CSS: `--theme-light-surface` · usage `fill-only`
    pub surface: Color,
    /// CSS: `--theme-light-surface-raised` · usage `fill-only`
    pub surface_raised: Color,
    /// CSS: `--theme-light-text-primary` · usage `on-light-text` · 11.75 : 1 on
    /// `theme.light.background`
    pub text_primary: Color,
    /// CSS: `--theme-light-text-secondary` · usage `on-light-text` · 5.10 : 1 on
    /// `theme.light.background`
    pub text_secondary: Color,
    /// CSS: `--theme-light-border` · usage `fill-only`
    pub border: Color,
    /// CSS: `--theme-light-border-subtle` · usage `fill-only`
    pub border_subtle: Color,
    /// fills, borders, indicators and icons. NOT text — see `accent-pressed`.
    ///
    /// CSS: `--theme-light-accent` · usage `fill-only` · 3.39 : 1 on `theme.light.surface`
    pub accent: Color,
    /// the pressed accent, and the only accent-coloured text colour on a light surface.
    ///
    /// CSS: `--theme-light-accent-pressed` · usage `on-light-text` · 5.34 : 1 on
    /// `theme.light.surface`
    pub accent_pressed: Color,
    /// CSS: `--theme-light-accent-surface` · usage `fill-only`
    pub accent_surface: Color,
    /// CSS: `--theme-light-accent-border` · usage `fill-only`
    pub accent_border: Color,
    /// CSS: `--theme-light-secondary-accent` · usage `fill-only` · 2.07 : 1 on
    /// `theme.light.surface`
    pub secondary_accent: Color,
    /// CSS: `--theme-light-secondary-surface` · usage `fill-only`
    pub secondary_surface: Color,
}

/// The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
/// conflating them is the classic mistake. The page stays true white in both schemes — a
/// document is white paper, and a warm-tinted or dark page changes what the author sees
/// relative to what they will print or send. What changes with the scheme is the canvas
/// backdrop behind the page, the page shadow, and the in-canvas UI. A reading-mode inversion of
/// the page itself is a user setting, not a theme consequence. These are the tokens the Rust
/// canvas needs and a CSS custom property cannot reach it, which is the reason this pipeline
/// emits three artefacts instead of one.
#[derive(Clone, Debug, PartialEq)]
pub struct DocumentSurfaces {
    /// Generated from the design-token source.
    pub light: DocumentColors,
    /// Generated from the design-token source.
    pub dark: DocumentColors,
}

/// Generated from the design-token source.
#[derive(Clone, Debug, PartialEq)]
pub struct DocumentColors {
    /// `color.paper` behind a true-white page makes the page read as a distinct, lit object
    /// rather than dissolving into the background.
    ///
    /// CSS: `--document-light-backdrop` · usage `fill-only`
    pub backdrop: Color,
    /// CSS: `--document-light-page` · usage `fill-only`
    pub page: Color,
    /// CSS: `--document-light-page-border` · usage `fill-only`
    pub page_border: Color,
    /// CSS: `--document-light-page-shadow`
    pub page_shadow: Shadow,
    /// `color.green` at 18% alpha (0.18 × 255 = 46 = 0x2e).
    ///
    /// CSS: `--document-light-selection-fill` · usage `fill-only`
    pub selection_fill: Color,
    /// CSS: `--document-light-selection-handle` · usage `fill-only`
    pub selection_handle: Color,
    /// CSS: `--document-light-alignment-guide` · usage `fill-only`
    pub alignment_guide: Color,
    /// grid and ruler lines.
    ///
    /// CSS: `--document-light-grid-line` · usage `fill-only`
    pub grid_line: Color,
    /// CSS: `--document-light-comment-anchor` · usage `fill-only`
    pub comment_anchor: Color,
    /// tagged `fill-only`: measured against the page it does not reach 4.5 : 1, so it is legal
    /// for the change bar, the underline rule and the marker, and a tracked insertion's own
    /// glyphs must stay `theme.*.text-primary`.
    ///
    /// CSS: `--document-light-tracked-change-insert` · usage `fill-only` · 3.39 : 1 on
    /// `document.light.page`
    pub tracked_change_insert: Color,
    /// tagged `fill-only` for the same reason as `tracked-change-insert`.
    ///
    /// CSS: `--document-light-tracked-change-delete` · usage `fill-only` · 3.49 : 1 on
    /// `document.light.page`
    pub tracked_change_delete: Color,
}

/// The colour schemes the platform defines. Generated from the source's scheme groups, so a third
/// scheme is a change to `tokens.json` and to nothing else.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ColorScheme {
    /// The `light` scheme.
    Light,
    /// The `dark` scheme.
    Dark,
}

impl Themes {
    /// The `ThemeColors` values for one colour scheme.
    #[must_use]
    pub fn scheme(&self, scheme: ColorScheme) -> &ThemeColors {
        match scheme {
            ColorScheme::Light => &self.light,
            ColorScheme::Dark => &self.dark,
        }
    }
}

impl DocumentSurfaces {
    /// The `DocumentColors` values for one colour scheme.
    #[must_use]
    pub fn scheme(&self, scheme: ColorScheme) -> &DocumentColors {
        match scheme {
            ColorScheme::Light => &self.light,
            ColorScheme::Dark => &self.dark,
        }
    }
}

/// The whole design-token set: the values the client platform ships with, and the shape a
/// host's overrides are resolved into.
#[derive(Clone, Debug, PartialEq)]
pub struct Tokens {
    /// The allr.work palette, verbatim. Warm and organic: the neutrals are beige rather than
    /// grey and the `black` is a green. These are the names the site itself declares, so
    /// dropping the platform into a host that already defines them re-themes it with no code
    /// change.
    pub color: Palette,
    /// The site's three families. Young Serif is display-only — empty states and onboarding,
    /// never the chrome and never document content.
    pub font: FontFamilies,
    /// The four weights the site loads. DESIGN_TOKENS.md §1 records the values but not the
    /// custom-property names; these are Tailwind v4's own (`--font-weight-*`), which is the
    /// layer the site's theme is written in.
    pub font_weight: FontWeights,
    /// The two small type sizes the site declares. Dense editor surfaces — the formula bar, the
    /// cell grid, a properties inspector — use `xs` with `leading.tight`, not the site's
    /// relaxed body measure.
    pub text: TextSizes,
    /// Line heights, unitless.
    pub leading: LineHeights,
    /// Letter spacing.
    pub tracking: LetterSpacings,
    /// The radii are large, and that is the most recognisable part of the source's character.
    /// Toolbars and inspectors keep that softness rather than reverting to the 2–4px corners
    /// Office uses.
    pub radius: Radii,
    /// The base spacing step, from which the site's spacing scale is multiplied. It is a token
    /// in its own right rather than a group so that its custom property is `--spacing`, exactly
    /// as the site declares it.
    ///
    /// CSS: `--spacing`
    pub spacing: Dimension,
    /// Shadows are ink-tinted, never neutral black.
    pub shadow: Shadows,
    /// `spring` overshoots: right for a panel or sheet entering, wrong for anything attached to
    /// a document object, where overshoot reads as imprecision. Selection, handles and canvas
    /// motion use `ink`.
    pub ease: Easings,
    /// DESIGN_TOKENS.md §1 records the site's `default duration` of 0.15s with no
    /// custom-property name of its own; it is named `--duration-transition` here for what it
    /// is.
    pub duration: Durations,
    /// The semantic application palette, in both colour schemes. DESIGN_TOKENS.md §2.1: the
    /// source stylesheet has no `prefers-color-scheme` block, no `.dark` class and no
    /// `[data-theme]` selector, so the dark scheme is DERIVED — the source's hue relationships
    /// held and lightness inverted, so the dark theme reads as the same brand rather than a
    /// different product. The two schemes must carry exactly the same member names; the
    /// generator fails if they drift, because a semantic role that exists in one scheme and not
    /// the other is a component that cannot be themed.
    pub theme: Themes,
    /// The document-surface palette. DESIGN_TOKENS.md §2.3: an editor has TWO palettes and
    /// conflating them is the classic mistake. The page stays true white in both schemes — a
    /// document is white paper, and a warm-tinted or dark page changes what the author sees
    /// relative to what they will print or send. What changes with the scheme is the canvas
    /// backdrop behind the page, the page shadow, and the in-canvas UI. A reading-mode
    /// inversion of the page itself is a user setting, not a theme consequence. These are the
    /// tokens the Rust canvas needs and a CSS custom property cannot reach it, which is the
    /// reason this pipeline emits three artefacts instead of one.
    pub document: DocumentSurfaces,
}

impl Tokens {
    /// The generated defaults — the bottom of the resolution order *explicit configuration →
    /// host-supplied overrides → generated defaults*.
    pub const DEFAULTS: Self = Self {
        color: Palette {
            paper: Color { red: 0xfd, green: 0xfc, blue: 0xf9, alpha: 0xff },
            card: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
            white: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
            ink: Color { red: 0x22, green: 0x3b, blue: 0x33, alpha: 0xff },
            ink_soft: Color { red: 0x5c, green: 0x71, blue: 0x68, alpha: 0xff },
            line: Color { red: 0xe7, green: 0xe0, blue: 0xd2, alpha: 0xff },
            line_soft: Color { red: 0xef, green: 0xe9, blue: 0xdc, alpha: 0xff },
            green: Color { red: 0x2e, green: 0x9e, blue: 0x63, alpha: 0xff },
            green_deep: Color { red: 0x1e, green: 0x7a, blue: 0x49, alpha: 0xff },
            green_line: Color { red: 0xc2, green: 0xe5, blue: 0xd0, alpha: 0xff },
            green_tint: Color { red: 0xe4, green: 0xf4, blue: 0xea, alpha: 0xff },
            honey: Color { red: 0xe9, green: 0xa8, blue: 0x3e, alpha: 0xff },
            honey_deep: Color { red: 0xb7, green: 0x7e, blue: 0x1f, alpha: 0xff },
            honey_line: Color { red: 0xf0, green: 0xdc, blue: 0xb4, alpha: 0xff },
            honey_tint: Color { red: 0xfb, green: 0xef, blue: 0xd8, alpha: 0xff },
            sage_line: Color { red: 0xdc, green: 0xe8, blue: 0xdd, alpha: 0xff },
            sage_tint: Color { red: 0xec, green: 0xf2, blue: 0xec, alpha: 0xff },
            clay_tint: Color { red: 0xf6, green: 0xed, blue: 0xe2, alpha: 0xff },
        },
        font: FontFamilies {
            sans: FontStack::from_static("\"Nunito Sans\", system-ui, sans-serif"),
            serif: FontStack::from_static("\"Young Serif\", serif"),
            mono: FontStack::from_static("ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"),
        },
        font_weight: FontWeights {
            medium: 500,
            semibold: 600,
            bold: 700,
            extrabold: 800,
        },
        text: TextSizes {
            xs: Dimension { magnitude: 0.75, unit: LengthUnit::Rem },
            sm: Dimension { magnitude: 0.875, unit: LengthUnit::Rem },
        },
        leading: LineHeights {
            tight: 1.25,
            snug: 1.375,
            relaxed: 1.625,
            body: 1.7,
        },
        tracking: LetterSpacings {
            tight: Dimension { magnitude: -0.025, unit: LengthUnit::Em },
        },
        radius: Radii {
            chip: Dimension { magnitude: 8.0, unit: LengthUnit::Pixels },
            control: Dimension { magnitude: 10.0, unit: LengthUnit::Pixels },
            card: Dimension { magnitude: 16.0, unit: LengthUnit::Pixels },
            panel: Dimension { magnitude: 20.0, unit: LengthUnit::Pixels },
            frame: Dimension { magnitude: 22.0, unit: LengthUnit::Pixels },
            phone: Dimension { magnitude: 36.0, unit: LengthUnit::Pixels },
        },
        spacing: Dimension { magnitude: 0.25, unit: LengthUnit::Rem },
        shadow: Shadows {
            lift: Shadow { offset_x: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, offset_y: Dimension { magnitude: 18.0, unit: LengthUnit::Pixels }, blur: Dimension { magnitude: 48.0, unit: LengthUnit::Pixels }, spread: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, color: Color { red: 0x22, green: 0x3b, blue: 0x33, alpha: 0x1c } },
        },
        ease: Easings {
            ink: CubicBezier { x1: 0.45, y1: 0.0, x2: 0.2, y2: 1.0 },
            out_soft: CubicBezier { x1: 0.22, y1: 1.0, x2: 0.36, y2: 1.0 },
            spring: CubicBezier { x1: 0.34, y1: 1.56, x2: 0.64, y2: 1.0 },
        },
        duration: Durations {
            transition: Duration { milliseconds: 150.0 },
        },
        theme: Themes {
            light: ThemeColors {
                background: Color { red: 0xfd, green: 0xfc, blue: 0xf9, alpha: 0xff },
                surface: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
                surface_raised: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
                text_primary: Color { red: 0x22, green: 0x3b, blue: 0x33, alpha: 0xff },
                text_secondary: Color { red: 0x5c, green: 0x71, blue: 0x68, alpha: 0xff },
                border: Color { red: 0xe7, green: 0xe0, blue: 0xd2, alpha: 0xff },
                border_subtle: Color { red: 0xef, green: 0xe9, blue: 0xdc, alpha: 0xff },
                accent: Color { red: 0x2e, green: 0x9e, blue: 0x63, alpha: 0xff },
                accent_pressed: Color { red: 0x1e, green: 0x7a, blue: 0x49, alpha: 0xff },
                accent_surface: Color { red: 0xe4, green: 0xf4, blue: 0xea, alpha: 0xff },
                accent_border: Color { red: 0xc2, green: 0xe5, blue: 0xd0, alpha: 0xff },
                secondary_accent: Color { red: 0xe9, green: 0xa8, blue: 0x3e, alpha: 0xff },
                secondary_surface: Color { red: 0xfb, green: 0xef, blue: 0xd8, alpha: 0xff },
            },
            dark: ThemeColors {
                background: Color { red: 0x13, green: 0x1a, blue: 0x17, alpha: 0xff },
                surface: Color { red: 0x1b, green: 0x24, blue: 0x20, alpha: 0xff },
                surface_raised: Color { red: 0x23, green: 0x30, blue: 0x2a, alpha: 0xff },
                text_primary: Color { red: 0xe8, green: 0xef, blue: 0xe9, alpha: 0xff },
                text_secondary: Color { red: 0x9a, green: 0xab, blue: 0xa2, alpha: 0xff },
                border: Color { red: 0x2e, green: 0x3b, blue: 0x35, alpha: 0xff },
                border_subtle: Color { red: 0x26, green: 0x31, blue: 0x2c, alpha: 0xff },
                accent: Color { red: 0x4f, green: 0xc9, blue: 0x8a, alpha: 0xff },
                accent_pressed: Color { red: 0x2e, green: 0x9e, blue: 0x63, alpha: 0xff },
                accent_surface: Color { red: 0x16, green: 0x30, blue: 0x23, alpha: 0xff },
                accent_border: Color { red: 0x22, green: 0x49, blue: 0x34, alpha: 0xff },
                secondary_accent: Color { red: 0xf0, green: 0xbe, blue: 0x62, alpha: 0xff },
                secondary_surface: Color { red: 0x33, green: 0x26, blue: 0x0f, alpha: 0xff },
            },
        },
        document: DocumentSurfaces {
            light: DocumentColors {
                backdrop: Color { red: 0xfd, green: 0xfc, blue: 0xf9, alpha: 0xff },
                page: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
                page_border: Color { red: 0xe7, green: 0xe0, blue: 0xd2, alpha: 0xff },
                page_shadow: Shadow { offset_x: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, offset_y: Dimension { magnitude: 2.0, unit: LengthUnit::Pixels }, blur: Dimension { magnitude: 10.0, unit: LengthUnit::Pixels }, spread: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, color: Color { red: 0x22, green: 0x3b, blue: 0x33, alpha: 0x14 } },
                selection_fill: Color { red: 0x2e, green: 0x9e, blue: 0x63, alpha: 0x2e },
                selection_handle: Color { red: 0x1e, green: 0x7a, blue: 0x49, alpha: 0xff },
                alignment_guide: Color { red: 0xe9, green: 0xa8, blue: 0x3e, alpha: 0xff },
                grid_line: Color { red: 0xef, green: 0xe9, blue: 0xdc, alpha: 0xff },
                comment_anchor: Color { red: 0xe9, green: 0xa8, blue: 0x3e, alpha: 0xff },
                tracked_change_insert: Color { red: 0x2e, green: 0x9e, blue: 0x63, alpha: 0xff },
                tracked_change_delete: Color { red: 0xb7, green: 0x7e, blue: 0x1f, alpha: 0xff },
            },
            dark: DocumentColors {
                backdrop: Color { red: 0x13, green: 0x1a, blue: 0x17, alpha: 0xff },
                page: Color { red: 0xff, green: 0xff, blue: 0xff, alpha: 0xff },
                page_border: Color { red: 0x2e, green: 0x3b, blue: 0x35, alpha: 0xff },
                page_shadow: Shadow { offset_x: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, offset_y: Dimension { magnitude: 2.0, unit: LengthUnit::Pixels }, blur: Dimension { magnitude: 14.0, unit: LengthUnit::Pixels }, spread: Dimension { magnitude: 0.0, unit: LengthUnit::Pixels }, color: Color { red: 0x00, green: 0x00, blue: 0x00, alpha: 0x59 } },
                selection_fill: Color { red: 0x4f, green: 0xc9, blue: 0x8a, alpha: 0x38 },
                selection_handle: Color { red: 0x4f, green: 0xc9, blue: 0x8a, alpha: 0xff },
                alignment_guide: Color { red: 0xf0, green: 0xbe, blue: 0x62, alpha: 0xff },
                grid_line: Color { red: 0x26, green: 0x31, blue: 0x2c, alpha: 0xff },
                comment_anchor: Color { red: 0xf0, green: 0xbe, blue: 0x62, alpha: 0xff },
                tracked_change_insert: Color { red: 0x4f, green: 0xc9, blue: 0x8a, alpha: 0xff },
                tracked_change_delete: Color { red: 0xf0, green: 0xbe, blue: 0x62, alpha: 0xff },
            },
        },
    };

    /// The typed value of one token, by the CSS custom property that names it, or `None` when the
    /// platform defines no such token.
    #[must_use]
    pub fn custom_property(&self, custom_property: &str) -> Option<TokenValue> {
        Some(match custom_property {
            "--color-paper" => TokenValue::Color(self.color.paper),
            "--color-card" => TokenValue::Color(self.color.card),
            "--color-white" => TokenValue::Color(self.color.white),
            "--color-ink" => TokenValue::Color(self.color.ink),
            "--color-ink-soft" => TokenValue::Color(self.color.ink_soft),
            "--color-line" => TokenValue::Color(self.color.line),
            "--color-line-soft" => TokenValue::Color(self.color.line_soft),
            "--color-green" => TokenValue::Color(self.color.green),
            "--color-green-deep" => TokenValue::Color(self.color.green_deep),
            "--color-green-line" => TokenValue::Color(self.color.green_line),
            "--color-green-tint" => TokenValue::Color(self.color.green_tint),
            "--color-honey" => TokenValue::Color(self.color.honey),
            "--color-honey-deep" => TokenValue::Color(self.color.honey_deep),
            "--color-honey-line" => TokenValue::Color(self.color.honey_line),
            "--color-honey-tint" => TokenValue::Color(self.color.honey_tint),
            "--color-sage-line" => TokenValue::Color(self.color.sage_line),
            "--color-sage-tint" => TokenValue::Color(self.color.sage_tint),
            "--color-clay-tint" => TokenValue::Color(self.color.clay_tint),
            "--font-sans" => TokenValue::FontStack(self.font.sans.clone()),
            "--font-serif" => TokenValue::FontStack(self.font.serif.clone()),
            "--font-mono" => TokenValue::FontStack(self.font.mono.clone()),
            "--font-weight-medium" => TokenValue::FontWeight(self.font_weight.medium),
            "--font-weight-semibold" => TokenValue::FontWeight(self.font_weight.semibold),
            "--font-weight-bold" => TokenValue::FontWeight(self.font_weight.bold),
            "--font-weight-extrabold" => TokenValue::FontWeight(self.font_weight.extrabold),
            "--text-xs" => TokenValue::Dimension(self.text.xs),
            "--text-sm" => TokenValue::Dimension(self.text.sm),
            "--leading-tight" => TokenValue::Number(self.leading.tight),
            "--leading-snug" => TokenValue::Number(self.leading.snug),
            "--leading-relaxed" => TokenValue::Number(self.leading.relaxed),
            "--leading-body" => TokenValue::Number(self.leading.body),
            "--tracking-tight" => TokenValue::Dimension(self.tracking.tight),
            "--radius-chip" => TokenValue::Dimension(self.radius.chip),
            "--radius-control" => TokenValue::Dimension(self.radius.control),
            "--radius-card" => TokenValue::Dimension(self.radius.card),
            "--radius-panel" => TokenValue::Dimension(self.radius.panel),
            "--radius-frame" => TokenValue::Dimension(self.radius.frame),
            "--radius-phone" => TokenValue::Dimension(self.radius.phone),
            "--spacing" => TokenValue::Dimension(self.spacing),
            "--shadow-lift" => TokenValue::Shadow(self.shadow.lift),
            "--ease-ink" => TokenValue::CubicBezier(self.ease.ink),
            "--ease-out-soft" => TokenValue::CubicBezier(self.ease.out_soft),
            "--ease-spring" => TokenValue::CubicBezier(self.ease.spring),
            "--duration-transition" => TokenValue::Duration(self.duration.transition),
            "--theme-light-background" => TokenValue::Color(self.theme.light.background),
            "--theme-light-surface" => TokenValue::Color(self.theme.light.surface),
            "--theme-light-surface-raised" => TokenValue::Color(self.theme.light.surface_raised),
            "--theme-light-text-primary" => TokenValue::Color(self.theme.light.text_primary),
            "--theme-light-text-secondary" => TokenValue::Color(self.theme.light.text_secondary),
            "--theme-light-border" => TokenValue::Color(self.theme.light.border),
            "--theme-light-border-subtle" => TokenValue::Color(self.theme.light.border_subtle),
            "--theme-light-accent" => TokenValue::Color(self.theme.light.accent),
            "--theme-light-accent-pressed" => TokenValue::Color(self.theme.light.accent_pressed),
            "--theme-light-accent-surface" => TokenValue::Color(self.theme.light.accent_surface),
            "--theme-light-accent-border" => TokenValue::Color(self.theme.light.accent_border),
            "--theme-light-secondary-accent" => {
                TokenValue::Color(self.theme.light.secondary_accent)
            }
            "--theme-light-secondary-surface" => {
                TokenValue::Color(self.theme.light.secondary_surface)
            }
            "--theme-dark-background" => TokenValue::Color(self.theme.dark.background),
            "--theme-dark-surface" => TokenValue::Color(self.theme.dark.surface),
            "--theme-dark-surface-raised" => TokenValue::Color(self.theme.dark.surface_raised),
            "--theme-dark-text-primary" => TokenValue::Color(self.theme.dark.text_primary),
            "--theme-dark-text-secondary" => TokenValue::Color(self.theme.dark.text_secondary),
            "--theme-dark-border" => TokenValue::Color(self.theme.dark.border),
            "--theme-dark-border-subtle" => TokenValue::Color(self.theme.dark.border_subtle),
            "--theme-dark-accent" => TokenValue::Color(self.theme.dark.accent),
            "--theme-dark-accent-pressed" => TokenValue::Color(self.theme.dark.accent_pressed),
            "--theme-dark-accent-surface" => TokenValue::Color(self.theme.dark.accent_surface),
            "--theme-dark-accent-border" => TokenValue::Color(self.theme.dark.accent_border),
            "--theme-dark-secondary-accent" => TokenValue::Color(self.theme.dark.secondary_accent),
            "--theme-dark-secondary-surface" => {
                TokenValue::Color(self.theme.dark.secondary_surface)
            }
            "--document-light-backdrop" => TokenValue::Color(self.document.light.backdrop),
            "--document-light-page" => TokenValue::Color(self.document.light.page),
            "--document-light-page-border" => TokenValue::Color(self.document.light.page_border),
            "--document-light-page-shadow" => TokenValue::Shadow(self.document.light.page_shadow),
            "--document-light-selection-fill" => {
                TokenValue::Color(self.document.light.selection_fill)
            }
            "--document-light-selection-handle" => {
                TokenValue::Color(self.document.light.selection_handle)
            }
            "--document-light-alignment-guide" => {
                TokenValue::Color(self.document.light.alignment_guide)
            }
            "--document-light-grid-line" => TokenValue::Color(self.document.light.grid_line),
            "--document-light-comment-anchor" => {
                TokenValue::Color(self.document.light.comment_anchor)
            }
            "--document-light-tracked-change-insert" => {
                TokenValue::Color(self.document.light.tracked_change_insert)
            }
            "--document-light-tracked-change-delete" => {
                TokenValue::Color(self.document.light.tracked_change_delete)
            }
            "--document-dark-backdrop" => TokenValue::Color(self.document.dark.backdrop),
            "--document-dark-page" => TokenValue::Color(self.document.dark.page),
            "--document-dark-page-border" => TokenValue::Color(self.document.dark.page_border),
            "--document-dark-page-shadow" => TokenValue::Shadow(self.document.dark.page_shadow),
            "--document-dark-selection-fill" => {
                TokenValue::Color(self.document.dark.selection_fill)
            }
            "--document-dark-selection-handle" => {
                TokenValue::Color(self.document.dark.selection_handle)
            }
            "--document-dark-alignment-guide" => {
                TokenValue::Color(self.document.dark.alignment_guide)
            }
            "--document-dark-grid-line" => TokenValue::Color(self.document.dark.grid_line),
            "--document-dark-comment-anchor" => {
                TokenValue::Color(self.document.dark.comment_anchor)
            }
            "--document-dark-tracked-change-insert" => {
                TokenValue::Color(self.document.dark.tracked_change_insert)
            }
            "--document-dark-tracked-change-delete" => {
                TokenValue::Color(self.document.dark.tracked_change_delete)
            }
            _ => return None,
        })
    }

    /// Replaces one token's value, parsed from the CSS text a host declared it with.
    ///
    /// # Errors
    ///
    /// [`TokenError::UnknownCustomProperty`] when the platform defines no such token, and
    /// [`TokenError::MalformedValue`] when the text is not a value of that token's type.
    pub fn set_custom_property(
        &mut self,
        custom_property: &str,
        css_text: &str,
    ) -> Result<(), TokenError> {
        match custom_property {
            "--color-paper" => self.color.paper = parse_token(custom_property, css_text)?,
            "--color-card" => self.color.card = parse_token(custom_property, css_text)?,
            "--color-white" => self.color.white = parse_token(custom_property, css_text)?,
            "--color-ink" => self.color.ink = parse_token(custom_property, css_text)?,
            "--color-ink-soft" => self.color.ink_soft = parse_token(custom_property, css_text)?,
            "--color-line" => self.color.line = parse_token(custom_property, css_text)?,
            "--color-line-soft" => self.color.line_soft = parse_token(custom_property, css_text)?,
            "--color-green" => self.color.green = parse_token(custom_property, css_text)?,
            "--color-green-deep" => self.color.green_deep = parse_token(custom_property, css_text)?,
            "--color-green-line" => self.color.green_line = parse_token(custom_property, css_text)?,
            "--color-green-tint" => self.color.green_tint = parse_token(custom_property, css_text)?,
            "--color-honey" => self.color.honey = parse_token(custom_property, css_text)?,
            "--color-honey-deep" => self.color.honey_deep = parse_token(custom_property, css_text)?,
            "--color-honey-line" => self.color.honey_line = parse_token(custom_property, css_text)?,
            "--color-honey-tint" => self.color.honey_tint = parse_token(custom_property, css_text)?,
            "--color-sage-line" => self.color.sage_line = parse_token(custom_property, css_text)?,
            "--color-sage-tint" => self.color.sage_tint = parse_token(custom_property, css_text)?,
            "--color-clay-tint" => self.color.clay_tint = parse_token(custom_property, css_text)?,
            "--font-sans" => self.font.sans = parse_token(custom_property, css_text)?,
            "--font-serif" => self.font.serif = parse_token(custom_property, css_text)?,
            "--font-mono" => self.font.mono = parse_token(custom_property, css_text)?,
            "--font-weight-medium" => {
                self.font_weight.medium = parse_token(custom_property, css_text)?
            }
            "--font-weight-semibold" => {
                self.font_weight.semibold = parse_token(custom_property, css_text)?
            }
            "--font-weight-bold" => self.font_weight.bold = parse_token(custom_property, css_text)?,
            "--font-weight-extrabold" => {
                self.font_weight.extrabold = parse_token(custom_property, css_text)?
            }
            "--text-xs" => self.text.xs = parse_token(custom_property, css_text)?,
            "--text-sm" => self.text.sm = parse_token(custom_property, css_text)?,
            "--leading-tight" => self.leading.tight = parse_token(custom_property, css_text)?,
            "--leading-snug" => self.leading.snug = parse_token(custom_property, css_text)?,
            "--leading-relaxed" => self.leading.relaxed = parse_token(custom_property, css_text)?,
            "--leading-body" => self.leading.body = parse_token(custom_property, css_text)?,
            "--tracking-tight" => self.tracking.tight = parse_token(custom_property, css_text)?,
            "--radius-chip" => self.radius.chip = parse_token(custom_property, css_text)?,
            "--radius-control" => self.radius.control = parse_token(custom_property, css_text)?,
            "--radius-card" => self.radius.card = parse_token(custom_property, css_text)?,
            "--radius-panel" => self.radius.panel = parse_token(custom_property, css_text)?,
            "--radius-frame" => self.radius.frame = parse_token(custom_property, css_text)?,
            "--radius-phone" => self.radius.phone = parse_token(custom_property, css_text)?,
            "--spacing" => self.spacing = parse_token(custom_property, css_text)?,
            "--shadow-lift" => self.shadow.lift = parse_token(custom_property, css_text)?,
            "--ease-ink" => self.ease.ink = parse_token(custom_property, css_text)?,
            "--ease-out-soft" => self.ease.out_soft = parse_token(custom_property, css_text)?,
            "--ease-spring" => self.ease.spring = parse_token(custom_property, css_text)?,
            "--duration-transition" => {
                self.duration.transition = parse_token(custom_property, css_text)?
            }
            "--theme-light-background" => {
                self.theme.light.background = parse_token(custom_property, css_text)?
            }
            "--theme-light-surface" => {
                self.theme.light.surface = parse_token(custom_property, css_text)?
            }
            "--theme-light-surface-raised" => {
                self.theme.light.surface_raised = parse_token(custom_property, css_text)?
            }
            "--theme-light-text-primary" => {
                self.theme.light.text_primary = parse_token(custom_property, css_text)?
            }
            "--theme-light-text-secondary" => {
                self.theme.light.text_secondary = parse_token(custom_property, css_text)?
            }
            "--theme-light-border" => {
                self.theme.light.border = parse_token(custom_property, css_text)?
            }
            "--theme-light-border-subtle" => {
                self.theme.light.border_subtle = parse_token(custom_property, css_text)?
            }
            "--theme-light-accent" => {
                self.theme.light.accent = parse_token(custom_property, css_text)?
            }
            "--theme-light-accent-pressed" => {
                self.theme.light.accent_pressed = parse_token(custom_property, css_text)?
            }
            "--theme-light-accent-surface" => {
                self.theme.light.accent_surface = parse_token(custom_property, css_text)?
            }
            "--theme-light-accent-border" => {
                self.theme.light.accent_border = parse_token(custom_property, css_text)?
            }
            "--theme-light-secondary-accent" => {
                self.theme.light.secondary_accent = parse_token(custom_property, css_text)?
            }
            "--theme-light-secondary-surface" => {
                self.theme.light.secondary_surface = parse_token(custom_property, css_text)?
            }
            "--theme-dark-background" => {
                self.theme.dark.background = parse_token(custom_property, css_text)?
            }
            "--theme-dark-surface" => {
                self.theme.dark.surface = parse_token(custom_property, css_text)?
            }
            "--theme-dark-surface-raised" => {
                self.theme.dark.surface_raised = parse_token(custom_property, css_text)?
            }
            "--theme-dark-text-primary" => {
                self.theme.dark.text_primary = parse_token(custom_property, css_text)?
            }
            "--theme-dark-text-secondary" => {
                self.theme.dark.text_secondary = parse_token(custom_property, css_text)?
            }
            "--theme-dark-border" => {
                self.theme.dark.border = parse_token(custom_property, css_text)?
            }
            "--theme-dark-border-subtle" => {
                self.theme.dark.border_subtle = parse_token(custom_property, css_text)?
            }
            "--theme-dark-accent" => {
                self.theme.dark.accent = parse_token(custom_property, css_text)?
            }
            "--theme-dark-accent-pressed" => {
                self.theme.dark.accent_pressed = parse_token(custom_property, css_text)?
            }
            "--theme-dark-accent-surface" => {
                self.theme.dark.accent_surface = parse_token(custom_property, css_text)?
            }
            "--theme-dark-accent-border" => {
                self.theme.dark.accent_border = parse_token(custom_property, css_text)?
            }
            "--theme-dark-secondary-accent" => {
                self.theme.dark.secondary_accent = parse_token(custom_property, css_text)?
            }
            "--theme-dark-secondary-surface" => {
                self.theme.dark.secondary_surface = parse_token(custom_property, css_text)?
            }
            "--document-light-backdrop" => {
                self.document.light.backdrop = parse_token(custom_property, css_text)?
            }
            "--document-light-page" => {
                self.document.light.page = parse_token(custom_property, css_text)?
            }
            "--document-light-page-border" => {
                self.document.light.page_border = parse_token(custom_property, css_text)?
            }
            "--document-light-page-shadow" => {
                self.document.light.page_shadow = parse_token(custom_property, css_text)?
            }
            "--document-light-selection-fill" => {
                self.document.light.selection_fill = parse_token(custom_property, css_text)?
            }
            "--document-light-selection-handle" => {
                self.document.light.selection_handle = parse_token(custom_property, css_text)?
            }
            "--document-light-alignment-guide" => {
                self.document.light.alignment_guide = parse_token(custom_property, css_text)?
            }
            "--document-light-grid-line" => {
                self.document.light.grid_line = parse_token(custom_property, css_text)?
            }
            "--document-light-comment-anchor" => {
                self.document.light.comment_anchor = parse_token(custom_property, css_text)?
            }
            "--document-light-tracked-change-insert" => {
                self.document.light.tracked_change_insert = parse_token(custom_property, css_text)?
            }
            "--document-light-tracked-change-delete" => {
                self.document.light.tracked_change_delete = parse_token(custom_property, css_text)?
            }
            "--document-dark-backdrop" => {
                self.document.dark.backdrop = parse_token(custom_property, css_text)?
            }
            "--document-dark-page" => {
                self.document.dark.page = parse_token(custom_property, css_text)?
            }
            "--document-dark-page-border" => {
                self.document.dark.page_border = parse_token(custom_property, css_text)?
            }
            "--document-dark-page-shadow" => {
                self.document.dark.page_shadow = parse_token(custom_property, css_text)?
            }
            "--document-dark-selection-fill" => {
                self.document.dark.selection_fill = parse_token(custom_property, css_text)?
            }
            "--document-dark-selection-handle" => {
                self.document.dark.selection_handle = parse_token(custom_property, css_text)?
            }
            "--document-dark-alignment-guide" => {
                self.document.dark.alignment_guide = parse_token(custom_property, css_text)?
            }
            "--document-dark-grid-line" => {
                self.document.dark.grid_line = parse_token(custom_property, css_text)?
            }
            "--document-dark-comment-anchor" => {
                self.document.dark.comment_anchor = parse_token(custom_property, css_text)?
            }
            "--document-dark-tracked-change-insert" => {
                self.document.dark.tracked_change_insert = parse_token(custom_property, css_text)?
            }
            "--document-dark-tracked-change-delete" => {
                self.document.dark.tracked_change_delete = parse_token(custom_property, css_text)?
            }
            _ => {
                return Err(TokenError::UnknownCustomProperty {
                    custom_property: custom_property.to_owned(),
                })
            }
        }
        Ok(())
    }
}

/// Every token the platform defines, in the order the source declares them, with the three names it
/// goes by — its path in `tokens.json`, its CSS custom property, and its path in `tokens.ts` — and
/// the contrast metadata every colour carries.
///
/// This is what makes the three artefacts comparable. A test that had to re-derive
/// `--color-ink-soft` from `color.inkSoft` itself could agree perfectly with a wrong rule.
///
/// `usage` and `background` are emitted as **data** rather than only as prose in each token's docs
/// (MJXOFF-166), because `xtask`'s generator is not the only writer of `tokens.json`: the canvas
/// harness's live token editor writes back to it and may not depend on `xtask`, so it has to be
/// able to call `mjx_tokens::check_usage` for itself.
pub const TOKENS: &[TokenIdentity] = &[
    TokenIdentity {
        path: "color.paper",
        custom_property: "--color-paper",
        typescript_path: "color.paper",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.card",
        custom_property: "--color-card",
        typescript_path: "color.card",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.white",
        custom_property: "--color-white",
        typescript_path: "color.white",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.ink",
        custom_property: "--color-ink",
        typescript_path: "color.ink",
        usage: Some(ColorUsage::OnLightText),
        background: Some("color.paper"),
    },
    TokenIdentity {
        path: "color.ink-soft",
        custom_property: "--color-ink-soft",
        typescript_path: "color.inkSoft",
        usage: Some(ColorUsage::OnLightText),
        background: Some("color.paper"),
    },
    TokenIdentity {
        path: "color.line",
        custom_property: "--color-line",
        typescript_path: "color.line",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.line-soft",
        custom_property: "--color-line-soft",
        typescript_path: "color.lineSoft",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.green",
        custom_property: "--color-green",
        typescript_path: "color.green",
        usage: Some(ColorUsage::FillOnly),
        background: Some("color.white"),
    },
    TokenIdentity {
        path: "color.green-deep",
        custom_property: "--color-green-deep",
        typescript_path: "color.greenDeep",
        usage: Some(ColorUsage::OnLightText),
        background: Some("color.white"),
    },
    TokenIdentity {
        path: "color.green-line",
        custom_property: "--color-green-line",
        typescript_path: "color.greenLine",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.green-tint",
        custom_property: "--color-green-tint",
        typescript_path: "color.greenTint",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.honey",
        custom_property: "--color-honey",
        typescript_path: "color.honey",
        usage: Some(ColorUsage::FillOnly),
        background: Some("color.white"),
    },
    TokenIdentity {
        path: "color.honey-deep",
        custom_property: "--color-honey-deep",
        typescript_path: "color.honeyDeep",
        usage: Some(ColorUsage::FillOnly),
        background: Some("color.white"),
    },
    TokenIdentity {
        path: "color.honey-line",
        custom_property: "--color-honey-line",
        typescript_path: "color.honeyLine",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.honey-tint",
        custom_property: "--color-honey-tint",
        typescript_path: "color.honeyTint",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.sage-line",
        custom_property: "--color-sage-line",
        typescript_path: "color.sageLine",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.sage-tint",
        custom_property: "--color-sage-tint",
        typescript_path: "color.sageTint",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "color.clay-tint",
        custom_property: "--color-clay-tint",
        typescript_path: "color.clayTint",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "font.sans",
        custom_property: "--font-sans",
        typescript_path: "font.sans",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font.serif",
        custom_property: "--font-serif",
        typescript_path: "font.serif",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font.mono",
        custom_property: "--font-mono",
        typescript_path: "font.mono",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font-weight.medium",
        custom_property: "--font-weight-medium",
        typescript_path: "fontWeight.medium",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font-weight.semibold",
        custom_property: "--font-weight-semibold",
        typescript_path: "fontWeight.semibold",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font-weight.bold",
        custom_property: "--font-weight-bold",
        typescript_path: "fontWeight.bold",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "font-weight.extrabold",
        custom_property: "--font-weight-extrabold",
        typescript_path: "fontWeight.extrabold",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "text.xs",
        custom_property: "--text-xs",
        typescript_path: "text.xs",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "text.sm",
        custom_property: "--text-sm",
        typescript_path: "text.sm",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "leading.tight",
        custom_property: "--leading-tight",
        typescript_path: "leading.tight",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "leading.snug",
        custom_property: "--leading-snug",
        typescript_path: "leading.snug",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "leading.relaxed",
        custom_property: "--leading-relaxed",
        typescript_path: "leading.relaxed",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "leading.body",
        custom_property: "--leading-body",
        typescript_path: "leading.body",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "tracking.tight",
        custom_property: "--tracking-tight",
        typescript_path: "tracking.tight",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.chip",
        custom_property: "--radius-chip",
        typescript_path: "radius.chip",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.control",
        custom_property: "--radius-control",
        typescript_path: "radius.control",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.card",
        custom_property: "--radius-card",
        typescript_path: "radius.card",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.panel",
        custom_property: "--radius-panel",
        typescript_path: "radius.panel",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.frame",
        custom_property: "--radius-frame",
        typescript_path: "radius.frame",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "radius.phone",
        custom_property: "--radius-phone",
        typescript_path: "radius.phone",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "spacing",
        custom_property: "--spacing",
        typescript_path: "spacing",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "shadow.lift",
        custom_property: "--shadow-lift",
        typescript_path: "shadow.lift",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "ease.ink",
        custom_property: "--ease-ink",
        typescript_path: "ease.ink",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "ease.out-soft",
        custom_property: "--ease-out-soft",
        typescript_path: "ease.outSoft",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "ease.spring",
        custom_property: "--ease-spring",
        typescript_path: "ease.spring",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "duration.transition",
        custom_property: "--duration-transition",
        typescript_path: "duration.transition",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "theme.light.background",
        custom_property: "--theme-light-background",
        typescript_path: "theme.light.background",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.surface",
        custom_property: "--theme-light-surface",
        typescript_path: "theme.light.surface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.surface-raised",
        custom_property: "--theme-light-surface-raised",
        typescript_path: "theme.light.surfaceRaised",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.text-primary",
        custom_property: "--theme-light-text-primary",
        typescript_path: "theme.light.textPrimary",
        usage: Some(ColorUsage::OnLightText),
        background: Some("theme.light.background"),
    },
    TokenIdentity {
        path: "theme.light.text-secondary",
        custom_property: "--theme-light-text-secondary",
        typescript_path: "theme.light.textSecondary",
        usage: Some(ColorUsage::OnLightText),
        background: Some("theme.light.background"),
    },
    TokenIdentity {
        path: "theme.light.border",
        custom_property: "--theme-light-border",
        typescript_path: "theme.light.border",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.border-subtle",
        custom_property: "--theme-light-border-subtle",
        typescript_path: "theme.light.borderSubtle",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.accent",
        custom_property: "--theme-light-accent",
        typescript_path: "theme.light.accent",
        usage: Some(ColorUsage::FillOnly),
        background: Some("theme.light.surface"),
    },
    TokenIdentity {
        path: "theme.light.accent-pressed",
        custom_property: "--theme-light-accent-pressed",
        typescript_path: "theme.light.accentPressed",
        usage: Some(ColorUsage::OnLightText),
        background: Some("theme.light.surface"),
    },
    TokenIdentity {
        path: "theme.light.accent-surface",
        custom_property: "--theme-light-accent-surface",
        typescript_path: "theme.light.accentSurface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.accent-border",
        custom_property: "--theme-light-accent-border",
        typescript_path: "theme.light.accentBorder",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.light.secondary-accent",
        custom_property: "--theme-light-secondary-accent",
        typescript_path: "theme.light.secondaryAccent",
        usage: Some(ColorUsage::FillOnly),
        background: Some("theme.light.surface"),
    },
    TokenIdentity {
        path: "theme.light.secondary-surface",
        custom_property: "--theme-light-secondary-surface",
        typescript_path: "theme.light.secondarySurface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.background",
        custom_property: "--theme-dark-background",
        typescript_path: "theme.dark.background",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.surface",
        custom_property: "--theme-dark-surface",
        typescript_path: "theme.dark.surface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.surface-raised",
        custom_property: "--theme-dark-surface-raised",
        typescript_path: "theme.dark.surfaceRaised",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.text-primary",
        custom_property: "--theme-dark-text-primary",
        typescript_path: "theme.dark.textPrimary",
        usage: Some(ColorUsage::OnDarkText),
        background: Some("theme.dark.background"),
    },
    TokenIdentity {
        path: "theme.dark.text-secondary",
        custom_property: "--theme-dark-text-secondary",
        typescript_path: "theme.dark.textSecondary",
        usage: Some(ColorUsage::OnDarkText),
        background: Some("theme.dark.background"),
    },
    TokenIdentity {
        path: "theme.dark.border",
        custom_property: "--theme-dark-border",
        typescript_path: "theme.dark.border",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.border-subtle",
        custom_property: "--theme-dark-border-subtle",
        typescript_path: "theme.dark.borderSubtle",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.accent",
        custom_property: "--theme-dark-accent",
        typescript_path: "theme.dark.accent",
        usage: Some(ColorUsage::FillOnly),
        background: Some("theme.dark.surface"),
    },
    TokenIdentity {
        path: "theme.dark.accent-pressed",
        custom_property: "--theme-dark-accent-pressed",
        typescript_path: "theme.dark.accentPressed",
        usage: Some(ColorUsage::OnDarkText),
        background: Some("theme.dark.surface"),
    },
    TokenIdentity {
        path: "theme.dark.accent-surface",
        custom_property: "--theme-dark-accent-surface",
        typescript_path: "theme.dark.accentSurface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.accent-border",
        custom_property: "--theme-dark-accent-border",
        typescript_path: "theme.dark.accentBorder",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "theme.dark.secondary-accent",
        custom_property: "--theme-dark-secondary-accent",
        typescript_path: "theme.dark.secondaryAccent",
        usage: Some(ColorUsage::FillOnly),
        background: Some("theme.dark.surface"),
    },
    TokenIdentity {
        path: "theme.dark.secondary-surface",
        custom_property: "--theme-dark-secondary-surface",
        typescript_path: "theme.dark.secondarySurface",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.backdrop",
        custom_property: "--document-light-backdrop",
        typescript_path: "document.light.backdrop",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.page",
        custom_property: "--document-light-page",
        typescript_path: "document.light.page",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.page-border",
        custom_property: "--document-light-page-border",
        typescript_path: "document.light.pageBorder",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.page-shadow",
        custom_property: "--document-light-page-shadow",
        typescript_path: "document.light.pageShadow",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "document.light.selection-fill",
        custom_property: "--document-light-selection-fill",
        typescript_path: "document.light.selectionFill",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.selection-handle",
        custom_property: "--document-light-selection-handle",
        typescript_path: "document.light.selectionHandle",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.alignment-guide",
        custom_property: "--document-light-alignment-guide",
        typescript_path: "document.light.alignmentGuide",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.grid-line",
        custom_property: "--document-light-grid-line",
        typescript_path: "document.light.gridLine",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.comment-anchor",
        custom_property: "--document-light-comment-anchor",
        typescript_path: "document.light.commentAnchor",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.light.tracked-change-insert",
        custom_property: "--document-light-tracked-change-insert",
        typescript_path: "document.light.trackedChangeInsert",
        usage: Some(ColorUsage::FillOnly),
        background: Some("document.light.page"),
    },
    TokenIdentity {
        path: "document.light.tracked-change-delete",
        custom_property: "--document-light-tracked-change-delete",
        typescript_path: "document.light.trackedChangeDelete",
        usage: Some(ColorUsage::FillOnly),
        background: Some("document.light.page"),
    },
    TokenIdentity {
        path: "document.dark.backdrop",
        custom_property: "--document-dark-backdrop",
        typescript_path: "document.dark.backdrop",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.page",
        custom_property: "--document-dark-page",
        typescript_path: "document.dark.page",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.page-border",
        custom_property: "--document-dark-page-border",
        typescript_path: "document.dark.pageBorder",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.page-shadow",
        custom_property: "--document-dark-page-shadow",
        typescript_path: "document.dark.pageShadow",
        usage: None,
        background: None,
    },
    TokenIdentity {
        path: "document.dark.selection-fill",
        custom_property: "--document-dark-selection-fill",
        typescript_path: "document.dark.selectionFill",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.selection-handle",
        custom_property: "--document-dark-selection-handle",
        typescript_path: "document.dark.selectionHandle",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.alignment-guide",
        custom_property: "--document-dark-alignment-guide",
        typescript_path: "document.dark.alignmentGuide",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.grid-line",
        custom_property: "--document-dark-grid-line",
        typescript_path: "document.dark.gridLine",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.comment-anchor",
        custom_property: "--document-dark-comment-anchor",
        typescript_path: "document.dark.commentAnchor",
        usage: Some(ColorUsage::FillOnly),
        background: None,
    },
    TokenIdentity {
        path: "document.dark.tracked-change-insert",
        custom_property: "--document-dark-tracked-change-insert",
        typescript_path: "document.dark.trackedChangeInsert",
        usage: Some(ColorUsage::FillOnly),
        background: Some("document.dark.page"),
    },
    TokenIdentity {
        path: "document.dark.tracked-change-delete",
        custom_property: "--document-dark-tracked-change-delete",
        typescript_path: "document.dark.trackedChangeDelete",
        usage: Some(ColorUsage::FillOnly),
        background: Some("document.dark.page"),
    },
];
