//! **A golden image generated by the code under test always matches the code under test.**
//!
//! This file is the answer to that sentence, and it is written as failures rather than as passes:
//! each case builds a baseline that *would* compare green and asserts that the comparison refuses to
//! run at all.
//!
//! Four ways a baseline can fail to be one, and the first is MJXOFF-165's own wording — *"an
//! unapproved baseline fails, proved by adding one with no approval record"*:
//!
//! 1. **No approval record.** [`ApprovalState::Missing`].
//! 2. **An artefact whose bytes are not the ones approved.** [`ApprovalState::Stale`] — the case
//!    that makes regeneration visible, because an approval that named only a file *name* would be
//!    satisfied by whatever later appeared under it.
//! 3. **A record that cannot be read**, or one that approves a different specimen.
//!    [`ApprovalState::Malformed`], which is a failure and never an absence: treating an unreadable
//!    record as a missing one would let a corrupted file be "fixed" by regenerating.
//! 4. **An artefact that is not there at all.**
//!
//! # And the honest one
//!
//! Every baseline this crate ships is approved by [`Approver::Generator`], which is a real approval
//! record and **not a human review**. [`every_committed_baseline_is_listed_as_awaiting_review`] is
//! what stops that set ageing into an unexamined one: it asserts the listing sees all of them, so a
//! baseline cannot become quietly reviewed-looking by being ignored.

use std::path::PathBuf;

use mjx_render_oracle::baseline::{
    awaiting_human_review, Approval, ApprovalState, Approver, Baselines, APPROVAL_FILE, ARTEFACTS,
};
use mjx_render_oracle::specimen::{Perturbation, SPECIMENS};
use mjx_render_oracle::{compare_against_baseline, specimen};

/// A scratch baseline holding the real artefacts for `SUBJECT`, with no approval beside them.
const SUBJECT: &str = "solid-panels";

fn subject() -> specimen::Specimen {
    specimen::Specimen::named(SUBJECT).expect("the solid specimen is in the corpus")
}

/// Copy the committed artefacts into a scratch directory, without an approval.
fn scratch_with_artefacts(case: &str) -> (PathBuf, Baselines) {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../target/oracle-scratch")
        .join(case);
    let _ = std::fs::remove_dir_all(&directory);
    std::fs::create_dir_all(directory.join(SUBJECT)).expect("a scratch baseline directory");
    let committed = Baselines::committed();
    for artefact in ARTEFACTS {
        std::fs::write(
            directory.join(SUBJECT).join(artefact),
            committed.artefact(SUBJECT, artefact).expect("an artefact"),
        )
        .expect("copying an artefact");
    }
    let baselines = Baselines::at(&directory);
    (directory, baselines)
}

#[test]
fn a_baseline_with_no_approval_record_fails_rather_than_passes() {
    let (directory, baselines) = scratch_with_artefacts("no-approval");

    // Every artefact is present and every one is byte-identical to the committed baseline, so a
    // comparison would agree at all three tiers. It must not get that far.
    assert_eq!(baselines.approval(SUBJECT), ApprovalState::Missing);
    assert!(!baselines.approval(SUBJECT).is_usable());

    let refused = compare_against_baseline(&baselines, &subject(), Perturbation::None)
        .expect_err("an unapproved baseline must refuse to be compared against");
    assert!(
        refused.contains("nobody has approved it"),
        "the refusal does not say why: {refused}"
    );
    assert!(
        refused.contains(SUBJECT),
        "the refusal does not name the baseline: {refused}"
    );

    // And the same directory with an approval in it does compare — otherwise the case above would
    // pass for any reason at all, including a scratch path that does not exist.
    baselines
        .approve(
            SUBJECT,
            Approver::Generator,
            "the control for the case above",
        )
        .expect("approving the scratch baseline");
    let comparison = compare_against_baseline(&baselines, &subject(), Perturbation::None)
        .expect("an approved baseline compares");
    assert!(comparison.agreed(), "{comparison}");

    let _ = std::fs::remove_dir_all(&directory);
}

#[test]
fn an_artefact_that_moved_since_it_was_approved_is_stale() {
    let (directory, baselines) = scratch_with_artefacts("stale");
    baselines
        .approve(SUBJECT, Approver::Generator, "approved, then changed")
        .expect("approving");
    assert!(baselines.approval(SUBJECT).is_usable());

    // One byte. **This is the whole reason an approval records a digest**: without it, rewriting the
    // image under an approved name would compare against the new image and agree with itself.
    let path = directory.join(SUBJECT).join(ARTEFACTS[2]);
    let mut bytes = std::fs::read(&path).expect("the image");
    let last = bytes.len() - 1;
    bytes[last] ^= 0x01;
    std::fs::write(&path, &bytes).expect("rewriting the image");

    match baselines.approval(SUBJECT) {
        ApprovalState::Stale {
            artefact,
            recorded,
            actual,
        } => {
            assert_eq!(artefact, ARTEFACTS[2]);
            assert_ne!(recorded, actual);
            assert_eq!(recorded.len(), 64, "a digest is sixty-four hex digits");
        }
        other => panic!("a changed artefact was reported as {other:?}"),
    }
    let refused = compare_against_baseline(&baselines, &subject(), Perturbation::None)
        .expect_err("a stale baseline must refuse");
    assert!(
        refused.contains("does not re-approve"),
        "the refusal does not explain what to do: {refused}"
    );

    let _ = std::fs::remove_dir_all(&directory);
}

#[test]
fn a_missing_artefact_is_not_an_absent_approval() {
    let (directory, baselines) = scratch_with_artefacts("missing-artefact");
    baselines
        .approve(SUBJECT, Approver::Generator, "then an artefact disappears")
        .expect("approving");
    std::fs::remove_file(directory.join(SUBJECT).join(ARTEFACTS[1])).expect("removing a snapshot");

    match baselines.approval(SUBJECT) {
        ApprovalState::Stale {
            artefact, actual, ..
        } => {
            assert_eq!(artefact, ARTEFACTS[1]);
            assert!(
                actual.starts_with("absent"),
                "a missing artefact is not reported as missing: {actual}"
            );
        }
        other => panic!("a missing artefact was reported as {other:?}"),
    }
    let _ = std::fs::remove_dir_all(&directory);
}

#[test]
fn an_unreadable_record_is_a_failure_and_never_an_absence() {
    let (directory, baselines) = scratch_with_artefacts("malformed");
    let record = directory.join(SUBJECT).join(APPROVAL_FILE);

    for (text, expected) in [
        ("this is not a record", "not a `key = value` line"),
        (
            "specimen = solid-panels\nnote = x\n",
            "`approver` is missing",
        ),
        (
            "specimen = solid-panels\napprover = maybe\nnote = x\napproved-at = 1\n",
            "not human or generator",
        ),
        (
            "specimen = solid-panels\napprover = human\nnote = x\napproved-at = 1\n",
            "`approved-by` is missing",
        ),
        (
            "specimen = solid-panels\napprover = generator\nnote = x\napproved-at = later\n",
            "not a Unix second",
        ),
    ] {
        std::fs::write(&record, text).expect("writing a malformed record");
        match baselines.approval(SUBJECT) {
            ApprovalState::Malformed { reason } => assert!(
                reason.contains(expected),
                "`{text}` was refused with `{reason}`, which does not mention `{expected}`"
            ),
            other => panic!("`{text}` was accepted as {other:?}"),
        }
    }

    // A record that is perfectly readable and approves a *different* baseline is malformed too — a
    // record copied from one directory to another is otherwise an approval of bytes nobody looked
    // at.
    let stolen = Approval {
        specimen: "gradient-panel".to_owned(),
        approver: Approver::Generator,
        approved_at: 1,
        note: "a record from somewhere else".to_owned(),
        digests: ARTEFACTS
            .iter()
            .map(|name| ((*name).to_owned(), "0".repeat(64)))
            .collect(),
    };
    std::fs::write(&record, stolen.to_text()).expect("writing the stolen record");
    match baselines.approval(SUBJECT) {
        ApprovalState::Malformed { reason } => {
            assert!(reason.contains("gradient-panel"), "{reason}");
        }
        other => panic!("a record for another baseline was accepted as {other:?}"),
    }

    let _ = std::fs::remove_dir_all(&directory);
}

#[test]
fn a_record_survives_being_written_and_read_back() {
    let approval = Approval {
        specimen: "solid-panels".to_owned(),
        approver: Approver::Human {
            name: "A Person <person@example.invalid>".to_owned(),
        },
        approved_at: 1_788_800_000,
        note: "the fills are where the fragments put them".to_owned(),
        digests: vec![("render.png".to_owned(), "ab".repeat(32))],
    };
    let read = Approval::parse(&approval.to_text()).expect("a record this crate wrote parses");
    assert_eq!(read, approval);
    assert!(read.is_reviewed());
    assert_eq!(read.digest_of("render.png"), Some(&*"ab".repeat(32)));
    assert_eq!(read.digest_of("nothing.png"), None);

    // The date is derived from the second and never read back, so the two can never disagree.
    assert_eq!(approval.date(), "2026-09-07");
    assert_eq!(mjx_render_oracle::baseline::iso_date(0), "1970-01-01");
    assert_eq!(
        mjx_render_oracle::baseline::iso_date(951_782_400),
        "2000-02-29"
    );
}

#[test]
fn every_committed_baseline_is_listed_as_awaiting_review() {
    let names: Vec<&str> = SPECIMENS.iter().map(|specimen| specimen.name).collect();
    let awaiting = awaiting_human_review(&Baselines::committed(), &names);
    assert_eq!(
        awaiting.len(),
        names.len(),
        "**{} of {} committed baselines claim a human review.** If a person really has approved \
         one, this assertion is the thing to update — and if nobody has, the record is claiming \
         something untrue, which is worse than having no approval machinery at all.",
        names.len() - awaiting.len(),
        names.len()
    );
    for specimen in SPECIMENS {
        let approval = Baselines::committed().approval(specimen.name);
        assert!(
            approval.is_usable(),
            "`{}` is not usable: {}",
            specimen.name,
            approval.refusal().unwrap_or_default()
        );
        assert!(
            !approval.is_reviewed(),
            "`{}` claims a human review that this file does not know about",
            specimen.name
        );
    }
}
