//! `pic:pic` (`CT_Picture`, `dml-picture.xsd`) — a picture: its non-visual identity, the image it
//! shows (`a:blipFill`), and its shape properties (`a:spPr`) — the exact `CT_ShapeProperties`
//! [`crate::shape_properties::ShapeProperties`] models, so a picture's crop rectangle, outline and
//! transform read through the same accessors a shape's do.
//!
//! `dml-picture.xsd` is three complex types and eleven lines: `CT_Picture` (`nvPicPr`, `blipFill`,
//! `spPr`), `CT_PictureNonVisual` (`cNvPr` + `cNvPicPr`) and the `pic` root element. Every child the
//! schema declares is typed here, and — since **MJXOFF-216/MJXOFF-217** — everything it does not
//! declare is kept: both types hold an ordered content vector with a `Raw` variant, generated by
//! `mjx-derive`, so the element's own name and prefix, its attributes, its self-closing flag and any
//! child beside the declared three all survive a rebuild.
//!
//! That was not true until 0.0.138. Both types hand-wrote their
//! [`FromXml`](mjx_ooxml_core::FromXml)/[`ToXml`](mjx_ooxml_core::ToXml) pair, read
//! three children by local name and discarded every other one, and rebuilt with a synthesised name
//! and an empty attribute vector — and this module's own doc comment said the opposite, which is
//! what made the gap look deliberate. The fix is not a bucket bolted on: it is *moving both types
//! onto the derive*, so they are covered by `crates/mjx-derive/tests/derive.rs` along with every
//! other derived type rather than by a promise made here.

use mjx_ooxml_core::{Interner, RawAttribute, RawName, RawNode};
use mjx_ooxml_types::namespaces::DML_PICTURE;

use crate::fill::PictureFill;
use crate::nonvisual::{NonVisualDrawingProps, NonVisualPictureProperties};
use crate::shape_properties::ShapeProperties;

/// Builds a `pic:local` qualified name in the DrawingML-picture namespace.
fn pic_name(interner: &mut Interner, local: &str) -> RawName {
    RawName {
        prefix: Some(interner.intern("pic")),
        local: interner.intern(local),
        namespace: Some(interner.intern(DML_PICTURE.transitional)),
    }
}

/// One ordered child of a [`PictureNonVisual`]: one of the two the schema declares, or an opaque
/// node kept exactly where it stood.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PictureNonVisualContent {
    /// `pic:cNvPr` — the picture's id, name, description, hidden flag and title.
    DrawingProps(NonVisualDrawingProps),
    /// `pic:cNvPicPr` — the picture's lock list and `@preferRelativeResize`.
    PictureProps(NonVisualPictureProperties),
    /// Any other child — a comment, whitespace, or a foreign element — preserved verbatim.
    Raw(RawNode),
}

/// `pic:nvPicPr` (`CT_PictureNonVisual`) — a picture's non-visual identity: `cNvPr` (its id/name/
/// description/hidden/title) and `cNvPicPr` (its lock list and `preferRelativeResize`).
///
/// The two declared children are typed; anything else keeps its position and its bytes. `cNvPr` and
/// `cNvPicPr` are *local* element declarations inside `dml-picture.xsd`, so they take `pic:`'s own
/// namespace even though their **types** are DrawingML-main's — which is why the derive is told
/// [`DML_PICTURE`] rather than `DML_MAIN`, and the same distinction
/// [`crate::wordprocessing_drawing`]'s module doc draws for `wp:docPr`.
#[derive(Debug, Clone, PartialEq, Eq, mjx_derive::FromXml, mjx_derive::ToXml)]
#[xml(namespace = DML_PICTURE)]
pub struct PictureNonVisual {
    name: RawName,
    attributes: Vec<RawAttribute>,
    empty: bool,
    #[xml(
        children,
        child(local = "cNvPr", variant = DrawingProps, ty = NonVisualDrawingProps),
        child(local = "cNvPicPr", variant = PictureProps, ty = NonVisualPictureProperties)
    )]
    children: Vec<PictureNonVisualContent>,
}

impl PictureNonVisual {
    /// Builds `<pic:nvPicPr><pic:cNvPr id="{id}" name="{name}"/><pic:cNvPicPr/></pic:nvPicPr>`.
    #[must_use]
    pub fn new(interner: &mut Interner, id: u32, name: &str) -> Self {
        let element_name = pic_name(interner, "nvPicPr");
        let cnv_pr_name = pic_name(interner, "cNvPr");
        let cnv_pic_pr_name = pic_name(interner, "cNvPicPr");
        Self {
            name: element_name,
            attributes: Vec::new(),
            empty: false,
            children: vec![
                PictureNonVisualContent::DrawingProps(NonVisualDrawingProps::with_name(
                    interner,
                    cnv_pr_name,
                    id,
                    name,
                )),
                PictureNonVisualContent::PictureProps(NonVisualPictureProperties::with_name(
                    interner,
                    cnv_pic_pr_name,
                )),
            ],
        }
    }

    /// The picture's own identity (`pic:cNvPr`), or `None` when the element is malformed (the
    /// schema requires it).
    #[must_use]
    pub fn drawing_props(&self) -> Option<&NonVisualDrawingProps> {
        self.children.iter().find_map(|child| match child {
            PictureNonVisualContent::DrawingProps(props) => Some(props),
            _ => None,
        })
    }

    /// The picture's own identity (`pic:cNvPr`), mutably.
    pub fn drawing_props_mut(&mut self) -> Option<&mut NonVisualDrawingProps> {
        self.children.iter_mut().find_map(|child| match child {
            PictureNonVisualContent::DrawingProps(props) => Some(props),
            _ => None,
        })
    }

    /// The picture's own lock list and resize preference (`pic:cNvPicPr`), or `None` when the
    /// element is malformed (the schema requires it).
    #[must_use]
    pub fn picture_props(&self) -> Option<&NonVisualPictureProperties> {
        self.children.iter().find_map(|child| match child {
            PictureNonVisualContent::PictureProps(props) => Some(props),
            _ => None,
        })
    }
}

/// One ordered child of a [`Picture`]: one of the three `CT_Picture` declares, or an opaque node
/// kept exactly where it stood.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PictureContent {
    /// `pic:nvPicPr` — the picture's non-visual identity.
    NonVisual(PictureNonVisual),
    /// `pic:blipFill` — the image itself.
    Fill(PictureFill),
    /// `pic:spPr` — the picture's transform, crop geometry, outline and effects.
    Properties(ShapeProperties),
    /// Any other child — a comment, whitespace, or a foreign element — preserved verbatim.
    Raw(RawNode),
}

/// `pic:pic` (`CT_Picture`) — a picture: `nvPicPr`, `blipFill` (required, unlike `spPr`'s own
/// `EG_FillProperties` — this is *the* fill, not one alternative), then `spPr`.
///
/// The three declared children are typed; anything else keeps its position and its bytes.
#[derive(Debug, Clone, PartialEq, Eq, mjx_derive::FromXml, mjx_derive::ToXml)]
#[xml(namespace = DML_PICTURE)]
pub struct Picture {
    name: RawName,
    attributes: Vec<RawAttribute>,
    empty: bool,
    #[xml(
        children,
        child(local = "nvPicPr", variant = NonVisual, ty = PictureNonVisual),
        child(local = "blipFill", variant = Fill, ty = PictureFill),
        child(local = "spPr", variant = Properties, ty = ShapeProperties)
    )]
    children: Vec<PictureContent>,
}

impl Picture {
    /// Builds `<pic:pic>` around the given non-visual identity, image fill and shape properties.
    #[must_use]
    pub fn new(
        interner: &mut Interner,
        non_visual: PictureNonVisual,
        fill: PictureFill,
        shape_properties: ShapeProperties,
    ) -> Self {
        Self {
            name: pic_name(interner, "pic"),
            attributes: Vec::new(),
            empty: false,
            children: vec![
                PictureContent::NonVisual(non_visual),
                PictureContent::Fill(fill),
                PictureContent::Properties(shape_properties),
            ],
        }
    }

    /// The picture's non-visual identity (`pic:nvPicPr`), or `None` when the element is malformed
    /// (the schema requires it).
    #[must_use]
    pub fn non_visual(&self) -> Option<&PictureNonVisual> {
        self.children.iter().find_map(|child| match child {
            PictureContent::NonVisual(value) => Some(value),
            _ => None,
        })
    }

    /// The picture's non-visual identity (`pic:nvPicPr`), mutably.
    pub fn non_visual_mut(&mut self) -> Option<&mut PictureNonVisual> {
        self.children.iter_mut().find_map(|child| match child {
            PictureContent::NonVisual(value) => Some(value),
            _ => None,
        })
    }

    /// The picture's image fill (`pic:blipFill`), holding the `a:blip@r:embed`/`@r:link`
    /// relationship id that resolves to the image part. `None` when the element is malformed (the
    /// schema requires it).
    #[must_use]
    pub fn fill(&self) -> Option<&PictureFill> {
        self.children.iter().find_map(|child| match child {
            PictureContent::Fill(value) => Some(value),
            _ => None,
        })
    }

    /// The picture's image fill (`pic:blipFill`), mutably.
    pub fn fill_mut(&mut self) -> Option<&mut PictureFill> {
        self.children.iter_mut().find_map(|child| match child {
            PictureContent::Fill(value) => Some(value),
            _ => None,
        })
    }

    /// The picture's shape properties (`pic:spPr`) — transform, crop geometry, outline. `None` when
    /// the element is malformed (the schema requires it).
    #[must_use]
    pub fn shape_properties(&self) -> Option<&ShapeProperties> {
        self.children.iter().find_map(|child| match child {
            PictureContent::Properties(value) => Some(value),
            _ => None,
        })
    }

    /// The picture's shape properties (`pic:spPr`), mutably.
    pub fn shape_properties_mut(&mut self) -> Option<&mut ShapeProperties> {
        self.children.iter_mut().find_map(|child| match child {
            PictureContent::Properties(value) => Some(value),
            _ => None,
        })
    }

    /// The embedded image relationship id (`pic:blipFill/a:blip@r:embed`), or `None` if this
    /// picture links an external image instead (`@r:link`), names neither, or has no `blipFill` at
    /// all.
    #[must_use]
    pub fn image_rel_id(&self, interner: &Interner) -> Option<String> {
        self.fill()?.image_rel_id(interner)
    }
}

/// A fresh, minimally-complete picture: `id`/`name` for its identity, `rel_id` naming the image part
/// relationship, and a `1 x 1` EMU transform placeholder a caller is expected to resize immediately
/// (the schema requires `a:off`/`a:ext` to be present once `a:xfrm` is written at all, so an inserted
/// picture cannot leave them unstated).
#[must_use]
pub fn new_picture(interner: &mut Interner, id: u32, name: &str, rel_id: &str) -> Picture {
    let non_visual = PictureNonVisual::new(interner, id, name);
    let blip_fill_name = pic_name(interner, "blipFill");
    let fill = PictureFill::with_name(
        interner,
        blip_fill_name,
        rel_id,
        crate::fill::PictureFillMode::Stretch,
    );
    let sp_pr_name = pic_name(interner, "spPr");
    let mut shape_properties = ShapeProperties::with_name(interner, sp_pr_name);
    shape_properties.set_transform(
        interner,
        crate::geometry::Transform2D {
            position: Some(crate::geometry::Position::from_emu(0, 0)),
            size: Some(crate::geometry::Size::from_emu(1, 1)),
            ..crate::geometry::Transform2D::default()
        },
    );
    let rectangle = crate::geometry::PresetGeometry::new(
        interner,
        mjx_ooxml_types::drawingml::PresetShapeType::Rectangle,
        None,
    );
    shape_properties.set_geometry(
        interner,
        crate::shape_properties::ShapeGeometryChoice::Preset(rectangle),
    );
    Picture::new(interner, non_visual, fill, shape_properties)
}
