//! Generating the whole pack, and the preliminary pass over it.
//!
//! # Reproducible, and what that costs
//!
//! [`generate`] writes the same bytes every time it runs. That is not decoration: the person doing
//! the sitting may generate the pack on a Monday and export it on a Thursday, and *"is this the pack
//! the harness expects?"* has to be answerable by comparing bytes rather than by trusting a memory.
//! It falls out of the authoring being a pure function of committed tables — no timestamps, no
//! random ids, no hash-map iteration order — and `tests/the_decks_generate_reproducibly.rs` is what
//! stops that quietly ceasing to be true.
//!
//! # The preliminary pass, and exactly what it is worth
//!
//! [`preliminary_pass`] converts each artefact with LibreOffice, rasterises both sides with one
//! rasteriser, and produces one [`Baseline`] per plate. **Every one of them is
//! [`ReferenceAuthority::Provisional`](mjx_text::ReferenceAuthority::Provisional), and
//! [`parity_count`](crate::parity_count) over the result is zero by construction.** It is a change
//! detector: it catches *"this used to render and now does not"* across all 187 shapes before a
//! person spends a Windows morning on them, and it is worth running for that and for nothing else.

use std::path::{Path, PathBuf};

use crate::authority::{Baseline, ReferenceProvider, RenderedContent, Verdict};
use crate::compare::plate_baseline;
use crate::deck::preset_deck;
use crate::hanging::{hanging_document, FILE_NAME as HANGING_FILE};
use crate::plates::{plates, PresetDeck};
use crate::scene::our_page_as_pdf;
use crate::tools::{convert_to_pdf, page_count, rasterise, Raster};
use crate::typography::{specimen_deck, FILE_NAME as SPECIMEN_FILE};
use crate::{ARTEFACTS, THE_SITTING};

/// One artefact, as bytes.
#[derive(Debug)]
pub struct Artefact {
    /// Its file name, which is the name the instructions use.
    pub name: &'static str,
    /// Its bytes.
    pub bytes: Vec<u8>,
}

/// Every artefact in the pack, in the order a person works through them.
///
/// # Errors
///
/// A sentence naming the artefact that would not be authored. Nothing here is input-driven, so a
/// failure is a defect in this crate or in a generated table.
pub fn artefacts() -> Result<Vec<Artefact>, String> {
    let mut built = Vec::new();
    for which in PresetDeck::ALL {
        built.push(Artefact {
            name: which.file_name(),
            bytes: preset_deck(which)
                .map_err(|error| format!("authoring {}: {error}", which.file_name()))?,
        });
    }
    built.push(Artefact {
        name: SPECIMEN_FILE,
        bytes: specimen_deck().map_err(|error| format!("authoring {SPECIMEN_FILE}: {error}"))?,
    });
    built.push(Artefact {
        name: HANGING_FILE,
        bytes: hanging_document().map_err(|error| format!("authoring {HANGING_FILE}: {error}"))?,
    });
    debug_assert_eq!(
        built
            .iter()
            .map(|artefact| artefact.name)
            .collect::<Vec<_>>(),
        ARTEFACTS,
        "the artefact list and the artefacts themselves have drifted"
    );
    Ok(built)
}

/// Write the pack into `directory`, with its instructions beside it.
///
/// # Errors
///
/// A sentence naming what could not be written.
pub fn generate(directory: &Path) -> Result<Vec<PathBuf>, String> {
    std::fs::create_dir_all(directory)
        .map_err(|error| format!("creating {}: {error}", directory.display()))?;
    let mut written = Vec::new();
    for artefact in artefacts()? {
        let path = directory.join(artefact.name);
        std::fs::write(&path, &artefact.bytes)
            .map_err(|error| format!("writing {}: {error}", path.display()))?;
        written.push(path);
    }
    let path = directory.join("INSTRUCTIONS.md");
    std::fs::write(&path, instructions())
        .map_err(|error| format!("writing {}: {error}", path.display()))?;
    written.push(path);
    Ok(written)
}

/// The instructions written beside the pack.
///
/// **Generated from the same tables the artefacts are**, so a renamed file or a new item cannot
/// leave the instructions describing a pack that no longer exists. The prose version a person reads
/// before the day — `docs/validation/07-the-reference-pack.md` — is committed and hand-written, and
/// `tests/the_instructions_are_complete.rs` holds the two in step by requiring every key and every
/// artefact name here to appear there.
#[must_use]
pub fn instructions() -> String {
    let mut text = String::new();
    text.push_str(
        "# The reference pack — what to do with these files\n\n\
         Generated by `cargo run -p mjx-reference-pack -- generate`. Everything here is derived \
         from the same tables the artefacts are, so it cannot describe a pack that does not \
         exist.\n\n\
         **This is one sitting.** Seven open questions are answered by opening four files, \
         exporting each one to PDF, and putting the PDFs in one directory. Nothing asks you to \
         measure anything or to judge whether a picture looks right.\n\n",
    );

    text.push_str("## What to do\n\n");
    for (position, artefact) in ARTEFACTS.iter().enumerate() {
        text.push_str(&format!(
            "{}. Open `{artefact}` in the real Microsoft application. Do not edit it. \
             **File → Export → Create PDF/XPS**, or **Save a Copy** with type PDF. Save it beside \
             the original as `{}.pdf`.\n",
            position + 1,
            artefact
                .rsplit_once('.')
                .map_or(*artefact, |(stem, _)| stem)
        ));
    }
    text.push_str(&format!(
        "\nThen copy the four PDFs into `{}` in the repository and commit them.\n\n",
        crate::OFFICE_EXPORT_DIRECTORY
    ));

    text.push_str("## What NOT to do\n\n");
    text.push_str(
        "* **Do not print to a PDF printer.** A print driver rasterises; the export keeps the \
         vectors and the glyph positions, which is the whole point.\n\
         * **Do not open the files in LibreOffice and export from there.** That comparison already \
         runs on every machine and is explicitly not evidence.\n\
         * **Do not edit, re-save or \"repair\" an artefact.** If Office offers to repair one, stop \
         and report that instead: a file this library wrote that Office will not open is a finding \
         worth more than the pass.\n\
         * **Do not change the theme, the fonts or the slide size.**\n\
         * **Do not fill the corpus directory with anything this project wrote.** Its value is \
         entirely its provenance.\n\n",
    );

    text.push_str("## What each file asks\n\n");
    for item in THE_SITTING {
        text.push_str(&format!(
            "### `{}` — {}\n\n{}\n\n*Read from the export by:* {}\n\n",
            item.key, item.artefact, item.question, item.how_it_is_read
        ));
    }

    text.push_str("## What comes back, and what it will and will not prove\n\n");
    text.push_str(
        "`cargo run -p mjx-reference-pack -- ingest` reads the four PDFs out of that one directory and \
         reports one row per plate, per probe and per hatch. It takes no directory and no provider \
         argument: a call that took either would let a LibreOffice PDF be recorded as Office's.\n\n\
         Until those PDFs exist, **every row this harness can produce is `Provisional` and none of \
         them may be recorded as parity**. A green LibreOffice run means *nothing obviously broke*. \
         It is not parity, it has never been parity, and it must never be written down as \
         fidelity.\n",
    );
    text
}

/// One artefact's LibreOffice conversion and the rows it produced.
#[derive(Debug)]
pub struct PassResult {
    /// The artefact.
    pub artefact: &'static str,
    /// The PDF LibreOffice wrote, if it wrote one.
    pub pdf: Option<PathBuf>,
    /// One row per plate.
    pub baselines: Vec<Baseline>,
}

/// Run the preliminary pass over one preset deck already written into `directory`.
///
/// Every plate gets a row. A plate whose conversion or rasterisation failed gets a row **saying so**
/// rather than being dropped: a quietly-skipped case is indistinguishable from a check that never
/// existed, and 187 rows of which some are `not evidence` is a report, while 140 rows is a mystery.
///
/// # Errors
///
/// A sentence, only for a failure that stops the whole artefact — LibreOffice refusing the file, or
/// the PDF having no pages. A per-plate failure is a row, not an error.
pub fn preliminary_pass(directory: &Path, which: PresetDeck) -> Result<PassResult, String> {
    let source = directory.join(which.file_name());
    let pdf = convert_to_pdf(&source, directory)?;
    let pages = page_count(&pdf)?;
    let plates = plates(which);
    let expected = crate::layout::pages_for(plates.len());
    if pages != expected {
        return Err(format!(
            "LibreOffice's PDF of {} has {pages} pages and the deck has {expected} slides; the \
             plate map would be off by a page and every row would be wrong",
            which.file_name()
        ));
    }

    let mut baselines = Vec::with_capacity(plates.len());
    for page in 0..pages {
        let reference = rasterise(&pdf, page + 1);
        let ours = our_page_as_pdf(&plates, page)
            .map_err(|error| format!("exporting our own page {page}: {error}"))
            .and_then(|render| {
                let path = directory.join(format!("ours-{}-{page}.pdf", which.file_name()));
                std::fs::write(&path, &render.pdf)
                    .map_err(|error| format!("writing {}: {error}", path.display()))?;
                rasterise(&path, 1)
            });
        for plate in plates.iter().filter(|plate| plate.page() == page) {
            baselines.push(row(plate, reference.as_ref(), ours.as_ref(), which));
        }
    }
    Ok(PassResult {
        artefact: which.file_name(),
        pdf: Some(pdf),
        baselines,
    })
}

/// One plate's row, including when one of the two rasters does not exist.
fn row(
    plate: &crate::Plate,
    reference: Result<&Raster, &String>,
    ours: Result<&Raster, &String>,
    which: PresetDeck,
) -> Baseline {
    match (reference, ours) {
        (Ok(reference), Ok(ours)) => plate_baseline(
            plate,
            reference,
            ours,
            ReferenceProvider::LibreOffice,
            which.file_name(),
        ),
        (Err(reason), _) | (_, Err(reason)) => Baseline {
            subject: plate.token.to_owned(),
            provenance: format!("{}, page {}", which.file_name(), plate.page() + 1),
            provider: ReferenceProvider::LibreOffice,
            authority: ReferenceProvider::LibreOffice.authority(),
            content: RenderedContent::Outline,
            verdict: Verdict::NotEvidence {
                reason: format!("this page could not be rasterised: {reason}"),
            },
        },
    }
}

/// The authoritative pass: read whatever Microsoft Office exported, out of the one directory Office
/// exports live in.
///
/// # ⚠ The provider is not a parameter, and that is the point
///
/// This reads [`crate::OFFICE_EXPORT_DIRECTORY`] and nothing else, and stamps every row
/// [`ReferenceProvider::OfficeExport`]. It does **not** take a directory, and it does not take a
/// provider — because a call that took either would let a LibreOffice PDF be pointed at it and
/// recorded as Office's, which is precisely the trap this whole crate is built against. The
/// LibreOffice path is [`preliminary_pass`], and that one hard-codes
/// [`ReferenceProvider::LibreOffice`] for the same reason in the other direction.
///
/// With the directory empty — which is its committed state — every row is
/// [`Verdict::NotEvidence`] naming the absent file. That is the honest answer and it is a *report*,
/// not an error: a person has not run Office yet, and no build can fix that.
///
/// # Errors
///
/// A sentence, only for a failure that stops the whole run.
pub fn office_pass() -> Result<Vec<Baseline>, String> {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(crate::OFFICE_EXPORT_DIRECTORY);
    let mut rows = Vec::new();

    for which in PresetDeck::ALL {
        let export = directory.join(export_name(which.file_name()));
        let plates = plates(which);
        if !export.is_file() {
            rows.extend(plates.iter().map(|plate| Baseline {
                subject: plate.token.to_owned(),
                provenance: format!("{}", export.display()),
                provider: ReferenceProvider::OfficeExport,
                authority: ReferenceProvider::OfficeExport.authority(),
                content: RenderedContent::Outline,
                verdict: Verdict::NotEvidence {
                    reason: format!(
                        "there is no Office export at {}; the reference is the one thing an agent \
                         cannot produce",
                        export.display()
                    ),
                },
            }));
            continue;
        }
        // **A page-count mismatch is a row for every plate, not a shorter report.** Taking the
        // smaller of the two counts would silently drop the plates on the pages that did not line
        // up, and a report with 140 rows where the deck has 187 is a mystery rather than a finding.
        let pages = page_count(&export)?;
        let expected = crate::layout::pages_for(plates.len());
        if pages != expected {
            rows.extend(plates.iter().map(|plate| Baseline {
                subject: plate.token.to_owned(),
                provenance: format!("{}", export.display()),
                provider: ReferenceProvider::OfficeExport,
                authority: ReferenceProvider::OfficeExport.authority(),
                content: RenderedContent::Outline,
                verdict: Verdict::NotEvidence {
                    reason: format!(
                        "the export of {} has {pages} pages and the deck has {expected} slides, so                          the plate map would be off by a page and every row would be about a                          different preset",
                        which.file_name()
                    ),
                },
            }));
            continue;
        }
        for page in 0..pages {
            let reference = rasterise(&export, page + 1);
            let scratch = directory.join(format!(
                "../../../target/reference-pack/office-{}-{page}.pdf",
                which.file_name()
            ));
            let ours = our_page_as_pdf(&plates, page)
                .map_err(|error| format!("exporting our own page {page}: {error}"))
                .and_then(|render| {
                    if let Some(parent) = scratch.parent() {
                        std::fs::create_dir_all(parent)
                            .map_err(|error| format!("creating {}: {error}", parent.display()))?;
                    }
                    std::fs::write(&scratch, &render.pdf)
                        .map_err(|error| format!("writing {}: {error}", scratch.display()))?;
                    rasterise(&scratch, 1)
                });
            for plate in plates.iter().filter(|plate| plate.page() == page) {
                rows.push(match (reference.as_ref(), ours.as_ref()) {
                    (Ok(reference), Ok(ours)) => plate_baseline(
                        plate,
                        reference,
                        ours,
                        ReferenceProvider::OfficeExport,
                        which.file_name(),
                    ),
                    (Err(reason), _) | (_, Err(reason)) => Baseline {
                        subject: plate.token.to_owned(),
                        provenance: format!("{}, page {}", which.file_name(), page + 1),
                        provider: ReferenceProvider::OfficeExport,
                        authority: ReferenceProvider::OfficeExport.authority(),
                        content: RenderedContent::Outline,
                        verdict: Verdict::NotEvidence {
                            reason: format!("this page could not be rasterised: {reason}"),
                        },
                    },
                });
            }
        }
    }

    // The typography and hatch items, out of the specimen deck and the hanging document.
    let specimens = directory.join(export_name(SPECIMEN_FILE));
    let hanging = directory.join(export_name(HANGING_FILE));
    if specimens.is_file() && hanging.is_file() {
        let advances = crate::ingest::read_advances(&specimens)?;
        let pitches = crate::ingest::read_line_pitch(&specimens)?;
        let hangs = crate::ingest::read_hanging(&hanging)?;
        let hatches = crate::ingest::read_hatch_tiles(&specimens)?;
        rows.extend(crate::ingest::as_baselines(
            &advances,
            &pitches,
            &hangs,
            &hatches,
            ReferenceProvider::OfficeExport,
            SPECIMEN_FILE,
        ));
    } else {
        for (name, path) in [(SPECIMEN_FILE, &specimens), (HANGING_FILE, &hanging)] {
            rows.push(Baseline {
                subject: name.to_owned(),
                provenance: format!("{}", path.display()),
                provider: ReferenceProvider::OfficeExport,
                authority: ReferenceProvider::OfficeExport.authority(),
                content: RenderedContent::TextLayout,
                verdict: Verdict::NotEvidence {
                    reason: format!("there is no Office export at {}", path.display()),
                },
            });
        }
    }
    Ok(rows)
}

/// What an artefact's export is called: the same stem with a `.pdf` on it.
#[must_use]
pub fn export_name(artefact: &str) -> String {
    artefact.rsplit_once('.').map_or_else(
        || format!("{artefact}.pdf"),
        |(stem, _)| format!("{stem}.pdf"),
    )
}

/// A printable table of one pass's rows, with the counts a reader needs in order not to misread it.
#[must_use]
pub fn report(baselines: &[Baseline]) -> String {
    let mut text = String::new();
    for baseline in baselines {
        text.push_str(&format!("{baseline}\n"));
    }
    let agreed = baselines.iter().filter(|row| row.verdict.is_pass()).count();
    let differs = baselines
        .iter()
        .filter(|row| row.verdict.is_failure())
        .count();
    let excluded = baselines
        .iter()
        .filter(|row| !row.verdict.is_evidence())
        .count();
    text.push_str(&format!(
        "\n{} row(s): {agreed} agreed, {differs} differ, {excluded} not evidence. \
         {} may be called parity.\n",
        baselines.len(),
        crate::parity_count(baselines)
    ));
    // The closing sentence is chosen from what the rows actually say, not printed unconditionally:
    // a report over Office exports that ended "a LibreOffice agreement is not parity" would be
    // describing a run that did not happen, and a reader would stop believing the line that matters.
    let provisional = baselines.iter().any(Baseline::is_provisional);
    let authoritative = baselines.iter().any(|row| row.provider.is_authoritative());
    text.push_str(match (provisional, authoritative) {
        (true, false) => {
            "A LibreOffice agreement means `nothing obviously broke`. It is not parity, and this \
             harness cannot make it one.\n"
        }
        (false, true) => {
            "These rows came from an authoritative reference, so an agreement here is parity and a \
             difference here is a finding. Neither is true of any other provider.\n"
        }
        (true, true) => {
            "This report mixes providers. Only the rows from an authoritative reference may be \
             called parity; `provisional_baselines` lists the rest, and every one of those must be \
             re-adjudicated.\n"
        }
        (false, false) => {
            "No provider in this report can produce evidence, so nothing here is a pass or a \
             failure.\n"
        }
    });
    text
}
