//! **Tier one, over the Word corpus.** One committed text snapshot per page, compared line by line,
//! so a position regression surfaces as *"line 14: node 6's rect is 152400 wide and was 101600"*
//! rather than as a mysterious picture.
//!
//! # Why this is here and not in `mjx-render-oracle`
//!
//! MJXOFF-165 built exactly this machinery — the three assertion tiers, the localisation, the
//! approval records — and this ticket asks for it to be used. **It cannot be, and the reason is
//! structural rather than a preference.** `mjx-render-oracle` depends on `mjx-paint`, which links
//! Vulkan; `xtask/tests/layering.rs` therefore forbids *any* ranked crate from naming it, in either
//! dependency section, because a test build that links Vulkan is still a build that links Vulkan.
//! This crate has a rank, so the edge is refused by name.
//!
//! The oracle cannot host these snapshots either: it is specified to name no format crate at all —
//! it is the rendering path with no document anywhere in it — and a specimen read from a `.docx`
//! would make every one of its baselines a baseline of the box model as well as of the renderer,
//! which is exactly the confusion it was built to prevent.
//!
//! So the *technique* is copied and the crate is not, exactly as `mjx-layout-pptx` and
//! `mjx-layout-xlsx` do: the same line shape, and deliberately **no glyph ids**, because a baseline
//! holding glyph ids is a baseline of a shaper version and a patch release of `swash` would expire
//! it for a reason that has nothing to do with layout.
//!
//! # What a Word baseline catches that a slide's and a sheet's cannot
//!
//! A page **boundary**. Every specimen below is reached the way a reader reaches it — page by page,
//! through each checkpoint — so a baseline of page one is also a check that resumption produces the
//! same page, and a baseline of the *last* page is a check that the boundaries before it did not
//! drift.
//!
//! # ⚠ Regeneration is deliberately not automatic
//!
//! A golden file generated by the code under test always matches the code under test. So
//! regeneration refuses without `MJX_LAYOUT_DOCX_REGENERATE=1`, and every committed baseline states
//! who approved it. Today every one says `generator`, which is a real record — it says the file is a
//! **change detector** and that no person has looked at it — and is not a human review. The Windows
//! sitting is where a person approves what these numbers should be.

mod support;

use std::path::{Path, PathBuf};

use mjx_docx::Document;
use mjx_layout::{BoxModel, Constraints, PageIndex};
use mjx_layout_docx::{constraints_for, DocumentFlow};
use support::{model, snapshot};

/// One page of one document, with a committed baseline.
struct Specimen {
    /// The fixture it is read from.
    file: &'static str,
    /// Which page, counted from zero.
    page: u32,
    /// Why this one is in the corpus — the thing its snapshot would notice.
    covers: &'static str,
}

/// The corpus. **Committed fixtures only**: a baseline over a document this crate *authored* would
/// move whenever `Document::blank` changed a default, which is a regression in a different crate.
const CORPUS: &[Specimen] = &[
    Specimen {
        file: "sample.docx",
        page: 0,
        covers: "the plainest document there is: a body of paragraphs and one section",
    },
    Specimen {
        file: "paragraph_properties.docx",
        page: 0,
        covers:
            "the `w:pPr` fixture — alignment, indents, spacing, tab stops and the keep flags, all \
             in one place, which is every input this crate's geometry is computed from",
    },
    Specimen {
        file: "effective_properties.docx",
        page: 0,
        covers: "the ladder fixture: `w:docDefaults`, a `w:basedOn` chain, a numbering level and \
             direct formatting all stating the same members, so a change in `mjx-docx`'s \
             resolution moves these numbers",
    },
    Specimen {
        file: "run_properties.docx",
        page: 0,
        covers: "`w:rPr` — the font, the size and the two style axes a shaped run is asked for",
    },
    Specimen {
        file: "run_content.docx",
        page: 0,
        covers:
            "the run-content fixture: the tabs, breaks and hyphens that become characters, and \
             the ones that deliberately do not",
    },
    Specimen {
        file: "three_section_document.docx",
        page: 0,
        covers:
            "three sections, of which this child lays out the first's geometry and reports the \
             other two — sections themselves are R20",
    },
    Specimen {
        file: "numbering_definitions.docx",
        page: 0,
        covers:
            "paragraphs in lists, whose **indents** are laid out from the numbering level's own \
             `w:pPr` while their numbers are not drawn at all (R22)",
    },
    Specimen {
        file: "style_based_on_chain.docx",
        page: 0,
        covers:
            "a deep `w:basedOn` chain, resolved once by the residency rather than per paragraph",
    },
];

impl Specimen {
    fn baseline(&self) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/baselines")
            .join(format!(
                "{}-page{}.txt",
                self.file.trim_end_matches(".docx"),
                self.page
            ))
    }

    /// The snapshot this specimen produces now.
    fn taken(&self) -> String {
        let mut document =
            Document::open(&mjx_fixtures::fixture(self.file)).expect("a committed fixture opens");
        let flow = DocumentFlow::read(&mut document).expect("the document resolves");
        let constraints = flow
            .formatting()
            .sections()
            .first()
            .map_or_else(default_constraints, constraints_for);

        // Reached the way a reader reaches it — page by page, through each checkpoint — so a
        // baseline of page one is also a check that resumption produces the same page.
        let mut model = model();
        let mut resume = None;
        let mut tree = None;
        let mut pages = 0_u32;
        for number in 0..=self.page {
            let Ok(page) =
                model.layout_page(&flow, PageIndex::new(number), &constraints, resume.as_ref())
            else {
                break;
            };
            resume = page.continuation().cloned();
            pages = number + 1;
            let last = resume.is_none();
            let (fragments, _) = page.into_parts();
            tree = Some(fragments);
            if last {
                break;
            }
        }
        let tree = tree.expect("the specimen lays out at least one page");
        format!(
            "# specimen: {} page {}\n# covers: {}\n# approver: generator\n# approval: a change \
             detector written by the code under test; no person has reviewed these numbers, and \
             the Windows sitting is where one will\n# paragraphs in the document: {}\n# pages \
             reached: {}\n{}",
            self.file,
            self.page,
            self.covers,
            flow.paragraph_count(),
            pages,
            snapshot(&tree)
        )
    }
}

/// US Letter with one-inch margins, for a fixture whose section states no page size.
fn default_constraints() -> Constraints {
    use mjx_ooxml_core::measure::Emu;
    Constraints::single_column(
        mjx_layout::LayoutSize {
            width: Emu::from_inches(8.5),
            height: Emu::from_inches(11.0),
        },
        Emu::from_inches(1.0),
    )
}

/// A baseline's text, with trailing whitespace stripped and a trailing blank line dropped, so an
/// editor that adds or removes a final newline cannot expire an approval.
fn normalise(text: &str) -> Vec<String> {
    let mut lines: Vec<String> = text
        .lines()
        .map(|line| line.trim_end().to_owned())
        .collect();
    while lines.last().is_some_and(String::is_empty) {
        lines.pop();
    }
    lines
}

/// The first line at which two snapshots differ, quoted from both sides.
///
/// **One line, not a whole diff.** A page is hundreds of lines and a failure that printed all of
/// them would be scrolled past; the first divergence is where a reader has to look and every later
/// one is usually its consequence.
fn first_difference(taken: &[String], baseline: &[String]) -> Option<String> {
    for (number, (mine, theirs)) in taken.iter().zip(baseline.iter()).enumerate() {
        if mine != theirs {
            return Some(format!(
                "line {}:\n  baseline: {theirs}\n  this run: {mine}",
                number + 1
            ));
        }
    }
    match taken.len().cmp(&baseline.len()) {
        std::cmp::Ordering::Equal => None,
        std::cmp::Ordering::Greater => Some(format!(
            "line {}: the baseline ends here and this run adds `{}` ({} lines against {})",
            baseline.len() + 1,
            taken.get(baseline.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
        std::cmp::Ordering::Less => Some(format!(
            "line {}: this run ends here and the baseline has `{}` ({} lines against {})",
            taken.len() + 1,
            baseline.get(taken.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
    }
}

#[test]
fn every_specimen_matches_its_committed_baseline() {
    let regenerate = std::env::var("MJX_LAYOUT_DOCX_REGENERATE").as_deref() == Ok("1");
    let mut failures = Vec::new();

    for specimen in CORPUS {
        let taken = specimen.taken();
        let path = specimen.baseline();
        if regenerate {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).expect("the baseline directory");
            }
            std::fs::write(&path, &taken)
                .unwrap_or_else(|error| panic!("writing {}: {error}", path.display()));
            continue;
        }
        let Ok(baseline) = std::fs::read_to_string(&path) else {
            failures.push(format!(
                "{} has no committed baseline at {}; regenerate with \
                 MJX_LAYOUT_DOCX_REGENERATE=1 and read what it wrote before committing it",
                specimen.file,
                path.display()
            ));
            continue;
        };
        if let Some(difference) = first_difference(&normalise(&taken), &normalise(&baseline)) {
            failures.push(format!(
                "{} page {}:\n{difference}",
                specimen.file, specimen.page
            ));
        }
    }

    assert!(
        regenerate || failures.is_empty(),
        "{} of {} specimens moved:\n\n{}",
        failures.len(),
        CORPUS.len(),
        failures.join("\n\n")
    );
}

/// Every baseline states who approved it, so a green run cannot be read as a human review.
#[test]
fn every_baseline_records_its_approval() {
    for specimen in CORPUS {
        let path = specimen.baseline();
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        assert!(
            text.contains("# approver: "),
            "{} states no approver",
            path.display()
        );
        assert!(
            text.contains("# covers: "),
            "{} does not say what it is for",
            path.display()
        );
    }
}

/// No baseline holds a glyph id — see the module documentation. A snapshot that did would expire on
/// a shaper's patch release for a reason that has nothing to do with layout.
#[test]
fn no_baseline_holds_a_glyph_id() {
    for specimen in CORPUS {
        let Ok(text) = std::fs::read_to_string(specimen.baseline()) else {
            continue;
        };
        assert!(
            !text.contains("glyph_id") && !text.contains("GlyphIndex"),
            "{} names a glyph, which makes it a baseline of a shaper version",
            specimen.file
        );
    }
}
