//! **Tier one, over the Excel corpus.** One committed text snapshot per band, compared line by line,
//! so a position regression surfaces as *"line 14: node 6's rect is 152400 wide and was 101600"*
//! rather than as a mysterious picture.
//!
//! # Why this is here and not in `mjx-render-oracle`
//!
//! MJXOFF-165 built exactly this machinery — the three assertion tiers, the localisation, the
//! approval records — and R16's ticket asks for it to be used. **It cannot be, and the reason is
//! structural rather than a preference.** `mjx-render-oracle` depends on `mjx-paint`, which links
//! Vulkan; `xtask/tests/layering.rs` therefore forbids *any* ranked crate from naming it, in either
//! dependency section, because a test build that links Vulkan is still a build that links Vulkan.
//! This crate has a rank, so the edge is refused by name.
//!
//! The oracle cannot host these snapshots either: it is specified to name no format crate at all —
//! it is the rendering path with no document anywhere in it — and a specimen read from a `.xlsx`
//! would make every one of its baselines a baseline of the box model as well as of the renderer,
//! which is exactly the confusion it was built to prevent.
//!
//! So the *technique* is copied and the crate is not, exactly as `mjx-layout-pptx` does: the same
//! line shape, down to carrying a glyph **count** rather than glyph ids, because a baseline holding
//! glyph ids is a baseline of a shaper version and a patch release of `swash` would expire it for a
//! reason that has nothing to do with layout.
//!
//! # ⚠ Regeneration is deliberately not automatic
//!
//! A golden file generated by the code under test always matches the code under test. So
//! regeneration refuses without `MJX_LAYOUT_XLSX_REGENERATE=1`, and every committed baseline states
//! who approved it. Today every one says `generator`, which is a real record — it says the file is a
//! **change detector** and that no person has looked at it — and is not a human review. The Windows
//! sitting is where a person approves what these numbers should be.

mod support;

use std::path::{Path, PathBuf};

use support::{model, snapshot, viewport};

/// One band of one sheet, with a committed baseline.
struct Specimen {
    /// The fixture it is read from.
    file: &'static str,
    /// Which tab.
    sheet: usize,
    /// Which band of it.
    band: u32,
    /// Why this one is in the corpus — the thing its snapshot would notice.
    covers: &'static str,
}

/// The corpus. **Committed fixtures only**: a baseline over a workbook this crate *authored* would
/// move whenever `Workbook::blank` changed a default, which is a regression in a different crate.
const CORPUS: &[Specimen] = &[
    Specimen {
        file: "sheet_grid.xlsx",
        sheet: 0,
        band: 0,
        covers:
            "custom row heights, hidden rows, outline levels, a five-column `col` run, a hidden \
                 column and two merged regions — the one sheet in the corpus with every knob turned",
    },
    Specimen {
        file: "sample.xlsx",
        sheet: 0,
        band: 0,
        covers: "the plainest sheet there is: shared strings, default geometry, no merges",
    },
    Specimen {
        file: "effective_cell_format.xlsx",
        sheet: 0,
        band: 0,
        covers:
            "cells whose formatting comes from the row, the column and the named style beneath \
                 the direct record — the `xf` ladder, consumed",
    },
    Specimen {
        file: "style_resources.xlsx",
        sheet: 0,
        band: 0,
        covers: "fonts, fills and borders resolved into decoration handles",
    },
    Specimen {
        file: "shared_strings_rich_text.xlsx",
        sheet: 0,
        band: 0,
        covers: "a shared string with formatting runs, which R16 lays out in the cell's own format",
    },
    Specimen {
        file: "formulas.xlsx",
        sheet: 0,
        band: 0,
        covers:
            "cells holding formulas, whose **cached** values are rendered as stored — there is \
                 no calculation engine in this loop",
    },
    Specimen {
        file: "row_spans_and_extensions.xlsx",
        sheet: 0,
        band: 0,
        covers:
            "a sheet carrying `row@spans` and extension markup the box model neither reads nor \
                 trips over",
    },
];

impl Specimen {
    fn baseline(&self) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/baselines")
            .join(format!(
                "{}-sheet{}-band{}.txt",
                self.file.trim_end_matches(".xlsx"),
                self.sheet,
                self.band
            ))
    }

    /// The snapshot this specimen produces now.
    fn taken(&self) -> String {
        let grid = support::grid_of(self.file, self.sheet);
        let constraints = viewport(8.0, 5.0);
        let mut model = model();
        // Reached the way a reader reaches it — band by band, through each checkpoint — so a
        // baseline of band one is also a check that resumption produces the same page.
        let tree = support::lay_out(&mut model, &grid, &constraints, self.band);
        format!(
            "# specimen: {} sheet {} band {}\n# covers: {}\n# approver: generator\n# approval: a \
             change detector written by the code under test; no person has reviewed these numbers, \
             and the Windows sitting is where one will\n# decorations: {}\n{}",
            self.file,
            self.sheet,
            self.band,
            self.covers,
            model.catalogue().decoration_count(),
            snapshot(&tree)
        )
    }
}

/// A baseline's text, with trailing whitespace stripped and a trailing blank line dropped, so an
/// editor that adds or removes a final newline cannot expire an approval.
fn normalise(text: &str) -> Vec<String> {
    let mut lines: Vec<String> = text
        .lines()
        .map(|line| line.trim_end().to_owned())
        .collect();
    while lines.last().is_some_and(String::is_empty) {
        lines.pop();
    }
    lines
}

/// The first line at which two snapshots differ, quoted from both sides.
///
/// **One line, not a whole diff.** A band is hundreds of lines and a failure that printed all of
/// them would be scrolled past; the first divergence is where a reader has to look and every later
/// one is usually its consequence.
fn first_difference(taken: &[String], baseline: &[String]) -> Option<String> {
    for (number, (mine, theirs)) in taken.iter().zip(baseline.iter()).enumerate() {
        if mine != theirs {
            return Some(format!(
                "line {}:\n  baseline: {theirs}\n  this run: {mine}",
                number + 1
            ));
        }
    }
    match taken.len().cmp(&baseline.len()) {
        std::cmp::Ordering::Equal => None,
        std::cmp::Ordering::Greater => Some(format!(
            "line {}: the baseline ends here and this run adds `{}` ({} lines against {})",
            baseline.len() + 1,
            taken.get(baseline.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
        std::cmp::Ordering::Less => Some(format!(
            "line {}: this run ends here and the baseline has `{}` ({} lines against {})",
            taken.len() + 1,
            baseline.get(taken.len()).map_or("", String::as_str),
            taken.len(),
            baseline.len()
        )),
    }
}

#[test]
fn every_specimen_matches_its_committed_baseline() {
    let regenerate = std::env::var("MJX_LAYOUT_XLSX_REGENERATE").as_deref() == Ok("1");
    let mut failures = Vec::new();

    for specimen in CORPUS {
        let taken = specimen.taken();
        let path = specimen.baseline();
        if regenerate {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).expect("the baseline directory");
            }
            std::fs::write(&path, &taken)
                .unwrap_or_else(|error| panic!("writing {}: {error}", path.display()));
            continue;
        }

        let Ok(committed) = std::fs::read_to_string(&path) else {
            failures.push(format!(
                "{} has no committed baseline. Regenerate with \
                 `MJX_LAYOUT_XLSX_REGENERATE=1 cargo test -p mjx-layout-xlsx --test \
                 the_fragments_match_their_baselines`, then read what it wrote before committing it.",
                path.display()
            ));
            continue;
        };
        if let Some(difference) = first_difference(&normalise(&taken), &normalise(&committed)) {
            failures.push(format!("{}\n{difference}", path.display()));
        }
    }

    assert!(
        !regenerate,
        "MJX_LAYOUT_XLSX_REGENERATE=1 rewrote every baseline. That is not a passing run: a golden \
         file generated by the code under test always matches the code under test. Read the diff.",
    );
    assert!(
        failures.is_empty(),
        "{} of {} specimens moved:\n\n{}",
        failures.len(),
        CORPUS.len(),
        failures.join("\n\n")
    );
}

#[test]
fn every_baseline_carries_an_approval_record() {
    // A baseline with no approver is a number nobody has taken responsibility for. `generator` is a
    // real record — it says the file is a change detector — and it is the only value in the tree
    // today; a human approval would name a person.
    for specimen in CORPUS {
        let path = specimen.baseline();
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue; // The other test reports a missing baseline; this one is about content.
        };
        let header: Vec<&str> = text.lines().take(5).collect();
        assert!(
            header
                .first()
                .is_some_and(|line| line.starts_with("# specimen: ")),
            "{} does not name its specimen",
            path.display()
        );
        for field in ["# covers: ", "# approver: ", "# approval: "] {
            assert!(
                header.iter().any(|line| line.starts_with(field)),
                "{} carries no `{field}` line",
                path.display()
            );
        }
    }
}

#[test]
fn a_baseline_notices_a_moved_fragment() {
    // The instrument's own instrument: proof that a snapshot comparison would *fail* if a fragment
    // moved, rather than being satisfied by any two runs of the same code.
    let specimen = CORPUS
        .iter()
        .find(|specimen| specimen.file == "sheet_grid.xlsx")
        .expect("the grid specimen");
    let taken = specimen.taken();
    let mut perturbed = normalise(&taken);
    let position = perturbed
        .iter()
        .position(|line| line.contains("box rect=["))
        .expect("a cell box in the snapshot");
    perturbed[position] = perturbed[position].replace("rect=[", "rect=[9");
    assert!(
        first_difference(&perturbed, &normalise(&taken)).is_some(),
        "a snapshot that cannot notice a moved fragment is not a baseline"
    );
}

#[test]
fn the_corpus_covers_more_than_one_shape_of_sheet() {
    // The "how many distinct values did the gate see?" instrument: a corpus of one workbook asserts
    // one workbook's arrangement, and every corner it happens not to use is uncovered.
    let files: std::collections::BTreeSet<&str> =
        CORPUS.iter().map(|specimen| specimen.file).collect();
    assert!(files.len() >= 5, "{files:?}");

    // And the specimens really do differ: a corpus of five identical snapshots would satisfy every
    // assertion above while proving nothing.
    let snapshots: std::collections::BTreeSet<usize> = CORPUS
        .iter()
        .map(|specimen| normalise(&specimen.taken()).len())
        .collect();
    assert!(
        snapshots.len() >= 4,
        "the specimens produce {} distinct snapshot sizes, which is too few for a corpus of {}",
        snapshots.len(),
        CORPUS.len()
    );
}
