/**
 * The catalogue's lint configuration.
 *
 * Three things here are gates rather than style, and each is written where the failure it prevents
 * would happen:
 *
 * 1. **`mjx/story-conventions`** on `*.stories.ts` — a story without its states matrix, token
 *    dependencies and keyboard/screen-reader behaviour is not ready for audit, and fifteen further
 *    children will each write stories. See `eslint-rules/story-conventions.js`.
 * 2. **The framework ban on `src/`** — the architecture decision is that a shipped component is a
 *    framework-free custom element, because that is what lets the platform embed in a host of any
 *    stack. `lit` is a legitimate *story-authoring* dependency (Storybook's web-components renderer
 *    is built on lit-html) and an illegitimate *component* dependency, and the only difference
 *    between the two is which directory the import is in. So the ban is scoped to the directory
 *    rather than left as a paragraph in a document.
 * 3. **The generated-artefact ban** — nothing under `tokens/` is linted or fixed, because it is
 *    generated by `cargo run -p xtask -- tokens` and an autofix landing in it would be silently
 *    reverted by the next regeneration, or silently kept and become drift.
 * 4. **`mjx/no-literal-design-values`** on `src/` (MJXOFF-181) — a hard-coded colour, radius,
 *    spacing or duration in a shipped component is invisible while it happens to match the token,
 *    and becomes one control that stayed the old green on the day the palette is re-seeded. See
 *    `eslint-rules/design-values.js` for what it allows and why. It is scoped to `src/` and not to
 *    `stories/` or `dev/` on purpose: the ticket's rule is about *components*, and the throwaway
 *    probes exist precisely to write values a component may not.
 *
 *    ⚠ **MJXOFF-279 re-examined that scope and kept it, deliberately rather than by default.** A
 *    story had pinned a literal `#808080` page colour, which went stale when MJXOFF-271 re-seeded
 *    the palette. Widening the rule would flag six files that are legitimately right — a colour
 *    picker's story supplies a document's palette *as data*, and `stories/gates/*` exist to be
 *    wrong on purpose — and a rule that cries wolf gets disabled, which is worse than no rule. So
 *    the exemption is **named and audited** instead: `tests/design-values.test.ts` lists exactly
 *    which files outside `src/` may carry a literal colour, so a seventh is a line somebody adds
 *    with a reason. The literal was never the instrument that would have caught that defect anyway
 *    — the wrong thing was a *pairing* (a theme text token on a colour we do not own), which only
 *    the a11y sweep can see, and did.
 * 5. **The icon-vendor ban** — `@fluentui/svg-icons` ships 20,679 SVG files, and
 *    `scripts/subset-icons.mjs` is the only thing allowed to read them. This is the *static* half
 *    of the subsetting guarantee: `tests/browser/icons.spec.ts` asserts what reached the bundle,
 *    and this asserts that there is no route for anything else to.
 *
 * Type-aware linting is deliberately *not* enabled. `tsc --noEmit` runs over the same files with
 * `strict`, `noUncheckedIndexedAccess` and `exactOptionalPropertyTypes`, so a type-checked lint
 * pass would be a second, slower type-check that finds the same defects; the lint pass here is for
 * what a type-checker cannot see.
 */

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import storyConventions from './eslint-rules/story-conventions.js';
import designValues from './eslint-rules/design-values.js';

/** The project's own rules, published under one plugin namespace. */
const mjx = { rules: { ...storyConventions.rules, ...designValues.rules } };

/**
 * The icon-vendor ban, stated once and repeated into every `no-restricted-imports` block.
 *
 * ESLint's flat config replaces a rule's options rather than merging them, so the block that gives
 * `src/` its framework ban would silently drop this one if it were only declared in the general
 * block. Repeating the object is the fix; a repeated *literal* would be the defect.
 */
const iconVendorBan = {
  group: ['@fluentui/svg-icons', '@fluentui/svg-icons/*'],
  message:
    'The vendor package ships 20,679 icons and 12.7 MB. Only scripts/subset-icons.mjs may read ' +
    'it; a component imports src/icons/generated.ts, which is the committed subset. Add a row to ' +
    'src/icons/manifest.ts and run `npm run icons:subset`.',
};

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'storybook-static/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by `cargo run -p xtask -- tokens`. Checked by `npm run tokens:check`, never by
      // a formatter.
      'tokens/**',
      // Deliberately malformed sources, fed to ESLint by tests/story-conventions.test.ts.
      'tests/fixtures/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { mjx },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  {
    // The vendor icon package is 20,679 files. Only the subsetter may open it.
    files: ['**/*.ts', '**/*.js', '**/*.mjs'],
    ignores: ['scripts/subset-icons.mjs'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [iconVendorBan] }],
    },
  },

  {
    // The shipped surface: framework-free, per the architecture, and token-driven.
    //
    // `src/icons/generated.ts` is excluded from the literal-value rule for the same reason
    // `tokens/**` is excluded from everything: it is generated output, and SVG path data is a
    // stream of numbers followed by single-letter commands, several of which spell a CSS duration
    // (`1.37s` is a smooth curve, not 1.37 seconds). Its integrity is `npm run icons:check`'s job,
    // which re-derives the whole file from the vendor package and fails on any difference — a
    // stronger guarantee than a lint pass, not a weaker one.
    files: ['src/**/*.ts'],
    ignores: ['src/icons/generated.ts'],
    rules: {
      'mjx/no-literal-design-values': 'error',
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lit',
              message:
                'A shipped component is a framework-free custom element. lit belongs to story ' +
                'authoring (stories/, dev/), never to src/.',
            },
            { name: 'lit-html', message: 'See the note on `lit`: story authoring only.' },
            { name: 'react', message: 'No framework in a shipped component.' },
            { name: 'react-dom', message: 'No framework in a shipped component.' },
            { name: 'vue', message: 'No framework in a shipped component.' },
            { name: 'svelte', message: 'No framework in a shipped component.' },
          ],
          patterns: [
            iconVendorBan,
            {
              group: ['@storybook/*', 'storybook', 'storybook/*'],
              message:
                'src/ is what the application ships. A component that imports Storybook has made ' +
                'the catalogue a runtime dependency of the product.',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['**/*.stories.ts'],
    rules: { 'mjx/story-conventions': 'error' },
  },

  {
    /*
     * **The assembly is held to the component rule** (MJXOFF-274).
     *
     * `mjx/no-literal-design-values` is scoped to `src/` because the ticket that wrote it is about
     * *components*, and MJXOFF-279 re-examined that scope and kept it. The nine shells are the one
     * place outside `src/` where the same argument applies with full force: an assembly is where
     * the temptation to write a width, a gap or a divider colour by hand is worst, and a literal
     * there is invisible for exactly as long as it happens to match the token.
     *
     * So this is a *narrowing* of the exemption rather than a widening of the rule: `stories/shell/`
     * is the assembly and nothing else, and `tests/design-values.test.ts` still lists which files
     * outside `src/` may legitimately carry a literal colour — none of them are here.
     *
     * **`stories/ribbons/` joins it because it is part of the same assembly.** The ribbon
     * programme's unit 0 moved every tab of every application out of the three shell stories and
     * into modules those stories now compose; the markup did not become less of an assembly by
     * changing directory, and the temptation the rule exists against — a group width, a gap between
     * commands, a divider colour written by hand — moved with it. Leaving the new directory
     * exempt would have made the rule easy to escape by relocating a file, which is worse than the
     * rule not existing.
     */
    files: ['stories/shell/**/*.ts', 'stories/ribbons/**/*.ts'],
    rules: { 'mjx/no-literal-design-values': 'error' },
  },

  {
    files: ['scripts/**/*.mjs', '*.config.ts', '.storybook/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
);
