/**
 * The catalogue's lint configuration.
 *
 * Three things here are gates rather than style, and each is written where the failure it prevents
 * would happen:
 *
 * 1. **`mjx/story-conventions`** on `*.stories.ts` — a story without its states matrix, token
 *    dependencies and keyboard/screen-reader behaviour is not ready for audit, and fifteen further
 *    children will each write stories. See `eslint-rules/story-conventions.js`.
 * 2. **The framework ban on `src/`** — the architecture decision is that a shipped component is a
 *    framework-free custom element, because that is what lets the platform embed in a host of any
 *    stack. `lit` is a legitimate *story-authoring* dependency (Storybook's web-components renderer
 *    is built on lit-html) and an illegitimate *component* dependency, and the only difference
 *    between the two is which directory the import is in. So the ban is scoped to the directory
 *    rather than left as a paragraph in a document.
 * 3. **The generated-artefact ban** — nothing under `tokens/` is linted or fixed, because it is
 *    generated by `cargo run -p xtask -- tokens` and an autofix landing in it would be silently
 *    reverted by the next regeneration, or silently kept and become drift.
 *
 * Type-aware linting is deliberately *not* enabled. `tsc --noEmit` runs over the same files with
 * `strict`, `noUncheckedIndexedAccess` and `exactOptionalPropertyTypes`, so a type-checked lint
 * pass would be a second, slower type-check that finds the same defects; the lint pass here is for
 * what a type-checker cannot see.
 */

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import mjx from './eslint-rules/story-conventions.js';

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'storybook-static/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by `cargo run -p xtask -- tokens`. Checked by `npm run tokens:check`, never by
      // a formatter.
      'tokens/**',
      // Deliberately malformed sources, fed to ESLint by tests/story-conventions.test.ts.
      'tests/fixtures/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { mjx },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  {
    // The shipped surface: framework-free, per the architecture.
    files: ['src/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lit',
              message:
                'A shipped component is a framework-free custom element. lit belongs to story ' +
                'authoring (stories/, dev/), never to src/.',
            },
            { name: 'lit-html', message: 'See the note on `lit`: story authoring only.' },
            { name: 'react', message: 'No framework in a shipped component.' },
            { name: 'react-dom', message: 'No framework in a shipped component.' },
            { name: 'vue', message: 'No framework in a shipped component.' },
            { name: 'svelte', message: 'No framework in a shipped component.' },
          ],
          patterns: [
            {
              group: ['@storybook/*', 'storybook', 'storybook/*'],
              message:
                'src/ is what the application ships. A component that imports Storybook has made ' +
                'the catalogue a runtime dependency of the product.',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['**/*.stories.ts'],
    rules: { 'mjx/story-conventions': 'error' },
  },

  {
    files: ['scripts/**/*.mjs', '*.config.ts', '.storybook/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
);
